// Code generated by tpl from sakila.actor. DO NOT EDIT.

/**
 * The `sakila.actor` row, the key that addresses it, the columns an ordering may
 * name, and the filter a search takes.
 *
 * @module
 */

/** @import { Direction } from './core.js' */

import { UnknownColumn } from './core.js';

/**
 * One row of `sakila.actor`.
 *
 * Every property is present on a row. A column that admits `NULL` is typed
 * `T | null`, which is what mysql2 hands back for a `NULL` and what `tsc`
 * makes a caller narrow before reading.
 *
 * @typedef {object} Actor
 * @property {number} actorId `actor_id`, declared `smallint(5) unsigned` NOT NULL AUTO_INCREMENT.
 *   It is part of the primary key.
 * @property {string} firstName `first_name`, declared `varchar(45)` NOT NULL.
 * @property {string} lastName `last_name`, declared `varchar(45)` NOT NULL.
 * @property {Date} lastUpdate `last_update`, declared `timestamp` NOT NULL.
 */

/**
 * The primary key of `sakila.actor`.
 *
 * @typedef {object} ActorKey
 * @property {number} actorId `actor_id`, declared `smallint(5) unsigned` NOT NULL AUTO_INCREMENT.
 */

/**
 * One column of `sakila.actor`.
 *
 * A search accepts an ordering term over these values and over nothing else,
 * so an ordering can carry no SQL of its own. A caller may write the column's
 * catalogue name as a string literal instead: {@link ActorColumn} is the union
 * of the values below, so the two are the same value and the same type.
 */
export const ActorColumns = Object.freeze(
  /** @type {const} */ ({
    /** `actor_id`, declared `smallint(5) unsigned` NOT NULL AUTO_INCREMENT. */
    ACTOR_ID: "actor_id",
    /** `first_name`, declared `varchar(45)` NOT NULL. */
    FIRST_NAME: "first_name",
    /** `last_name`, declared `varchar(45)` NOT NULL. */
    LAST_NAME: "last_name",
    /** `last_update`, declared `timestamp` NOT NULL. */
    LAST_UPDATE: "last_update",
  }),
);

/**
 * A column of `sakila.actor` an ordering may name.
 *
 * @typedef {(typeof ActorColumns)[keyof typeof ActorColumns]} ActorColumn
 */

/**
 * The one place a column of `sakila.actor` becomes SQL.
 *
 * It is closed over the constants above, and every identifier in it was quoted
 * at render time by `tpl`, so no value a caller supplies can reach a
 * statement's text through an ordering term.
 *
 * @type {Readonly<Record<ActorColumn, string>>}
 */
const COLUMN_SQL = Object.freeze({
  "actor_id": "`actor_id`",
  "first_name": "`first_name`",
  "last_name": "`last_name`",
  "last_update": "`last_update`",
});

/**
 * The column as a statement's text names it: quoted for MariaDB.
 *
 * The lookup is by own property and the refusal is unconditional, so a caller
 * that reached past the type — with an unchecked string, or a value read from
 * a request — is refused here rather than interpolated.
 *
 * @param {ActorColumn} column
 * @returns {string}
 * @throws {UnknownColumn} for every name the table does not carry.
 */
export function actorColumnSql(column) {
  if (!Object.hasOwn(COLUMN_SQL, column)) {
    throw new UnknownColumn("sakila.actor", String(column));
  }
  return COLUMN_SQL[column];
}

/**
 * One ordering term of a search over `sakila.actor`.
 *
 * @typedef {object} ActorOrder
 * @property {ActorColumn} column the column to order by
 * @property {Direction} [direction] the direction to order in. Ascending when absent.
 */

/**
 * What narrows a search over `sakila.actor`.
 *
 * Every property is optional: a property left absent adds no condition, and the
 * conditions a search does build are joined with `AND`. The empty object is the
 * filter that matches every row.
 *
 * A property is absent for *no condition* and is never `null` for *is NULL*.
 * That question is asked through the `…IsNull` property a nullable column also
 * gets, so the two meanings never collide, and it is why no filter property
 * admits `null`.
 *
 * @typedef {object} ActorFilter
 * @property {number} [actorId] where set, requires `actor_id` to equal it.
 * @property {number} [actorIdFrom] where set, requires `actor_id` to be at least it.
 * @property {number} [actorIdTo] where set, requires `actor_id` to be at most it.
 * @property {string} [firstName] where set, requires `first_name` to equal it.
 * @property {string} [firstNameLike] where set, requires `first_name` to match it, as LIKE matches.
 * @property {string} [lastName] where set, requires `last_name` to equal it.
 * @property {string} [lastNameLike] where set, requires `last_name` to match it, as LIKE matches.
 * @property {Date} [lastUpdate] where set, requires `last_update` to equal it.
 * @property {Date} [lastUpdateFrom] where set, requires `last_update` to be at least it.
 * @property {Date} [lastUpdateTo] where set, requires `last_update` to be at most it.
 */
