// Code generated by tpl from sakila.category. DO NOT EDIT.

/**
 * The mysql2 implementation of the `sakila.category` data layer.
 *
 * @module
 */

/** @import { Connection, ResultSetHeader, RowDataPacket } from 'mysql2/promise' */
/** @import { BoundValue } from './core.js' */
/** @import { Category, CategoryFilter, CategoryKey, CategoryOrder } from './category.js' */

import { NotFound, directionSql, failure } from './core.js';
import { categoryColumnSql } from './category.js';
import { CategoryRepository } from './category_repository.js';

/** The table every statement of this module addresses, as an error names it. */
const TABLE = "sakila.category";

/** Selects every column of the table, in catalogue order. */
const SELECT = "SELECT `category_id`, `name`, `last_update` FROM `category`";

/** Selects the one row a primary key names. */
const READ = "SELECT `category_id`, `name`, `last_update` FROM `category` WHERE `category_id` = ?";

/**
 * Inserts one row. It names neither a generated column nor an auto-increment
 * key, because the server writes both.
 */
const INSERT = "INSERT INTO `category` (`name`, `last_update`) VALUES (?, ?)";

/** Writes every column that is neither generated nor part of the key. */
const UPDATE = "UPDATE `category` SET `name` = ?, `last_update` = ? WHERE `category_id` = ?";

/** Removes the one row a primary key names. */
const DELETE = "DELETE FROM `category` WHERE `category_id` = ?";

/**
 * Build a row from one result tuple.
 *
 * The positions are the order `SELECT` names the columns in, which is
 * catalogue order. Every statement below is run with `rowsAsArray`, so a
 * result is an array and never an object: a column named `__proto__` or
 * `constructor` would otherwise reach an object literal as a key, and the
 * first of those sets a prototype instead of defining a property.
 *
 * The values are whatever mysql2 decoded, and the types `Category` declares
 * are this example's record of what that is.
 *
 * @param {RowDataPacket} values
 * @returns {Category}
 */
function toRow(values) {
  return {
    categoryId: values[0],
    name: values[1],
    lastUpdate: values[2],
  };
}

/**
 * The mysql2 data layer of `sakila.category`.
 *
 * Nothing here commits. mysql2 autocommits until a caller calls
 * `beginTransaction`, so transaction control stays with the caller.
 */
export class CategoryMysql2 extends CategoryRepository {
  /** @type {Connection} */
  #connection;

  /**
   * Build the data layer of `sakila.category` over `connection`.
   *
   * The connection must address the schema `SCHEMA` names, because the
   * statements above address the table unqualified. `connect` is the
   * connection that carries it.
   *
   * @param {Connection} connection
   */
  constructor(connection) {
    super();
    this.#connection = connection;
  }

  /**
   * Insert `row`.
   *
   * The key is assigned by the server and is written back into `row`.
   *
   * @override
   * @param {Category} row
   * @returns {Promise<void>}
   */
  async create(row) {
    /** @type {BoundValue[]} */
    const values = [
      row.name,
      row.lastUpdate,
    ];
    try {
      const [result] = await this.#connection.execute(INSERT, values);
      const { insertId } = /** @type {ResultSetHeader} */ (result);
      row.categoryId = insertId;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Return the row `key` names.
   *
   * @override
   * @param {CategoryKey} key
   * @returns {Promise<Category>}
   */
  async read(key) {
    /** @type {BoundValue[]} */
    const values = [
      key.categoryId,
    ];
    try {
      const [rows] = await this.#connection.execute(
        { sql: READ, rowsAsArray: true },
        values,
      );
      const found = /** @type {RowDataPacket[]} */ (rows);
      if (found.length === 0) {
        throw new NotFound(TABLE);
      }
      return toRow(found[0]);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Write every writable column of `row` over the row its key names.
   *
   * @override
   * @param {Category} row
   * @returns {Promise<number>}
   */
  async update(row) {
    /** @type {BoundValue[]} */
    const values = [
      row.name,
      row.lastUpdate,
      row.categoryId,
    ];
    try {
      const [result] = await this.#connection.execute(UPDATE, values);
      return /** @type {ResultSetHeader} */ (result).affectedRows;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Remove the row `key` names.
   *
   * @override
   * @param {CategoryKey} key
   * @returns {Promise<number>}
   */
  async delete(key) {
    /** @type {BoundValue[]} */
    const values = [
      key.categoryId,
    ];
    try {
      const [result] = await this.#connection.execute(DELETE, values);
      return /** @type {ResultSetHeader} */ (result).affectedRows;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Return every row matching `criteria`, ordered by the terms of `order`.
   *
   * @override
   * @param {CategoryFilter} criteria
   * @param {readonly CategoryOrder[]} [order]
   * @param {number | null} [limit]
   * @param {number | null} [offset]
   * @returns {Promise<Category[]>}
   */
  async search(criteria, order = [], limit = null, offset = null) {
    /** @type {string[]} */
    const conditions = [];
    /** @type {BoundValue[]} */
    const values = [];

    if (criteria.categoryId !== undefined) {
      conditions.push("`category_id` = ?");
      values.push(criteria.categoryId);
    }
    if (criteria.categoryIdFrom !== undefined) {
      conditions.push("`category_id` >= ?");
      values.push(criteria.categoryIdFrom);
    }
    if (criteria.categoryIdTo !== undefined) {
      conditions.push("`category_id` <= ?");
      values.push(criteria.categoryIdTo);
    }
    if (criteria.name !== undefined) {
      conditions.push("`name` = ?");
      values.push(criteria.name);
    }
    if (criteria.nameLike !== undefined) {
      conditions.push("`name` LIKE ?");
      values.push(criteria.nameLike);
    }
    if (criteria.lastUpdate !== undefined) {
      conditions.push("`last_update` = ?");
      values.push(criteria.lastUpdate);
    }
    if (criteria.lastUpdateFrom !== undefined) {
      conditions.push("`last_update` >= ?");
      values.push(criteria.lastUpdateFrom);
    }
    if (criteria.lastUpdateTo !== undefined) {
      conditions.push("`last_update` <= ?");
      values.push(criteria.lastUpdateTo);
    }

    let sql = SELECT;
    if (conditions.length > 0) {
      sql += ' WHERE ' + conditions.join(' AND ');
    }
    if (order.length > 0) {
      sql +=
        ' ORDER BY ' +
        order
          .map(
            (term) =>
              categoryColumnSql(term.column) +
              ' ' +
              directionSql(term.direction ?? 'asc'),
          )
          .join(', ');
    }
    if (limit !== null) {
      sql += ' LIMIT ?';
      values.push(limit);
      if (offset !== null) {
        sql += ' OFFSET ?';
        values.push(offset);
      }
    }

    try {
      const [rows] = await this.#connection.execute(
        { sql, rowsAsArray: true },
        values,
      );
      return /** @type {RowDataPacket[]} */ (rows).map(toRow);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }
}
