// Code generated by tpl from sakila.film_actor. DO NOT EDIT.

/**
 * The `sakila.film_actor` row, the key that addresses it, the columns an ordering may
 * name, and the filter a search takes.
 *
 * @module
 */

/** @import { Direction } from './core.js' */

import { UnknownColumn } from './core.js';

/**
 * One row of `sakila.film_actor`.
 *
 * Every property is present on a row. A column that admits `NULL` is typed
 * `T | null`, which is what mysql2 hands back for a `NULL` and what `tsc`
 * makes a caller narrow before reading.
 *
 * @typedef {object} FilmActor
 * @property {number} actorId `actor_id`, declared `smallint(5) unsigned` NOT NULL.
 *   It is part of the primary key.
 * @property {number} filmId `film_id`, declared `smallint(5) unsigned` NOT NULL.
 *   It is part of the primary key.
 * @property {Date} lastUpdate `last_update`, declared `timestamp` NOT NULL.
 */

/**
 * The primary key of `sakila.film_actor`.
 *
 * @typedef {object} FilmActorKey
 * @property {number} actorId `actor_id`, declared `smallint(5) unsigned` NOT NULL.
 * @property {number} filmId `film_id`, declared `smallint(5) unsigned` NOT NULL.
 */

/**
 * One column of `sakila.film_actor`.
 *
 * A search accepts an ordering term over these values and over nothing else,
 * so an ordering can carry no SQL of its own. A caller may write the column's
 * catalogue name as a string literal instead: {@link FilmActorColumn} is the union
 * of the values below, so the two are the same value and the same type.
 */
export const FilmActorColumns = Object.freeze(
  /** @type {const} */ ({
    /** `actor_id`, declared `smallint(5) unsigned` NOT NULL. */
    ACTOR_ID: "actor_id",
    /** `film_id`, declared `smallint(5) unsigned` NOT NULL. */
    FILM_ID: "film_id",
    /** `last_update`, declared `timestamp` NOT NULL. */
    LAST_UPDATE: "last_update",
  }),
);

/**
 * A column of `sakila.film_actor` an ordering may name.
 *
 * @typedef {(typeof FilmActorColumns)[keyof typeof FilmActorColumns]} FilmActorColumn
 */

/**
 * The one place a column of `sakila.film_actor` becomes SQL.
 *
 * It is closed over the constants above, and every identifier in it was quoted
 * at render time by `tpl`, so no value a caller supplies can reach a
 * statement's text through an ordering term.
 *
 * @type {Readonly<Record<FilmActorColumn, string>>}
 */
const COLUMN_SQL = Object.freeze({
  "actor_id": "`actor_id`",
  "film_id": "`film_id`",
  "last_update": "`last_update`",
});

/**
 * The column as a statement's text names it: quoted for MariaDB.
 *
 * The lookup is by own property and the refusal is unconditional, so a caller
 * that reached past the type — with an unchecked string, or a value read from
 * a request — is refused here rather than interpolated.
 *
 * @param {FilmActorColumn} column
 * @returns {string}
 * @throws {UnknownColumn} for every name the table does not carry.
 */
export function filmActorColumnSql(column) {
  if (!Object.hasOwn(COLUMN_SQL, column)) {
    throw new UnknownColumn("sakila.film_actor", String(column));
  }
  return COLUMN_SQL[column];
}

/**
 * One ordering term of a search over `sakila.film_actor`.
 *
 * @typedef {object} FilmActorOrder
 * @property {FilmActorColumn} column the column to order by
 * @property {Direction} [direction] the direction to order in. Ascending when absent.
 */

/**
 * What narrows a search over `sakila.film_actor`.
 *
 * Every property is optional: a property left absent adds no condition, and the
 * conditions a search does build are joined with `AND`. The empty object is the
 * filter that matches every row.
 *
 * A property is absent for *no condition* and is never `null` for *is NULL*.
 * That question is asked through the `…IsNull` property a nullable column also
 * gets, so the two meanings never collide, and it is why no filter property
 * admits `null`.
 *
 * @typedef {object} FilmActorFilter
 * @property {number} [actorId] where set, requires `actor_id` to equal it.
 * @property {number} [actorIdFrom] where set, requires `actor_id` to be at least it.
 * @property {number} [actorIdTo] where set, requires `actor_id` to be at most it.
 * @property {number} [filmId] where set, requires `film_id` to equal it.
 * @property {number} [filmIdFrom] where set, requires `film_id` to be at least it.
 * @property {number} [filmIdTo] where set, requires `film_id` to be at most it.
 * @property {Date} [lastUpdate] where set, requires `last_update` to equal it.
 * @property {Date} [lastUpdateFrom] where set, requires `last_update` to be at least it.
 * @property {Date} [lastUpdateTo] where set, requires `last_update` to be at most it.
 */
