// Code generated by tpl from sakila.film_actor. DO NOT EDIT.

/**
 * The mysql2 implementation of the `sakila.film_actor` data layer.
 *
 * @module
 */

/** @import { Connection, ResultSetHeader, RowDataPacket } from 'mysql2/promise' */
/** @import { BoundValue } from './core.js' */
/** @import { FilmActor, FilmActorFilter, FilmActorKey, FilmActorOrder } from './film_actor.js' */

import { NotFound, directionSql, failure } from './core.js';
import { filmActorColumnSql } from './film_actor.js';
import { FilmActorRepository } from './film_actor_repository.js';

/** The table every statement of this module addresses, as an error names it. */
const TABLE = "sakila.film_actor";

/** Selects every column of the table, in catalogue order. */
const SELECT = "SELECT `actor_id`, `film_id`, `last_update` FROM `film_actor`";

/** Selects the one row a primary key names. */
const READ = "SELECT `actor_id`, `film_id`, `last_update` FROM `film_actor` WHERE `actor_id` = ? AND `film_id` = ?";

/**
 * Inserts one row. It names neither a generated column nor an auto-increment
 * key, because the server writes both.
 */
const INSERT = "INSERT INTO `film_actor` (`actor_id`, `film_id`, `last_update`) VALUES (?, ?, ?)";

/** Writes every column that is neither generated nor part of the key. */
const UPDATE = "UPDATE `film_actor` SET `last_update` = ? WHERE `actor_id` = ? AND `film_id` = ?";

/** Removes the one row a primary key names. */
const DELETE = "DELETE FROM `film_actor` WHERE `actor_id` = ? AND `film_id` = ?";

/**
 * Build a row from one result tuple.
 *
 * The positions are the order `SELECT` names the columns in, which is
 * catalogue order. Every statement below is run with `rowsAsArray`, so a
 * result is an array and never an object: a column named `__proto__` or
 * `constructor` would otherwise reach an object literal as a key, and the
 * first of those sets a prototype instead of defining a property.
 *
 * The values are whatever mysql2 decoded, and the types `FilmActor` declares
 * are this example's record of what that is.
 *
 * @param {RowDataPacket} values
 * @returns {FilmActor}
 */
function toRow(values) {
  return {
    actorId: values[0],
    filmId: values[1],
    lastUpdate: values[2],
  };
}

/**
 * The mysql2 data layer of `sakila.film_actor`.
 *
 * Nothing here commits. mysql2 autocommits until a caller calls
 * `beginTransaction`, so transaction control stays with the caller.
 */
export class FilmActorMysql2 extends FilmActorRepository {
  /** @type {Connection} */
  #connection;

  /**
   * Build the data layer of `sakila.film_actor` over `connection`.
   *
   * The connection must address the schema `SCHEMA` names, because the
   * statements above address the table unqualified. `connect` is the
   * connection that carries it.
   *
   * @param {Connection} connection
   */
  constructor(connection) {
    super();
    this.#connection = connection;
  }

  /**
   * Insert `row`.
   *
   * The whole key is taken from `row`, which the caller therefore fills.
   *
   * @override
   * @param {FilmActor} row
   * @returns {Promise<void>}
   */
  async create(row) {
    /** @type {BoundValue[]} */
    const values = [
      row.actorId,
      row.filmId,
      row.lastUpdate,
    ];
    try {
      const [result] = await this.#connection.execute(INSERT, values);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Return the row `key` names.
   *
   * @override
   * @param {FilmActorKey} key
   * @returns {Promise<FilmActor>}
   */
  async read(key) {
    /** @type {BoundValue[]} */
    const values = [
      key.actorId,
      key.filmId,
    ];
    try {
      const [rows] = await this.#connection.execute(
        { sql: READ, rowsAsArray: true },
        values,
      );
      const found = /** @type {RowDataPacket[]} */ (rows);
      if (found.length === 0) {
        throw new NotFound(TABLE);
      }
      return toRow(found[0]);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Write every writable column of `row` over the row its key names.
   *
   * @override
   * @param {FilmActor} row
   * @returns {Promise<number>}
   */
  async update(row) {
    /** @type {BoundValue[]} */
    const values = [
      row.lastUpdate,
      row.actorId,
      row.filmId,
    ];
    try {
      const [result] = await this.#connection.execute(UPDATE, values);
      return /** @type {ResultSetHeader} */ (result).affectedRows;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Remove the row `key` names.
   *
   * @override
   * @param {FilmActorKey} key
   * @returns {Promise<number>}
   */
  async delete(key) {
    /** @type {BoundValue[]} */
    const values = [
      key.actorId,
      key.filmId,
    ];
    try {
      const [result] = await this.#connection.execute(DELETE, values);
      return /** @type {ResultSetHeader} */ (result).affectedRows;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Return every row matching `criteria`, ordered by the terms of `order`.
   *
   * @override
   * @param {FilmActorFilter} criteria
   * @param {readonly FilmActorOrder[]} [order]
   * @param {number | null} [limit]
   * @param {number | null} [offset]
   * @returns {Promise<FilmActor[]>}
   */
  async search(criteria, order = [], limit = null, offset = null) {
    /** @type {string[]} */
    const conditions = [];
    /** @type {BoundValue[]} */
    const values = [];

    if (criteria.actorId !== undefined) {
      conditions.push("`actor_id` = ?");
      values.push(criteria.actorId);
    }
    if (criteria.actorIdFrom !== undefined) {
      conditions.push("`actor_id` >= ?");
      values.push(criteria.actorIdFrom);
    }
    if (criteria.actorIdTo !== undefined) {
      conditions.push("`actor_id` <= ?");
      values.push(criteria.actorIdTo);
    }
    if (criteria.filmId !== undefined) {
      conditions.push("`film_id` = ?");
      values.push(criteria.filmId);
    }
    if (criteria.filmIdFrom !== undefined) {
      conditions.push("`film_id` >= ?");
      values.push(criteria.filmIdFrom);
    }
    if (criteria.filmIdTo !== undefined) {
      conditions.push("`film_id` <= ?");
      values.push(criteria.filmIdTo);
    }
    if (criteria.lastUpdate !== undefined) {
      conditions.push("`last_update` = ?");
      values.push(criteria.lastUpdate);
    }
    if (criteria.lastUpdateFrom !== undefined) {
      conditions.push("`last_update` >= ?");
      values.push(criteria.lastUpdateFrom);
    }
    if (criteria.lastUpdateTo !== undefined) {
      conditions.push("`last_update` <= ?");
      values.push(criteria.lastUpdateTo);
    }

    let sql = SELECT;
    if (conditions.length > 0) {
      sql += ' WHERE ' + conditions.join(' AND ');
    }
    if (order.length > 0) {
      sql +=
        ' ORDER BY ' +
        order
          .map(
            (term) =>
              filmActorColumnSql(term.column) +
              ' ' +
              directionSql(term.direction ?? 'asc'),
          )
          .join(', ');
    }
    if (limit !== null) {
      sql += ' LIMIT ?';
      values.push(limit);
      if (offset !== null) {
        sql += ' OFFSET ?';
        values.push(offset);
      }
    }

    try {
      const [rows] = await this.#connection.execute(
        { sql, rowsAsArray: true },
        values,
      );
      return /** @type {RowDataPacket[]} */ (rows).map(toRow);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }
}
