// Code generated by tpl from sakila.payment. DO NOT EDIT.

/**
 * The `sakila.payment` row, the key that addresses it, the columns an ordering may
 * name, and the filter a search takes.
 *
 * @module
 */

/** @import { Direction } from './core.js' */

import { UnknownColumn } from './core.js';

/**
 * One row of `sakila.payment`.
 *
 * Every property is present on a row. A column that admits `NULL` is typed
 * `T | null`, which is what mysql2 hands back for a `NULL` and what `tsc`
 * makes a caller narrow before reading.
 *
 * @typedef {object} Payment
 * @property {number} paymentId `payment_id`, declared `smallint(5) unsigned` NOT NULL AUTO_INCREMENT.
 *   It is part of the primary key.
 * @property {number} customerId `customer_id`, declared `smallint(5) unsigned` NOT NULL.
 * @property {number} staffId `staff_id`, declared `tinyint(3) unsigned` NOT NULL.
 * @property {number | null} rentalId `rental_id`, declared `int(11)` NULL.
 * @property {string} amount `amount`, declared `decimal(5,2)` NOT NULL.
 * @property {Date} paymentDate `payment_date`, declared `datetime` NOT NULL.
 * @property {Date | null} lastUpdate `last_update`, declared `timestamp` NULL.
 */

/**
 * The primary key of `sakila.payment`.
 *
 * @typedef {object} PaymentKey
 * @property {number} paymentId `payment_id`, declared `smallint(5) unsigned` NOT NULL AUTO_INCREMENT.
 */

/**
 * One column of `sakila.payment`.
 *
 * A search accepts an ordering term over these values and over nothing else,
 * so an ordering can carry no SQL of its own. A caller may write the column's
 * catalogue name as a string literal instead: {@link PaymentColumn} is the union
 * of the values below, so the two are the same value and the same type.
 */
export const PaymentColumns = Object.freeze(
  /** @type {const} */ ({
    /** `payment_id`, declared `smallint(5) unsigned` NOT NULL AUTO_INCREMENT. */
    PAYMENT_ID: "payment_id",
    /** `customer_id`, declared `smallint(5) unsigned` NOT NULL. */
    CUSTOMER_ID: "customer_id",
    /** `staff_id`, declared `tinyint(3) unsigned` NOT NULL. */
    STAFF_ID: "staff_id",
    /** `rental_id`, declared `int(11)` NULL. */
    RENTAL_ID: "rental_id",
    /** `amount`, declared `decimal(5,2)` NOT NULL. */
    AMOUNT: "amount",
    /** `payment_date`, declared `datetime` NOT NULL. */
    PAYMENT_DATE: "payment_date",
    /** `last_update`, declared `timestamp` NULL. */
    LAST_UPDATE: "last_update",
  }),
);

/**
 * A column of `sakila.payment` an ordering may name.
 *
 * @typedef {(typeof PaymentColumns)[keyof typeof PaymentColumns]} PaymentColumn
 */

/**
 * The one place a column of `sakila.payment` becomes SQL.
 *
 * It is closed over the constants above, and every identifier in it was quoted
 * at render time by `tpl`, so no value a caller supplies can reach a
 * statement's text through an ordering term.
 *
 * @type {Readonly<Record<PaymentColumn, string>>}
 */
const COLUMN_SQL = Object.freeze({
  "payment_id": "`payment_id`",
  "customer_id": "`customer_id`",
  "staff_id": "`staff_id`",
  "rental_id": "`rental_id`",
  "amount": "`amount`",
  "payment_date": "`payment_date`",
  "last_update": "`last_update`",
});

/**
 * The column as a statement's text names it: quoted for MariaDB.
 *
 * The lookup is by own property and the refusal is unconditional, so a caller
 * that reached past the type — with an unchecked string, or a value read from
 * a request — is refused here rather than interpolated.
 *
 * @param {PaymentColumn} column
 * @returns {string}
 * @throws {UnknownColumn} for every name the table does not carry.
 */
export function paymentColumnSql(column) {
  if (!Object.hasOwn(COLUMN_SQL, column)) {
    throw new UnknownColumn("sakila.payment", String(column));
  }
  return COLUMN_SQL[column];
}

/**
 * One ordering term of a search over `sakila.payment`.
 *
 * @typedef {object} PaymentOrder
 * @property {PaymentColumn} column the column to order by
 * @property {Direction} [direction] the direction to order in. Ascending when absent.
 */

/**
 * What narrows a search over `sakila.payment`.
 *
 * Every property is optional: a property left absent adds no condition, and the
 * conditions a search does build are joined with `AND`. The empty object is the
 * filter that matches every row.
 *
 * A property is absent for *no condition* and is never `null` for *is NULL*.
 * That question is asked through the `…IsNull` property a nullable column also
 * gets, so the two meanings never collide, and it is why no filter property
 * admits `null`.
 *
 * @typedef {object} PaymentFilter
 * @property {number} [paymentId] where set, requires `payment_id` to equal it.
 * @property {number} [paymentIdFrom] where set, requires `payment_id` to be at least it.
 * @property {number} [paymentIdTo] where set, requires `payment_id` to be at most it.
 * @property {number} [customerId] where set, requires `customer_id` to equal it.
 * @property {number} [customerIdFrom] where set, requires `customer_id` to be at least it.
 * @property {number} [customerIdTo] where set, requires `customer_id` to be at most it.
 * @property {number} [staffId] where set, requires `staff_id` to equal it.
 * @property {number} [staffIdFrom] where set, requires `staff_id` to be at least it.
 * @property {number} [staffIdTo] where set, requires `staff_id` to be at most it.
 * @property {number} [rentalId] where set, requires `rental_id` to equal it.
 * @property {number} [rentalIdFrom] where set, requires `rental_id` to be at least it.
 * @property {number} [rentalIdTo] where set, requires `rental_id` to be at most it.
 * @property {boolean} [rentalIdIsNull] where true, requires `rental_id` to be NULL; where false, requires it not to be.
 * @property {string} [amount] where set, requires `amount` to equal it.
 * @property {string} [amountFrom] where set, requires `amount` to be at least it.
 * @property {string} [amountTo] where set, requires `amount` to be at most it.
 * @property {Date} [paymentDate] where set, requires `payment_date` to equal it.
 * @property {Date} [paymentDateFrom] where set, requires `payment_date` to be at least it.
 * @property {Date} [paymentDateTo] where set, requires `payment_date` to be at most it.
 * @property {Date} [lastUpdate] where set, requires `last_update` to equal it.
 * @property {Date} [lastUpdateFrom] where set, requires `last_update` to be at least it.
 * @property {Date} [lastUpdateTo] where set, requires `last_update` to be at most it.
 * @property {boolean} [lastUpdateIsNull] where true, requires `last_update` to be NULL; where false, requires it not to be.
 */
