// Code generated by tpl from sakila.rental. DO NOT EDIT.

/**
 * The mysql2 implementation of the `sakila.rental` data layer.
 *
 * @module
 */

/** @import { Connection, ResultSetHeader, RowDataPacket } from 'mysql2/promise' */
/** @import { BoundValue } from './core.js' */
/** @import { Rental, RentalFilter, RentalKey, RentalOrder } from './rental.js' */

import { NotFound, directionSql, failure } from './core.js';
import { rentalColumnSql } from './rental.js';
import { RentalRepository } from './rental_repository.js';

/** The table every statement of this module addresses, as an error names it. */
const TABLE = "sakila.rental";

/** Selects every column of the table, in catalogue order. */
const SELECT = "SELECT `rental_id`, `rental_date`, `inventory_id`, `customer_id`, `return_date`, `staff_id`, `last_update` FROM `rental`";

/** Selects the one row a primary key names. */
const READ = "SELECT `rental_id`, `rental_date`, `inventory_id`, `customer_id`, `return_date`, `staff_id`, `last_update` FROM `rental` WHERE `rental_id` = ?";

/**
 * Inserts one row. It names neither a generated column nor an auto-increment
 * key, because the server writes both.
 */
const INSERT = "INSERT INTO `rental` (`rental_date`, `inventory_id`, `customer_id`, `return_date`, `staff_id`, `last_update`) VALUES (?, ?, ?, ?, ?, ?)";

/** Writes every column that is neither generated nor part of the key. */
const UPDATE = "UPDATE `rental` SET `rental_date` = ?, `inventory_id` = ?, `customer_id` = ?, `return_date` = ?, `staff_id` = ?, `last_update` = ? WHERE `rental_id` = ?";

/** Removes the one row a primary key names. */
const DELETE = "DELETE FROM `rental` WHERE `rental_id` = ?";

/**
 * Build a row from one result tuple.
 *
 * The positions are the order `SELECT` names the columns in, which is
 * catalogue order. Every statement below is run with `rowsAsArray`, so a
 * result is an array and never an object: a column named `__proto__` or
 * `constructor` would otherwise reach an object literal as a key, and the
 * first of those sets a prototype instead of defining a property.
 *
 * The values are whatever mysql2 decoded, and the types `Rental` declares
 * are this example's record of what that is.
 *
 * @param {RowDataPacket} values
 * @returns {Rental}
 */
function toRow(values) {
  return {
    rentalId: values[0],
    rentalDate: values[1],
    inventoryId: values[2],
    customerId: values[3],
    returnDate: values[4],
    staffId: values[5],
    lastUpdate: values[6],
  };
}

/**
 * The mysql2 data layer of `sakila.rental`.
 *
 * Nothing here commits. mysql2 autocommits until a caller calls
 * `beginTransaction`, so transaction control stays with the caller.
 */
export class RentalMysql2 extends RentalRepository {
  /** @type {Connection} */
  #connection;

  /**
   * Build the data layer of `sakila.rental` over `connection`.
   *
   * The connection must address the schema `SCHEMA` names, because the
   * statements above address the table unqualified. `connect` is the
   * connection that carries it.
   *
   * @param {Connection} connection
   */
  constructor(connection) {
    super();
    this.#connection = connection;
  }

  /**
   * Insert `row`.
   *
   * The key is assigned by the server and is written back into `row`.
   *
   * @override
   * @param {Rental} row
   * @returns {Promise<void>}
   */
  async create(row) {
    /** @type {BoundValue[]} */
    const values = [
      row.rentalDate,
      row.inventoryId,
      row.customerId,
      row.returnDate,
      row.staffId,
      row.lastUpdate,
    ];
    try {
      const [result] = await this.#connection.execute(INSERT, values);
      const { insertId } = /** @type {ResultSetHeader} */ (result);
      row.rentalId = insertId;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Return the row `key` names.
   *
   * @override
   * @param {RentalKey} key
   * @returns {Promise<Rental>}
   */
  async read(key) {
    /** @type {BoundValue[]} */
    const values = [
      key.rentalId,
    ];
    try {
      const [rows] = await this.#connection.execute(
        { sql: READ, rowsAsArray: true },
        values,
      );
      const found = /** @type {RowDataPacket[]} */ (rows);
      if (found.length === 0) {
        throw new NotFound(TABLE);
      }
      return toRow(found[0]);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Write every writable column of `row` over the row its key names.
   *
   * @override
   * @param {Rental} row
   * @returns {Promise<number>}
   */
  async update(row) {
    /** @type {BoundValue[]} */
    const values = [
      row.rentalDate,
      row.inventoryId,
      row.customerId,
      row.returnDate,
      row.staffId,
      row.lastUpdate,
      row.rentalId,
    ];
    try {
      const [result] = await this.#connection.execute(UPDATE, values);
      return /** @type {ResultSetHeader} */ (result).affectedRows;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Remove the row `key` names.
   *
   * @override
   * @param {RentalKey} key
   * @returns {Promise<number>}
   */
  async delete(key) {
    /** @type {BoundValue[]} */
    const values = [
      key.rentalId,
    ];
    try {
      const [result] = await this.#connection.execute(DELETE, values);
      return /** @type {ResultSetHeader} */ (result).affectedRows;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Return every row matching `criteria`, ordered by the terms of `order`.
   *
   * @override
   * @param {RentalFilter} criteria
   * @param {readonly RentalOrder[]} [order]
   * @param {number | null} [limit]
   * @param {number | null} [offset]
   * @returns {Promise<Rental[]>}
   */
  async search(criteria, order = [], limit = null, offset = null) {
    /** @type {string[]} */
    const conditions = [];
    /** @type {BoundValue[]} */
    const values = [];

    if (criteria.rentalId !== undefined) {
      conditions.push("`rental_id` = ?");
      values.push(criteria.rentalId);
    }
    if (criteria.rentalIdFrom !== undefined) {
      conditions.push("`rental_id` >= ?");
      values.push(criteria.rentalIdFrom);
    }
    if (criteria.rentalIdTo !== undefined) {
      conditions.push("`rental_id` <= ?");
      values.push(criteria.rentalIdTo);
    }
    if (criteria.rentalDate !== undefined) {
      conditions.push("`rental_date` = ?");
      values.push(criteria.rentalDate);
    }
    if (criteria.rentalDateFrom !== undefined) {
      conditions.push("`rental_date` >= ?");
      values.push(criteria.rentalDateFrom);
    }
    if (criteria.rentalDateTo !== undefined) {
      conditions.push("`rental_date` <= ?");
      values.push(criteria.rentalDateTo);
    }
    if (criteria.inventoryId !== undefined) {
      conditions.push("`inventory_id` = ?");
      values.push(criteria.inventoryId);
    }
    if (criteria.inventoryIdFrom !== undefined) {
      conditions.push("`inventory_id` >= ?");
      values.push(criteria.inventoryIdFrom);
    }
    if (criteria.inventoryIdTo !== undefined) {
      conditions.push("`inventory_id` <= ?");
      values.push(criteria.inventoryIdTo);
    }
    if (criteria.customerId !== undefined) {
      conditions.push("`customer_id` = ?");
      values.push(criteria.customerId);
    }
    if (criteria.customerIdFrom !== undefined) {
      conditions.push("`customer_id` >= ?");
      values.push(criteria.customerIdFrom);
    }
    if (criteria.customerIdTo !== undefined) {
      conditions.push("`customer_id` <= ?");
      values.push(criteria.customerIdTo);
    }
    if (criteria.returnDate !== undefined) {
      conditions.push("`return_date` = ?");
      values.push(criteria.returnDate);
    }
    if (criteria.returnDateFrom !== undefined) {
      conditions.push("`return_date` >= ?");
      values.push(criteria.returnDateFrom);
    }
    if (criteria.returnDateTo !== undefined) {
      conditions.push("`return_date` <= ?");
      values.push(criteria.returnDateTo);
    }
    if (criteria.returnDateIsNull !== undefined) {
      conditions.push(
        criteria.returnDateIsNull
          ? "`return_date` IS NULL"
          : "`return_date` IS NOT NULL",
      );
    }
    if (criteria.staffId !== undefined) {
      conditions.push("`staff_id` = ?");
      values.push(criteria.staffId);
    }
    if (criteria.staffIdFrom !== undefined) {
      conditions.push("`staff_id` >= ?");
      values.push(criteria.staffIdFrom);
    }
    if (criteria.staffIdTo !== undefined) {
      conditions.push("`staff_id` <= ?");
      values.push(criteria.staffIdTo);
    }
    if (criteria.lastUpdate !== undefined) {
      conditions.push("`last_update` = ?");
      values.push(criteria.lastUpdate);
    }
    if (criteria.lastUpdateFrom !== undefined) {
      conditions.push("`last_update` >= ?");
      values.push(criteria.lastUpdateFrom);
    }
    if (criteria.lastUpdateTo !== undefined) {
      conditions.push("`last_update` <= ?");
      values.push(criteria.lastUpdateTo);
    }

    let sql = SELECT;
    if (conditions.length > 0) {
      sql += ' WHERE ' + conditions.join(' AND ');
    }
    if (order.length > 0) {
      sql +=
        ' ORDER BY ' +
        order
          .map(
            (term) =>
              rentalColumnSql(term.column) +
              ' ' +
              directionSql(term.direction ?? 'asc'),
          )
          .join(', ');
    }
    if (limit !== null) {
      sql += ' LIMIT ?';
      values.push(limit);
      if (offset !== null) {
        sql += ' OFFSET ?';
        values.push(offset);
      }
    }

    try {
      const [rows] = await this.#connection.execute(
        { sql, rowsAsArray: true },
        values,
      );
      return /** @type {RowDataPacket[]} */ (rows).map(toRow);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }
}
