// Code generated by tpl from sakila.rental. DO NOT EDIT.

/**
 * The `sakila.rental` row, the key that addresses it, the columns an ordering may
 * name, and the filter a search takes.
 *
 * @module
 */

/** @import { Direction } from './core.js' */

import { UnknownColumn } from './core.js';

/**
 * One row of `sakila.rental`.
 *
 * Every property is present on a row. A column that admits `NULL` is typed
 * `T | null`, which is what mysql2 hands back for a `NULL` and what `tsc`
 * makes a caller narrow before reading.
 *
 * @typedef {object} Rental
 * @property {number} rentalId `rental_id`, declared `int(11)` NOT NULL AUTO_INCREMENT.
 *   It is part of the primary key.
 * @property {Date} rentalDate `rental_date`, declared `datetime` NOT NULL.
 *   It is part of a unique index.
 * @property {number} inventoryId `inventory_id`, declared `mediumint(8) unsigned` NOT NULL.
 *   It is part of a unique index.
 * @property {number} customerId `customer_id`, declared `smallint(5) unsigned` NOT NULL.
 *   It is part of a unique index.
 * @property {Date | null} returnDate `return_date`, declared `datetime` NULL.
 * @property {number} staffId `staff_id`, declared `tinyint(3) unsigned` NOT NULL.
 * @property {Date} lastUpdate `last_update`, declared `timestamp` NOT NULL.
 */

/**
 * The primary key of `sakila.rental`.
 *
 * @typedef {object} RentalKey
 * @property {number} rentalId `rental_id`, declared `int(11)` NOT NULL AUTO_INCREMENT.
 */

/**
 * One column of `sakila.rental`.
 *
 * A search accepts an ordering term over these values and over nothing else,
 * so an ordering can carry no SQL of its own. A caller may write the column's
 * catalogue name as a string literal instead: {@link RentalColumn} is the union
 * of the values below, so the two are the same value and the same type.
 */
export const RentalColumns = Object.freeze(
  /** @type {const} */ ({
    /** `rental_id`, declared `int(11)` NOT NULL AUTO_INCREMENT. */
    RENTAL_ID: "rental_id",
    /** `rental_date`, declared `datetime` NOT NULL. */
    RENTAL_DATE: "rental_date",
    /** `inventory_id`, declared `mediumint(8) unsigned` NOT NULL. */
    INVENTORY_ID: "inventory_id",
    /** `customer_id`, declared `smallint(5) unsigned` NOT NULL. */
    CUSTOMER_ID: "customer_id",
    /** `return_date`, declared `datetime` NULL. */
    RETURN_DATE: "return_date",
    /** `staff_id`, declared `tinyint(3) unsigned` NOT NULL. */
    STAFF_ID: "staff_id",
    /** `last_update`, declared `timestamp` NOT NULL. */
    LAST_UPDATE: "last_update",
  }),
);

/**
 * A column of `sakila.rental` an ordering may name.
 *
 * @typedef {(typeof RentalColumns)[keyof typeof RentalColumns]} RentalColumn
 */

/**
 * The one place a column of `sakila.rental` becomes SQL.
 *
 * It is closed over the constants above, and every identifier in it was quoted
 * at render time by `tpl`, so no value a caller supplies can reach a
 * statement's text through an ordering term.
 *
 * @type {Readonly<Record<RentalColumn, string>>}
 */
const COLUMN_SQL = Object.freeze({
  "rental_id": "`rental_id`",
  "rental_date": "`rental_date`",
  "inventory_id": "`inventory_id`",
  "customer_id": "`customer_id`",
  "return_date": "`return_date`",
  "staff_id": "`staff_id`",
  "last_update": "`last_update`",
});

/**
 * The column as a statement's text names it: quoted for MariaDB.
 *
 * The lookup is by own property and the refusal is unconditional, so a caller
 * that reached past the type — with an unchecked string, or a value read from
 * a request — is refused here rather than interpolated.
 *
 * @param {RentalColumn} column
 * @returns {string}
 * @throws {UnknownColumn} for every name the table does not carry.
 */
export function rentalColumnSql(column) {
  if (!Object.hasOwn(COLUMN_SQL, column)) {
    throw new UnknownColumn("sakila.rental", String(column));
  }
  return COLUMN_SQL[column];
}

/**
 * One ordering term of a search over `sakila.rental`.
 *
 * @typedef {object} RentalOrder
 * @property {RentalColumn} column the column to order by
 * @property {Direction} [direction] the direction to order in. Ascending when absent.
 */

/**
 * What narrows a search over `sakila.rental`.
 *
 * Every property is optional: a property left absent adds no condition, and the
 * conditions a search does build are joined with `AND`. The empty object is the
 * filter that matches every row.
 *
 * A property is absent for *no condition* and is never `null` for *is NULL*.
 * That question is asked through the `…IsNull` property a nullable column also
 * gets, so the two meanings never collide, and it is why no filter property
 * admits `null`.
 *
 * @typedef {object} RentalFilter
 * @property {number} [rentalId] where set, requires `rental_id` to equal it.
 * @property {number} [rentalIdFrom] where set, requires `rental_id` to be at least it.
 * @property {number} [rentalIdTo] where set, requires `rental_id` to be at most it.
 * @property {Date} [rentalDate] where set, requires `rental_date` to equal it.
 * @property {Date} [rentalDateFrom] where set, requires `rental_date` to be at least it.
 * @property {Date} [rentalDateTo] where set, requires `rental_date` to be at most it.
 * @property {number} [inventoryId] where set, requires `inventory_id` to equal it.
 * @property {number} [inventoryIdFrom] where set, requires `inventory_id` to be at least it.
 * @property {number} [inventoryIdTo] where set, requires `inventory_id` to be at most it.
 * @property {number} [customerId] where set, requires `customer_id` to equal it.
 * @property {number} [customerIdFrom] where set, requires `customer_id` to be at least it.
 * @property {number} [customerIdTo] where set, requires `customer_id` to be at most it.
 * @property {Date} [returnDate] where set, requires `return_date` to equal it.
 * @property {Date} [returnDateFrom] where set, requires `return_date` to be at least it.
 * @property {Date} [returnDateTo] where set, requires `return_date` to be at most it.
 * @property {boolean} [returnDateIsNull] where true, requires `return_date` to be NULL; where false, requires it not to be.
 * @property {number} [staffId] where set, requires `staff_id` to equal it.
 * @property {number} [staffIdFrom] where set, requires `staff_id` to be at least it.
 * @property {number} [staffIdTo] where set, requires `staff_id` to be at most it.
 * @property {Date} [lastUpdate] where set, requires `last_update` to equal it.
 * @property {Date} [lastUpdateFrom] where set, requires `last_update` to be at least it.
 * @property {Date} [lastUpdateTo] where set, requires `last_update` to be at most it.
 */
