// Code generated by tpl from sakila.staff. DO NOT EDIT.

/**
 * The `sakila.staff` row, the key that addresses it, the columns an ordering may
 * name, and the filter a search takes.
 *
 * @module
 */

/** @import { Direction } from './core.js' */

import { UnknownColumn } from './core.js';

/**
 * One row of `sakila.staff`.
 *
 * Every property is present on a row. A column that admits `NULL` is typed
 * `T | null`, which is what mysql2 hands back for a `NULL` and what `tsc`
 * makes a caller narrow before reading.
 *
 * @typedef {object} Staff
 * @property {number} staffId `staff_id`, declared `tinyint(3) unsigned` NOT NULL AUTO_INCREMENT.
 *   It is part of the primary key.
 * @property {string} firstName `first_name`, declared `varchar(45)` NOT NULL.
 * @property {string} lastName `last_name`, declared `varchar(45)` NOT NULL.
 * @property {number} addressId `address_id`, declared `smallint(5) unsigned` NOT NULL.
 * @property {Buffer | null} picture `picture`, declared `blob` NULL.
 * @property {string | null} email `email`, declared `varchar(50)` NULL.
 * @property {number} storeId `store_id`, declared `tinyint(3) unsigned` NOT NULL.
 * @property {number} active `active`, declared `tinyint(1)` NOT NULL.
 * @property {string} username `username`, declared `varchar(16)` NOT NULL.
 * @property {string | null} password `password`, declared `varchar(40)` NULL.
 * @property {Date} lastUpdate `last_update`, declared `timestamp` NOT NULL.
 */

/**
 * The primary key of `sakila.staff`.
 *
 * @typedef {object} StaffKey
 * @property {number} staffId `staff_id`, declared `tinyint(3) unsigned` NOT NULL AUTO_INCREMENT.
 */

/**
 * One column of `sakila.staff`.
 *
 * A search accepts an ordering term over these values and over nothing else,
 * so an ordering can carry no SQL of its own. A caller may write the column's
 * catalogue name as a string literal instead: {@link StaffColumn} is the union
 * of the values below, so the two are the same value and the same type.
 */
export const StaffColumns = Object.freeze(
  /** @type {const} */ ({
    /** `staff_id`, declared `tinyint(3) unsigned` NOT NULL AUTO_INCREMENT. */
    STAFF_ID: "staff_id",
    /** `first_name`, declared `varchar(45)` NOT NULL. */
    FIRST_NAME: "first_name",
    /** `last_name`, declared `varchar(45)` NOT NULL. */
    LAST_NAME: "last_name",
    /** `address_id`, declared `smallint(5) unsigned` NOT NULL. */
    ADDRESS_ID: "address_id",
    /** `picture`, declared `blob` NULL. */
    PICTURE: "picture",
    /** `email`, declared `varchar(50)` NULL. */
    EMAIL: "email",
    /** `store_id`, declared `tinyint(3) unsigned` NOT NULL. */
    STORE_ID: "store_id",
    /** `active`, declared `tinyint(1)` NOT NULL. */
    ACTIVE: "active",
    /** `username`, declared `varchar(16)` NOT NULL. */
    USERNAME: "username",
    /** `password`, declared `varchar(40)` NULL. */
    PASSWORD: "password",
    /** `last_update`, declared `timestamp` NOT NULL. */
    LAST_UPDATE: "last_update",
  }),
);

/**
 * A column of `sakila.staff` an ordering may name.
 *
 * @typedef {(typeof StaffColumns)[keyof typeof StaffColumns]} StaffColumn
 */

/**
 * The one place a column of `sakila.staff` becomes SQL.
 *
 * It is closed over the constants above, and every identifier in it was quoted
 * at render time by `tpl`, so no value a caller supplies can reach a
 * statement's text through an ordering term.
 *
 * @type {Readonly<Record<StaffColumn, string>>}
 */
const COLUMN_SQL = Object.freeze({
  "staff_id": "`staff_id`",
  "first_name": "`first_name`",
  "last_name": "`last_name`",
  "address_id": "`address_id`",
  "picture": "`picture`",
  "email": "`email`",
  "store_id": "`store_id`",
  "active": "`active`",
  "username": "`username`",
  "password": "`password`",
  "last_update": "`last_update`",
});

/**
 * The column as a statement's text names it: quoted for MariaDB.
 *
 * The lookup is by own property and the refusal is unconditional, so a caller
 * that reached past the type — with an unchecked string, or a value read from
 * a request — is refused here rather than interpolated.
 *
 * @param {StaffColumn} column
 * @returns {string}
 * @throws {UnknownColumn} for every name the table does not carry.
 */
export function staffColumnSql(column) {
  if (!Object.hasOwn(COLUMN_SQL, column)) {
    throw new UnknownColumn("sakila.staff", String(column));
  }
  return COLUMN_SQL[column];
}

/**
 * One ordering term of a search over `sakila.staff`.
 *
 * @typedef {object} StaffOrder
 * @property {StaffColumn} column the column to order by
 * @property {Direction} [direction] the direction to order in. Ascending when absent.
 */

/**
 * What narrows a search over `sakila.staff`.
 *
 * Every property is optional: a property left absent adds no condition, and the
 * conditions a search does build are joined with `AND`. The empty object is the
 * filter that matches every row.
 *
 * A property is absent for *no condition* and is never `null` for *is NULL*.
 * That question is asked through the `…IsNull` property a nullable column also
 * gets, so the two meanings never collide, and it is why no filter property
 * admits `null`.
 *
 * @typedef {object} StaffFilter
 * @property {number} [staffId] where set, requires `staff_id` to equal it.
 * @property {number} [staffIdFrom] where set, requires `staff_id` to be at least it.
 * @property {number} [staffIdTo] where set, requires `staff_id` to be at most it.
 * @property {string} [firstName] where set, requires `first_name` to equal it.
 * @property {string} [firstNameLike] where set, requires `first_name` to match it, as LIKE matches.
 * @property {string} [lastName] where set, requires `last_name` to equal it.
 * @property {string} [lastNameLike] where set, requires `last_name` to match it, as LIKE matches.
 * @property {number} [addressId] where set, requires `address_id` to equal it.
 * @property {number} [addressIdFrom] where set, requires `address_id` to be at least it.
 * @property {number} [addressIdTo] where set, requires `address_id` to be at most it.
 * @property {Buffer} [picture] where set, requires `picture` to equal it.
 * @property {boolean} [pictureIsNull] where true, requires `picture` to be NULL; where false, requires it not to be.
 * @property {string} [email] where set, requires `email` to equal it.
 * @property {string} [emailLike] where set, requires `email` to match it, as LIKE matches.
 * @property {boolean} [emailIsNull] where true, requires `email` to be NULL; where false, requires it not to be.
 * @property {number} [storeId] where set, requires `store_id` to equal it.
 * @property {number} [storeIdFrom] where set, requires `store_id` to be at least it.
 * @property {number} [storeIdTo] where set, requires `store_id` to be at most it.
 * @property {number} [active] where set, requires `active` to equal it.
 * @property {number} [activeFrom] where set, requires `active` to be at least it.
 * @property {number} [activeTo] where set, requires `active` to be at most it.
 * @property {string} [username] where set, requires `username` to equal it.
 * @property {string} [usernameLike] where set, requires `username` to match it, as LIKE matches.
 * @property {string} [password] where set, requires `password` to equal it.
 * @property {string} [passwordLike] where set, requires `password` to match it, as LIKE matches.
 * @property {boolean} [passwordIsNull] where true, requires `password` to be NULL; where false, requires it not to be.
 * @property {Date} [lastUpdate] where set, requires `last_update` to equal it.
 * @property {Date} [lastUpdateFrom] where set, requires `last_update` to be at least it.
 * @property {Date} [lastUpdateTo] where set, requires `last_update` to be at most it.
 */
