// Code generated by tpl from sakila.store. DO NOT EDIT.

/**
 * The mysql2 implementation of the `sakila.store` data layer.
 *
 * @module
 */

/** @import { Connection, ResultSetHeader, RowDataPacket } from 'mysql2/promise' */
/** @import { BoundValue } from './core.js' */
/** @import { Store, StoreFilter, StoreKey, StoreOrder } from './store.js' */

import { NotFound, directionSql, failure } from './core.js';
import { storeColumnSql } from './store.js';
import { StoreRepository } from './store_repository.js';

/** The table every statement of this module addresses, as an error names it. */
const TABLE = "sakila.store";

/** Selects every column of the table, in catalogue order. */
const SELECT = "SELECT `store_id`, `manager_staff_id`, `address_id`, `last_update` FROM `store`";

/** Selects the one row a primary key names. */
const READ = "SELECT `store_id`, `manager_staff_id`, `address_id`, `last_update` FROM `store` WHERE `store_id` = ?";

/**
 * Inserts one row. It names neither a generated column nor an auto-increment
 * key, because the server writes both.
 */
const INSERT = "INSERT INTO `store` (`manager_staff_id`, `address_id`, `last_update`) VALUES (?, ?, ?)";

/** Writes every column that is neither generated nor part of the key. */
const UPDATE = "UPDATE `store` SET `manager_staff_id` = ?, `address_id` = ?, `last_update` = ? WHERE `store_id` = ?";

/** Removes the one row a primary key names. */
const DELETE = "DELETE FROM `store` WHERE `store_id` = ?";

/**
 * Build a row from one result tuple.
 *
 * The positions are the order `SELECT` names the columns in, which is
 * catalogue order. Every statement below is run with `rowsAsArray`, so a
 * result is an array and never an object: a column named `__proto__` or
 * `constructor` would otherwise reach an object literal as a key, and the
 * first of those sets a prototype instead of defining a property.
 *
 * The values are whatever mysql2 decoded, and the types `Store` declares
 * are this example's record of what that is.
 *
 * @param {RowDataPacket} values
 * @returns {Store}
 */
function toRow(values) {
  return {
    storeId: values[0],
    managerStaffId: values[1],
    addressId: values[2],
    lastUpdate: values[3],
  };
}

/**
 * The mysql2 data layer of `sakila.store`.
 *
 * Nothing here commits. mysql2 autocommits until a caller calls
 * `beginTransaction`, so transaction control stays with the caller.
 */
export class StoreMysql2 extends StoreRepository {
  /** @type {Connection} */
  #connection;

  /**
   * Build the data layer of `sakila.store` over `connection`.
   *
   * The connection must address the schema `SCHEMA` names, because the
   * statements above address the table unqualified. `connect` is the
   * connection that carries it.
   *
   * @param {Connection} connection
   */
  constructor(connection) {
    super();
    this.#connection = connection;
  }

  /**
   * Insert `row`.
   *
   * The key is assigned by the server and is written back into `row`.
   *
   * @override
   * @param {Store} row
   * @returns {Promise<void>}
   */
  async create(row) {
    /** @type {BoundValue[]} */
    const values = [
      row.managerStaffId,
      row.addressId,
      row.lastUpdate,
    ];
    try {
      const [result] = await this.#connection.execute(INSERT, values);
      const { insertId } = /** @type {ResultSetHeader} */ (result);
      row.storeId = insertId;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Return the row `key` names.
   *
   * @override
   * @param {StoreKey} key
   * @returns {Promise<Store>}
   */
  async read(key) {
    /** @type {BoundValue[]} */
    const values = [
      key.storeId,
    ];
    try {
      const [rows] = await this.#connection.execute(
        { sql: READ, rowsAsArray: true },
        values,
      );
      const found = /** @type {RowDataPacket[]} */ (rows);
      if (found.length === 0) {
        throw new NotFound(TABLE);
      }
      return toRow(found[0]);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Write every writable column of `row` over the row its key names.
   *
   * @override
   * @param {Store} row
   * @returns {Promise<number>}
   */
  async update(row) {
    /** @type {BoundValue[]} */
    const values = [
      row.managerStaffId,
      row.addressId,
      row.lastUpdate,
      row.storeId,
    ];
    try {
      const [result] = await this.#connection.execute(UPDATE, values);
      return /** @type {ResultSetHeader} */ (result).affectedRows;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Remove the row `key` names.
   *
   * @override
   * @param {StoreKey} key
   * @returns {Promise<number>}
   */
  async delete(key) {
    /** @type {BoundValue[]} */
    const values = [
      key.storeId,
    ];
    try {
      const [result] = await this.#connection.execute(DELETE, values);
      return /** @type {ResultSetHeader} */ (result).affectedRows;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Return every row matching `criteria`, ordered by the terms of `order`.
   *
   * @override
   * @param {StoreFilter} criteria
   * @param {readonly StoreOrder[]} [order]
   * @param {number | null} [limit]
   * @param {number | null} [offset]
   * @returns {Promise<Store[]>}
   */
  async search(criteria, order = [], limit = null, offset = null) {
    /** @type {string[]} */
    const conditions = [];
    /** @type {BoundValue[]} */
    const values = [];

    if (criteria.storeId !== undefined) {
      conditions.push("`store_id` = ?");
      values.push(criteria.storeId);
    }
    if (criteria.storeIdFrom !== undefined) {
      conditions.push("`store_id` >= ?");
      values.push(criteria.storeIdFrom);
    }
    if (criteria.storeIdTo !== undefined) {
      conditions.push("`store_id` <= ?");
      values.push(criteria.storeIdTo);
    }
    if (criteria.managerStaffId !== undefined) {
      conditions.push("`manager_staff_id` = ?");
      values.push(criteria.managerStaffId);
    }
    if (criteria.managerStaffIdFrom !== undefined) {
      conditions.push("`manager_staff_id` >= ?");
      values.push(criteria.managerStaffIdFrom);
    }
    if (criteria.managerStaffIdTo !== undefined) {
      conditions.push("`manager_staff_id` <= ?");
      values.push(criteria.managerStaffIdTo);
    }
    if (criteria.addressId !== undefined) {
      conditions.push("`address_id` = ?");
      values.push(criteria.addressId);
    }
    if (criteria.addressIdFrom !== undefined) {
      conditions.push("`address_id` >= ?");
      values.push(criteria.addressIdFrom);
    }
    if (criteria.addressIdTo !== undefined) {
      conditions.push("`address_id` <= ?");
      values.push(criteria.addressIdTo);
    }
    if (criteria.lastUpdate !== undefined) {
      conditions.push("`last_update` = ?");
      values.push(criteria.lastUpdate);
    }
    if (criteria.lastUpdateFrom !== undefined) {
      conditions.push("`last_update` >= ?");
      values.push(criteria.lastUpdateFrom);
    }
    if (criteria.lastUpdateTo !== undefined) {
      conditions.push("`last_update` <= ?");
      values.push(criteria.lastUpdateTo);
    }

    let sql = SELECT;
    if (conditions.length > 0) {
      sql += ' WHERE ' + conditions.join(' AND ');
    }
    if (order.length > 0) {
      sql +=
        ' ORDER BY ' +
        order
          .map(
            (term) =>
              storeColumnSql(term.column) +
              ' ' +
              directionSql(term.direction ?? 'asc'),
          )
          .join(', ');
    }
    if (limit !== null) {
      sql += ' LIMIT ?';
      values.push(limit);
      if (offset !== null) {
        sql += ' OFFSET ?';
        values.push(offset);
      }
    }

    try {
      const [rows] = await this.#connection.execute(
        { sql, rowsAsArray: true },
        values,
      );
      return /** @type {RowDataPacket[]} */ (rows).map(toRow);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }
}
