# Code generated by tpl from sakila.actor. DO NOT EDIT.

"""The `sakila.actor` row, the key that addresses it, the columns an ordering may
name, and the filter a search takes.
"""

from __future__ import annotations

import dataclasses
import datetime
import enum
from collections.abc import Mapping
from typing import Final

from ._core import Direction, UnknownColumn

__all__ = [
    "Actor",
    "ActorColumn",
    "ActorFilter",
    "ActorKey",
    "ActorOrder",
]


@dataclasses.dataclass
class Actor:
    """One row of `sakila.actor`.

    The dataclass is mutable, because :meth:`create` writes a server-assigned
    key back into it.
    """

    #: `actor_id`, declared `smallint(5) unsigned` NOT NULL AUTO_INCREMENT.
    #:
    #: It is part of the primary key.
    actor_id: int
    #: `first_name`, declared `varchar(45)` NOT NULL.
    first_name: str
    #: `last_name`, declared `varchar(45)` NOT NULL.
    last_name: str
    #: `last_update`, declared `timestamp` NOT NULL.
    last_update: datetime.datetime

    def key(self) -> ActorKey:
        """Return the primary key of the row."""
        return ActorKey(
            actor_id=self.actor_id,
        )


@dataclasses.dataclass(frozen=True)
class ActorKey:
    """The primary key of `sakila.actor`.

    Frozen, so that it hashes and compares by value. Every type this example's
    mapping produces is hashable, so no key of these three schemas is refused
    for that reason.
    """

    #: `actor_id`, declared `smallint(5) unsigned` NOT NULL AUTO_INCREMENT.
    actor_id: int


class ActorColumn(enum.Enum):
    """One column of `sakila.actor`.

    A search accepts an ordering term over these members and over nothing else,
    so an ordering can carry no SQL of its own: :attr:`sql` answers from a
    closed mapping this template wrote, and :meth:`from_name` is the one door a
    name a caller supplied can come through.

    A member's value is the column's name as the catalogue carries it, which is
    what :meth:`from_name` matches on and what ``member.value`` returns.
    """

    #: `actor_id`, declared `smallint(5) unsigned` NOT NULL AUTO_INCREMENT.
    ACTOR_ID = "actor_id"
    #: `first_name`, declared `varchar(45)` NOT NULL.
    FIRST_NAME = "first_name"
    #: `last_name`, declared `varchar(45)` NOT NULL.
    LAST_NAME = "last_name"
    #: `last_update`, declared `timestamp` NOT NULL.
    LAST_UPDATE = "last_update"

    @property
    def sql(self) -> str:
        """The column as a statement's text names it: quoted for MariaDB."""
        return _COLUMNS[self]

    @classmethod
    def from_name(cls, name: str) -> ActorColumn:
        """Read a column a caller supplied as text.

        Raises:
            UnknownColumn: for every name the table does not carry. That
                refusal is what keeps a caller's text out of a statement.
        """
        try:
            return cls(name)
        except ValueError:
            raise UnknownColumn("sakila.actor", name) from None


#: The one place a column becomes SQL. It is closed over the enumeration above,
#: and every identifier in it was quoted at render time by `tpl`, so no value a
#: caller supplies can reach a statement's text through an ordering term.
_COLUMNS: Final[Mapping[ActorColumn, str]] = {
    ActorColumn.ACTOR_ID: "`actor_id`",
    ActorColumn.FIRST_NAME: "`first_name`",
    ActorColumn.LAST_NAME: "`last_name`",
    ActorColumn.LAST_UPDATE: "`last_update`",
}


@dataclasses.dataclass(frozen=True)
class ActorOrder:
    """One ordering term of a search over `sakila.actor`."""

    #: The column to order by.
    column: ActorColumn
    #: The direction to order in.
    direction: Direction = Direction.ASCENDING


@dataclasses.dataclass
class ActorFilter:
    """What narrows a search over `sakila.actor`.

    Every field is optional: a field left ``None`` adds no condition, and the
    conditions a search does build are joined with ``AND``. The default
    instance is the filter that matches every row.

    A nullable column's field is ``None`` for *no condition* and never for
    *is NULL*; that question is asked through the ``…_is_null`` field such a
    column also gets, so the two meanings never collide.
    """

    #: Where set, requires `actor_id` to equal it.
    actor_id: int | None = None
    #: Where set, requires `actor_id` to be at least it.
    actor_id_from: int | None = None
    #: Where set, requires `actor_id` to be at most it.
    actor_id_to: int | None = None
    #: Where set, requires `first_name` to equal it.
    first_name: str | None = None
    #: Where set, requires `first_name` to match it, as LIKE matches.
    first_name_like: str | None = None
    #: Where set, requires `last_name` to equal it.
    last_name: str | None = None
    #: Where set, requires `last_name` to match it, as LIKE matches.
    last_name_like: str | None = None
    #: Where set, requires `last_update` to equal it.
    last_update: datetime.datetime | None = None
    #: Where set, requires `last_update` to be at least it.
    last_update_from: datetime.datetime | None = None
    #: Where set, requires `last_update` to be at most it.
    last_update_to: datetime.datetime | None = None

    def is_empty(self) -> bool:
        """Is no field set?

        A search over an empty filter builds no ``WHERE`` clause and matches
        every row of the table.
        """
        return (
            self.actor_id is None
            and self.actor_id_from is None
            and self.actor_id_to is None
            and self.first_name is None
            and self.first_name_like is None
            and self.last_name is None
            and self.last_name_like is None
            and self.last_update is None
            and self.last_update_from is None
            and self.last_update_to is None
        )
