# Code generated by tpl from sakila.customer. DO NOT EDIT.

"""The PyMySQL implementation of the `sakila.customer` data layer."""

from __future__ import annotations

from collections.abc import Sequence
from typing import TYPE_CHECKING, Any, Final

from pymysql.connections import Connection
from pymysql.cursors import Cursor

from ._core import NotFound, translating
from .customer import Customer, CustomerFilter, CustomerKey, CustomerOrder
from .customer_repository import CustomerRepository

__all__ = ["CustomerPyMySQL"]

#: The table every statement of this module addresses, as an error names it.
TABLE: Final = "sakila.customer"

#: Selects every column of the table, in catalogue order.
SELECT: Final = "SELECT `customer_id`, `store_id`, `first_name`, `last_name`, `email`, `address_id`, `active`, `create_date`, `last_update` FROM `customer`"

#: Selects the one row a primary key names.
READ: Final = "SELECT `customer_id`, `store_id`, `first_name`, `last_name`, `email`, `address_id`, `active`, `create_date`, `last_update` FROM `customer` WHERE `customer_id` = %s"

#: Inserts one row. It names neither a generated column nor an auto-increment
#: key, because the server writes both.
INSERT: Final = "INSERT INTO `customer` (`store_id`, `first_name`, `last_name`, `email`, `address_id`, `active`, `create_date`, `last_update`) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)"

#: Writes every column that is neither generated nor part of the key.
UPDATE: Final = "UPDATE `customer` SET `store_id` = %s, `first_name` = %s, `last_name` = %s, `email` = %s, `address_id` = %s, `active` = %s, `create_date` = %s, `last_update` = %s WHERE `customer_id` = %s"

#: Removes the one row a primary key names.
DELETE: Final = "DELETE FROM `customer` WHERE `customer_id` = %s"


def _row(values: tuple[Any, ...]) -> Customer:
    """Build a row from one result tuple.

    The positions are the order :data:`SELECT` names the columns in, which is
    catalogue order. The values are whatever PyMySQL decoded, and the types the
    dataclass declares are this example's record of what that is.
    """
    return Customer(
        customer_id=values[0],
        store_id=values[1],
        first_name=values[2],
        last_name=values[3],
        email=values[4],
        address_id=values[5],
        active=values[6],
        create_date=values[7],
        last_update=values[8],
    )


class CustomerPyMySQL:
    """The PyMySQL data layer of `sakila.customer`.

    It names no base class. ``CustomerRepository`` is a ``Protocol`` and is
    satisfied structurally, and the check at the foot of this module is where
    `mypy` proves that this class satisfies it.
    """

    def __init__(self, connection: Connection[Cursor]) -> None:
        """Build the data layer of `sakila.customer` over `connection`.

        The connection must address the schema ``SCHEMA`` names, because the
        statements above address the table unqualified. ``connect`` is the
        connection that carries it.

        Nothing here commits. A connection opened by ``connect`` autocommits
        unless the caller said otherwise, so transaction control stays with the
        caller.
        """
        self._connection = connection

    def create(self, row: Customer) -> None:
        """Insert `row`.

        The key is assigned by the server and is written back into `row`.

        Raises:
            DatabaseFailure: where the server refused the insert.
        """
        with translating(TABLE), self._connection.cursor() as cursor:
            cursor.execute(
                INSERT,
                (
                    row.store_id,
                    row.first_name,
                    row.last_name,
                    row.email,
                    row.address_id,
                    row.active,
                    row.create_date,
                    row.last_update,
                ),
            )
            row.customer_id = cursor.lastrowid

    def read(self, key: CustomerKey) -> Customer:
        """Return the row `key` names.

        Raises:
            NotFound: where the table carries no such row.
            DatabaseFailure: where the server refused the query.
        """
        with translating(TABLE), self._connection.cursor() as cursor:
            cursor.execute(
                READ,
                (
                    key.customer_id,
                ),
            )
            found = cursor.fetchone()
        if found is None:
            raise NotFound(TABLE)
        return _row(found)

    def update(self, row: Customer) -> int:
        """Write every writable column of `row` over the row its key names.

        Returns:
            The number of rows the server reported as changed.

        Raises:
            DatabaseFailure: where the server refused the update.
        """
        with translating(TABLE), self._connection.cursor() as cursor:
            affected = cursor.execute(
                UPDATE,
                (
                    row.store_id,
                    row.first_name,
                    row.last_name,
                    row.email,
                    row.address_id,
                    row.active,
                    row.create_date,
                    row.last_update,
                    row.customer_id,
                ),
            )
        return affected

    def delete(self, key: CustomerKey) -> int:
        """Remove the row `key` names.

        Returns:
            The number of rows the server reported as removed.

        Raises:
            DatabaseFailure: where the server refused the delete.
        """
        with translating(TABLE), self._connection.cursor() as cursor:
            affected = cursor.execute(
                DELETE,
                (
                    key.customer_id,
                ),
            )
        return affected

    def search(
        self,
        criteria: CustomerFilter,
        order: Sequence[CustomerOrder] = (),
        limit: int | None = None,
        offset: int | None = None,
    ) -> list[Customer]:
        """Return every row matching `criteria`, ordered by the terms of `order`.

        Raises:
            DatabaseFailure: where the server refused the query.
        """
        statement: list[str] = [SELECT]
        conditions: list[str] = []
        arguments: list[object] = []

        if criteria.customer_id is not None:
            conditions.append("`customer_id` = %s")
            arguments.append(criteria.customer_id)
        if criteria.customer_id_from is not None:
            conditions.append("`customer_id` >= %s")
            arguments.append(criteria.customer_id_from)
        if criteria.customer_id_to is not None:
            conditions.append("`customer_id` <= %s")
            arguments.append(criteria.customer_id_to)
        if criteria.store_id is not None:
            conditions.append("`store_id` = %s")
            arguments.append(criteria.store_id)
        if criteria.store_id_from is not None:
            conditions.append("`store_id` >= %s")
            arguments.append(criteria.store_id_from)
        if criteria.store_id_to is not None:
            conditions.append("`store_id` <= %s")
            arguments.append(criteria.store_id_to)
        if criteria.first_name is not None:
            conditions.append("`first_name` = %s")
            arguments.append(criteria.first_name)
        if criteria.first_name_like is not None:
            conditions.append("`first_name` LIKE %s")
            arguments.append(criteria.first_name_like)
        if criteria.last_name is not None:
            conditions.append("`last_name` = %s")
            arguments.append(criteria.last_name)
        if criteria.last_name_like is not None:
            conditions.append("`last_name` LIKE %s")
            arguments.append(criteria.last_name_like)
        if criteria.email is not None:
            conditions.append("`email` = %s")
            arguments.append(criteria.email)
        if criteria.email_like is not None:
            conditions.append("`email` LIKE %s")
            arguments.append(criteria.email_like)
        if criteria.email_is_null is not None:
            conditions.append(
                "`email` IS NULL"
                if criteria.email_is_null
                else "`email` IS NOT NULL"
            )
        if criteria.address_id is not None:
            conditions.append("`address_id` = %s")
            arguments.append(criteria.address_id)
        if criteria.address_id_from is not None:
            conditions.append("`address_id` >= %s")
            arguments.append(criteria.address_id_from)
        if criteria.address_id_to is not None:
            conditions.append("`address_id` <= %s")
            arguments.append(criteria.address_id_to)
        if criteria.active is not None:
            conditions.append("`active` = %s")
            arguments.append(criteria.active)
        if criteria.active_from is not None:
            conditions.append("`active` >= %s")
            arguments.append(criteria.active_from)
        if criteria.active_to is not None:
            conditions.append("`active` <= %s")
            arguments.append(criteria.active_to)
        if criteria.create_date is not None:
            conditions.append("`create_date` = %s")
            arguments.append(criteria.create_date)
        if criteria.create_date_from is not None:
            conditions.append("`create_date` >= %s")
            arguments.append(criteria.create_date_from)
        if criteria.create_date_to is not None:
            conditions.append("`create_date` <= %s")
            arguments.append(criteria.create_date_to)
        if criteria.last_update is not None:
            conditions.append("`last_update` = %s")
            arguments.append(criteria.last_update)
        if criteria.last_update_from is not None:
            conditions.append("`last_update` >= %s")
            arguments.append(criteria.last_update_from)
        if criteria.last_update_to is not None:
            conditions.append("`last_update` <= %s")
            arguments.append(criteria.last_update_to)
        if criteria.last_update_is_null is not None:
            conditions.append(
                "`last_update` IS NULL"
                if criteria.last_update_is_null
                else "`last_update` IS NOT NULL"
            )

        if conditions:
            statement.append(" WHERE " + " AND ".join(conditions))
        if order:
            statement.append(
                " ORDER BY "
                + ", ".join(f"{term.column.sql} {term.direction.sql}" for term in order)
            )
        if limit is not None:
            statement.append(" LIMIT %s")
            arguments.append(limit)
            if offset is not None:
                statement.append(" OFFSET %s")
                arguments.append(offset)

        with translating(TABLE), self._connection.cursor() as cursor:
            cursor.execute("".join(statement), tuple(arguments))
            found = cursor.fetchall()
        return [_row(values) for values in found]


if TYPE_CHECKING:

    def _implements_the_protocol(
        implementation: CustomerPyMySQL,
    ) -> CustomerRepository:
        """Where `mypy` proves the implementation satisfies the contract.

        The return is the whole of the check: a method whose signature drifted
        from the protocol's fails the compile gate here, rather than a caller
        at run time. It costs nothing at run time because the block is never
        executed.
        """
        return implementation
