# Code generated by tpl from sakila.film_actor. DO NOT EDIT.

"""The PyMySQL implementation of the `sakila.film_actor` data layer."""

from __future__ import annotations

from collections.abc import Sequence
from typing import TYPE_CHECKING, Any, Final

from pymysql.connections import Connection
from pymysql.cursors import Cursor

from ._core import NotFound, translating
from .film_actor import FilmActor, FilmActorFilter, FilmActorKey, FilmActorOrder
from .film_actor_repository import FilmActorRepository

__all__ = ["FilmActorPyMySQL"]

#: The table every statement of this module addresses, as an error names it.
TABLE: Final = "sakila.film_actor"

#: Selects every column of the table, in catalogue order.
SELECT: Final = "SELECT `actor_id`, `film_id`, `last_update` FROM `film_actor`"

#: Selects the one row a primary key names.
READ: Final = "SELECT `actor_id`, `film_id`, `last_update` FROM `film_actor` WHERE `actor_id` = %s AND `film_id` = %s"

#: Inserts one row. It names neither a generated column nor an auto-increment
#: key, because the server writes both.
INSERT: Final = "INSERT INTO `film_actor` (`actor_id`, `film_id`, `last_update`) VALUES (%s, %s, %s)"

#: Writes every column that is neither generated nor part of the key.
UPDATE: Final = "UPDATE `film_actor` SET `last_update` = %s WHERE `actor_id` = %s AND `film_id` = %s"

#: Removes the one row a primary key names.
DELETE: Final = "DELETE FROM `film_actor` WHERE `actor_id` = %s AND `film_id` = %s"


def _row(values: tuple[Any, ...]) -> FilmActor:
    """Build a row from one result tuple.

    The positions are the order :data:`SELECT` names the columns in, which is
    catalogue order. The values are whatever PyMySQL decoded, and the types the
    dataclass declares are this example's record of what that is.
    """
    return FilmActor(
        actor_id=values[0],
        film_id=values[1],
        last_update=values[2],
    )


class FilmActorPyMySQL:
    """The PyMySQL data layer of `sakila.film_actor`.

    It names no base class. ``FilmActorRepository`` is a ``Protocol`` and is
    satisfied structurally, and the check at the foot of this module is where
    `mypy` proves that this class satisfies it.
    """

    def __init__(self, connection: Connection[Cursor]) -> None:
        """Build the data layer of `sakila.film_actor` over `connection`.

        The connection must address the schema ``SCHEMA`` names, because the
        statements above address the table unqualified. ``connect`` is the
        connection that carries it.

        Nothing here commits. A connection opened by ``connect`` autocommits
        unless the caller said otherwise, so transaction control stays with the
        caller.
        """
        self._connection = connection

    def create(self, row: FilmActor) -> None:
        """Insert `row`.

        The whole key is taken from `row`, which the caller therefore fills.

        Raises:
            DatabaseFailure: where the server refused the insert.
        """
        with translating(TABLE), self._connection.cursor() as cursor:
            cursor.execute(
                INSERT,
                (
                    row.actor_id,
                    row.film_id,
                    row.last_update,
                ),
            )

    def read(self, key: FilmActorKey) -> FilmActor:
        """Return the row `key` names.

        Raises:
            NotFound: where the table carries no such row.
            DatabaseFailure: where the server refused the query.
        """
        with translating(TABLE), self._connection.cursor() as cursor:
            cursor.execute(
                READ,
                (
                    key.actor_id,
                    key.film_id,
                ),
            )
            found = cursor.fetchone()
        if found is None:
            raise NotFound(TABLE)
        return _row(found)

    def update(self, row: FilmActor) -> int:
        """Write every writable column of `row` over the row its key names.

        Returns:
            The number of rows the server reported as changed.

        Raises:
            DatabaseFailure: where the server refused the update.
        """
        with translating(TABLE), self._connection.cursor() as cursor:
            affected = cursor.execute(
                UPDATE,
                (
                    row.last_update,
                    row.actor_id,
                    row.film_id,
                ),
            )
        return affected

    def delete(self, key: FilmActorKey) -> int:
        """Remove the row `key` names.

        Returns:
            The number of rows the server reported as removed.

        Raises:
            DatabaseFailure: where the server refused the delete.
        """
        with translating(TABLE), self._connection.cursor() as cursor:
            affected = cursor.execute(
                DELETE,
                (
                    key.actor_id,
                    key.film_id,
                ),
            )
        return affected

    def search(
        self,
        criteria: FilmActorFilter,
        order: Sequence[FilmActorOrder] = (),
        limit: int | None = None,
        offset: int | None = None,
    ) -> list[FilmActor]:
        """Return every row matching `criteria`, ordered by the terms of `order`.

        Raises:
            DatabaseFailure: where the server refused the query.
        """
        statement: list[str] = [SELECT]
        conditions: list[str] = []
        arguments: list[object] = []

        if criteria.actor_id is not None:
            conditions.append("`actor_id` = %s")
            arguments.append(criteria.actor_id)
        if criteria.actor_id_from is not None:
            conditions.append("`actor_id` >= %s")
            arguments.append(criteria.actor_id_from)
        if criteria.actor_id_to is not None:
            conditions.append("`actor_id` <= %s")
            arguments.append(criteria.actor_id_to)
        if criteria.film_id is not None:
            conditions.append("`film_id` = %s")
            arguments.append(criteria.film_id)
        if criteria.film_id_from is not None:
            conditions.append("`film_id` >= %s")
            arguments.append(criteria.film_id_from)
        if criteria.film_id_to is not None:
            conditions.append("`film_id` <= %s")
            arguments.append(criteria.film_id_to)
        if criteria.last_update is not None:
            conditions.append("`last_update` = %s")
            arguments.append(criteria.last_update)
        if criteria.last_update_from is not None:
            conditions.append("`last_update` >= %s")
            arguments.append(criteria.last_update_from)
        if criteria.last_update_to is not None:
            conditions.append("`last_update` <= %s")
            arguments.append(criteria.last_update_to)

        if conditions:
            statement.append(" WHERE " + " AND ".join(conditions))
        if order:
            statement.append(
                " ORDER BY "
                + ", ".join(f"{term.column.sql} {term.direction.sql}" for term in order)
            )
        if limit is not None:
            statement.append(" LIMIT %s")
            arguments.append(limit)
            if offset is not None:
                statement.append(" OFFSET %s")
                arguments.append(offset)

        with translating(TABLE), self._connection.cursor() as cursor:
            cursor.execute("".join(statement), tuple(arguments))
            found = cursor.fetchall()
        return [_row(values) for values in found]


if TYPE_CHECKING:

    def _implements_the_protocol(
        implementation: FilmActorPyMySQL,
    ) -> FilmActorRepository:
        """Where `mypy` proves the implementation satisfies the contract.

        The return is the whole of the check: a method whose signature drifted
        from the protocol's fails the compile gate here, rather than a caller
        at run time. It costs nothing at run time because the block is never
        executed.
        """
        return implementation
