# Code generated by tpl from sakila.film. DO NOT EDIT.

"""The `sakila.film` row, the key that addresses it, the columns an ordering may
name, and the filter a search takes.
"""

from __future__ import annotations

import dataclasses
import datetime
import decimal
import enum
from collections.abc import Mapping
from typing import Final

from ._core import Direction, UnknownColumn

__all__ = [
    "Film",
    "FilmColumn",
    "FilmFilter",
    "FilmKey",
    "FilmOrder",
]


@dataclasses.dataclass
class Film:
    """One row of `sakila.film`.

    The dataclass is mutable, because :meth:`create` writes a server-assigned
    key back into it.
    """

    #: `film_id`, declared `smallint(5) unsigned` NOT NULL AUTO_INCREMENT.
    #:
    #: It is part of the primary key.
    film_id: int
    #: `title`, declared `varchar(128)` NOT NULL.
    title: str
    #: `description`, declared `text` NULL.
    description: str | None
    #: `release_year`, declared `year(4)` NULL.
    release_year: int | None
    #: `language_id`, declared `tinyint(3) unsigned` NOT NULL.
    language_id: int
    #: `original_language_id`, declared `tinyint(3) unsigned` NULL.
    original_language_id: int | None
    #: `rental_duration`, declared `tinyint(3) unsigned` NOT NULL.
    rental_duration: int
    #: `rental_rate`, declared `decimal(4,2)` NOT NULL.
    rental_rate: decimal.Decimal
    #: `length`, declared `smallint(5) unsigned` NULL.
    length: int | None
    #: `replacement_cost`, declared `decimal(5,2)` NOT NULL.
    replacement_cost: decimal.Decimal
    #: `rating`, declared `enum('G','PG','PG-13','R','NC-17')` NULL.
    rating: str | None
    #: `special_features`, declared `set('Trailers','Commentaries','Deleted Scenes','Behind the Scenes')` NULL.
    special_features: str | None
    #: `last_update`, declared `timestamp` NOT NULL.
    last_update: datetime.datetime

    def key(self) -> FilmKey:
        """Return the primary key of the row."""
        return FilmKey(
            film_id=self.film_id,
        )


@dataclasses.dataclass(frozen=True)
class FilmKey:
    """The primary key of `sakila.film`.

    Frozen, so that it hashes and compares by value. Every type this example's
    mapping produces is hashable, so no key of these three schemas is refused
    for that reason.
    """

    #: `film_id`, declared `smallint(5) unsigned` NOT NULL AUTO_INCREMENT.
    film_id: int


class FilmColumn(enum.Enum):
    """One column of `sakila.film`.

    A search accepts an ordering term over these members and over nothing else,
    so an ordering can carry no SQL of its own: :attr:`sql` answers from a
    closed mapping this template wrote, and :meth:`from_name` is the one door a
    name a caller supplied can come through.

    A member's value is the column's name as the catalogue carries it, which is
    what :meth:`from_name` matches on and what ``member.value`` returns.
    """

    #: `film_id`, declared `smallint(5) unsigned` NOT NULL AUTO_INCREMENT.
    FILM_ID = "film_id"
    #: `title`, declared `varchar(128)` NOT NULL.
    TITLE = "title"
    #: `description`, declared `text` NULL.
    DESCRIPTION = "description"
    #: `release_year`, declared `year(4)` NULL.
    RELEASE_YEAR = "release_year"
    #: `language_id`, declared `tinyint(3) unsigned` NOT NULL.
    LANGUAGE_ID = "language_id"
    #: `original_language_id`, declared `tinyint(3) unsigned` NULL.
    ORIGINAL_LANGUAGE_ID = "original_language_id"
    #: `rental_duration`, declared `tinyint(3) unsigned` NOT NULL.
    RENTAL_DURATION = "rental_duration"
    #: `rental_rate`, declared `decimal(4,2)` NOT NULL.
    RENTAL_RATE = "rental_rate"
    #: `length`, declared `smallint(5) unsigned` NULL.
    LENGTH = "length"
    #: `replacement_cost`, declared `decimal(5,2)` NOT NULL.
    REPLACEMENT_COST = "replacement_cost"
    #: `rating`, declared `enum('G','PG','PG-13','R','NC-17')` NULL.
    RATING = "rating"
    #: `special_features`, declared `set('Trailers','Commentaries','Deleted Scenes','Behind the Scenes')` NULL.
    SPECIAL_FEATURES = "special_features"
    #: `last_update`, declared `timestamp` NOT NULL.
    LAST_UPDATE = "last_update"

    @property
    def sql(self) -> str:
        """The column as a statement's text names it: quoted for MariaDB."""
        return _COLUMNS[self]

    @classmethod
    def from_name(cls, name: str) -> FilmColumn:
        """Read a column a caller supplied as text.

        Raises:
            UnknownColumn: for every name the table does not carry. That
                refusal is what keeps a caller's text out of a statement.
        """
        try:
            return cls(name)
        except ValueError:
            raise UnknownColumn("sakila.film", name) from None


#: The one place a column becomes SQL. It is closed over the enumeration above,
#: and every identifier in it was quoted at render time by `tpl`, so no value a
#: caller supplies can reach a statement's text through an ordering term.
_COLUMNS: Final[Mapping[FilmColumn, str]] = {
    FilmColumn.FILM_ID: "`film_id`",
    FilmColumn.TITLE: "`title`",
    FilmColumn.DESCRIPTION: "`description`",
    FilmColumn.RELEASE_YEAR: "`release_year`",
    FilmColumn.LANGUAGE_ID: "`language_id`",
    FilmColumn.ORIGINAL_LANGUAGE_ID: "`original_language_id`",
    FilmColumn.RENTAL_DURATION: "`rental_duration`",
    FilmColumn.RENTAL_RATE: "`rental_rate`",
    FilmColumn.LENGTH: "`length`",
    FilmColumn.REPLACEMENT_COST: "`replacement_cost`",
    FilmColumn.RATING: "`rating`",
    FilmColumn.SPECIAL_FEATURES: "`special_features`",
    FilmColumn.LAST_UPDATE: "`last_update`",
}


@dataclasses.dataclass(frozen=True)
class FilmOrder:
    """One ordering term of a search over `sakila.film`."""

    #: The column to order by.
    column: FilmColumn
    #: The direction to order in.
    direction: Direction = Direction.ASCENDING


@dataclasses.dataclass
class FilmFilter:
    """What narrows a search over `sakila.film`.

    Every field is optional: a field left ``None`` adds no condition, and the
    conditions a search does build are joined with ``AND``. The default
    instance is the filter that matches every row.

    A nullable column's field is ``None`` for *no condition* and never for
    *is NULL*; that question is asked through the ``…_is_null`` field such a
    column also gets, so the two meanings never collide.
    """

    #: Where set, requires `film_id` to equal it.
    film_id: int | None = None
    #: Where set, requires `film_id` to be at least it.
    film_id_from: int | None = None
    #: Where set, requires `film_id` to be at most it.
    film_id_to: int | None = None
    #: Where set, requires `title` to equal it.
    title: str | None = None
    #: Where set, requires `title` to match it, as LIKE matches.
    title_like: str | None = None
    #: Where set, requires `description` to equal it.
    description: str | None = None
    #: Where set, requires `description` to match it, as LIKE matches.
    description_like: str | None = None
    #: Where True, requires `description` to be NULL; where False, requires it not to be.
    description_is_null: bool | None = None
    #: Where set, requires `release_year` to equal it.
    release_year: int | None = None
    #: Where set, requires `release_year` to be at least it.
    release_year_from: int | None = None
    #: Where set, requires `release_year` to be at most it.
    release_year_to: int | None = None
    #: Where True, requires `release_year` to be NULL; where False, requires it not to be.
    release_year_is_null: bool | None = None
    #: Where set, requires `language_id` to equal it.
    language_id: int | None = None
    #: Where set, requires `language_id` to be at least it.
    language_id_from: int | None = None
    #: Where set, requires `language_id` to be at most it.
    language_id_to: int | None = None
    #: Where set, requires `original_language_id` to equal it.
    original_language_id: int | None = None
    #: Where set, requires `original_language_id` to be at least it.
    original_language_id_from: int | None = None
    #: Where set, requires `original_language_id` to be at most it.
    original_language_id_to: int | None = None
    #: Where True, requires `original_language_id` to be NULL; where False, requires it not to be.
    original_language_id_is_null: bool | None = None
    #: Where set, requires `rental_duration` to equal it.
    rental_duration: int | None = None
    #: Where set, requires `rental_duration` to be at least it.
    rental_duration_from: int | None = None
    #: Where set, requires `rental_duration` to be at most it.
    rental_duration_to: int | None = None
    #: Where set, requires `rental_rate` to equal it.
    rental_rate: decimal.Decimal | None = None
    #: Where set, requires `rental_rate` to be at least it.
    rental_rate_from: decimal.Decimal | None = None
    #: Where set, requires `rental_rate` to be at most it.
    rental_rate_to: decimal.Decimal | None = None
    #: Where set, requires `length` to equal it.
    length: int | None = None
    #: Where set, requires `length` to be at least it.
    length_from: int | None = None
    #: Where set, requires `length` to be at most it.
    length_to: int | None = None
    #: Where True, requires `length` to be NULL; where False, requires it not to be.
    length_is_null: bool | None = None
    #: Where set, requires `replacement_cost` to equal it.
    replacement_cost: decimal.Decimal | None = None
    #: Where set, requires `replacement_cost` to be at least it.
    replacement_cost_from: decimal.Decimal | None = None
    #: Where set, requires `replacement_cost` to be at most it.
    replacement_cost_to: decimal.Decimal | None = None
    #: Where set, requires `rating` to equal it.
    rating: str | None = None
    #: Where set, requires `rating` to match it, as LIKE matches.
    rating_like: str | None = None
    #: Where True, requires `rating` to be NULL; where False, requires it not to be.
    rating_is_null: bool | None = None
    #: Where set, requires `special_features` to equal it.
    special_features: str | None = None
    #: Where set, requires `special_features` to match it, as LIKE matches.
    special_features_like: str | None = None
    #: Where True, requires `special_features` to be NULL; where False, requires it not to be.
    special_features_is_null: bool | None = None
    #: Where set, requires `last_update` to equal it.
    last_update: datetime.datetime | None = None
    #: Where set, requires `last_update` to be at least it.
    last_update_from: datetime.datetime | None = None
    #: Where set, requires `last_update` to be at most it.
    last_update_to: datetime.datetime | None = None

    def is_empty(self) -> bool:
        """Is no field set?

        A search over an empty filter builds no ``WHERE`` clause and matches
        every row of the table.
        """
        return (
            self.film_id is None
            and self.film_id_from is None
            and self.film_id_to is None
            and self.title is None
            and self.title_like is None
            and self.description is None
            and self.description_like is None
            and self.description_is_null is None
            and self.release_year is None
            and self.release_year_from is None
            and self.release_year_to is None
            and self.release_year_is_null is None
            and self.language_id is None
            and self.language_id_from is None
            and self.language_id_to is None
            and self.original_language_id is None
            and self.original_language_id_from is None
            and self.original_language_id_to is None
            and self.original_language_id_is_null is None
            and self.rental_duration is None
            and self.rental_duration_from is None
            and self.rental_duration_to is None
            and self.rental_rate is None
            and self.rental_rate_from is None
            and self.rental_rate_to is None
            and self.length is None
            and self.length_from is None
            and self.length_to is None
            and self.length_is_null is None
            and self.replacement_cost is None
            and self.replacement_cost_from is None
            and self.replacement_cost_to is None
            and self.rating is None
            and self.rating_like is None
            and self.rating_is_null is None
            and self.special_features is None
            and self.special_features_like is None
            and self.special_features_is_null is None
            and self.last_update is None
            and self.last_update_from is None
            and self.last_update_to is None
        )
