# Code generated by tpl from sakila.inventory. DO NOT EDIT.

"""The `sakila.inventory` row, the key that addresses it, the columns an ordering may
name, and the filter a search takes.
"""

from __future__ import annotations

import dataclasses
import datetime
import enum
from collections.abc import Mapping
from typing import Final

from ._core import Direction, UnknownColumn

__all__ = [
    "Inventory",
    "InventoryColumn",
    "InventoryFilter",
    "InventoryKey",
    "InventoryOrder",
]


@dataclasses.dataclass
class Inventory:
    """One row of `sakila.inventory`.

    The dataclass is mutable, because :meth:`create` writes a server-assigned
    key back into it.
    """

    #: `inventory_id`, declared `mediumint(8) unsigned` NOT NULL AUTO_INCREMENT.
    #:
    #: It is part of the primary key.
    inventory_id: int
    #: `film_id`, declared `smallint(5) unsigned` NOT NULL.
    film_id: int
    #: `store_id`, declared `tinyint(3) unsigned` NOT NULL.
    store_id: int
    #: `last_update`, declared `timestamp` NOT NULL.
    last_update: datetime.datetime

    def key(self) -> InventoryKey:
        """Return the primary key of the row."""
        return InventoryKey(
            inventory_id=self.inventory_id,
        )


@dataclasses.dataclass(frozen=True)
class InventoryKey:
    """The primary key of `sakila.inventory`.

    Frozen, so that it hashes and compares by value. Every type this example's
    mapping produces is hashable, so no key of these three schemas is refused
    for that reason.
    """

    #: `inventory_id`, declared `mediumint(8) unsigned` NOT NULL AUTO_INCREMENT.
    inventory_id: int


class InventoryColumn(enum.Enum):
    """One column of `sakila.inventory`.

    A search accepts an ordering term over these members and over nothing else,
    so an ordering can carry no SQL of its own: :attr:`sql` answers from a
    closed mapping this template wrote, and :meth:`from_name` is the one door a
    name a caller supplied can come through.

    A member's value is the column's name as the catalogue carries it, which is
    what :meth:`from_name` matches on and what ``member.value`` returns.
    """

    #: `inventory_id`, declared `mediumint(8) unsigned` NOT NULL AUTO_INCREMENT.
    INVENTORY_ID = "inventory_id"
    #: `film_id`, declared `smallint(5) unsigned` NOT NULL.
    FILM_ID = "film_id"
    #: `store_id`, declared `tinyint(3) unsigned` NOT NULL.
    STORE_ID = "store_id"
    #: `last_update`, declared `timestamp` NOT NULL.
    LAST_UPDATE = "last_update"

    @property
    def sql(self) -> str:
        """The column as a statement's text names it: quoted for MariaDB."""
        return _COLUMNS[self]

    @classmethod
    def from_name(cls, name: str) -> InventoryColumn:
        """Read a column a caller supplied as text.

        Raises:
            UnknownColumn: for every name the table does not carry. That
                refusal is what keeps a caller's text out of a statement.
        """
        try:
            return cls(name)
        except ValueError:
            raise UnknownColumn("sakila.inventory", name) from None


#: The one place a column becomes SQL. It is closed over the enumeration above,
#: and every identifier in it was quoted at render time by `tpl`, so no value a
#: caller supplies can reach a statement's text through an ordering term.
_COLUMNS: Final[Mapping[InventoryColumn, str]] = {
    InventoryColumn.INVENTORY_ID: "`inventory_id`",
    InventoryColumn.FILM_ID: "`film_id`",
    InventoryColumn.STORE_ID: "`store_id`",
    InventoryColumn.LAST_UPDATE: "`last_update`",
}


@dataclasses.dataclass(frozen=True)
class InventoryOrder:
    """One ordering term of a search over `sakila.inventory`."""

    #: The column to order by.
    column: InventoryColumn
    #: The direction to order in.
    direction: Direction = Direction.ASCENDING


@dataclasses.dataclass
class InventoryFilter:
    """What narrows a search over `sakila.inventory`.

    Every field is optional: a field left ``None`` adds no condition, and the
    conditions a search does build are joined with ``AND``. The default
    instance is the filter that matches every row.

    A nullable column's field is ``None`` for *no condition* and never for
    *is NULL*; that question is asked through the ``…_is_null`` field such a
    column also gets, so the two meanings never collide.
    """

    #: Where set, requires `inventory_id` to equal it.
    inventory_id: int | None = None
    #: Where set, requires `inventory_id` to be at least it.
    inventory_id_from: int | None = None
    #: Where set, requires `inventory_id` to be at most it.
    inventory_id_to: int | None = None
    #: Where set, requires `film_id` to equal it.
    film_id: int | None = None
    #: Where set, requires `film_id` to be at least it.
    film_id_from: int | None = None
    #: Where set, requires `film_id` to be at most it.
    film_id_to: int | None = None
    #: Where set, requires `store_id` to equal it.
    store_id: int | None = None
    #: Where set, requires `store_id` to be at least it.
    store_id_from: int | None = None
    #: Where set, requires `store_id` to be at most it.
    store_id_to: int | None = None
    #: Where set, requires `last_update` to equal it.
    last_update: datetime.datetime | None = None
    #: Where set, requires `last_update` to be at least it.
    last_update_from: datetime.datetime | None = None
    #: Where set, requires `last_update` to be at most it.
    last_update_to: datetime.datetime | None = None

    def is_empty(self) -> bool:
        """Is no field set?

        A search over an empty filter builds no ``WHERE`` clause and matches
        every row of the table.
        """
        return (
            self.inventory_id is None
            and self.inventory_id_from is None
            and self.inventory_id_to is None
            and self.film_id is None
            and self.film_id_from is None
            and self.film_id_to is None
            and self.store_id is None
            and self.store_id_from is None
            and self.store_id_to is None
            and self.last_update is None
            and self.last_update_from is None
            and self.last_update_to is None
        )
