# Code generated by tpl from freight.cargo_item. DO NOT EDIT.

"""The PyMySQL implementation of the `freight.cargo_item` data layer."""

from __future__ import annotations

from collections.abc import Sequence
from typing import TYPE_CHECKING, Any, Final

from pymysql.connections import Connection
from pymysql.cursors import Cursor

from ._core import NotFound, translating
from .cargo_item import CargoItem, CargoItemFilter, CargoItemKey, CargoItemOrder
from .cargo_item_repository import CargoItemRepository

__all__ = ["CargoItemPyMySQL"]

#: The table every statement of this module addresses, as an error names it.
TABLE: Final = "freight.cargo_item"

#: Selects every column of the table, in catalogue order.
SELECT: Final = "SELECT `cargo_item_id`, `consignment_id`, `container_id`, `line_number`, `hs_code`, `description`, `package_kind`, `package_count`, `gross_weight_kg`, `net_weight_kg`, `volume_cbm`, `chargeable_weight_kg`, `imdg_class`, `un_number`, `origin_country`, `unit_value`, `line_value` FROM `cargo_item`"

#: Selects the one row a primary key names.
READ: Final = "SELECT `cargo_item_id`, `consignment_id`, `container_id`, `line_number`, `hs_code`, `description`, `package_kind`, `package_count`, `gross_weight_kg`, `net_weight_kg`, `volume_cbm`, `chargeable_weight_kg`, `imdg_class`, `un_number`, `origin_country`, `unit_value`, `line_value` FROM `cargo_item` WHERE `cargo_item_id` = %s"

#: Inserts one row. It names neither a generated column nor an auto-increment
#: key, because the server writes both.
INSERT: Final = "INSERT INTO `cargo_item` (`consignment_id`, `container_id`, `line_number`, `hs_code`, `description`, `package_kind`, `package_count`, `gross_weight_kg`, `net_weight_kg`, `volume_cbm`, `imdg_class`, `un_number`, `origin_country`, `unit_value`) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"

#: Writes every column that is neither generated nor part of the key.
UPDATE: Final = "UPDATE `cargo_item` SET `consignment_id` = %s, `container_id` = %s, `line_number` = %s, `hs_code` = %s, `description` = %s, `package_kind` = %s, `package_count` = %s, `gross_weight_kg` = %s, `net_weight_kg` = %s, `volume_cbm` = %s, `imdg_class` = %s, `un_number` = %s, `origin_country` = %s, `unit_value` = %s WHERE `cargo_item_id` = %s"

#: Removes the one row a primary key names.
DELETE: Final = "DELETE FROM `cargo_item` WHERE `cargo_item_id` = %s"


def _row(values: tuple[Any, ...]) -> CargoItem:
    """Build a row from one result tuple.

    The positions are the order :data:`SELECT` names the columns in, which is
    catalogue order. The values are whatever PyMySQL decoded, and the types the
    dataclass declares are this example's record of what that is.
    """
    return CargoItem(
        cargo_item_id=values[0],
        consignment_id=values[1],
        container_id=values[2],
        line_number=values[3],
        hs_code=values[4],
        description=values[5],
        package_kind=values[6],
        package_count=values[7],
        gross_weight_kg=values[8],
        net_weight_kg=values[9],
        volume_cbm=values[10],
        chargeable_weight_kg=values[11],
        imdg_class=values[12],
        un_number=values[13],
        origin_country=values[14],
        unit_value=values[15],
        line_value=values[16],
    )


class CargoItemPyMySQL:
    """The PyMySQL data layer of `freight.cargo_item`.

    It names no base class. ``CargoItemRepository`` is a ``Protocol`` and is
    satisfied structurally, and the check at the foot of this module is where
    `mypy` proves that this class satisfies it.
    """

    def __init__(self, connection: Connection[Cursor]) -> None:
        """Build the data layer of `freight.cargo_item` over `connection`.

        The connection must address the schema ``SCHEMA`` names, because the
        statements above address the table unqualified. ``connect`` is the
        connection that carries it.

        Nothing here commits. A connection opened by ``connect`` autocommits
        unless the caller said otherwise, so transaction control stays with the
        caller.
        """
        self._connection = connection

    def create(self, row: CargoItem) -> None:
        """Insert `row`.

        The key is assigned by the server and is written back into `row`.

        Raises:
            DatabaseFailure: where the server refused the insert.
        """
        with translating(TABLE), self._connection.cursor() as cursor:
            cursor.execute(
                INSERT,
                (
                    row.consignment_id,
                    row.container_id,
                    row.line_number,
                    row.hs_code,
                    row.description,
                    row.package_kind,
                    row.package_count,
                    row.gross_weight_kg,
                    row.net_weight_kg,
                    row.volume_cbm,
                    row.imdg_class,
                    row.un_number,
                    row.origin_country,
                    row.unit_value,
                ),
            )
            row.cargo_item_id = cursor.lastrowid

    def read(self, key: CargoItemKey) -> CargoItem:
        """Return the row `key` names.

        Raises:
            NotFound: where the table carries no such row.
            DatabaseFailure: where the server refused the query.
        """
        with translating(TABLE), self._connection.cursor() as cursor:
            cursor.execute(
                READ,
                (
                    key.cargo_item_id,
                ),
            )
            found = cursor.fetchone()
        if found is None:
            raise NotFound(TABLE)
        return _row(found)

    def update(self, row: CargoItem) -> int:
        """Write every writable column of `row` over the row its key names.

        Returns:
            The number of rows the server reported as changed.

        Raises:
            DatabaseFailure: where the server refused the update.
        """
        with translating(TABLE), self._connection.cursor() as cursor:
            affected = cursor.execute(
                UPDATE,
                (
                    row.consignment_id,
                    row.container_id,
                    row.line_number,
                    row.hs_code,
                    row.description,
                    row.package_kind,
                    row.package_count,
                    row.gross_weight_kg,
                    row.net_weight_kg,
                    row.volume_cbm,
                    row.imdg_class,
                    row.un_number,
                    row.origin_country,
                    row.unit_value,
                    row.cargo_item_id,
                ),
            )
        return affected

    def delete(self, key: CargoItemKey) -> int:
        """Remove the row `key` names.

        Returns:
            The number of rows the server reported as removed.

        Raises:
            DatabaseFailure: where the server refused the delete.
        """
        with translating(TABLE), self._connection.cursor() as cursor:
            affected = cursor.execute(
                DELETE,
                (
                    key.cargo_item_id,
                ),
            )
        return affected

    def search(
        self,
        criteria: CargoItemFilter,
        order: Sequence[CargoItemOrder] = (),
        limit: int | None = None,
        offset: int | None = None,
    ) -> list[CargoItem]:
        """Return every row matching `criteria`, ordered by the terms of `order`.

        Raises:
            DatabaseFailure: where the server refused the query.
        """
        statement: list[str] = [SELECT]
        conditions: list[str] = []
        arguments: list[object] = []

        if criteria.cargo_item_id is not None:
            conditions.append("`cargo_item_id` = %s")
            arguments.append(criteria.cargo_item_id)
        if criteria.cargo_item_id_from is not None:
            conditions.append("`cargo_item_id` >= %s")
            arguments.append(criteria.cargo_item_id_from)
        if criteria.cargo_item_id_to is not None:
            conditions.append("`cargo_item_id` <= %s")
            arguments.append(criteria.cargo_item_id_to)
        if criteria.consignment_id is not None:
            conditions.append("`consignment_id` = %s")
            arguments.append(criteria.consignment_id)
        if criteria.consignment_id_from is not None:
            conditions.append("`consignment_id` >= %s")
            arguments.append(criteria.consignment_id_from)
        if criteria.consignment_id_to is not None:
            conditions.append("`consignment_id` <= %s")
            arguments.append(criteria.consignment_id_to)
        if criteria.container_id is not None:
            conditions.append("`container_id` = %s")
            arguments.append(criteria.container_id)
        if criteria.container_id_from is not None:
            conditions.append("`container_id` >= %s")
            arguments.append(criteria.container_id_from)
        if criteria.container_id_to is not None:
            conditions.append("`container_id` <= %s")
            arguments.append(criteria.container_id_to)
        if criteria.container_id_is_null is not None:
            conditions.append(
                "`container_id` IS NULL"
                if criteria.container_id_is_null
                else "`container_id` IS NOT NULL"
            )
        if criteria.line_number is not None:
            conditions.append("`line_number` = %s")
            arguments.append(criteria.line_number)
        if criteria.line_number_from is not None:
            conditions.append("`line_number` >= %s")
            arguments.append(criteria.line_number_from)
        if criteria.line_number_to is not None:
            conditions.append("`line_number` <= %s")
            arguments.append(criteria.line_number_to)
        if criteria.hs_code is not None:
            conditions.append("`hs_code` = %s")
            arguments.append(criteria.hs_code)
        if criteria.hs_code_like is not None:
            conditions.append("`hs_code` LIKE %s")
            arguments.append(criteria.hs_code_like)
        if criteria.description is not None:
            conditions.append("`description` = %s")
            arguments.append(criteria.description)
        if criteria.description_like is not None:
            conditions.append("`description` LIKE %s")
            arguments.append(criteria.description_like)
        if criteria.package_kind is not None:
            conditions.append("`package_kind` = %s")
            arguments.append(criteria.package_kind)
        if criteria.package_kind_like is not None:
            conditions.append("`package_kind` LIKE %s")
            arguments.append(criteria.package_kind_like)
        if criteria.package_count is not None:
            conditions.append("`package_count` = %s")
            arguments.append(criteria.package_count)
        if criteria.package_count_from is not None:
            conditions.append("`package_count` >= %s")
            arguments.append(criteria.package_count_from)
        if criteria.package_count_to is not None:
            conditions.append("`package_count` <= %s")
            arguments.append(criteria.package_count_to)
        if criteria.gross_weight_kg is not None:
            conditions.append("`gross_weight_kg` = %s")
            arguments.append(criteria.gross_weight_kg)
        if criteria.gross_weight_kg_from is not None:
            conditions.append("`gross_weight_kg` >= %s")
            arguments.append(criteria.gross_weight_kg_from)
        if criteria.gross_weight_kg_to is not None:
            conditions.append("`gross_weight_kg` <= %s")
            arguments.append(criteria.gross_weight_kg_to)
        if criteria.net_weight_kg is not None:
            conditions.append("`net_weight_kg` = %s")
            arguments.append(criteria.net_weight_kg)
        if criteria.net_weight_kg_from is not None:
            conditions.append("`net_weight_kg` >= %s")
            arguments.append(criteria.net_weight_kg_from)
        if criteria.net_weight_kg_to is not None:
            conditions.append("`net_weight_kg` <= %s")
            arguments.append(criteria.net_weight_kg_to)
        if criteria.volume_cbm is not None:
            conditions.append("`volume_cbm` = %s")
            arguments.append(criteria.volume_cbm)
        if criteria.volume_cbm_from is not None:
            conditions.append("`volume_cbm` >= %s")
            arguments.append(criteria.volume_cbm_from)
        if criteria.volume_cbm_to is not None:
            conditions.append("`volume_cbm` <= %s")
            arguments.append(criteria.volume_cbm_to)
        if criteria.chargeable_weight_kg is not None:
            conditions.append("`chargeable_weight_kg` = %s")
            arguments.append(criteria.chargeable_weight_kg)
        if criteria.chargeable_weight_kg_from is not None:
            conditions.append("`chargeable_weight_kg` >= %s")
            arguments.append(criteria.chargeable_weight_kg_from)
        if criteria.chargeable_weight_kg_to is not None:
            conditions.append("`chargeable_weight_kg` <= %s")
            arguments.append(criteria.chargeable_weight_kg_to)
        if criteria.chargeable_weight_kg_is_null is not None:
            conditions.append(
                "`chargeable_weight_kg` IS NULL"
                if criteria.chargeable_weight_kg_is_null
                else "`chargeable_weight_kg` IS NOT NULL"
            )
        if criteria.imdg_class is not None:
            conditions.append("`imdg_class` = %s")
            arguments.append(criteria.imdg_class)
        if criteria.imdg_class_like is not None:
            conditions.append("`imdg_class` LIKE %s")
            arguments.append(criteria.imdg_class_like)
        if criteria.un_number is not None:
            conditions.append("`un_number` = %s")
            arguments.append(criteria.un_number)
        if criteria.un_number_from is not None:
            conditions.append("`un_number` >= %s")
            arguments.append(criteria.un_number_from)
        if criteria.un_number_to is not None:
            conditions.append("`un_number` <= %s")
            arguments.append(criteria.un_number_to)
        if criteria.un_number_is_null is not None:
            conditions.append(
                "`un_number` IS NULL"
                if criteria.un_number_is_null
                else "`un_number` IS NOT NULL"
            )
        if criteria.origin_country is not None:
            conditions.append("`origin_country` = %s")
            arguments.append(criteria.origin_country)
        if criteria.origin_country_like is not None:
            conditions.append("`origin_country` LIKE %s")
            arguments.append(criteria.origin_country_like)
        if criteria.unit_value is not None:
            conditions.append("`unit_value` = %s")
            arguments.append(criteria.unit_value)
        if criteria.unit_value_from is not None:
            conditions.append("`unit_value` >= %s")
            arguments.append(criteria.unit_value_from)
        if criteria.unit_value_to is not None:
            conditions.append("`unit_value` <= %s")
            arguments.append(criteria.unit_value_to)
        if criteria.line_value is not None:
            conditions.append("`line_value` = %s")
            arguments.append(criteria.line_value)
        if criteria.line_value_from is not None:
            conditions.append("`line_value` >= %s")
            arguments.append(criteria.line_value_from)
        if criteria.line_value_to is not None:
            conditions.append("`line_value` <= %s")
            arguments.append(criteria.line_value_to)
        if criteria.line_value_is_null is not None:
            conditions.append(
                "`line_value` IS NULL"
                if criteria.line_value_is_null
                else "`line_value` IS NOT NULL"
            )

        if conditions:
            statement.append(" WHERE " + " AND ".join(conditions))
        if order:
            statement.append(
                " ORDER BY "
                + ", ".join(f"{term.column.sql} {term.direction.sql}" for term in order)
            )
        if limit is not None:
            statement.append(" LIMIT %s")
            arguments.append(limit)
            if offset is not None:
                statement.append(" OFFSET %s")
                arguments.append(offset)

        with translating(TABLE), self._connection.cursor() as cursor:
            cursor.execute("".join(statement), tuple(arguments))
            found = cursor.fetchall()
        return [_row(values) for values in found]


if TYPE_CHECKING:

    def _implements_the_protocol(
        implementation: CargoItemPyMySQL,
    ) -> CargoItemRepository:
        """Where `mypy` proves the implementation satisfies the contract.

        The return is the whole of the check: a method whose signature drifted
        from the protocol's fails the compile gate here, rather than a caller
        at run time. It costs nothing at run time because the block is never
        executed.
        """
        return implementation
