# Code generated by tpl from freight.container. DO NOT EDIT.

"""The `freight.container` row, the key that addresses it, the columns an ordering may
name, and the filter a search takes.
"""

from __future__ import annotations

import dataclasses
import datetime
import decimal
import enum
from collections.abc import Mapping
from typing import Final

from ._core import Direction, UnknownColumn

__all__ = [
    "Container",
    "ContainerColumn",
    "ContainerFilter",
    "ContainerKey",
    "ContainerOrder",
]


@dataclasses.dataclass
class Container:
    """One row of `freight.container`.

    The dataclass is mutable, because :meth:`create` writes a server-assigned
    key back into it.
    """

    # The table's own comment, as the catalogue carries it:
    # Contentores afectos a cada expedição, com massa bruta verificada (VGM)

    #: `container_id`, declared `bigint(20) unsigned` NOT NULL AUTO_INCREMENT.
    #:
    #: It is part of the primary key.
    container_id: int
    #: `equipment_no`, declared `char(11)` NOT NULL.
    #:
    #: It is part of a unique index.
    #:
    #: ISO 6346 equipment number: four-letter prefix, six digits, one check digit
    equipment_no: str
    #: `consignment_id`, declared `bigint(20) unsigned` NOT NULL.
    #:
    #: It is part of a unique index.
    consignment_id: int
    #: `iso_code`, declared `char(4)` NOT NULL.
    #:
    #: Defaults to the standard dry twenty-foot box
    iso_code: str
    #: `seal_number`, declared `varchar(15)` NULL.
    seal_number: str | None
    #: `tare_weight_kg`, declared `decimal(8,2)` NOT NULL.
    tare_weight_kg: decimal.Decimal
    #: `cargo_weight_kg`, declared `decimal(10,3)` NOT NULL.
    cargo_weight_kg: decimal.Decimal
    #: `vgm_kg`, declared `decimal(10,3)` NULL STORED GENERATED AS (`tare_weight_kg` + `cargo_weight_kg`).
    #:
    #: Stored generated column: SOLAS verified gross mass
    vgm_kg: decimal.Decimal | None
    #: `vgm_method`, declared `enum('Method 1 — weighbridge','Method 2 — calculated','Not yet verified')` NOT NULL.
    vgm_method: str
    #: `setpoint_celsius`, declared `decimal(4,1)` NULL.
    #:
    #: Reefer setpoint; NULL for a dry box
    setpoint_celsius: decimal.Decimal | None
    #: `humidity_pct`, declared `tinyint(3) unsigned` NULL.
    humidity_pct: int | None
    #: `vent_setting`, declared `varchar(12)` NULL.
    vent_setting: str | None
    #: `stow_position`, declared `varchar(8)` NULL.
    #:
    #: Bay-row-tier as loaded, e.g. 0340882
    stow_position: str | None
    #: `loaded_at`, declared `datetime(6)` NULL.
    loaded_at: datetime.datetime | None

    def key(self) -> ContainerKey:
        """Return the primary key of the row."""
        return ContainerKey(
            container_id=self.container_id,
        )


@dataclasses.dataclass(frozen=True)
class ContainerKey:
    """The primary key of `freight.container`.

    Frozen, so that it hashes and compares by value. Every type this example's
    mapping produces is hashable, so no key of these three schemas is refused
    for that reason.
    """

    #: `container_id`, declared `bigint(20) unsigned` NOT NULL AUTO_INCREMENT.
    container_id: int


class ContainerColumn(enum.Enum):
    """One column of `freight.container`.

    A search accepts an ordering term over these members and over nothing else,
    so an ordering can carry no SQL of its own: :attr:`sql` answers from a
    closed mapping this template wrote, and :meth:`from_name` is the one door a
    name a caller supplied can come through.

    A member's value is the column's name as the catalogue carries it, which is
    what :meth:`from_name` matches on and what ``member.value`` returns.
    """

    #: `container_id`, declared `bigint(20) unsigned` NOT NULL AUTO_INCREMENT.
    CONTAINER_ID = "container_id"
    #: `equipment_no`, declared `char(11)` NOT NULL.
    EQUIPMENT_NO = "equipment_no"
    #: `consignment_id`, declared `bigint(20) unsigned` NOT NULL.
    CONSIGNMENT_ID = "consignment_id"
    #: `iso_code`, declared `char(4)` NOT NULL.
    ISO_CODE = "iso_code"
    #: `seal_number`, declared `varchar(15)` NULL.
    SEAL_NUMBER = "seal_number"
    #: `tare_weight_kg`, declared `decimal(8,2)` NOT NULL.
    TARE_WEIGHT_KG = "tare_weight_kg"
    #: `cargo_weight_kg`, declared `decimal(10,3)` NOT NULL.
    CARGO_WEIGHT_KG = "cargo_weight_kg"
    #: `vgm_kg`, declared `decimal(10,3)` NULL STORED GENERATED AS (`tare_weight_kg` + `cargo_weight_kg`).
    VGM_KG = "vgm_kg"
    #: `vgm_method`, declared `enum('Method 1 — weighbridge','Method 2 — calculated','Not yet verified')` NOT NULL.
    VGM_METHOD = "vgm_method"
    #: `setpoint_celsius`, declared `decimal(4,1)` NULL.
    SETPOINT_CELSIUS = "setpoint_celsius"
    #: `humidity_pct`, declared `tinyint(3) unsigned` NULL.
    HUMIDITY_PCT = "humidity_pct"
    #: `vent_setting`, declared `varchar(12)` NULL.
    VENT_SETTING = "vent_setting"
    #: `stow_position`, declared `varchar(8)` NULL.
    STOW_POSITION = "stow_position"
    #: `loaded_at`, declared `datetime(6)` NULL.
    LOADED_AT = "loaded_at"

    @property
    def sql(self) -> str:
        """The column as a statement's text names it: quoted for MariaDB."""
        return _COLUMNS[self]

    @classmethod
    def from_name(cls, name: str) -> ContainerColumn:
        """Read a column a caller supplied as text.

        Raises:
            UnknownColumn: for every name the table does not carry. That
                refusal is what keeps a caller's text out of a statement.
        """
        try:
            return cls(name)
        except ValueError:
            raise UnknownColumn("freight.container", name) from None


#: The one place a column becomes SQL. It is closed over the enumeration above,
#: and every identifier in it was quoted at render time by `tpl`, so no value a
#: caller supplies can reach a statement's text through an ordering term.
_COLUMNS: Final[Mapping[ContainerColumn, str]] = {
    ContainerColumn.CONTAINER_ID: "`container_id`",
    ContainerColumn.EQUIPMENT_NO: "`equipment_no`",
    ContainerColumn.CONSIGNMENT_ID: "`consignment_id`",
    ContainerColumn.ISO_CODE: "`iso_code`",
    ContainerColumn.SEAL_NUMBER: "`seal_number`",
    ContainerColumn.TARE_WEIGHT_KG: "`tare_weight_kg`",
    ContainerColumn.CARGO_WEIGHT_KG: "`cargo_weight_kg`",
    ContainerColumn.VGM_KG: "`vgm_kg`",
    ContainerColumn.VGM_METHOD: "`vgm_method`",
    ContainerColumn.SETPOINT_CELSIUS: "`setpoint_celsius`",
    ContainerColumn.HUMIDITY_PCT: "`humidity_pct`",
    ContainerColumn.VENT_SETTING: "`vent_setting`",
    ContainerColumn.STOW_POSITION: "`stow_position`",
    ContainerColumn.LOADED_AT: "`loaded_at`",
}


@dataclasses.dataclass(frozen=True)
class ContainerOrder:
    """One ordering term of a search over `freight.container`."""

    #: The column to order by.
    column: ContainerColumn
    #: The direction to order in.
    direction: Direction = Direction.ASCENDING


@dataclasses.dataclass
class ContainerFilter:
    """What narrows a search over `freight.container`.

    Every field is optional: a field left ``None`` adds no condition, and the
    conditions a search does build are joined with ``AND``. The default
    instance is the filter that matches every row.

    A nullable column's field is ``None`` for *no condition* and never for
    *is NULL*; that question is asked through the ``…_is_null`` field such a
    column also gets, so the two meanings never collide.
    """

    #: Where set, requires `container_id` to equal it.
    container_id: int | None = None
    #: Where set, requires `container_id` to be at least it.
    container_id_from: int | None = None
    #: Where set, requires `container_id` to be at most it.
    container_id_to: int | None = None
    #: Where set, requires `equipment_no` to equal it.
    equipment_no: str | None = None
    #: Where set, requires `equipment_no` to match it, as LIKE matches.
    equipment_no_like: str | None = None
    #: Where set, requires `consignment_id` to equal it.
    consignment_id: int | None = None
    #: Where set, requires `consignment_id` to be at least it.
    consignment_id_from: int | None = None
    #: Where set, requires `consignment_id` to be at most it.
    consignment_id_to: int | None = None
    #: Where set, requires `iso_code` to equal it.
    iso_code: str | None = None
    #: Where set, requires `iso_code` to match it, as LIKE matches.
    iso_code_like: str | None = None
    #: Where set, requires `seal_number` to equal it.
    seal_number: str | None = None
    #: Where set, requires `seal_number` to match it, as LIKE matches.
    seal_number_like: str | None = None
    #: Where True, requires `seal_number` to be NULL; where False, requires it not to be.
    seal_number_is_null: bool | None = None
    #: Where set, requires `tare_weight_kg` to equal it.
    tare_weight_kg: decimal.Decimal | None = None
    #: Where set, requires `tare_weight_kg` to be at least it.
    tare_weight_kg_from: decimal.Decimal | None = None
    #: Where set, requires `tare_weight_kg` to be at most it.
    tare_weight_kg_to: decimal.Decimal | None = None
    #: Where set, requires `cargo_weight_kg` to equal it.
    cargo_weight_kg: decimal.Decimal | None = None
    #: Where set, requires `cargo_weight_kg` to be at least it.
    cargo_weight_kg_from: decimal.Decimal | None = None
    #: Where set, requires `cargo_weight_kg` to be at most it.
    cargo_weight_kg_to: decimal.Decimal | None = None
    #: Where set, requires `vgm_kg` to equal it.
    vgm_kg: decimal.Decimal | None = None
    #: Where set, requires `vgm_kg` to be at least it.
    vgm_kg_from: decimal.Decimal | None = None
    #: Where set, requires `vgm_kg` to be at most it.
    vgm_kg_to: decimal.Decimal | None = None
    #: Where True, requires `vgm_kg` to be NULL; where False, requires it not to be.
    vgm_kg_is_null: bool | None = None
    #: Where set, requires `vgm_method` to equal it.
    vgm_method: str | None = None
    #: Where set, requires `vgm_method` to match it, as LIKE matches.
    vgm_method_like: str | None = None
    #: Where set, requires `setpoint_celsius` to equal it.
    setpoint_celsius: decimal.Decimal | None = None
    #: Where set, requires `setpoint_celsius` to be at least it.
    setpoint_celsius_from: decimal.Decimal | None = None
    #: Where set, requires `setpoint_celsius` to be at most it.
    setpoint_celsius_to: decimal.Decimal | None = None
    #: Where True, requires `setpoint_celsius` to be NULL; where False, requires it not to be.
    setpoint_celsius_is_null: bool | None = None
    #: Where set, requires `humidity_pct` to equal it.
    humidity_pct: int | None = None
    #: Where set, requires `humidity_pct` to be at least it.
    humidity_pct_from: int | None = None
    #: Where set, requires `humidity_pct` to be at most it.
    humidity_pct_to: int | None = None
    #: Where True, requires `humidity_pct` to be NULL; where False, requires it not to be.
    humidity_pct_is_null: bool | None = None
    #: Where set, requires `vent_setting` to equal it.
    vent_setting: str | None = None
    #: Where set, requires `vent_setting` to match it, as LIKE matches.
    vent_setting_like: str | None = None
    #: Where True, requires `vent_setting` to be NULL; where False, requires it not to be.
    vent_setting_is_null: bool | None = None
    #: Where set, requires `stow_position` to equal it.
    stow_position: str | None = None
    #: Where set, requires `stow_position` to match it, as LIKE matches.
    stow_position_like: str | None = None
    #: Where True, requires `stow_position` to be NULL; where False, requires it not to be.
    stow_position_is_null: bool | None = None
    #: Where set, requires `loaded_at` to equal it.
    loaded_at: datetime.datetime | None = None
    #: Where set, requires `loaded_at` to be at least it.
    loaded_at_from: datetime.datetime | None = None
    #: Where set, requires `loaded_at` to be at most it.
    loaded_at_to: datetime.datetime | None = None
    #: Where True, requires `loaded_at` to be NULL; where False, requires it not to be.
    loaded_at_is_null: bool | None = None

    def is_empty(self) -> bool:
        """Is no field set?

        A search over an empty filter builds no ``WHERE`` clause and matches
        every row of the table.
        """
        return (
            self.container_id is None
            and self.container_id_from is None
            and self.container_id_to is None
            and self.equipment_no is None
            and self.equipment_no_like is None
            and self.consignment_id is None
            and self.consignment_id_from is None
            and self.consignment_id_to is None
            and self.iso_code is None
            and self.iso_code_like is None
            and self.seal_number is None
            and self.seal_number_like is None
            and self.seal_number_is_null is None
            and self.tare_weight_kg is None
            and self.tare_weight_kg_from is None
            and self.tare_weight_kg_to is None
            and self.cargo_weight_kg is None
            and self.cargo_weight_kg_from is None
            and self.cargo_weight_kg_to is None
            and self.vgm_kg is None
            and self.vgm_kg_from is None
            and self.vgm_kg_to is None
            and self.vgm_kg_is_null is None
            and self.vgm_method is None
            and self.vgm_method_like is None
            and self.setpoint_celsius is None
            and self.setpoint_celsius_from is None
            and self.setpoint_celsius_to is None
            and self.setpoint_celsius_is_null is None
            and self.humidity_pct is None
            and self.humidity_pct_from is None
            and self.humidity_pct_to is None
            and self.humidity_pct_is_null is None
            and self.vent_setting is None
            and self.vent_setting_like is None
            and self.vent_setting_is_null is None
            and self.stow_position is None
            and self.stow_position_like is None
            and self.stow_position_is_null is None
            and self.loaded_at is None
            and self.loaded_at_from is None
            and self.loaded_at_to is None
            and self.loaded_at_is_null is None
        )
