# Code generated by tpl from freight.customs_declaration. DO NOT EDIT.

"""The `freight.customs_declaration` row, the key that addresses it, the columns an ordering may
name, and the filter a search takes.
"""

from __future__ import annotations

import dataclasses
import datetime
import decimal
import enum
from collections.abc import Mapping
from typing import Final

from ._core import Direction, UnknownColumn

__all__ = [
    "CustomsDeclaration",
    "CustomsDeclarationColumn",
    "CustomsDeclarationFilter",
    "CustomsDeclarationKey",
    "CustomsDeclarationOrder",
]


@dataclasses.dataclass
class CustomsDeclaration:
    """One row of `freight.customs_declaration`.

    The dataclass is mutable, because :meth:`create` writes a server-assigned
    key back into it.
    """

    # The table's own comment, as the catalogue carries it:
    # Declarações aduaneiras associadas às expedições

    #: `declaration_id`, declared `bigint(20) unsigned` NOT NULL AUTO_INCREMENT.
    #:
    #: It is part of the primary key.
    declaration_id: int
    #: `consignment_id`, declared `bigint(20) unsigned` NOT NULL.
    consignment_id: int
    #: `clearance_port_id`, declared `smallint(5) unsigned` NULL.
    #:
    #: NULL once the port record is retired; the declaration itself must survive
    clearance_port_id: int | None
    #: `mrn`, declared `varchar(21)` NOT NULL.
    #:
    #: It is part of a unique index.
    #:
    #: Movement Reference Number issued by the customs office
    mrn: str
    #: `procedure_code`, declared `char(4)` NOT NULL.
    procedure_code: str
    #: `regime`, declared `enum('Export','Import','Transit T1','Transit T2','Temporary admission','Re-export')` NOT NULL.
    regime: str
    #: `status`, declared `enum('Draft','Lodged','Under control','Released','Rejected')` NOT NULL.
    status: str
    #: `lodged_at`, declared `datetime(6)` NULL.
    lodged_at: datetime.datetime | None
    #: `released_at`, declared `datetime(6)` NULL.
    released_at: datetime.datetime | None
    #: `duty_amount`, declared `decimal(12,2)` NOT NULL.
    duty_amount: decimal.Decimal
    #: `vat_amount`, declared `decimal(12,2)` NOT NULL.
    vat_amount: decimal.Decimal
    #: `total_payable`, declared `decimal(12,2)` NULL STORED GENERATED AS (`duty_amount` + `vat_amount`).
    total_payable: decimal.Decimal | None
    #: `officer_remarks`, declared `varchar(500)` NULL.
    officer_remarks: str | None

    def key(self) -> CustomsDeclarationKey:
        """Return the primary key of the row."""
        return CustomsDeclarationKey(
            declaration_id=self.declaration_id,
        )


@dataclasses.dataclass(frozen=True)
class CustomsDeclarationKey:
    """The primary key of `freight.customs_declaration`.

    Frozen, so that it hashes and compares by value. Every type this example's
    mapping produces is hashable, so no key of these three schemas is refused
    for that reason.
    """

    #: `declaration_id`, declared `bigint(20) unsigned` NOT NULL AUTO_INCREMENT.
    declaration_id: int


class CustomsDeclarationColumn(enum.Enum):
    """One column of `freight.customs_declaration`.

    A search accepts an ordering term over these members and over nothing else,
    so an ordering can carry no SQL of its own: :attr:`sql` answers from a
    closed mapping this template wrote, and :meth:`from_name` is the one door a
    name a caller supplied can come through.

    A member's value is the column's name as the catalogue carries it, which is
    what :meth:`from_name` matches on and what ``member.value`` returns.
    """

    #: `declaration_id`, declared `bigint(20) unsigned` NOT NULL AUTO_INCREMENT.
    DECLARATION_ID = "declaration_id"
    #: `consignment_id`, declared `bigint(20) unsigned` NOT NULL.
    CONSIGNMENT_ID = "consignment_id"
    #: `clearance_port_id`, declared `smallint(5) unsigned` NULL.
    CLEARANCE_PORT_ID = "clearance_port_id"
    #: `mrn`, declared `varchar(21)` NOT NULL.
    MRN = "mrn"
    #: `procedure_code`, declared `char(4)` NOT NULL.
    PROCEDURE_CODE = "procedure_code"
    #: `regime`, declared `enum('Export','Import','Transit T1','Transit T2','Temporary admission','Re-export')` NOT NULL.
    REGIME = "regime"
    #: `status`, declared `enum('Draft','Lodged','Under control','Released','Rejected')` NOT NULL.
    STATUS = "status"
    #: `lodged_at`, declared `datetime(6)` NULL.
    LODGED_AT = "lodged_at"
    #: `released_at`, declared `datetime(6)` NULL.
    RELEASED_AT = "released_at"
    #: `duty_amount`, declared `decimal(12,2)` NOT NULL.
    DUTY_AMOUNT = "duty_amount"
    #: `vat_amount`, declared `decimal(12,2)` NOT NULL.
    VAT_AMOUNT = "vat_amount"
    #: `total_payable`, declared `decimal(12,2)` NULL STORED GENERATED AS (`duty_amount` + `vat_amount`).
    TOTAL_PAYABLE = "total_payable"
    #: `officer_remarks`, declared `varchar(500)` NULL.
    OFFICER_REMARKS = "officer_remarks"

    @property
    def sql(self) -> str:
        """The column as a statement's text names it: quoted for MariaDB."""
        return _COLUMNS[self]

    @classmethod
    def from_name(cls, name: str) -> CustomsDeclarationColumn:
        """Read a column a caller supplied as text.

        Raises:
            UnknownColumn: for every name the table does not carry. That
                refusal is what keeps a caller's text out of a statement.
        """
        try:
            return cls(name)
        except ValueError:
            raise UnknownColumn("freight.customs_declaration", name) from None


#: The one place a column becomes SQL. It is closed over the enumeration above,
#: and every identifier in it was quoted at render time by `tpl`, so no value a
#: caller supplies can reach a statement's text through an ordering term.
_COLUMNS: Final[Mapping[CustomsDeclarationColumn, str]] = {
    CustomsDeclarationColumn.DECLARATION_ID: "`declaration_id`",
    CustomsDeclarationColumn.CONSIGNMENT_ID: "`consignment_id`",
    CustomsDeclarationColumn.CLEARANCE_PORT_ID: "`clearance_port_id`",
    CustomsDeclarationColumn.MRN: "`mrn`",
    CustomsDeclarationColumn.PROCEDURE_CODE: "`procedure_code`",
    CustomsDeclarationColumn.REGIME: "`regime`",
    CustomsDeclarationColumn.STATUS: "`status`",
    CustomsDeclarationColumn.LODGED_AT: "`lodged_at`",
    CustomsDeclarationColumn.RELEASED_AT: "`released_at`",
    CustomsDeclarationColumn.DUTY_AMOUNT: "`duty_amount`",
    CustomsDeclarationColumn.VAT_AMOUNT: "`vat_amount`",
    CustomsDeclarationColumn.TOTAL_PAYABLE: "`total_payable`",
    CustomsDeclarationColumn.OFFICER_REMARKS: "`officer_remarks`",
}


@dataclasses.dataclass(frozen=True)
class CustomsDeclarationOrder:
    """One ordering term of a search over `freight.customs_declaration`."""

    #: The column to order by.
    column: CustomsDeclarationColumn
    #: The direction to order in.
    direction: Direction = Direction.ASCENDING


@dataclasses.dataclass
class CustomsDeclarationFilter:
    """What narrows a search over `freight.customs_declaration`.

    Every field is optional: a field left ``None`` adds no condition, and the
    conditions a search does build are joined with ``AND``. The default
    instance is the filter that matches every row.

    A nullable column's field is ``None`` for *no condition* and never for
    *is NULL*; that question is asked through the ``…_is_null`` field such a
    column also gets, so the two meanings never collide.
    """

    #: Where set, requires `declaration_id` to equal it.
    declaration_id: int | None = None
    #: Where set, requires `declaration_id` to be at least it.
    declaration_id_from: int | None = None
    #: Where set, requires `declaration_id` to be at most it.
    declaration_id_to: int | None = None
    #: Where set, requires `consignment_id` to equal it.
    consignment_id: int | None = None
    #: Where set, requires `consignment_id` to be at least it.
    consignment_id_from: int | None = None
    #: Where set, requires `consignment_id` to be at most it.
    consignment_id_to: int | None = None
    #: Where set, requires `clearance_port_id` to equal it.
    clearance_port_id: int | None = None
    #: Where set, requires `clearance_port_id` to be at least it.
    clearance_port_id_from: int | None = None
    #: Where set, requires `clearance_port_id` to be at most it.
    clearance_port_id_to: int | None = None
    #: Where True, requires `clearance_port_id` to be NULL; where False, requires it not to be.
    clearance_port_id_is_null: bool | None = None
    #: Where set, requires `mrn` to equal it.
    mrn: str | None = None
    #: Where set, requires `mrn` to match it, as LIKE matches.
    mrn_like: str | None = None
    #: Where set, requires `procedure_code` to equal it.
    procedure_code: str | None = None
    #: Where set, requires `procedure_code` to match it, as LIKE matches.
    procedure_code_like: str | None = None
    #: Where set, requires `regime` to equal it.
    regime: str | None = None
    #: Where set, requires `regime` to match it, as LIKE matches.
    regime_like: str | None = None
    #: Where set, requires `status` to equal it.
    status: str | None = None
    #: Where set, requires `status` to match it, as LIKE matches.
    status_like: str | None = None
    #: Where set, requires `lodged_at` to equal it.
    lodged_at: datetime.datetime | None = None
    #: Where set, requires `lodged_at` to be at least it.
    lodged_at_from: datetime.datetime | None = None
    #: Where set, requires `lodged_at` to be at most it.
    lodged_at_to: datetime.datetime | None = None
    #: Where True, requires `lodged_at` to be NULL; where False, requires it not to be.
    lodged_at_is_null: bool | None = None
    #: Where set, requires `released_at` to equal it.
    released_at: datetime.datetime | None = None
    #: Where set, requires `released_at` to be at least it.
    released_at_from: datetime.datetime | None = None
    #: Where set, requires `released_at` to be at most it.
    released_at_to: datetime.datetime | None = None
    #: Where True, requires `released_at` to be NULL; where False, requires it not to be.
    released_at_is_null: bool | None = None
    #: Where set, requires `duty_amount` to equal it.
    duty_amount: decimal.Decimal | None = None
    #: Where set, requires `duty_amount` to be at least it.
    duty_amount_from: decimal.Decimal | None = None
    #: Where set, requires `duty_amount` to be at most it.
    duty_amount_to: decimal.Decimal | None = None
    #: Where set, requires `vat_amount` to equal it.
    vat_amount: decimal.Decimal | None = None
    #: Where set, requires `vat_amount` to be at least it.
    vat_amount_from: decimal.Decimal | None = None
    #: Where set, requires `vat_amount` to be at most it.
    vat_amount_to: decimal.Decimal | None = None
    #: Where set, requires `total_payable` to equal it.
    total_payable: decimal.Decimal | None = None
    #: Where set, requires `total_payable` to be at least it.
    total_payable_from: decimal.Decimal | None = None
    #: Where set, requires `total_payable` to be at most it.
    total_payable_to: decimal.Decimal | None = None
    #: Where True, requires `total_payable` to be NULL; where False, requires it not to be.
    total_payable_is_null: bool | None = None
    #: Where set, requires `officer_remarks` to equal it.
    officer_remarks: str | None = None
    #: Where set, requires `officer_remarks` to match it, as LIKE matches.
    officer_remarks_like: str | None = None
    #: Where True, requires `officer_remarks` to be NULL; where False, requires it not to be.
    officer_remarks_is_null: bool | None = None

    def is_empty(self) -> bool:
        """Is no field set?

        A search over an empty filter builds no ``WHERE`` clause and matches
        every row of the table.
        """
        return (
            self.declaration_id is None
            and self.declaration_id_from is None
            and self.declaration_id_to is None
            and self.consignment_id is None
            and self.consignment_id_from is None
            and self.consignment_id_to is None
            and self.clearance_port_id is None
            and self.clearance_port_id_from is None
            and self.clearance_port_id_to is None
            and self.clearance_port_id_is_null is None
            and self.mrn is None
            and self.mrn_like is None
            and self.procedure_code is None
            and self.procedure_code_like is None
            and self.regime is None
            and self.regime_like is None
            and self.status is None
            and self.status_like is None
            and self.lodged_at is None
            and self.lodged_at_from is None
            and self.lodged_at_to is None
            and self.lodged_at_is_null is None
            and self.released_at is None
            and self.released_at_from is None
            and self.released_at_to is None
            and self.released_at_is_null is None
            and self.duty_amount is None
            and self.duty_amount_from is None
            and self.duty_amount_to is None
            and self.vat_amount is None
            and self.vat_amount_from is None
            and self.vat_amount_to is None
            and self.total_payable is None
            and self.total_payable_from is None
            and self.total_payable_to is None
            and self.total_payable_is_null is None
            and self.officer_remarks is None
            and self.officer_remarks_like is None
            and self.officer_remarks_is_null is None
        )
