# Code generated by tpl from freight.port. DO NOT EDIT.

"""The PyMySQL implementation of the `freight.port` data layer."""

from __future__ import annotations

from collections.abc import Sequence
from typing import TYPE_CHECKING, Any, Final

from pymysql.connections import Connection
from pymysql.cursors import Cursor

from ._core import NotFound, translating
from .port import Port, PortFilter, PortKey, PortOrder
from .port_repository import PortRepository

__all__ = ["PortPyMySQL"]

#: The table every statement of this module addresses, as an error names it.
TABLE: Final = "freight.port"

#: Selects every column of the table, in catalogue order.
SELECT: Final = "SELECT `port_id`, `un_locode`, `name`, `country_code`, `local_name`, `timezone_name`, `utc_offset_minutes`, `berth_count`, `max_draught_m`, `tidal_range_m`, `annual_throughput_teu`, `customs_round_clock`, `harbour_dues_currency`, `approach_notes` FROM `port`"

#: Selects the one row a primary key names.
READ: Final = "SELECT `port_id`, `un_locode`, `name`, `country_code`, `local_name`, `timezone_name`, `utc_offset_minutes`, `berth_count`, `max_draught_m`, `tidal_range_m`, `annual_throughput_teu`, `customs_round_clock`, `harbour_dues_currency`, `approach_notes` FROM `port` WHERE `port_id` = %s"

#: Inserts one row. It names neither a generated column nor an auto-increment
#: key, because the server writes both.
INSERT: Final = "INSERT INTO `port` (`un_locode`, `name`, `country_code`, `local_name`, `timezone_name`, `utc_offset_minutes`, `berth_count`, `max_draught_m`, `tidal_range_m`, `annual_throughput_teu`, `customs_round_clock`, `harbour_dues_currency`, `approach_notes`) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"

#: Writes every column that is neither generated nor part of the key.
UPDATE: Final = "UPDATE `port` SET `un_locode` = %s, `name` = %s, `country_code` = %s, `local_name` = %s, `timezone_name` = %s, `utc_offset_minutes` = %s, `berth_count` = %s, `max_draught_m` = %s, `tidal_range_m` = %s, `annual_throughput_teu` = %s, `customs_round_clock` = %s, `harbour_dues_currency` = %s, `approach_notes` = %s WHERE `port_id` = %s"

#: Removes the one row a primary key names.
DELETE: Final = "DELETE FROM `port` WHERE `port_id` = %s"


def _row(values: tuple[Any, ...]) -> Port:
    """Build a row from one result tuple.

    The positions are the order :data:`SELECT` names the columns in, which is
    catalogue order. The values are whatever PyMySQL decoded, and the types the
    dataclass declares are this example's record of what that is.
    """
    return Port(
        port_id=values[0],
        un_locode=values[1],
        name=values[2],
        country_code=values[3],
        local_name=values[4],
        timezone_name=values[5],
        utc_offset_minutes=values[6],
        berth_count=values[7],
        max_draught_m=values[8],
        tidal_range_m=values[9],
        annual_throughput_teu=values[10],
        customs_round_clock=values[11],
        harbour_dues_currency=values[12],
        approach_notes=values[13],
    )


class PortPyMySQL:
    """The PyMySQL data layer of `freight.port`.

    It names no base class. ``PortRepository`` is a ``Protocol`` and is
    satisfied structurally, and the check at the foot of this module is where
    `mypy` proves that this class satisfies it.
    """

    def __init__(self, connection: Connection[Cursor]) -> None:
        """Build the data layer of `freight.port` over `connection`.

        The connection must address the schema ``SCHEMA`` names, because the
        statements above address the table unqualified. ``connect`` is the
        connection that carries it.

        Nothing here commits. A connection opened by ``connect`` autocommits
        unless the caller said otherwise, so transaction control stays with the
        caller.
        """
        self._connection = connection

    def create(self, row: Port) -> None:
        """Insert `row`.

        The key is assigned by the server and is written back into `row`.

        Raises:
            DatabaseFailure: where the server refused the insert.
        """
        with translating(TABLE), self._connection.cursor() as cursor:
            cursor.execute(
                INSERT,
                (
                    row.un_locode,
                    row.name,
                    row.country_code,
                    row.local_name,
                    row.timezone_name,
                    row.utc_offset_minutes,
                    row.berth_count,
                    row.max_draught_m,
                    row.tidal_range_m,
                    row.annual_throughput_teu,
                    row.customs_round_clock,
                    row.harbour_dues_currency,
                    row.approach_notes,
                ),
            )
            row.port_id = cursor.lastrowid

    def read(self, key: PortKey) -> Port:
        """Return the row `key` names.

        Raises:
            NotFound: where the table carries no such row.
            DatabaseFailure: where the server refused the query.
        """
        with translating(TABLE), self._connection.cursor() as cursor:
            cursor.execute(
                READ,
                (
                    key.port_id,
                ),
            )
            found = cursor.fetchone()
        if found is None:
            raise NotFound(TABLE)
        return _row(found)

    def update(self, row: Port) -> int:
        """Write every writable column of `row` over the row its key names.

        Returns:
            The number of rows the server reported as changed.

        Raises:
            DatabaseFailure: where the server refused the update.
        """
        with translating(TABLE), self._connection.cursor() as cursor:
            affected = cursor.execute(
                UPDATE,
                (
                    row.un_locode,
                    row.name,
                    row.country_code,
                    row.local_name,
                    row.timezone_name,
                    row.utc_offset_minutes,
                    row.berth_count,
                    row.max_draught_m,
                    row.tidal_range_m,
                    row.annual_throughput_teu,
                    row.customs_round_clock,
                    row.harbour_dues_currency,
                    row.approach_notes,
                    row.port_id,
                ),
            )
        return affected

    def delete(self, key: PortKey) -> int:
        """Remove the row `key` names.

        Returns:
            The number of rows the server reported as removed.

        Raises:
            DatabaseFailure: where the server refused the delete.
        """
        with translating(TABLE), self._connection.cursor() as cursor:
            affected = cursor.execute(
                DELETE,
                (
                    key.port_id,
                ),
            )
        return affected

    def search(
        self,
        criteria: PortFilter,
        order: Sequence[PortOrder] = (),
        limit: int | None = None,
        offset: int | None = None,
    ) -> list[Port]:
        """Return every row matching `criteria`, ordered by the terms of `order`.

        Raises:
            DatabaseFailure: where the server refused the query.
        """
        statement: list[str] = [SELECT]
        conditions: list[str] = []
        arguments: list[object] = []

        if criteria.port_id is not None:
            conditions.append("`port_id` = %s")
            arguments.append(criteria.port_id)
        if criteria.port_id_from is not None:
            conditions.append("`port_id` >= %s")
            arguments.append(criteria.port_id_from)
        if criteria.port_id_to is not None:
            conditions.append("`port_id` <= %s")
            arguments.append(criteria.port_id_to)
        if criteria.un_locode is not None:
            conditions.append("`un_locode` = %s")
            arguments.append(criteria.un_locode)
        if criteria.un_locode_like is not None:
            conditions.append("`un_locode` LIKE %s")
            arguments.append(criteria.un_locode_like)
        if criteria.name is not None:
            conditions.append("`name` = %s")
            arguments.append(criteria.name)
        if criteria.name_like is not None:
            conditions.append("`name` LIKE %s")
            arguments.append(criteria.name_like)
        if criteria.country_code is not None:
            conditions.append("`country_code` = %s")
            arguments.append(criteria.country_code)
        if criteria.country_code_like is not None:
            conditions.append("`country_code` LIKE %s")
            arguments.append(criteria.country_code_like)
        if criteria.local_name is not None:
            conditions.append("`local_name` = %s")
            arguments.append(criteria.local_name)
        if criteria.local_name_like is not None:
            conditions.append("`local_name` LIKE %s")
            arguments.append(criteria.local_name_like)
        if criteria.local_name_is_null is not None:
            conditions.append(
                "`local_name` IS NULL"
                if criteria.local_name_is_null
                else "`local_name` IS NOT NULL"
            )
        if criteria.timezone_name is not None:
            conditions.append("`timezone_name` = %s")
            arguments.append(criteria.timezone_name)
        if criteria.timezone_name_like is not None:
            conditions.append("`timezone_name` LIKE %s")
            arguments.append(criteria.timezone_name_like)
        if criteria.utc_offset_minutes is not None:
            conditions.append("`utc_offset_minutes` = %s")
            arguments.append(criteria.utc_offset_minutes)
        if criteria.utc_offset_minutes_from is not None:
            conditions.append("`utc_offset_minutes` >= %s")
            arguments.append(criteria.utc_offset_minutes_from)
        if criteria.utc_offset_minutes_to is not None:
            conditions.append("`utc_offset_minutes` <= %s")
            arguments.append(criteria.utc_offset_minutes_to)
        if criteria.berth_count is not None:
            conditions.append("`berth_count` = %s")
            arguments.append(criteria.berth_count)
        if criteria.berth_count_from is not None:
            conditions.append("`berth_count` >= %s")
            arguments.append(criteria.berth_count_from)
        if criteria.berth_count_to is not None:
            conditions.append("`berth_count` <= %s")
            arguments.append(criteria.berth_count_to)
        if criteria.max_draught_m is not None:
            conditions.append("`max_draught_m` = %s")
            arguments.append(criteria.max_draught_m)
        if criteria.max_draught_m_from is not None:
            conditions.append("`max_draught_m` >= %s")
            arguments.append(criteria.max_draught_m_from)
        if criteria.max_draught_m_to is not None:
            conditions.append("`max_draught_m` <= %s")
            arguments.append(criteria.max_draught_m_to)
        if criteria.tidal_range_m is not None:
            conditions.append("`tidal_range_m` = %s")
            arguments.append(criteria.tidal_range_m)
        if criteria.tidal_range_m_from is not None:
            conditions.append("`tidal_range_m` >= %s")
            arguments.append(criteria.tidal_range_m_from)
        if criteria.tidal_range_m_to is not None:
            conditions.append("`tidal_range_m` <= %s")
            arguments.append(criteria.tidal_range_m_to)
        if criteria.tidal_range_m_is_null is not None:
            conditions.append(
                "`tidal_range_m` IS NULL"
                if criteria.tidal_range_m_is_null
                else "`tidal_range_m` IS NOT NULL"
            )
        if criteria.annual_throughput_teu is not None:
            conditions.append("`annual_throughput_teu` = %s")
            arguments.append(criteria.annual_throughput_teu)
        if criteria.annual_throughput_teu_from is not None:
            conditions.append("`annual_throughput_teu` >= %s")
            arguments.append(criteria.annual_throughput_teu_from)
        if criteria.annual_throughput_teu_to is not None:
            conditions.append("`annual_throughput_teu` <= %s")
            arguments.append(criteria.annual_throughput_teu_to)
        if criteria.annual_throughput_teu_is_null is not None:
            conditions.append(
                "`annual_throughput_teu` IS NULL"
                if criteria.annual_throughput_teu_is_null
                else "`annual_throughput_teu` IS NOT NULL"
            )
        if criteria.customs_round_clock is not None:
            conditions.append("`customs_round_clock` = %s")
            arguments.append(criteria.customs_round_clock)
        if criteria.customs_round_clock_from is not None:
            conditions.append("`customs_round_clock` >= %s")
            arguments.append(criteria.customs_round_clock_from)
        if criteria.customs_round_clock_to is not None:
            conditions.append("`customs_round_clock` <= %s")
            arguments.append(criteria.customs_round_clock_to)
        if criteria.harbour_dues_currency is not None:
            conditions.append("`harbour_dues_currency` = %s")
            arguments.append(criteria.harbour_dues_currency)
        if criteria.harbour_dues_currency_like is not None:
            conditions.append("`harbour_dues_currency` LIKE %s")
            arguments.append(criteria.harbour_dues_currency_like)
        if criteria.approach_notes is not None:
            conditions.append("`approach_notes` = %s")
            arguments.append(criteria.approach_notes)
        if criteria.approach_notes_like is not None:
            conditions.append("`approach_notes` LIKE %s")
            arguments.append(criteria.approach_notes_like)
        if criteria.approach_notes_is_null is not None:
            conditions.append(
                "`approach_notes` IS NULL"
                if criteria.approach_notes_is_null
                else "`approach_notes` IS NOT NULL"
            )

        if conditions:
            statement.append(" WHERE " + " AND ".join(conditions))
        if order:
            statement.append(
                " ORDER BY "
                + ", ".join(f"{term.column.sql} {term.direction.sql}" for term in order)
            )
        if limit is not None:
            statement.append(" LIMIT %s")
            arguments.append(limit)
            if offset is not None:
                statement.append(" OFFSET %s")
                arguments.append(offset)

        with translating(TABLE), self._connection.cursor() as cursor:
            cursor.execute("".join(statement), tuple(arguments))
            found = cursor.fetchall()
        return [_row(values) for values in found]


if TYPE_CHECKING:

    def _implements_the_protocol(
        implementation: PortPyMySQL,
    ) -> PortRepository:
        """Where `mypy` proves the implementation satisfies the contract.

        The return is the whole of the check: a method whose signature drifted
        from the protocol's fails the compile gate here, rather than a caller
        at run time. It costs nothing at run time because the block is never
        executed.
        """
        return implementation
