# Code generated by tpl from freight.tariff. DO NOT EDIT.

"""The PyMySQL implementation of the `freight.tariff` data layer."""

from __future__ import annotations

from collections.abc import Sequence
from typing import TYPE_CHECKING, Any, Final

from pymysql.connections import Connection
from pymysql.cursors import Cursor

from ._core import NotFound, translating
from .tariff import Tariff, TariffFilter, TariffKey, TariffOrder
from .tariff_repository import TariffRepository

__all__ = ["TariffPyMySQL"]

#: The table every statement of this module addresses, as an error names it.
TABLE: Final = "freight.tariff"

#: Selects every column of the table, in catalogue order.
SELECT: Final = "SELECT `tariff_id`, `trade_lane`, `origin_region`, `destination_region`, `equipment_iso_code`, `basis`, `currency`, `base_rate`, `bunker_surcharge`, `congestion_surcharge`, `all_in_rate`, `valid_from`, `valid_until` FROM `tariff`"

#: Selects the one row a primary key names.
READ: Final = "SELECT `tariff_id`, `trade_lane`, `origin_region`, `destination_region`, `equipment_iso_code`, `basis`, `currency`, `base_rate`, `bunker_surcharge`, `congestion_surcharge`, `all_in_rate`, `valid_from`, `valid_until` FROM `tariff` WHERE `tariff_id` = %s"

#: Inserts one row. It names neither a generated column nor an auto-increment
#: key, because the server writes both.
INSERT: Final = "INSERT INTO `tariff` (`trade_lane`, `origin_region`, `destination_region`, `equipment_iso_code`, `basis`, `currency`, `base_rate`, `bunker_surcharge`, `congestion_surcharge`, `valid_from`, `valid_until`) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"

#: Writes every column that is neither generated nor part of the key.
UPDATE: Final = "UPDATE `tariff` SET `trade_lane` = %s, `origin_region` = %s, `destination_region` = %s, `equipment_iso_code` = %s, `basis` = %s, `currency` = %s, `base_rate` = %s, `bunker_surcharge` = %s, `congestion_surcharge` = %s, `valid_from` = %s, `valid_until` = %s WHERE `tariff_id` = %s"

#: Removes the one row a primary key names.
DELETE: Final = "DELETE FROM `tariff` WHERE `tariff_id` = %s"


def _row(values: tuple[Any, ...]) -> Tariff:
    """Build a row from one result tuple.

    The positions are the order :data:`SELECT` names the columns in, which is
    catalogue order. The values are whatever PyMySQL decoded, and the types the
    dataclass declares are this example's record of what that is.
    """
    return Tariff(
        tariff_id=values[0],
        trade_lane=values[1],
        origin_region=values[2],
        destination_region=values[3],
        equipment_iso_code=values[4],
        basis=values[5],
        currency=values[6],
        base_rate=values[7],
        bunker_surcharge=values[8],
        congestion_surcharge=values[9],
        all_in_rate=values[10],
        valid_from=values[11],
        valid_until=values[12],
    )


class TariffPyMySQL:
    """The PyMySQL data layer of `freight.tariff`.

    It names no base class. ``TariffRepository`` is a ``Protocol`` and is
    satisfied structurally, and the check at the foot of this module is where
    `mypy` proves that this class satisfies it.
    """

    def __init__(self, connection: Connection[Cursor]) -> None:
        """Build the data layer of `freight.tariff` over `connection`.

        The connection must address the schema ``SCHEMA`` names, because the
        statements above address the table unqualified. ``connect`` is the
        connection that carries it.

        Nothing here commits. A connection opened by ``connect`` autocommits
        unless the caller said otherwise, so transaction control stays with the
        caller.
        """
        self._connection = connection

    def create(self, row: Tariff) -> None:
        """Insert `row`.

        The key is assigned by the server and is written back into `row`.

        Raises:
            DatabaseFailure: where the server refused the insert.
        """
        with translating(TABLE), self._connection.cursor() as cursor:
            cursor.execute(
                INSERT,
                (
                    row.trade_lane,
                    row.origin_region,
                    row.destination_region,
                    row.equipment_iso_code,
                    row.basis,
                    row.currency,
                    row.base_rate,
                    row.bunker_surcharge,
                    row.congestion_surcharge,
                    row.valid_from,
                    row.valid_until,
                ),
            )
            row.tariff_id = cursor.lastrowid

    def read(self, key: TariffKey) -> Tariff:
        """Return the row `key` names.

        Raises:
            NotFound: where the table carries no such row.
            DatabaseFailure: where the server refused the query.
        """
        with translating(TABLE), self._connection.cursor() as cursor:
            cursor.execute(
                READ,
                (
                    key.tariff_id,
                ),
            )
            found = cursor.fetchone()
        if found is None:
            raise NotFound(TABLE)
        return _row(found)

    def update(self, row: Tariff) -> int:
        """Write every writable column of `row` over the row its key names.

        Returns:
            The number of rows the server reported as changed.

        Raises:
            DatabaseFailure: where the server refused the update.
        """
        with translating(TABLE), self._connection.cursor() as cursor:
            affected = cursor.execute(
                UPDATE,
                (
                    row.trade_lane,
                    row.origin_region,
                    row.destination_region,
                    row.equipment_iso_code,
                    row.basis,
                    row.currency,
                    row.base_rate,
                    row.bunker_surcharge,
                    row.congestion_surcharge,
                    row.valid_from,
                    row.valid_until,
                    row.tariff_id,
                ),
            )
        return affected

    def delete(self, key: TariffKey) -> int:
        """Remove the row `key` names.

        Returns:
            The number of rows the server reported as removed.

        Raises:
            DatabaseFailure: where the server refused the delete.
        """
        with translating(TABLE), self._connection.cursor() as cursor:
            affected = cursor.execute(
                DELETE,
                (
                    key.tariff_id,
                ),
            )
        return affected

    def search(
        self,
        criteria: TariffFilter,
        order: Sequence[TariffOrder] = (),
        limit: int | None = None,
        offset: int | None = None,
    ) -> list[Tariff]:
        """Return every row matching `criteria`, ordered by the terms of `order`.

        Raises:
            DatabaseFailure: where the server refused the query.
        """
        statement: list[str] = [SELECT]
        conditions: list[str] = []
        arguments: list[object] = []

        if criteria.tariff_id is not None:
            conditions.append("`tariff_id` = %s")
            arguments.append(criteria.tariff_id)
        if criteria.tariff_id_from is not None:
            conditions.append("`tariff_id` >= %s")
            arguments.append(criteria.tariff_id_from)
        if criteria.tariff_id_to is not None:
            conditions.append("`tariff_id` <= %s")
            arguments.append(criteria.tariff_id_to)
        if criteria.trade_lane is not None:
            conditions.append("`trade_lane` = %s")
            arguments.append(criteria.trade_lane)
        if criteria.trade_lane_like is not None:
            conditions.append("`trade_lane` LIKE %s")
            arguments.append(criteria.trade_lane_like)
        if criteria.origin_region is not None:
            conditions.append("`origin_region` = %s")
            arguments.append(criteria.origin_region)
        if criteria.origin_region_like is not None:
            conditions.append("`origin_region` LIKE %s")
            arguments.append(criteria.origin_region_like)
        if criteria.destination_region is not None:
            conditions.append("`destination_region` = %s")
            arguments.append(criteria.destination_region)
        if criteria.destination_region_like is not None:
            conditions.append("`destination_region` LIKE %s")
            arguments.append(criteria.destination_region_like)
        if criteria.equipment_iso_code is not None:
            conditions.append("`equipment_iso_code` = %s")
            arguments.append(criteria.equipment_iso_code)
        if criteria.equipment_iso_code_like is not None:
            conditions.append("`equipment_iso_code` LIKE %s")
            arguments.append(criteria.equipment_iso_code_like)
        if criteria.basis is not None:
            conditions.append("`basis` = %s")
            arguments.append(criteria.basis)
        if criteria.basis_like is not None:
            conditions.append("`basis` LIKE %s")
            arguments.append(criteria.basis_like)
        if criteria.currency is not None:
            conditions.append("`currency` = %s")
            arguments.append(criteria.currency)
        if criteria.currency_like is not None:
            conditions.append("`currency` LIKE %s")
            arguments.append(criteria.currency_like)
        if criteria.base_rate is not None:
            conditions.append("`base_rate` = %s")
            arguments.append(criteria.base_rate)
        if criteria.base_rate_from is not None:
            conditions.append("`base_rate` >= %s")
            arguments.append(criteria.base_rate_from)
        if criteria.base_rate_to is not None:
            conditions.append("`base_rate` <= %s")
            arguments.append(criteria.base_rate_to)
        if criteria.bunker_surcharge is not None:
            conditions.append("`bunker_surcharge` = %s")
            arguments.append(criteria.bunker_surcharge)
        if criteria.bunker_surcharge_from is not None:
            conditions.append("`bunker_surcharge` >= %s")
            arguments.append(criteria.bunker_surcharge_from)
        if criteria.bunker_surcharge_to is not None:
            conditions.append("`bunker_surcharge` <= %s")
            arguments.append(criteria.bunker_surcharge_to)
        if criteria.congestion_surcharge is not None:
            conditions.append("`congestion_surcharge` = %s")
            arguments.append(criteria.congestion_surcharge)
        if criteria.congestion_surcharge_from is not None:
            conditions.append("`congestion_surcharge` >= %s")
            arguments.append(criteria.congestion_surcharge_from)
        if criteria.congestion_surcharge_to is not None:
            conditions.append("`congestion_surcharge` <= %s")
            arguments.append(criteria.congestion_surcharge_to)
        if criteria.all_in_rate is not None:
            conditions.append("`all_in_rate` = %s")
            arguments.append(criteria.all_in_rate)
        if criteria.all_in_rate_from is not None:
            conditions.append("`all_in_rate` >= %s")
            arguments.append(criteria.all_in_rate_from)
        if criteria.all_in_rate_to is not None:
            conditions.append("`all_in_rate` <= %s")
            arguments.append(criteria.all_in_rate_to)
        if criteria.all_in_rate_is_null is not None:
            conditions.append(
                "`all_in_rate` IS NULL"
                if criteria.all_in_rate_is_null
                else "`all_in_rate` IS NOT NULL"
            )
        if criteria.valid_from is not None:
            conditions.append("`valid_from` = %s")
            arguments.append(criteria.valid_from)
        if criteria.valid_from_from is not None:
            conditions.append("`valid_from` >= %s")
            arguments.append(criteria.valid_from_from)
        if criteria.valid_from_to is not None:
            conditions.append("`valid_from` <= %s")
            arguments.append(criteria.valid_from_to)
        if criteria.valid_until is not None:
            conditions.append("`valid_until` = %s")
            arguments.append(criteria.valid_until)
        if criteria.valid_until_from is not None:
            conditions.append("`valid_until` >= %s")
            arguments.append(criteria.valid_until_from)
        if criteria.valid_until_to is not None:
            conditions.append("`valid_until` <= %s")
            arguments.append(criteria.valid_until_to)

        if conditions:
            statement.append(" WHERE " + " AND ".join(conditions))
        if order:
            statement.append(
                " ORDER BY "
                + ", ".join(f"{term.column.sql} {term.direction.sql}" for term in order)
            )
        if limit is not None:
            statement.append(" LIMIT %s")
            arguments.append(limit)
            if offset is not None:
                statement.append(" OFFSET %s")
                arguments.append(offset)

        with translating(TABLE), self._connection.cursor() as cursor:
            cursor.execute("".join(statement), tuple(arguments))
            found = cursor.fetchall()
        return [_row(values) for values in found]


if TYPE_CHECKING:

    def _implements_the_protocol(
        implementation: TariffPyMySQL,
    ) -> TariffRepository:
        """Where `mypy` proves the implementation satisfies the contract.

        The return is the whole of the check: a method whose signature drifted
        from the protocol's fails the compile gate here, rather than a caller
        at run time. It costs nothing at run time because the block is never
        executed.
        """
        return implementation
