# Code generated by tpl from freight.voyage. DO NOT EDIT.

"""The `freight.voyage` row, the key that addresses it, the columns an ordering may
name, and the filter a search takes.
"""

from __future__ import annotations

import dataclasses
import datetime
import decimal
import enum
from collections.abc import Mapping
from typing import Final

from ._core import Direction, UnknownColumn

__all__ = [
    "Voyage",
    "VoyageColumn",
    "VoyageFilter",
    "VoyageKey",
    "VoyageOrder",
]


@dataclasses.dataclass
class Voyage:
    """One row of `freight.voyage`.

    The dataclass is mutable, because :meth:`create` writes a server-assigned
    key back into it.
    """

    # The table's own comment, as the catalogue carries it:
    # Viagens programadas por navio e número de viagem

    #: `vessel_imo`, declared `char(7)` NOT NULL.
    #:
    #: It is part of the primary key.
    vessel_imo: str
    #: `voyage_number`, declared `varchar(12)` NOT NULL.
    #:
    #: It is part of the primary key.
    #:
    #: Carrier voyage number, e.g. 2026-014W; W and E denote direction
    voyage_number: str
    #: `service_code`, declared `char(4)` NOT NULL.
    #:
    #: Liner service the voyage is operated under
    service_code: str
    #: `etd`, declared `datetime` NOT NULL.
    #:
    #: Estimated time of departure from the first load port
    etd: datetime.datetime
    #: `eta`, declared `datetime` NOT NULL.
    #:
    #: Estimated time of arrival at the last discharge port
    eta: datetime.datetime
    #: `atd`, declared `datetime` NULL.
    #:
    #: Actual time of departure; NULL until the vessel sails
    atd: datetime.datetime | None
    #: `status`, declared `enum('Planned','Announced','Sailing','Completed','Cancelled')` NOT NULL.
    status: str
    #: `bunker_price_usd_t`, declared `decimal(9,2)` NULL.
    #:
    #: VLSFO price used for the bunker adjustment factor
    bunker_price_usd_t: decimal.Decimal | None
    #: `slot_allocation_teu`, declared `mediumint(8) unsigned` NOT NULL.
    slot_allocation_teu: int
    #: `utilisation_pct`, declared `decimal(5,2)` NULL.
    utilisation_pct: decimal.Decimal | None

    def key(self) -> VoyageKey:
        """Return the primary key of the row."""
        return VoyageKey(
            vessel_imo=self.vessel_imo,
            voyage_number=self.voyage_number,
        )


@dataclasses.dataclass(frozen=True)
class VoyageKey:
    """The primary key of `freight.voyage`.

    Frozen, so that it hashes and compares by value. Every type this example's
    mapping produces is hashable, so no key of these three schemas is refused
    for that reason.
    """

    #: `vessel_imo`, declared `char(7)` NOT NULL.
    vessel_imo: str
    #: `voyage_number`, declared `varchar(12)` NOT NULL.
    voyage_number: str


class VoyageColumn(enum.Enum):
    """One column of `freight.voyage`.

    A search accepts an ordering term over these members and over nothing else,
    so an ordering can carry no SQL of its own: :attr:`sql` answers from a
    closed mapping this template wrote, and :meth:`from_name` is the one door a
    name a caller supplied can come through.

    A member's value is the column's name as the catalogue carries it, which is
    what :meth:`from_name` matches on and what ``member.value`` returns.
    """

    #: `vessel_imo`, declared `char(7)` NOT NULL.
    VESSEL_IMO = "vessel_imo"
    #: `voyage_number`, declared `varchar(12)` NOT NULL.
    VOYAGE_NUMBER = "voyage_number"
    #: `service_code`, declared `char(4)` NOT NULL.
    SERVICE_CODE = "service_code"
    #: `etd`, declared `datetime` NOT NULL.
    ETD = "etd"
    #: `eta`, declared `datetime` NOT NULL.
    ETA = "eta"
    #: `atd`, declared `datetime` NULL.
    ATD = "atd"
    #: `status`, declared `enum('Planned','Announced','Sailing','Completed','Cancelled')` NOT NULL.
    STATUS = "status"
    #: `bunker_price_usd_t`, declared `decimal(9,2)` NULL.
    BUNKER_PRICE_USD_T = "bunker_price_usd_t"
    #: `slot_allocation_teu`, declared `mediumint(8) unsigned` NOT NULL.
    SLOT_ALLOCATION_TEU = "slot_allocation_teu"
    #: `utilisation_pct`, declared `decimal(5,2)` NULL.
    UTILISATION_PCT = "utilisation_pct"

    @property
    def sql(self) -> str:
        """The column as a statement's text names it: quoted for MariaDB."""
        return _COLUMNS[self]

    @classmethod
    def from_name(cls, name: str) -> VoyageColumn:
        """Read a column a caller supplied as text.

        Raises:
            UnknownColumn: for every name the table does not carry. That
                refusal is what keeps a caller's text out of a statement.
        """
        try:
            return cls(name)
        except ValueError:
            raise UnknownColumn("freight.voyage", name) from None


#: The one place a column becomes SQL. It is closed over the enumeration above,
#: and every identifier in it was quoted at render time by `tpl`, so no value a
#: caller supplies can reach a statement's text through an ordering term.
_COLUMNS: Final[Mapping[VoyageColumn, str]] = {
    VoyageColumn.VESSEL_IMO: "`vessel_imo`",
    VoyageColumn.VOYAGE_NUMBER: "`voyage_number`",
    VoyageColumn.SERVICE_CODE: "`service_code`",
    VoyageColumn.ETD: "`etd`",
    VoyageColumn.ETA: "`eta`",
    VoyageColumn.ATD: "`atd`",
    VoyageColumn.STATUS: "`status`",
    VoyageColumn.BUNKER_PRICE_USD_T: "`bunker_price_usd_t`",
    VoyageColumn.SLOT_ALLOCATION_TEU: "`slot_allocation_teu`",
    VoyageColumn.UTILISATION_PCT: "`utilisation_pct`",
}


@dataclasses.dataclass(frozen=True)
class VoyageOrder:
    """One ordering term of a search over `freight.voyage`."""

    #: The column to order by.
    column: VoyageColumn
    #: The direction to order in.
    direction: Direction = Direction.ASCENDING


@dataclasses.dataclass
class VoyageFilter:
    """What narrows a search over `freight.voyage`.

    Every field is optional: a field left ``None`` adds no condition, and the
    conditions a search does build are joined with ``AND``. The default
    instance is the filter that matches every row.

    A nullable column's field is ``None`` for *no condition* and never for
    *is NULL*; that question is asked through the ``…_is_null`` field such a
    column also gets, so the two meanings never collide.
    """

    #: Where set, requires `vessel_imo` to equal it.
    vessel_imo: str | None = None
    #: Where set, requires `vessel_imo` to match it, as LIKE matches.
    vessel_imo_like: str | None = None
    #: Where set, requires `voyage_number` to equal it.
    voyage_number: str | None = None
    #: Where set, requires `voyage_number` to match it, as LIKE matches.
    voyage_number_like: str | None = None
    #: Where set, requires `service_code` to equal it.
    service_code: str | None = None
    #: Where set, requires `service_code` to match it, as LIKE matches.
    service_code_like: str | None = None
    #: Where set, requires `etd` to equal it.
    etd: datetime.datetime | None = None
    #: Where set, requires `etd` to be at least it.
    etd_from: datetime.datetime | None = None
    #: Where set, requires `etd` to be at most it.
    etd_to: datetime.datetime | None = None
    #: Where set, requires `eta` to equal it.
    eta: datetime.datetime | None = None
    #: Where set, requires `eta` to be at least it.
    eta_from: datetime.datetime | None = None
    #: Where set, requires `eta` to be at most it.
    eta_to: datetime.datetime | None = None
    #: Where set, requires `atd` to equal it.
    atd: datetime.datetime | None = None
    #: Where set, requires `atd` to be at least it.
    atd_from: datetime.datetime | None = None
    #: Where set, requires `atd` to be at most it.
    atd_to: datetime.datetime | None = None
    #: Where True, requires `atd` to be NULL; where False, requires it not to be.
    atd_is_null: bool | None = None
    #: Where set, requires `status` to equal it.
    status: str | None = None
    #: Where set, requires `status` to match it, as LIKE matches.
    status_like: str | None = None
    #: Where set, requires `bunker_price_usd_t` to equal it.
    bunker_price_usd_t: decimal.Decimal | None = None
    #: Where set, requires `bunker_price_usd_t` to be at least it.
    bunker_price_usd_t_from: decimal.Decimal | None = None
    #: Where set, requires `bunker_price_usd_t` to be at most it.
    bunker_price_usd_t_to: decimal.Decimal | None = None
    #: Where True, requires `bunker_price_usd_t` to be NULL; where False, requires it not to be.
    bunker_price_usd_t_is_null: bool | None = None
    #: Where set, requires `slot_allocation_teu` to equal it.
    slot_allocation_teu: int | None = None
    #: Where set, requires `slot_allocation_teu` to be at least it.
    slot_allocation_teu_from: int | None = None
    #: Where set, requires `slot_allocation_teu` to be at most it.
    slot_allocation_teu_to: int | None = None
    #: Where set, requires `utilisation_pct` to equal it.
    utilisation_pct: decimal.Decimal | None = None
    #: Where set, requires `utilisation_pct` to be at least it.
    utilisation_pct_from: decimal.Decimal | None = None
    #: Where set, requires `utilisation_pct` to be at most it.
    utilisation_pct_to: decimal.Decimal | None = None
    #: Where True, requires `utilisation_pct` to be NULL; where False, requires it not to be.
    utilisation_pct_is_null: bool | None = None

    def is_empty(self) -> bool:
        """Is no field set?

        A search over an empty filter builds no ``WHERE`` clause and matches
        every row of the table.
        """
        return (
            self.vessel_imo is None
            and self.vessel_imo_like is None
            and self.voyage_number is None
            and self.voyage_number_like is None
            and self.service_code is None
            and self.service_code_like is None
            and self.etd is None
            and self.etd_from is None
            and self.etd_to is None
            and self.eta is None
            and self.eta_from is None
            and self.eta_to is None
            and self.atd is None
            and self.atd_from is None
            and self.atd_to is None
            and self.atd_is_null is None
            and self.status is None
            and self.status_like is None
            and self.bunker_price_usd_t is None
            and self.bunker_price_usd_t_from is None
            and self.bunker_price_usd_t_to is None
            and self.bunker_price_usd_t_is_null is None
            and self.slot_allocation_teu is None
            and self.slot_allocation_teu_from is None
            and self.slot_allocation_teu_to is None
            and self.utilisation_pct is None
            and self.utilisation_pct_from is None
            and self.utilisation_pct_to is None
            and self.utilisation_pct_is_null is None
        )
