// Code generated by tpl from sakila.address. DO NOT EDIT.

//! The `sqlx` implementation of the `sakila.address` data layer.

use sqlx::{MySql, QueryBuilder};

use super::Error;
use super::address::{Address, AddressFilter, AddressKey, AddressOrder};
use super::address_repository::AddressRepository;

/// The table every statement of this module addresses, as an error names it.
const TABLE: &str = "sakila.address";

/// Selects every column of the table, in catalogue order.
const SELECT: &str = "SELECT `address_id`, `address`, `address2`, `district`, `city_id`, `postal_code`, `phone`, `last_update` FROM `address`";

/// Selects the one row a primary key names.
const READ: &str = "SELECT `address_id`, `address`, `address2`, `district`, `city_id`, `postal_code`, `phone`, `last_update` FROM `address` WHERE `address_id` = ?";

/// Inserts one row.
///
/// It names neither a generated column nor an auto-increment key, because the
/// server writes both.
const INSERT: &str = "INSERT INTO `address` (`address`, `address2`, `district`, `city_id`, `postal_code`, `phone`, `last_update`) VALUES (?, ?, ?, ?, ?, ?, ?)";

/// Writes every column that is neither generated nor part of the key.
const UPDATE: &str = "UPDATE `address` SET `address` = ?, `address2` = ?, `district` = ?, `city_id` = ?, `postal_code` = ?, `phone` = ?, `last_update` = ? WHERE `address_id` = ?";

/// Removes the one row a primary key names.
const DELETE: &str = "DELETE FROM `address` WHERE `address_id` = ?";

/// The `sqlx` data layer of `sakila.address`.
#[derive(Debug, Clone)]
pub struct AddressSqlx {
    pool: sqlx::MySqlPool,
}

impl AddressSqlx {
    /// Builds the data layer of `sakila.address` over `pool`.
    ///
    /// The pool must address the schema [`SCHEMA`] names, because the
    /// statements above address the table unqualified. [`connect`] is the pool
    /// that carries it.
    ///
    /// [`SCHEMA`]: super::SCHEMA
    /// [`connect`]: super::connect
    #[must_use]
    pub fn new(pool: sqlx::MySqlPool) -> Self {
        Self { pool }
    }
}

impl AddressRepository for AddressSqlx {
    async fn create(&self, row: &mut Address) -> Result<(), Error> {
        let assigned = sqlx::query(INSERT)
            .bind(&row.address)
            .bind(&row.address2)
            .bind(&row.district)
            .bind(row.city_id)
            .bind(&row.postal_code)
            .bind(&row.phone)
            .bind(row.last_update)
            .execute(&self.pool)
            .await?
            .last_insert_id();
        row.address_id =
            u16::try_from(assigned).map_err(|source| Error::AssignedKey {
                table: TABLE,
                column: "address_id",
                source,
            })?;
        Ok(())
    }

    async fn read(&self, key: &AddressKey) -> Result<Address, Error> {
        sqlx::query_as::<_, Address>(READ)
            .bind(key.address_id)
            .fetch_optional(&self.pool)
            .await?
            .ok_or(Error::NotFound { table: TABLE })
    }

    async fn update(&self, row: &Address) -> Result<u64, Error> {
        let outcome = sqlx::query(UPDATE)
            .bind(&row.address)
            .bind(&row.address2)
            .bind(&row.district)
            .bind(row.city_id)
            .bind(&row.postal_code)
            .bind(&row.phone)
            .bind(row.last_update)
            .bind(row.address_id)
            .execute(&self.pool)
            .await?;

        Ok(outcome.rows_affected())
    }

    async fn delete(&self, key: &AddressKey) -> Result<u64, Error> {
        let outcome = sqlx::query(DELETE)
            .bind(key.address_id)
            .execute(&self.pool)
            .await?;

        Ok(outcome.rows_affected())
    }

    async fn search(
        &self,
        filter: AddressFilter,
        order: &[AddressOrder],
        limit: Option<u64>,
        offset: Option<u64>,
    ) -> Result<Vec<Address>, Error> {
        let mut builder: QueryBuilder<MySql> = QueryBuilder::new(SELECT);

        if !filter.is_empty() {
            builder.push(" WHERE ");
            let mut conditions = builder.separated(" AND ");

            if let Some(value) = filter.address_id {
                conditions
                    .push("`address_id` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.address_id_from {
                conditions
                    .push("`address_id` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.address_id_to {
                conditions
                    .push("`address_id` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.address {
                conditions
                    .push("`address` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.address_like {
                conditions
                    .push("`address` LIKE ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.address2 {
                conditions
                    .push("`address2` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.address2_like {
                conditions
                    .push("`address2` LIKE ")
                    .push_bind_unseparated(value);
            }
            if let Some(is_null) = filter.address2_is_null {
                conditions.push(if is_null {
                    "`address2` IS NULL"
                } else {
                    "`address2` IS NOT NULL"
                });
            }
            if let Some(value) = filter.district {
                conditions
                    .push("`district` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.district_like {
                conditions
                    .push("`district` LIKE ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.city_id {
                conditions
                    .push("`city_id` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.city_id_from {
                conditions
                    .push("`city_id` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.city_id_to {
                conditions
                    .push("`city_id` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.postal_code {
                conditions
                    .push("`postal_code` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.postal_code_like {
                conditions
                    .push("`postal_code` LIKE ")
                    .push_bind_unseparated(value);
            }
            if let Some(is_null) = filter.postal_code_is_null {
                conditions.push(if is_null {
                    "`postal_code` IS NULL"
                } else {
                    "`postal_code` IS NOT NULL"
                });
            }
            if let Some(value) = filter.phone {
                conditions
                    .push("`phone` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.phone_like {
                conditions
                    .push("`phone` LIKE ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.last_update {
                conditions
                    .push("`last_update` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.last_update_from {
                conditions
                    .push("`last_update` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.last_update_to {
                conditions
                    .push("`last_update` <= ")
                    .push_bind_unseparated(value);
            }
        }

        if !order.is_empty() {
            builder.push(" ORDER BY ");
            for (position, term) in order.iter().enumerate() {
                if position > 0 {
                    builder.push(", ");
                }
                builder.push(term.column.as_sql());
                builder.push(" ");
                builder.push(term.direction.as_sql());
            }
        }

        if let Some(limit) = limit {
            builder.push(" LIMIT ").push_bind(limit);

            if let Some(offset) = offset {
                builder.push(" OFFSET ").push_bind(offset);
            }
        }

        builder
            .build_query_as::<Address>()
            .fetch_all(&self.pool)
            .await
            .map_err(Error::from)
    }
}
