// Code generated by tpl from sakila.customer. DO NOT EDIT.

//! The `sqlx` implementation of the `sakila.customer` data layer.

use sqlx::{MySql, QueryBuilder};

use super::Error;
use super::customer::{Customer, CustomerFilter, CustomerKey, CustomerOrder};
use super::customer_repository::CustomerRepository;

/// The table every statement of this module addresses, as an error names it.
const TABLE: &str = "sakila.customer";

/// Selects every column of the table, in catalogue order.
const SELECT: &str = "SELECT `customer_id`, `store_id`, `first_name`, `last_name`, `email`, `address_id`, `active`, `create_date`, `last_update` FROM `customer`";

/// Selects the one row a primary key names.
const READ: &str = "SELECT `customer_id`, `store_id`, `first_name`, `last_name`, `email`, `address_id`, `active`, `create_date`, `last_update` FROM `customer` WHERE `customer_id` = ?";

/// Inserts one row.
///
/// It names neither a generated column nor an auto-increment key, because the
/// server writes both.
const INSERT: &str = "INSERT INTO `customer` (`store_id`, `first_name`, `last_name`, `email`, `address_id`, `active`, `create_date`, `last_update`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

/// Writes every column that is neither generated nor part of the key.
const UPDATE: &str = "UPDATE `customer` SET `store_id` = ?, `first_name` = ?, `last_name` = ?, `email` = ?, `address_id` = ?, `active` = ?, `create_date` = ?, `last_update` = ? WHERE `customer_id` = ?";

/// Removes the one row a primary key names.
const DELETE: &str = "DELETE FROM `customer` WHERE `customer_id` = ?";

/// The `sqlx` data layer of `sakila.customer`.
#[derive(Debug, Clone)]
pub struct CustomerSqlx {
    pool: sqlx::MySqlPool,
}

impl CustomerSqlx {
    /// Builds the data layer of `sakila.customer` over `pool`.
    ///
    /// The pool must address the schema [`SCHEMA`] names, because the
    /// statements above address the table unqualified. [`connect`] is the pool
    /// that carries it.
    ///
    /// [`SCHEMA`]: super::SCHEMA
    /// [`connect`]: super::connect
    #[must_use]
    pub fn new(pool: sqlx::MySqlPool) -> Self {
        Self { pool }
    }
}

impl CustomerRepository for CustomerSqlx {
    async fn create(&self, row: &mut Customer) -> Result<(), Error> {
        let assigned = sqlx::query(INSERT)
            .bind(row.store_id)
            .bind(&row.first_name)
            .bind(&row.last_name)
            .bind(&row.email)
            .bind(row.address_id)
            .bind(row.active)
            .bind(row.create_date)
            .bind(row.last_update)
            .execute(&self.pool)
            .await?
            .last_insert_id();
        row.customer_id =
            u16::try_from(assigned).map_err(|source| Error::AssignedKey {
                table: TABLE,
                column: "customer_id",
                source,
            })?;
        Ok(())
    }

    async fn read(&self, key: &CustomerKey) -> Result<Customer, Error> {
        sqlx::query_as::<_, Customer>(READ)
            .bind(key.customer_id)
            .fetch_optional(&self.pool)
            .await?
            .ok_or(Error::NotFound { table: TABLE })
    }

    async fn update(&self, row: &Customer) -> Result<u64, Error> {
        let outcome = sqlx::query(UPDATE)
            .bind(row.store_id)
            .bind(&row.first_name)
            .bind(&row.last_name)
            .bind(&row.email)
            .bind(row.address_id)
            .bind(row.active)
            .bind(row.create_date)
            .bind(row.last_update)
            .bind(row.customer_id)
            .execute(&self.pool)
            .await?;

        Ok(outcome.rows_affected())
    }

    async fn delete(&self, key: &CustomerKey) -> Result<u64, Error> {
        let outcome = sqlx::query(DELETE)
            .bind(key.customer_id)
            .execute(&self.pool)
            .await?;

        Ok(outcome.rows_affected())
    }

    async fn search(
        &self,
        filter: CustomerFilter,
        order: &[CustomerOrder],
        limit: Option<u64>,
        offset: Option<u64>,
    ) -> Result<Vec<Customer>, Error> {
        let mut builder: QueryBuilder<MySql> = QueryBuilder::new(SELECT);

        if !filter.is_empty() {
            builder.push(" WHERE ");
            let mut conditions = builder.separated(" AND ");

            if let Some(value) = filter.customer_id {
                conditions
                    .push("`customer_id` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.customer_id_from {
                conditions
                    .push("`customer_id` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.customer_id_to {
                conditions
                    .push("`customer_id` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.store_id {
                conditions
                    .push("`store_id` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.store_id_from {
                conditions
                    .push("`store_id` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.store_id_to {
                conditions
                    .push("`store_id` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.first_name {
                conditions
                    .push("`first_name` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.first_name_like {
                conditions
                    .push("`first_name` LIKE ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.last_name {
                conditions
                    .push("`last_name` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.last_name_like {
                conditions
                    .push("`last_name` LIKE ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.email {
                conditions
                    .push("`email` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.email_like {
                conditions
                    .push("`email` LIKE ")
                    .push_bind_unseparated(value);
            }
            if let Some(is_null) = filter.email_is_null {
                conditions.push(if is_null {
                    "`email` IS NULL"
                } else {
                    "`email` IS NOT NULL"
                });
            }
            if let Some(value) = filter.address_id {
                conditions
                    .push("`address_id` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.address_id_from {
                conditions
                    .push("`address_id` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.address_id_to {
                conditions
                    .push("`address_id` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.active {
                conditions
                    .push("`active` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.active_from {
                conditions
                    .push("`active` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.active_to {
                conditions
                    .push("`active` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.create_date {
                conditions
                    .push("`create_date` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.create_date_from {
                conditions
                    .push("`create_date` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.create_date_to {
                conditions
                    .push("`create_date` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.last_update {
                conditions
                    .push("`last_update` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.last_update_from {
                conditions
                    .push("`last_update` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.last_update_to {
                conditions
                    .push("`last_update` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(is_null) = filter.last_update_is_null {
                conditions.push(if is_null {
                    "`last_update` IS NULL"
                } else {
                    "`last_update` IS NOT NULL"
                });
            }
        }

        if !order.is_empty() {
            builder.push(" ORDER BY ");
            for (position, term) in order.iter().enumerate() {
                if position > 0 {
                    builder.push(", ");
                }
                builder.push(term.column.as_sql());
                builder.push(" ");
                builder.push(term.direction.as_sql());
            }
        }

        if let Some(limit) = limit {
            builder.push(" LIMIT ").push_bind(limit);

            if let Some(offset) = offset {
                builder.push(" OFFSET ").push_bind(offset);
            }
        }

        builder
            .build_query_as::<Customer>()
            .fetch_all(&self.pool)
            .await
            .map_err(Error::from)
    }
}
