// Code generated by tpl from sakila.rental. DO NOT EDIT.

//! The `sqlx` implementation of the `sakila.rental` data layer.

use sqlx::{MySql, QueryBuilder};

use super::Error;
use super::rental::{Rental, RentalFilter, RentalKey, RentalOrder};
use super::rental_repository::RentalRepository;

/// The table every statement of this module addresses, as an error names it.
const TABLE: &str = "sakila.rental";

/// Selects every column of the table, in catalogue order.
const SELECT: &str = "SELECT `rental_id`, `rental_date`, `inventory_id`, `customer_id`, `return_date`, `staff_id`, `last_update` FROM `rental`";

/// Selects the one row a primary key names.
const READ: &str = "SELECT `rental_id`, `rental_date`, `inventory_id`, `customer_id`, `return_date`, `staff_id`, `last_update` FROM `rental` WHERE `rental_id` = ?";

/// Inserts one row.
///
/// It names neither a generated column nor an auto-increment key, because the
/// server writes both.
const INSERT: &str = "INSERT INTO `rental` (`rental_date`, `inventory_id`, `customer_id`, `return_date`, `staff_id`, `last_update`) VALUES (?, ?, ?, ?, ?, ?)";

/// Writes every column that is neither generated nor part of the key.
const UPDATE: &str = "UPDATE `rental` SET `rental_date` = ?, `inventory_id` = ?, `customer_id` = ?, `return_date` = ?, `staff_id` = ?, `last_update` = ? WHERE `rental_id` = ?";

/// Removes the one row a primary key names.
const DELETE: &str = "DELETE FROM `rental` WHERE `rental_id` = ?";

/// The `sqlx` data layer of `sakila.rental`.
#[derive(Debug, Clone)]
pub struct RentalSqlx {
    pool: sqlx::MySqlPool,
}

impl RentalSqlx {
    /// Builds the data layer of `sakila.rental` over `pool`.
    ///
    /// The pool must address the schema [`SCHEMA`] names, because the
    /// statements above address the table unqualified. [`connect`] is the pool
    /// that carries it.
    ///
    /// [`SCHEMA`]: super::SCHEMA
    /// [`connect`]: super::connect
    #[must_use]
    pub fn new(pool: sqlx::MySqlPool) -> Self {
        Self { pool }
    }
}

impl RentalRepository for RentalSqlx {
    async fn create(&self, row: &mut Rental) -> Result<(), Error> {
        let assigned = sqlx::query(INSERT)
            .bind(row.rental_date)
            .bind(row.inventory_id)
            .bind(row.customer_id)
            .bind(row.return_date)
            .bind(row.staff_id)
            .bind(row.last_update)
            .execute(&self.pool)
            .await?
            .last_insert_id();
        row.rental_id =
            i32::try_from(assigned).map_err(|source| Error::AssignedKey {
                table: TABLE,
                column: "rental_id",
                source,
            })?;
        Ok(())
    }

    async fn read(&self, key: &RentalKey) -> Result<Rental, Error> {
        sqlx::query_as::<_, Rental>(READ)
            .bind(key.rental_id)
            .fetch_optional(&self.pool)
            .await?
            .ok_or(Error::NotFound { table: TABLE })
    }

    async fn update(&self, row: &Rental) -> Result<u64, Error> {
        let outcome = sqlx::query(UPDATE)
            .bind(row.rental_date)
            .bind(row.inventory_id)
            .bind(row.customer_id)
            .bind(row.return_date)
            .bind(row.staff_id)
            .bind(row.last_update)
            .bind(row.rental_id)
            .execute(&self.pool)
            .await?;

        Ok(outcome.rows_affected())
    }

    async fn delete(&self, key: &RentalKey) -> Result<u64, Error> {
        let outcome = sqlx::query(DELETE)
            .bind(key.rental_id)
            .execute(&self.pool)
            .await?;

        Ok(outcome.rows_affected())
    }

    async fn search(
        &self,
        filter: RentalFilter,
        order: &[RentalOrder],
        limit: Option<u64>,
        offset: Option<u64>,
    ) -> Result<Vec<Rental>, Error> {
        let mut builder: QueryBuilder<MySql> = QueryBuilder::new(SELECT);

        if !filter.is_empty() {
            builder.push(" WHERE ");
            let mut conditions = builder.separated(" AND ");

            if let Some(value) = filter.rental_id {
                conditions
                    .push("`rental_id` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.rental_id_from {
                conditions
                    .push("`rental_id` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.rental_id_to {
                conditions
                    .push("`rental_id` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.rental_date {
                conditions
                    .push("`rental_date` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.rental_date_from {
                conditions
                    .push("`rental_date` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.rental_date_to {
                conditions
                    .push("`rental_date` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.inventory_id {
                conditions
                    .push("`inventory_id` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.inventory_id_from {
                conditions
                    .push("`inventory_id` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.inventory_id_to {
                conditions
                    .push("`inventory_id` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.customer_id {
                conditions
                    .push("`customer_id` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.customer_id_from {
                conditions
                    .push("`customer_id` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.customer_id_to {
                conditions
                    .push("`customer_id` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.return_date {
                conditions
                    .push("`return_date` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.return_date_from {
                conditions
                    .push("`return_date` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.return_date_to {
                conditions
                    .push("`return_date` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(is_null) = filter.return_date_is_null {
                conditions.push(if is_null {
                    "`return_date` IS NULL"
                } else {
                    "`return_date` IS NOT NULL"
                });
            }
            if let Some(value) = filter.staff_id {
                conditions
                    .push("`staff_id` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.staff_id_from {
                conditions
                    .push("`staff_id` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.staff_id_to {
                conditions
                    .push("`staff_id` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.last_update {
                conditions
                    .push("`last_update` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.last_update_from {
                conditions
                    .push("`last_update` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.last_update_to {
                conditions
                    .push("`last_update` <= ")
                    .push_bind_unseparated(value);
            }
        }

        if !order.is_empty() {
            builder.push(" ORDER BY ");
            for (position, term) in order.iter().enumerate() {
                if position > 0 {
                    builder.push(", ");
                }
                builder.push(term.column.as_sql());
                builder.push(" ");
                builder.push(term.direction.as_sql());
            }
        }

        if let Some(limit) = limit {
            builder.push(" LIMIT ").push_bind(limit);

            if let Some(offset) = offset {
                builder.push(" OFFSET ").push_bind(offset);
            }
        }

        builder
            .build_query_as::<Rental>()
            .fetch_all(&self.pool)
            .await
            .map_err(Error::from)
    }
}
