# Code generated by tpl from world.country. DO NOT EDIT.

"""The `world.country` row, the key that addresses it, the columns an ordering may
name, and the filter a search takes.
"""

from __future__ import annotations

import dataclasses
import decimal
import enum
from collections.abc import Mapping
from typing import Final

from ._core import Direction, UnknownColumn

__all__ = [
    "Country",
    "CountryColumn",
    "CountryFilter",
    "CountryKey",
    "CountryOrder",
]


@dataclasses.dataclass
class Country:
    """One row of `world.country`.

    The dataclass is mutable, because :meth:`create` writes a server-assigned
    key back into it.
    """

    #: `Code`, declared `char(3)` NOT NULL.
    #:
    #: It is part of the primary key.
    code: str
    #: `Name`, declared `char(52)` NOT NULL.
    name: str
    #: `Continent`, declared `enum('Asia','Europe','North America','Africa','Oceania','Antarctica','South America')` NOT NULL.
    continent: str
    #: `Region`, declared `char(26)` NOT NULL.
    region: str
    #: `SurfaceArea`, declared `decimal(10,2)` NOT NULL.
    surface_area: decimal.Decimal
    #: `IndepYear`, declared `smallint(6)` NULL.
    indep_year: int | None
    #: `Population`, declared `int(11)` NOT NULL.
    population: int
    #: `LifeExpectancy`, declared `decimal(3,1)` NULL.
    life_expectancy: decimal.Decimal | None
    #: `GNP`, declared `decimal(10,2)` NULL.
    gnp: decimal.Decimal | None
    #: `GNPOld`, declared `decimal(10,2)` NULL.
    gnp_old: decimal.Decimal | None
    #: `LocalName`, declared `char(45)` NOT NULL.
    local_name: str
    #: `GovernmentForm`, declared `char(45)` NOT NULL.
    government_form: str
    #: `HeadOfState`, declared `char(60)` NULL.
    head_of_state: str | None
    #: `Capital`, declared `int(11)` NULL.
    capital: int | None
    #: `Code2`, declared `char(2)` NOT NULL.
    code2: str

    def key(self) -> CountryKey:
        """Return the primary key of the row."""
        return CountryKey(
            code=self.code,
        )


@dataclasses.dataclass(frozen=True)
class CountryKey:
    """The primary key of `world.country`.

    Frozen, so that it hashes and compares by value. Every type this example's
    mapping produces is hashable, so no key of these three schemas is refused
    for that reason.
    """

    #: `Code`, declared `char(3)` NOT NULL.
    code: str


class CountryColumn(enum.Enum):
    """One column of `world.country`.

    A search accepts an ordering term over these members and over nothing else,
    so an ordering can carry no SQL of its own: :attr:`sql` answers from a
    closed mapping this template wrote, and :meth:`from_name` is the one door a
    name a caller supplied can come through.

    A member's value is the column's name as the catalogue carries it, which is
    what :meth:`from_name` matches on and what ``member.value`` returns.
    """

    #: `Code`, declared `char(3)` NOT NULL.
    CODE = "Code"
    #: `Name`, declared `char(52)` NOT NULL.
    NAME = "Name"
    #: `Continent`, declared `enum('Asia','Europe','North America','Africa','Oceania','Antarctica','South America')` NOT NULL.
    CONTINENT = "Continent"
    #: `Region`, declared `char(26)` NOT NULL.
    REGION = "Region"
    #: `SurfaceArea`, declared `decimal(10,2)` NOT NULL.
    SURFACE_AREA = "SurfaceArea"
    #: `IndepYear`, declared `smallint(6)` NULL.
    INDEP_YEAR = "IndepYear"
    #: `Population`, declared `int(11)` NOT NULL.
    POPULATION = "Population"
    #: `LifeExpectancy`, declared `decimal(3,1)` NULL.
    LIFE_EXPECTANCY = "LifeExpectancy"
    #: `GNP`, declared `decimal(10,2)` NULL.
    GNP = "GNP"
    #: `GNPOld`, declared `decimal(10,2)` NULL.
    GNP_OLD = "GNPOld"
    #: `LocalName`, declared `char(45)` NOT NULL.
    LOCAL_NAME = "LocalName"
    #: `GovernmentForm`, declared `char(45)` NOT NULL.
    GOVERNMENT_FORM = "GovernmentForm"
    #: `HeadOfState`, declared `char(60)` NULL.
    HEAD_OF_STATE = "HeadOfState"
    #: `Capital`, declared `int(11)` NULL.
    CAPITAL = "Capital"
    #: `Code2`, declared `char(2)` NOT NULL.
    CODE2 = "Code2"

    @property
    def sql(self) -> str:
        """The column as a statement's text names it: quoted for MariaDB."""
        return _COLUMNS[self]

    @classmethod
    def from_name(cls, name: str) -> CountryColumn:
        """Read a column a caller supplied as text.

        Raises:
            UnknownColumn: for every name the table does not carry. That
                refusal is what keeps a caller's text out of a statement.
        """
        try:
            return cls(name)
        except ValueError:
            raise UnknownColumn("world.country", name) from None


#: The one place a column becomes SQL. It is closed over the enumeration above,
#: and every identifier in it was quoted at render time by `tpl`, so no value a
#: caller supplies can reach a statement's text through an ordering term.
_COLUMNS: Final[Mapping[CountryColumn, str]] = {
    CountryColumn.CODE: "`Code`",
    CountryColumn.NAME: "`Name`",
    CountryColumn.CONTINENT: "`Continent`",
    CountryColumn.REGION: "`Region`",
    CountryColumn.SURFACE_AREA: "`SurfaceArea`",
    CountryColumn.INDEP_YEAR: "`IndepYear`",
    CountryColumn.POPULATION: "`Population`",
    CountryColumn.LIFE_EXPECTANCY: "`LifeExpectancy`",
    CountryColumn.GNP: "`GNP`",
    CountryColumn.GNP_OLD: "`GNPOld`",
    CountryColumn.LOCAL_NAME: "`LocalName`",
    CountryColumn.GOVERNMENT_FORM: "`GovernmentForm`",
    CountryColumn.HEAD_OF_STATE: "`HeadOfState`",
    CountryColumn.CAPITAL: "`Capital`",
    CountryColumn.CODE2: "`Code2`",
}


@dataclasses.dataclass(frozen=True)
class CountryOrder:
    """One ordering term of a search over `world.country`."""

    #: The column to order by.
    column: CountryColumn
    #: The direction to order in.
    direction: Direction = Direction.ASCENDING


@dataclasses.dataclass
class CountryFilter:
    """What narrows a search over `world.country`.

    Every field is optional: a field left ``None`` adds no condition, and the
    conditions a search does build are joined with ``AND``. The default
    instance is the filter that matches every row.

    A nullable column's field is ``None`` for *no condition* and never for
    *is NULL*; that question is asked through the ``…_is_null`` field such a
    column also gets, so the two meanings never collide.
    """

    #: Where set, requires `Code` to equal it.
    code: str | None = None
    #: Where set, requires `Code` to match it, as LIKE matches.
    code_like: str | None = None
    #: Where set, requires `Name` to equal it.
    name: str | None = None
    #: Where set, requires `Name` to match it, as LIKE matches.
    name_like: str | None = None
    #: Where set, requires `Continent` to equal it.
    continent: str | None = None
    #: Where set, requires `Continent` to match it, as LIKE matches.
    continent_like: str | None = None
    #: Where set, requires `Region` to equal it.
    region: str | None = None
    #: Where set, requires `Region` to match it, as LIKE matches.
    region_like: str | None = None
    #: Where set, requires `SurfaceArea` to equal it.
    surface_area: decimal.Decimal | None = None
    #: Where set, requires `SurfaceArea` to be at least it.
    surface_area_from: decimal.Decimal | None = None
    #: Where set, requires `SurfaceArea` to be at most it.
    surface_area_to: decimal.Decimal | None = None
    #: Where set, requires `IndepYear` to equal it.
    indep_year: int | None = None
    #: Where set, requires `IndepYear` to be at least it.
    indep_year_from: int | None = None
    #: Where set, requires `IndepYear` to be at most it.
    indep_year_to: int | None = None
    #: Where True, requires `IndepYear` to be NULL; where False, requires it not to be.
    indep_year_is_null: bool | None = None
    #: Where set, requires `Population` to equal it.
    population: int | None = None
    #: Where set, requires `Population` to be at least it.
    population_from: int | None = None
    #: Where set, requires `Population` to be at most it.
    population_to: int | None = None
    #: Where set, requires `LifeExpectancy` to equal it.
    life_expectancy: decimal.Decimal | None = None
    #: Where set, requires `LifeExpectancy` to be at least it.
    life_expectancy_from: decimal.Decimal | None = None
    #: Where set, requires `LifeExpectancy` to be at most it.
    life_expectancy_to: decimal.Decimal | None = None
    #: Where True, requires `LifeExpectancy` to be NULL; where False, requires it not to be.
    life_expectancy_is_null: bool | None = None
    #: Where set, requires `GNP` to equal it.
    gnp: decimal.Decimal | None = None
    #: Where set, requires `GNP` to be at least it.
    gnp_from: decimal.Decimal | None = None
    #: Where set, requires `GNP` to be at most it.
    gnp_to: decimal.Decimal | None = None
    #: Where True, requires `GNP` to be NULL; where False, requires it not to be.
    gnp_is_null: bool | None = None
    #: Where set, requires `GNPOld` to equal it.
    gnp_old: decimal.Decimal | None = None
    #: Where set, requires `GNPOld` to be at least it.
    gnp_old_from: decimal.Decimal | None = None
    #: Where set, requires `GNPOld` to be at most it.
    gnp_old_to: decimal.Decimal | None = None
    #: Where True, requires `GNPOld` to be NULL; where False, requires it not to be.
    gnp_old_is_null: bool | None = None
    #: Where set, requires `LocalName` to equal it.
    local_name: str | None = None
    #: Where set, requires `LocalName` to match it, as LIKE matches.
    local_name_like: str | None = None
    #: Where set, requires `GovernmentForm` to equal it.
    government_form: str | None = None
    #: Where set, requires `GovernmentForm` to match it, as LIKE matches.
    government_form_like: str | None = None
    #: Where set, requires `HeadOfState` to equal it.
    head_of_state: str | None = None
    #: Where set, requires `HeadOfState` to match it, as LIKE matches.
    head_of_state_like: str | None = None
    #: Where True, requires `HeadOfState` to be NULL; where False, requires it not to be.
    head_of_state_is_null: bool | None = None
    #: Where set, requires `Capital` to equal it.
    capital: int | None = None
    #: Where set, requires `Capital` to be at least it.
    capital_from: int | None = None
    #: Where set, requires `Capital` to be at most it.
    capital_to: int | None = None
    #: Where True, requires `Capital` to be NULL; where False, requires it not to be.
    capital_is_null: bool | None = None
    #: Where set, requires `Code2` to equal it.
    code2: str | None = None
    #: Where set, requires `Code2` to match it, as LIKE matches.
    code2_like: str | None = None

    def is_empty(self) -> bool:
        """Is no field set?

        A search over an empty filter builds no ``WHERE`` clause and matches
        every row of the table.
        """
        return (
            self.code is None
            and self.code_like is None
            and self.name is None
            and self.name_like is None
            and self.continent is None
            and self.continent_like is None
            and self.region is None
            and self.region_like is None
            and self.surface_area is None
            and self.surface_area_from is None
            and self.surface_area_to is None
            and self.indep_year is None
            and self.indep_year_from is None
            and self.indep_year_to is None
            and self.indep_year_is_null is None
            and self.population is None
            and self.population_from is None
            and self.population_to is None
            and self.life_expectancy is None
            and self.life_expectancy_from is None
            and self.life_expectancy_to is None
            and self.life_expectancy_is_null is None
            and self.gnp is None
            and self.gnp_from is None
            and self.gnp_to is None
            and self.gnp_is_null is None
            and self.gnp_old is None
            and self.gnp_old_from is None
            and self.gnp_old_to is None
            and self.gnp_old_is_null is None
            and self.local_name is None
            and self.local_name_like is None
            and self.government_form is None
            and self.government_form_like is None
            and self.head_of_state is None
            and self.head_of_state_like is None
            and self.head_of_state_is_null is None
            and self.capital is None
            and self.capital_from is None
            and self.capital_to is None
            and self.capital_is_null is None
            and self.code2 is None
            and self.code2_like is None
        )
