// Code generated by tpl from the world schema. DO NOT EDIT.
//
// Server:   MariaDB 12.3.3-MariaDB-ubu2404, series 12.3, standing supported.
// Schema:   world, utf8mb4 / utf8mb4_uca1400_ai_ci.
// Tables:   3.
// Renderer: tpl 0.0.1.

/**
 * A data layer for the `world` schema, rendered from the catalogue of the
 * server named above.
 *
 * Every table of the schema contributes three modules: the row and the types
 * that address it, a base class carrying create, read, update, delete and
 * search, and an implementation of that base class over mysql2. Each module's
 * public names are re-exported here, so a caller writes
 * `CityMysql2` after one import rather than reaching into a file.
 * {@link Repositories} carries one implementation per table over one
 * connection.
 *
 * ### Types
 *
 * A column becomes a JavaScript type through this example's own mapping macro,
 * which is a template of the example and not a feature of `tpl`: `FR-ENV-009`
 * and `FR-ENV-010` declare that `tpl` ships no such filter, and `BR-ENV-002`
 * says why — a type mapping is an opinion, and it belongs to the project that
 * holds it.
 *
 * A nullable column is not the same JavaScript type as a non-nullable one. The
 * non-nullable form is the value type; the nullable form is `T | null`, which
 * is what mysql2 returns a `NULL` as and what `tsc` makes a caller narrow
 * before reading.
 *
 * ### What this package never does
 *
 * No statement it runs interpolates a value. Identifiers were quoted at render
 * time by the tool, values are placeholders MariaDB binds in a prepared
 * statement, and the one part of a statement a caller chooses — the column an
 * ordering names — resolves through a closed mapping into a quoted identifier.
 * A value that is not one of the table's columns is refused rather than
 * interpolated.
 *
 * Nothing here commits, and nothing here writes to the catalogue.
 *
 * @module
 */

/** @import { Connection } from 'mysql2/promise' */

export * from './core.js';
export * from './city.js';
export * from './city_repository.js';
export * from './city_mysql2.js';
export * from './country.js';
export * from './country_repository.js';
export * from './country_mysql2.js';
export * from './countrylanguage.js';
export * from './countrylanguage_repository.js';
export * from './countrylanguage_mysql2.js';

import { CityMysql2 } from './city_mysql2.js';
import { CountryMysql2 } from './country_mysql2.js';
import { CountrylanguageMysql2 } from './countrylanguage_mysql2.js';

/**
 * One repository per table of the `world` schema.
 *
 * The repositories share one connection. A mysql2 `Connection` carries one
 * session and serialises the statements sent over it, so a caller wanting
 * concurrency builds one `Repositories` per connection — or passes a
 * `PoolConnection`, which is a `Connection` and is what a pool hands out.
 */
export class Repositories {
  /**
   * Build one repository per table of the `world` schema over `connection`.
   *
   * @param {Connection} connection a connection addressing `SCHEMA`.
   *   `connect` is the one that carries it.
   */
  constructor(connection) {
    /**
     * The data layer of `world.city`.
     *
     * @type {CityMysql2}
     */
    this.city = new CityMysql2(connection);
    /**
     * The data layer of `world.country`.
     *
     * @type {CountryMysql2}
     */
    this.country = new CountryMysql2(connection);
    /**
     * The data layer of `world.countrylanguage`.
     *
     * @type {CountrylanguageMysql2}
     */
    this.countrylanguage = new CountrylanguageMysql2(connection);
  }
}
