// Code generated by tpl from freight.cargo_item. DO NOT EDIT.

/**
 * The mysql2 implementation of the `freight.cargo_item` data layer.
 *
 * @module
 */

/** @import { Connection, ResultSetHeader, RowDataPacket } from 'mysql2/promise' */
/** @import { BoundValue } from './core.js' */
/** @import { CargoItem, CargoItemFilter, CargoItemKey, CargoItemOrder } from './cargo_item.js' */

import { NotFound, directionSql, failure } from './core.js';
import { cargoItemColumnSql } from './cargo_item.js';
import { CargoItemRepository } from './cargo_item_repository.js';

/** The table every statement of this module addresses, as an error names it. */
const TABLE = "freight.cargo_item";

/** Selects every column of the table, in catalogue order. */
const SELECT = "SELECT `cargo_item_id`, `consignment_id`, `container_id`, `line_number`, `hs_code`, `description`, `package_kind`, `package_count`, `gross_weight_kg`, `net_weight_kg`, `volume_cbm`, `chargeable_weight_kg`, `imdg_class`, `un_number`, `origin_country`, `unit_value`, `line_value` FROM `cargo_item`";

/** Selects the one row a primary key names. */
const READ = "SELECT `cargo_item_id`, `consignment_id`, `container_id`, `line_number`, `hs_code`, `description`, `package_kind`, `package_count`, `gross_weight_kg`, `net_weight_kg`, `volume_cbm`, `chargeable_weight_kg`, `imdg_class`, `un_number`, `origin_country`, `unit_value`, `line_value` FROM `cargo_item` WHERE `cargo_item_id` = ?";

/**
 * Inserts one row. It names neither a generated column nor an auto-increment
 * key, because the server writes both.
 */
const INSERT = "INSERT INTO `cargo_item` (`consignment_id`, `container_id`, `line_number`, `hs_code`, `description`, `package_kind`, `package_count`, `gross_weight_kg`, `net_weight_kg`, `volume_cbm`, `imdg_class`, `un_number`, `origin_country`, `unit_value`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

/** Writes every column that is neither generated nor part of the key. */
const UPDATE = "UPDATE `cargo_item` SET `consignment_id` = ?, `container_id` = ?, `line_number` = ?, `hs_code` = ?, `description` = ?, `package_kind` = ?, `package_count` = ?, `gross_weight_kg` = ?, `net_weight_kg` = ?, `volume_cbm` = ?, `imdg_class` = ?, `un_number` = ?, `origin_country` = ?, `unit_value` = ? WHERE `cargo_item_id` = ?";

/** Removes the one row a primary key names. */
const DELETE = "DELETE FROM `cargo_item` WHERE `cargo_item_id` = ?";

/**
 * Build a row from one result tuple.
 *
 * The positions are the order `SELECT` names the columns in, which is
 * catalogue order. Every statement below is run with `rowsAsArray`, so a
 * result is an array and never an object: a column named `__proto__` or
 * `constructor` would otherwise reach an object literal as a key, and the
 * first of those sets a prototype instead of defining a property.
 *
 * The values are whatever mysql2 decoded, and the types `CargoItem` declares
 * are this example's record of what that is.
 *
 * @param {RowDataPacket} values
 * @returns {CargoItem}
 */
function toRow(values) {
  return {
    cargoItemId: values[0],
    consignmentId: values[1],
    containerId: values[2],
    lineNumber: values[3],
    hsCode: values[4],
    description: values[5],
    packageKind: values[6],
    packageCount: values[7],
    grossWeightKg: values[8],
    netWeightKg: values[9],
    volumeCbm: values[10],
    chargeableWeightKg: values[11],
    imdgClass: values[12],
    unNumber: values[13],
    originCountry: values[14],
    unitValue: values[15],
    lineValue: values[16],
  };
}

/**
 * The mysql2 data layer of `freight.cargo_item`.
 *
 * Nothing here commits. mysql2 autocommits until a caller calls
 * `beginTransaction`, so transaction control stays with the caller.
 */
export class CargoItemMysql2 extends CargoItemRepository {
  /** @type {Connection} */
  #connection;

  /**
   * Build the data layer of `freight.cargo_item` over `connection`.
   *
   * The connection must address the schema `SCHEMA` names, because the
   * statements above address the table unqualified. `connect` is the
   * connection that carries it.
   *
   * @param {Connection} connection
   */
  constructor(connection) {
    super();
    this.#connection = connection;
  }

  /**
   * Insert `row`.
   *
   * The key is assigned by the server and is written back into `row`.
   *
   * @override
   * @param {CargoItem} row
   * @returns {Promise<void>}
   */
  async create(row) {
    /** @type {BoundValue[]} */
    const values = [
      row.consignmentId,
      row.containerId,
      row.lineNumber,
      row.hsCode,
      row.description,
      row.packageKind,
      row.packageCount,
      row.grossWeightKg,
      row.netWeightKg,
      row.volumeCbm,
      row.imdgClass,
      row.unNumber,
      row.originCountry,
      row.unitValue,
    ];
    try {
      const [result] = await this.#connection.execute(INSERT, values);
      const { insertId } = /** @type {ResultSetHeader} */ (result);
      // The key is a BIGINT and every row of this package carries one as a
      // `string`, because `connect` sets `bigNumberStrings`. mysql2 reports
      // `insertId` as a `number` whatever the column is, so it is converted
      // here rather than left to widen the row's type.
      row.cargoItemId = String(insertId);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Return the row `key` names.
   *
   * @override
   * @param {CargoItemKey} key
   * @returns {Promise<CargoItem>}
   */
  async read(key) {
    /** @type {BoundValue[]} */
    const values = [
      key.cargoItemId,
    ];
    try {
      const [rows] = await this.#connection.execute(
        { sql: READ, rowsAsArray: true },
        values,
      );
      const found = /** @type {RowDataPacket[]} */ (rows);
      if (found.length === 0) {
        throw new NotFound(TABLE);
      }
      return toRow(found[0]);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Write every writable column of `row` over the row its key names.
   *
   * @override
   * @param {CargoItem} row
   * @returns {Promise<number>}
   */
  async update(row) {
    /** @type {BoundValue[]} */
    const values = [
      row.consignmentId,
      row.containerId,
      row.lineNumber,
      row.hsCode,
      row.description,
      row.packageKind,
      row.packageCount,
      row.grossWeightKg,
      row.netWeightKg,
      row.volumeCbm,
      row.imdgClass,
      row.unNumber,
      row.originCountry,
      row.unitValue,
      row.cargoItemId,
    ];
    try {
      const [result] = await this.#connection.execute(UPDATE, values);
      return /** @type {ResultSetHeader} */ (result).affectedRows;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Remove the row `key` names.
   *
   * @override
   * @param {CargoItemKey} key
   * @returns {Promise<number>}
   */
  async delete(key) {
    /** @type {BoundValue[]} */
    const values = [
      key.cargoItemId,
    ];
    try {
      const [result] = await this.#connection.execute(DELETE, values);
      return /** @type {ResultSetHeader} */ (result).affectedRows;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Return every row matching `criteria`, ordered by the terms of `order`.
   *
   * @override
   * @param {CargoItemFilter} criteria
   * @param {readonly CargoItemOrder[]} [order]
   * @param {number | null} [limit]
   * @param {number | null} [offset]
   * @returns {Promise<CargoItem[]>}
   */
  async search(criteria, order = [], limit = null, offset = null) {
    /** @type {string[]} */
    const conditions = [];
    /** @type {BoundValue[]} */
    const values = [];

    if (criteria.cargoItemId !== undefined) {
      conditions.push("`cargo_item_id` = ?");
      values.push(criteria.cargoItemId);
    }
    if (criteria.cargoItemIdFrom !== undefined) {
      conditions.push("`cargo_item_id` >= ?");
      values.push(criteria.cargoItemIdFrom);
    }
    if (criteria.cargoItemIdTo !== undefined) {
      conditions.push("`cargo_item_id` <= ?");
      values.push(criteria.cargoItemIdTo);
    }
    if (criteria.consignmentId !== undefined) {
      conditions.push("`consignment_id` = ?");
      values.push(criteria.consignmentId);
    }
    if (criteria.consignmentIdFrom !== undefined) {
      conditions.push("`consignment_id` >= ?");
      values.push(criteria.consignmentIdFrom);
    }
    if (criteria.consignmentIdTo !== undefined) {
      conditions.push("`consignment_id` <= ?");
      values.push(criteria.consignmentIdTo);
    }
    if (criteria.containerId !== undefined) {
      conditions.push("`container_id` = ?");
      values.push(criteria.containerId);
    }
    if (criteria.containerIdFrom !== undefined) {
      conditions.push("`container_id` >= ?");
      values.push(criteria.containerIdFrom);
    }
    if (criteria.containerIdTo !== undefined) {
      conditions.push("`container_id` <= ?");
      values.push(criteria.containerIdTo);
    }
    if (criteria.containerIdIsNull !== undefined) {
      conditions.push(
        criteria.containerIdIsNull
          ? "`container_id` IS NULL"
          : "`container_id` IS NOT NULL",
      );
    }
    if (criteria.lineNumber !== undefined) {
      conditions.push("`line_number` = ?");
      values.push(criteria.lineNumber);
    }
    if (criteria.lineNumberFrom !== undefined) {
      conditions.push("`line_number` >= ?");
      values.push(criteria.lineNumberFrom);
    }
    if (criteria.lineNumberTo !== undefined) {
      conditions.push("`line_number` <= ?");
      values.push(criteria.lineNumberTo);
    }
    if (criteria.hsCode !== undefined) {
      conditions.push("`hs_code` = ?");
      values.push(criteria.hsCode);
    }
    if (criteria.hsCodeLike !== undefined) {
      conditions.push("`hs_code` LIKE ?");
      values.push(criteria.hsCodeLike);
    }
    if (criteria.description !== undefined) {
      conditions.push("`description` = ?");
      values.push(criteria.description);
    }
    if (criteria.descriptionLike !== undefined) {
      conditions.push("`description` LIKE ?");
      values.push(criteria.descriptionLike);
    }
    if (criteria.packageKind !== undefined) {
      conditions.push("`package_kind` = ?");
      values.push(criteria.packageKind);
    }
    if (criteria.packageKindLike !== undefined) {
      conditions.push("`package_kind` LIKE ?");
      values.push(criteria.packageKindLike);
    }
    if (criteria.packageCount !== undefined) {
      conditions.push("`package_count` = ?");
      values.push(criteria.packageCount);
    }
    if (criteria.packageCountFrom !== undefined) {
      conditions.push("`package_count` >= ?");
      values.push(criteria.packageCountFrom);
    }
    if (criteria.packageCountTo !== undefined) {
      conditions.push("`package_count` <= ?");
      values.push(criteria.packageCountTo);
    }
    if (criteria.grossWeightKg !== undefined) {
      conditions.push("`gross_weight_kg` = ?");
      values.push(criteria.grossWeightKg);
    }
    if (criteria.grossWeightKgFrom !== undefined) {
      conditions.push("`gross_weight_kg` >= ?");
      values.push(criteria.grossWeightKgFrom);
    }
    if (criteria.grossWeightKgTo !== undefined) {
      conditions.push("`gross_weight_kg` <= ?");
      values.push(criteria.grossWeightKgTo);
    }
    if (criteria.netWeightKg !== undefined) {
      conditions.push("`net_weight_kg` = ?");
      values.push(criteria.netWeightKg);
    }
    if (criteria.netWeightKgFrom !== undefined) {
      conditions.push("`net_weight_kg` >= ?");
      values.push(criteria.netWeightKgFrom);
    }
    if (criteria.netWeightKgTo !== undefined) {
      conditions.push("`net_weight_kg` <= ?");
      values.push(criteria.netWeightKgTo);
    }
    if (criteria.volumeCbm !== undefined) {
      conditions.push("`volume_cbm` = ?");
      values.push(criteria.volumeCbm);
    }
    if (criteria.volumeCbmFrom !== undefined) {
      conditions.push("`volume_cbm` >= ?");
      values.push(criteria.volumeCbmFrom);
    }
    if (criteria.volumeCbmTo !== undefined) {
      conditions.push("`volume_cbm` <= ?");
      values.push(criteria.volumeCbmTo);
    }
    if (criteria.chargeableWeightKg !== undefined) {
      conditions.push("`chargeable_weight_kg` = ?");
      values.push(criteria.chargeableWeightKg);
    }
    if (criteria.chargeableWeightKgFrom !== undefined) {
      conditions.push("`chargeable_weight_kg` >= ?");
      values.push(criteria.chargeableWeightKgFrom);
    }
    if (criteria.chargeableWeightKgTo !== undefined) {
      conditions.push("`chargeable_weight_kg` <= ?");
      values.push(criteria.chargeableWeightKgTo);
    }
    if (criteria.chargeableWeightKgIsNull !== undefined) {
      conditions.push(
        criteria.chargeableWeightKgIsNull
          ? "`chargeable_weight_kg` IS NULL"
          : "`chargeable_weight_kg` IS NOT NULL",
      );
    }
    if (criteria.imdgClass !== undefined) {
      conditions.push("`imdg_class` = ?");
      values.push(criteria.imdgClass);
    }
    if (criteria.imdgClassLike !== undefined) {
      conditions.push("`imdg_class` LIKE ?");
      values.push(criteria.imdgClassLike);
    }
    if (criteria.unNumber !== undefined) {
      conditions.push("`un_number` = ?");
      values.push(criteria.unNumber);
    }
    if (criteria.unNumberFrom !== undefined) {
      conditions.push("`un_number` >= ?");
      values.push(criteria.unNumberFrom);
    }
    if (criteria.unNumberTo !== undefined) {
      conditions.push("`un_number` <= ?");
      values.push(criteria.unNumberTo);
    }
    if (criteria.unNumberIsNull !== undefined) {
      conditions.push(
        criteria.unNumberIsNull
          ? "`un_number` IS NULL"
          : "`un_number` IS NOT NULL",
      );
    }
    if (criteria.originCountry !== undefined) {
      conditions.push("`origin_country` = ?");
      values.push(criteria.originCountry);
    }
    if (criteria.originCountryLike !== undefined) {
      conditions.push("`origin_country` LIKE ?");
      values.push(criteria.originCountryLike);
    }
    if (criteria.unitValue !== undefined) {
      conditions.push("`unit_value` = ?");
      values.push(criteria.unitValue);
    }
    if (criteria.unitValueFrom !== undefined) {
      conditions.push("`unit_value` >= ?");
      values.push(criteria.unitValueFrom);
    }
    if (criteria.unitValueTo !== undefined) {
      conditions.push("`unit_value` <= ?");
      values.push(criteria.unitValueTo);
    }
    if (criteria.lineValue !== undefined) {
      conditions.push("`line_value` = ?");
      values.push(criteria.lineValue);
    }
    if (criteria.lineValueFrom !== undefined) {
      conditions.push("`line_value` >= ?");
      values.push(criteria.lineValueFrom);
    }
    if (criteria.lineValueTo !== undefined) {
      conditions.push("`line_value` <= ?");
      values.push(criteria.lineValueTo);
    }
    if (criteria.lineValueIsNull !== undefined) {
      conditions.push(
        criteria.lineValueIsNull
          ? "`line_value` IS NULL"
          : "`line_value` IS NOT NULL",
      );
    }

    let sql = SELECT;
    if (conditions.length > 0) {
      sql += ' WHERE ' + conditions.join(' AND ');
    }
    if (order.length > 0) {
      sql +=
        ' ORDER BY ' +
        order
          .map(
            (term) =>
              cargoItemColumnSql(term.column) +
              ' ' +
              directionSql(term.direction ?? 'asc'),
          )
          .join(', ');
    }
    if (limit !== null) {
      sql += ' LIMIT ?';
      values.push(limit);
      if (offset !== null) {
        sql += ' OFFSET ?';
        values.push(offset);
      }
    }

    try {
      const [rows] = await this.#connection.execute(
        { sql, rowsAsArray: true },
        values,
      );
      return /** @type {RowDataPacket[]} */ (rows).map(toRow);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }
}
