// Code generated by tpl from freight.charge. DO NOT EDIT.

/**
 * The `freight.charge` row, the key that addresses it, the columns an ordering may
 * name, and the filter a search takes.
 *
 * @module
 */

/** @import { Direction } from './core.js' */

import { UnknownColumn } from './core.js';

// The table's own comment, as the catalogue carries it:
// Encargos aplicados a cada expedição

/**
 * One row of `freight.charge`.
 *
 * Every property is present on a row. A column that admits `NULL` is typed
 * `T | null`, which is what mysql2 hands back for a `NULL` and what `tsc`
 * makes a caller narrow before reading.
 *
 * @typedef {object} Charge
 * @property {string} chargeId `charge_id`, declared `bigint(20) unsigned` NOT NULL AUTO_INCREMENT.
 *   It is part of the primary key.
 * @property {string} consignmentId `consignment_id`, declared `bigint(20) unsigned` NOT NULL.
 * @property {string} chargeCode `charge_code`, declared `varchar(8)` NOT NULL.
 * @property {string} quantity `quantity`, declared `decimal(10,3)` NOT NULL.
 * @property {string} unitAmount `unit_amount`, declared `decimal(12,4)` NOT NULL.
 * @property {string} currency `currency`, declared `char(3)` NOT NULL.
 * @property {string} fxRateToEur `fx_rate_to_eur`, declared `decimal(12,6)` NOT NULL.
 * @property {string | null} netAmount `net_amount`, declared `decimal(14,2)` NULL STORED GENERATED AS (round(`quantity` * `unit_amount`,2)).
 *   Comment: Stored generated column: the line total before tax
 * @property {string} payer `payer`, declared `enum('Shipper','Consignee','Third party')` NOT NULL.
 * @property {Date | null} invoicedOn `invoiced_on`, declared `date` NULL.
 * @property {string | null} invoiceNumber `invoice_number`, declared `varchar(20)` NULL.
 */

/**
 * The primary key of `freight.charge`.
 *
 * @typedef {object} ChargeKey
 * @property {string} chargeId `charge_id`, declared `bigint(20) unsigned` NOT NULL AUTO_INCREMENT.
 */

/**
 * One column of `freight.charge`.
 *
 * A search accepts an ordering term over these values and over nothing else,
 * so an ordering can carry no SQL of its own. A caller may write the column's
 * catalogue name as a string literal instead: {@link ChargeColumn} is the union
 * of the values below, so the two are the same value and the same type.
 */
export const ChargeColumns = Object.freeze(
  /** @type {const} */ ({
    /** `charge_id`, declared `bigint(20) unsigned` NOT NULL AUTO_INCREMENT. */
    CHARGE_ID: "charge_id",
    /** `consignment_id`, declared `bigint(20) unsigned` NOT NULL. */
    CONSIGNMENT_ID: "consignment_id",
    /** `charge_code`, declared `varchar(8)` NOT NULL. */
    CHARGE_CODE: "charge_code",
    /** `quantity`, declared `decimal(10,3)` NOT NULL. */
    QUANTITY: "quantity",
    /** `unit_amount`, declared `decimal(12,4)` NOT NULL. */
    UNIT_AMOUNT: "unit_amount",
    /** `currency`, declared `char(3)` NOT NULL. */
    CURRENCY: "currency",
    /** `fx_rate_to_eur`, declared `decimal(12,6)` NOT NULL. */
    FX_RATE_TO_EUR: "fx_rate_to_eur",
    /** `net_amount`, declared `decimal(14,2)` NULL STORED GENERATED AS (round(`quantity` * `unit_amount`,2)). */
    NET_AMOUNT: "net_amount",
    /** `payer`, declared `enum('Shipper','Consignee','Third party')` NOT NULL. */
    PAYER: "payer",
    /** `invoiced_on`, declared `date` NULL. */
    INVOICED_ON: "invoiced_on",
    /** `invoice_number`, declared `varchar(20)` NULL. */
    INVOICE_NUMBER: "invoice_number",
  }),
);

/**
 * A column of `freight.charge` an ordering may name.
 *
 * @typedef {(typeof ChargeColumns)[keyof typeof ChargeColumns]} ChargeColumn
 */

/**
 * The one place a column of `freight.charge` becomes SQL.
 *
 * It is closed over the constants above, and every identifier in it was quoted
 * at render time by `tpl`, so no value a caller supplies can reach a
 * statement's text through an ordering term.
 *
 * @type {Readonly<Record<ChargeColumn, string>>}
 */
const COLUMN_SQL = Object.freeze({
  "charge_id": "`charge_id`",
  "consignment_id": "`consignment_id`",
  "charge_code": "`charge_code`",
  "quantity": "`quantity`",
  "unit_amount": "`unit_amount`",
  "currency": "`currency`",
  "fx_rate_to_eur": "`fx_rate_to_eur`",
  "net_amount": "`net_amount`",
  "payer": "`payer`",
  "invoiced_on": "`invoiced_on`",
  "invoice_number": "`invoice_number`",
});

/**
 * The column as a statement's text names it: quoted for MariaDB.
 *
 * The lookup is by own property and the refusal is unconditional, so a caller
 * that reached past the type — with an unchecked string, or a value read from
 * a request — is refused here rather than interpolated.
 *
 * @param {ChargeColumn} column
 * @returns {string}
 * @throws {UnknownColumn} for every name the table does not carry.
 */
export function chargeColumnSql(column) {
  if (!Object.hasOwn(COLUMN_SQL, column)) {
    throw new UnknownColumn("freight.charge", String(column));
  }
  return COLUMN_SQL[column];
}

/**
 * One ordering term of a search over `freight.charge`.
 *
 * @typedef {object} ChargeOrder
 * @property {ChargeColumn} column the column to order by
 * @property {Direction} [direction] the direction to order in. Ascending when absent.
 */

/**
 * What narrows a search over `freight.charge`.
 *
 * Every property is optional: a property left absent adds no condition, and the
 * conditions a search does build are joined with `AND`. The empty object is the
 * filter that matches every row.
 *
 * A property is absent for *no condition* and is never `null` for *is NULL*.
 * That question is asked through the `…IsNull` property a nullable column also
 * gets, so the two meanings never collide, and it is why no filter property
 * admits `null`.
 *
 * @typedef {object} ChargeFilter
 * @property {string} [chargeId] where set, requires `charge_id` to equal it.
 * @property {string} [chargeIdFrom] where set, requires `charge_id` to be at least it.
 * @property {string} [chargeIdTo] where set, requires `charge_id` to be at most it.
 * @property {string} [consignmentId] where set, requires `consignment_id` to equal it.
 * @property {string} [consignmentIdFrom] where set, requires `consignment_id` to be at least it.
 * @property {string} [consignmentIdTo] where set, requires `consignment_id` to be at most it.
 * @property {string} [chargeCode] where set, requires `charge_code` to equal it.
 * @property {string} [chargeCodeLike] where set, requires `charge_code` to match it, as LIKE matches.
 * @property {string} [quantity] where set, requires `quantity` to equal it.
 * @property {string} [quantityFrom] where set, requires `quantity` to be at least it.
 * @property {string} [quantityTo] where set, requires `quantity` to be at most it.
 * @property {string} [unitAmount] where set, requires `unit_amount` to equal it.
 * @property {string} [unitAmountFrom] where set, requires `unit_amount` to be at least it.
 * @property {string} [unitAmountTo] where set, requires `unit_amount` to be at most it.
 * @property {string} [currency] where set, requires `currency` to equal it.
 * @property {string} [currencyLike] where set, requires `currency` to match it, as LIKE matches.
 * @property {string} [fxRateToEur] where set, requires `fx_rate_to_eur` to equal it.
 * @property {string} [fxRateToEurFrom] where set, requires `fx_rate_to_eur` to be at least it.
 * @property {string} [fxRateToEurTo] where set, requires `fx_rate_to_eur` to be at most it.
 * @property {string} [netAmount] where set, requires `net_amount` to equal it.
 * @property {string} [netAmountFrom] where set, requires `net_amount` to be at least it.
 * @property {string} [netAmountTo] where set, requires `net_amount` to be at most it.
 * @property {boolean} [netAmountIsNull] where true, requires `net_amount` to be NULL; where false, requires it not to be.
 * @property {string} [payer] where set, requires `payer` to equal it.
 * @property {string} [payerLike] where set, requires `payer` to match it, as LIKE matches.
 * @property {Date} [invoicedOn] where set, requires `invoiced_on` to equal it.
 * @property {Date} [invoicedOnFrom] where set, requires `invoiced_on` to be at least it.
 * @property {Date} [invoicedOnTo] where set, requires `invoiced_on` to be at most it.
 * @property {boolean} [invoicedOnIsNull] where true, requires `invoiced_on` to be NULL; where false, requires it not to be.
 * @property {string} [invoiceNumber] where set, requires `invoice_number` to equal it.
 * @property {string} [invoiceNumberLike] where set, requires `invoice_number` to match it, as LIKE matches.
 * @property {boolean} [invoiceNumberIsNull] where true, requires `invoice_number` to be NULL; where false, requires it not to be.
 */
