// Code generated by tpl from freight.charge_code. DO NOT EDIT.

/**
 * The `freight.charge_code` row, the key that addresses it, the columns an ordering may
 * name, and the filter a search takes.
 *
 * @module
 */

/** @import { Direction } from './core.js' */

import { UnknownColumn } from './core.js';

// The table's own comment, as the catalogue carries it:
// Códigos de encargo utilizados na facturação

/**
 * One row of `freight.charge_code`.
 *
 * Every property is present on a row. A column that admits `NULL` is typed
 * `T | null`, which is what mysql2 hands back for a `NULL` and what `tsc`
 * makes a caller narrow before reading.
 *
 * @typedef {object} ChargeCode
 * @property {string} chargeCode `charge_code`, declared `varchar(8)` NOT NULL.
 *   It is part of the primary key.
 *   Comment: Industry charge code, e.g. BAF, THC, ISPS
 * @property {string} description `description`, declared `varchar(100)` NOT NULL.
 * @property {number} isFreight `is_freight`, declared `tinyint(1)` NOT NULL.
 *   Comment: Counts towards ocean freight rather than local charges
 * @property {string} vatRate `vat_rate`, declared `decimal(5,4)` NOT NULL.
 * @property {string} glAccount `gl_account`, declared `varchar(12)` NOT NULL.
 */

/**
 * The primary key of `freight.charge_code`.
 *
 * @typedef {object} ChargeCodeKey
 * @property {string} chargeCode `charge_code`, declared `varchar(8)` NOT NULL.
 */

/**
 * One column of `freight.charge_code`.
 *
 * A search accepts an ordering term over these values and over nothing else,
 * so an ordering can carry no SQL of its own. A caller may write the column's
 * catalogue name as a string literal instead: {@link ChargeCodeColumn} is the union
 * of the values below, so the two are the same value and the same type.
 */
export const ChargeCodeColumns = Object.freeze(
  /** @type {const} */ ({
    /** `charge_code`, declared `varchar(8)` NOT NULL. */
    CHARGE_CODE: "charge_code",
    /** `description`, declared `varchar(100)` NOT NULL. */
    DESCRIPTION: "description",
    /** `is_freight`, declared `tinyint(1)` NOT NULL. */
    IS_FREIGHT: "is_freight",
    /** `vat_rate`, declared `decimal(5,4)` NOT NULL. */
    VAT_RATE: "vat_rate",
    /** `gl_account`, declared `varchar(12)` NOT NULL. */
    GL_ACCOUNT: "gl_account",
  }),
);

/**
 * A column of `freight.charge_code` an ordering may name.
 *
 * @typedef {(typeof ChargeCodeColumns)[keyof typeof ChargeCodeColumns]} ChargeCodeColumn
 */

/**
 * The one place a column of `freight.charge_code` becomes SQL.
 *
 * It is closed over the constants above, and every identifier in it was quoted
 * at render time by `tpl`, so no value a caller supplies can reach a
 * statement's text through an ordering term.
 *
 * @type {Readonly<Record<ChargeCodeColumn, string>>}
 */
const COLUMN_SQL = Object.freeze({
  "charge_code": "`charge_code`",
  "description": "`description`",
  "is_freight": "`is_freight`",
  "vat_rate": "`vat_rate`",
  "gl_account": "`gl_account`",
});

/**
 * The column as a statement's text names it: quoted for MariaDB.
 *
 * The lookup is by own property and the refusal is unconditional, so a caller
 * that reached past the type — with an unchecked string, or a value read from
 * a request — is refused here rather than interpolated.
 *
 * @param {ChargeCodeColumn} column
 * @returns {string}
 * @throws {UnknownColumn} for every name the table does not carry.
 */
export function chargeCodeColumnSql(column) {
  if (!Object.hasOwn(COLUMN_SQL, column)) {
    throw new UnknownColumn("freight.charge_code", String(column));
  }
  return COLUMN_SQL[column];
}

/**
 * One ordering term of a search over `freight.charge_code`.
 *
 * @typedef {object} ChargeCodeOrder
 * @property {ChargeCodeColumn} column the column to order by
 * @property {Direction} [direction] the direction to order in. Ascending when absent.
 */

/**
 * What narrows a search over `freight.charge_code`.
 *
 * Every property is optional: a property left absent adds no condition, and the
 * conditions a search does build are joined with `AND`. The empty object is the
 * filter that matches every row.
 *
 * A property is absent for *no condition* and is never `null` for *is NULL*.
 * That question is asked through the `…IsNull` property a nullable column also
 * gets, so the two meanings never collide, and it is why no filter property
 * admits `null`.
 *
 * @typedef {object} ChargeCodeFilter
 * @property {string} [chargeCode] where set, requires `charge_code` to equal it.
 * @property {string} [chargeCodeLike] where set, requires `charge_code` to match it, as LIKE matches.
 * @property {string} [description] where set, requires `description` to equal it.
 * @property {string} [descriptionLike] where set, requires `description` to match it, as LIKE matches.
 * @property {number} [isFreight] where set, requires `is_freight` to equal it.
 * @property {number} [isFreightFrom] where set, requires `is_freight` to be at least it.
 * @property {number} [isFreightTo] where set, requires `is_freight` to be at most it.
 * @property {string} [vatRate] where set, requires `vat_rate` to equal it.
 * @property {string} [vatRateFrom] where set, requires `vat_rate` to be at least it.
 * @property {string} [vatRateTo] where set, requires `vat_rate` to be at most it.
 * @property {string} [glAccount] where set, requires `gl_account` to equal it.
 * @property {string} [glAccountLike] where set, requires `gl_account` to match it, as LIKE matches.
 */
