// Code generated by tpl from freight.consignment. DO NOT EDIT.

/**
 * The mysql2 implementation of the `freight.consignment` data layer.
 *
 * @module
 */

/** @import { Connection, ResultSetHeader, RowDataPacket } from 'mysql2/promise' */
/** @import { BoundValue } from './core.js' */
/** @import { Consignment, ConsignmentFilter, ConsignmentKey, ConsignmentOrder } from './consignment.js' */

import { NotFound, directionSql, failure } from './core.js';
import { consignmentColumnSql } from './consignment.js';
import { ConsignmentRepository } from './consignment_repository.js';

/** The table every statement of this module addresses, as an error names it. */
const TABLE = "freight.consignment";

/** Selects every column of the table, in catalogue order. */
const SELECT = "SELECT `consignment_id`, `booking_reference`, `bill_of_lading_no`, `shipper_id`, `consignee_id`, `vessel_imo`, `voyage_number`, `origin_locode`, `destination_locode`, `invoice_currency`, `payment_due_on`, `hs_code_override`, `shipper_reference`, `broker_reference`, `incoterm`, `service_scope`, `handling_flags`, `status`, `declared_value`, `freight_amount`, `insurance_rate`, `insured_amount`, `gross_weight_kg`, `volume_cbm`, `notification_flags`, `is_hazardous`, `marks_and_numbers`, `goods_description`, `packing_list`, `terms_and_conditions`, `booked_at`, `updated_at` FROM `consignment`";

/** Selects the one row a primary key names. */
const READ = "SELECT `consignment_id`, `booking_reference`, `bill_of_lading_no`, `shipper_id`, `consignee_id`, `vessel_imo`, `voyage_number`, `origin_locode`, `destination_locode`, `invoice_currency`, `payment_due_on`, `hs_code_override`, `shipper_reference`, `broker_reference`, `incoterm`, `service_scope`, `handling_flags`, `status`, `declared_value`, `freight_amount`, `insurance_rate`, `insured_amount`, `gross_weight_kg`, `volume_cbm`, `notification_flags`, `is_hazardous`, `marks_and_numbers`, `goods_description`, `packing_list`, `terms_and_conditions`, `booked_at`, `updated_at` FROM `consignment` WHERE `consignment_id` = ?";

/**
 * Inserts one row. It names neither a generated column nor an auto-increment
 * key, because the server writes both.
 */
const INSERT = "INSERT INTO `consignment` (`booking_reference`, `bill_of_lading_no`, `shipper_id`, `consignee_id`, `vessel_imo`, `voyage_number`, `origin_locode`, `destination_locode`, `invoice_currency`, `payment_due_on`, `hs_code_override`, `shipper_reference`, `broker_reference`, `incoterm`, `service_scope`, `handling_flags`, `status`, `declared_value`, `freight_amount`, `insurance_rate`, `gross_weight_kg`, `volume_cbm`, `notification_flags`, `is_hazardous`, `marks_and_numbers`, `goods_description`, `packing_list`, `terms_and_conditions`, `booked_at`, `updated_at`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

/** Writes every column that is neither generated nor part of the key. */
const UPDATE = "UPDATE `consignment` SET `booking_reference` = ?, `bill_of_lading_no` = ?, `shipper_id` = ?, `consignee_id` = ?, `vessel_imo` = ?, `voyage_number` = ?, `origin_locode` = ?, `destination_locode` = ?, `invoice_currency` = ?, `payment_due_on` = ?, `hs_code_override` = ?, `shipper_reference` = ?, `broker_reference` = ?, `incoterm` = ?, `service_scope` = ?, `handling_flags` = ?, `status` = ?, `declared_value` = ?, `freight_amount` = ?, `insurance_rate` = ?, `gross_weight_kg` = ?, `volume_cbm` = ?, `notification_flags` = ?, `is_hazardous` = ?, `marks_and_numbers` = ?, `goods_description` = ?, `packing_list` = ?, `terms_and_conditions` = ?, `booked_at` = ?, `updated_at` = ? WHERE `consignment_id` = ?";

/** Removes the one row a primary key names. */
const DELETE = "DELETE FROM `consignment` WHERE `consignment_id` = ?";

/**
 * Build a row from one result tuple.
 *
 * The positions are the order `SELECT` names the columns in, which is
 * catalogue order. Every statement below is run with `rowsAsArray`, so a
 * result is an array and never an object: a column named `__proto__` or
 * `constructor` would otherwise reach an object literal as a key, and the
 * first of those sets a prototype instead of defining a property.
 *
 * The values are whatever mysql2 decoded, and the types `Consignment` declares
 * are this example's record of what that is.
 *
 * @param {RowDataPacket} values
 * @returns {Consignment}
 */
function toRow(values) {
  return {
    consignmentId: values[0],
    bookingReference: values[1],
    billOfLadingNo: values[2],
    shipperId: values[3],
    consigneeId: values[4],
    vesselImo: values[5],
    voyageNumber: values[6],
    originLocode: values[7],
    destinationLocode: values[8],
    invoiceCurrency: values[9],
    paymentDueOn: values[10],
    hsCodeOverride: values[11],
    shipperReference: values[12],
    brokerReference: values[13],
    incoterm: values[14],
    serviceScope: values[15],
    handlingFlags: values[16],
    status: values[17],
    declaredValue: values[18],
    freightAmount: values[19],
    insuranceRate: values[20],
    insuredAmount: values[21],
    grossWeightKg: values[22],
    volumeCbm: values[23],
    notificationFlags: values[24],
    isHazardous: values[25],
    marksAndNumbers: values[26],
    goodsDescription: values[27],
    packingList: values[28],
    termsAndConditions: values[29],
    bookedAt: values[30],
    updatedAt: values[31],
  };
}

/**
 * The mysql2 data layer of `freight.consignment`.
 *
 * Nothing here commits. mysql2 autocommits until a caller calls
 * `beginTransaction`, so transaction control stays with the caller.
 */
export class ConsignmentMysql2 extends ConsignmentRepository {
  /** @type {Connection} */
  #connection;

  /**
   * Build the data layer of `freight.consignment` over `connection`.
   *
   * The connection must address the schema `SCHEMA` names, because the
   * statements above address the table unqualified. `connect` is the
   * connection that carries it.
   *
   * @param {Connection} connection
   */
  constructor(connection) {
    super();
    this.#connection = connection;
  }

  /**
   * Insert `row`.
   *
   * The key is assigned by the server and is written back into `row`.
   *
   * @override
   * @param {Consignment} row
   * @returns {Promise<void>}
   */
  async create(row) {
    /** @type {BoundValue[]} */
    const values = [
      row.bookingReference,
      row.billOfLadingNo,
      row.shipperId,
      row.consigneeId,
      row.vesselImo,
      row.voyageNumber,
      row.originLocode,
      row.destinationLocode,
      row.invoiceCurrency,
      row.paymentDueOn,
      row.hsCodeOverride,
      row.shipperReference,
      row.brokerReference,
      row.incoterm,
      row.serviceScope,
      row.handlingFlags,
      row.status,
      row.declaredValue,
      row.freightAmount,
      row.insuranceRate,
      row.grossWeightKg,
      row.volumeCbm,
      row.notificationFlags,
      row.isHazardous,
      row.marksAndNumbers,
      row.goodsDescription,
      row.packingList,
      row.termsAndConditions,
      row.bookedAt,
      row.updatedAt,
    ];
    try {
      const [result] = await this.#connection.execute(INSERT, values);
      const { insertId } = /** @type {ResultSetHeader} */ (result);
      // The key is a BIGINT and every row of this package carries one as a
      // `string`, because `connect` sets `bigNumberStrings`. mysql2 reports
      // `insertId` as a `number` whatever the column is, so it is converted
      // here rather than left to widen the row's type.
      row.consignmentId = String(insertId);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Return the row `key` names.
   *
   * @override
   * @param {ConsignmentKey} key
   * @returns {Promise<Consignment>}
   */
  async read(key) {
    /** @type {BoundValue[]} */
    const values = [
      key.consignmentId,
    ];
    try {
      const [rows] = await this.#connection.execute(
        { sql: READ, rowsAsArray: true },
        values,
      );
      const found = /** @type {RowDataPacket[]} */ (rows);
      if (found.length === 0) {
        throw new NotFound(TABLE);
      }
      return toRow(found[0]);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Write every writable column of `row` over the row its key names.
   *
   * @override
   * @param {Consignment} row
   * @returns {Promise<number>}
   */
  async update(row) {
    /** @type {BoundValue[]} */
    const values = [
      row.bookingReference,
      row.billOfLadingNo,
      row.shipperId,
      row.consigneeId,
      row.vesselImo,
      row.voyageNumber,
      row.originLocode,
      row.destinationLocode,
      row.invoiceCurrency,
      row.paymentDueOn,
      row.hsCodeOverride,
      row.shipperReference,
      row.brokerReference,
      row.incoterm,
      row.serviceScope,
      row.handlingFlags,
      row.status,
      row.declaredValue,
      row.freightAmount,
      row.insuranceRate,
      row.grossWeightKg,
      row.volumeCbm,
      row.notificationFlags,
      row.isHazardous,
      row.marksAndNumbers,
      row.goodsDescription,
      row.packingList,
      row.termsAndConditions,
      row.bookedAt,
      row.updatedAt,
      row.consignmentId,
    ];
    try {
      const [result] = await this.#connection.execute(UPDATE, values);
      return /** @type {ResultSetHeader} */ (result).affectedRows;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Remove the row `key` names.
   *
   * @override
   * @param {ConsignmentKey} key
   * @returns {Promise<number>}
   */
  async delete(key) {
    /** @type {BoundValue[]} */
    const values = [
      key.consignmentId,
    ];
    try {
      const [result] = await this.#connection.execute(DELETE, values);
      return /** @type {ResultSetHeader} */ (result).affectedRows;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Return every row matching `criteria`, ordered by the terms of `order`.
   *
   * @override
   * @param {ConsignmentFilter} criteria
   * @param {readonly ConsignmentOrder[]} [order]
   * @param {number | null} [limit]
   * @param {number | null} [offset]
   * @returns {Promise<Consignment[]>}
   */
  async search(criteria, order = [], limit = null, offset = null) {
    /** @type {string[]} */
    const conditions = [];
    /** @type {BoundValue[]} */
    const values = [];

    if (criteria.consignmentId !== undefined) {
      conditions.push("`consignment_id` = ?");
      values.push(criteria.consignmentId);
    }
    if (criteria.consignmentIdFrom !== undefined) {
      conditions.push("`consignment_id` >= ?");
      values.push(criteria.consignmentIdFrom);
    }
    if (criteria.consignmentIdTo !== undefined) {
      conditions.push("`consignment_id` <= ?");
      values.push(criteria.consignmentIdTo);
    }
    if (criteria.bookingReference !== undefined) {
      conditions.push("`booking_reference` = ?");
      values.push(criteria.bookingReference);
    }
    if (criteria.bookingReferenceLike !== undefined) {
      conditions.push("`booking_reference` LIKE ?");
      values.push(criteria.bookingReferenceLike);
    }
    if (criteria.billOfLadingNo !== undefined) {
      conditions.push("`bill_of_lading_no` = ?");
      values.push(criteria.billOfLadingNo);
    }
    if (criteria.billOfLadingNoLike !== undefined) {
      conditions.push("`bill_of_lading_no` LIKE ?");
      values.push(criteria.billOfLadingNoLike);
    }
    if (criteria.billOfLadingNoIsNull !== undefined) {
      conditions.push(
        criteria.billOfLadingNoIsNull
          ? "`bill_of_lading_no` IS NULL"
          : "`bill_of_lading_no` IS NOT NULL",
      );
    }
    if (criteria.shipperId !== undefined) {
      conditions.push("`shipper_id` = ?");
      values.push(criteria.shipperId);
    }
    if (criteria.shipperIdFrom !== undefined) {
      conditions.push("`shipper_id` >= ?");
      values.push(criteria.shipperIdFrom);
    }
    if (criteria.shipperIdTo !== undefined) {
      conditions.push("`shipper_id` <= ?");
      values.push(criteria.shipperIdTo);
    }
    if (criteria.consigneeId !== undefined) {
      conditions.push("`consignee_id` = ?");
      values.push(criteria.consigneeId);
    }
    if (criteria.consigneeIdFrom !== undefined) {
      conditions.push("`consignee_id` >= ?");
      values.push(criteria.consigneeIdFrom);
    }
    if (criteria.consigneeIdTo !== undefined) {
      conditions.push("`consignee_id` <= ?");
      values.push(criteria.consigneeIdTo);
    }
    if (criteria.consigneeIdIsNull !== undefined) {
      conditions.push(
        criteria.consigneeIdIsNull
          ? "`consignee_id` IS NULL"
          : "`consignee_id` IS NOT NULL",
      );
    }
    if (criteria.vesselImo !== undefined) {
      conditions.push("`vessel_imo` = ?");
      values.push(criteria.vesselImo);
    }
    if (criteria.vesselImoLike !== undefined) {
      conditions.push("`vessel_imo` LIKE ?");
      values.push(criteria.vesselImoLike);
    }
    if (criteria.vesselImoIsNull !== undefined) {
      conditions.push(
        criteria.vesselImoIsNull
          ? "`vessel_imo` IS NULL"
          : "`vessel_imo` IS NOT NULL",
      );
    }
    if (criteria.voyageNumber !== undefined) {
      conditions.push("`voyage_number` = ?");
      values.push(criteria.voyageNumber);
    }
    if (criteria.voyageNumberLike !== undefined) {
      conditions.push("`voyage_number` LIKE ?");
      values.push(criteria.voyageNumberLike);
    }
    if (criteria.voyageNumberIsNull !== undefined) {
      conditions.push(
        criteria.voyageNumberIsNull
          ? "`voyage_number` IS NULL"
          : "`voyage_number` IS NOT NULL",
      );
    }
    if (criteria.originLocode !== undefined) {
      conditions.push("`origin_locode` = ?");
      values.push(criteria.originLocode);
    }
    if (criteria.originLocodeLike !== undefined) {
      conditions.push("`origin_locode` LIKE ?");
      values.push(criteria.originLocodeLike);
    }
    if (criteria.destinationLocode !== undefined) {
      conditions.push("`destination_locode` = ?");
      values.push(criteria.destinationLocode);
    }
    if (criteria.destinationLocodeLike !== undefined) {
      conditions.push("`destination_locode` LIKE ?");
      values.push(criteria.destinationLocodeLike);
    }
    if (criteria.invoiceCurrency !== undefined) {
      conditions.push("`invoice_currency` = ?");
      values.push(criteria.invoiceCurrency);
    }
    if (criteria.invoiceCurrencyLike !== undefined) {
      conditions.push("`invoice_currency` LIKE ?");
      values.push(criteria.invoiceCurrencyLike);
    }
    if (criteria.paymentDueOn !== undefined) {
      conditions.push("`payment_due_on` = ?");
      values.push(criteria.paymentDueOn);
    }
    if (criteria.paymentDueOnFrom !== undefined) {
      conditions.push("`payment_due_on` >= ?");
      values.push(criteria.paymentDueOnFrom);
    }
    if (criteria.paymentDueOnTo !== undefined) {
      conditions.push("`payment_due_on` <= ?");
      values.push(criteria.paymentDueOnTo);
    }
    if (criteria.hsCodeOverride !== undefined) {
      conditions.push("`hs_code_override` = ?");
      values.push(criteria.hsCodeOverride);
    }
    if (criteria.hsCodeOverrideLike !== undefined) {
      conditions.push("`hs_code_override` LIKE ?");
      values.push(criteria.hsCodeOverrideLike);
    }
    if (criteria.hsCodeOverrideIsNull !== undefined) {
      conditions.push(
        criteria.hsCodeOverrideIsNull
          ? "`hs_code_override` IS NULL"
          : "`hs_code_override` IS NOT NULL",
      );
    }
    if (criteria.shipperReference !== undefined) {
      conditions.push("`shipper_reference` = ?");
      values.push(criteria.shipperReference);
    }
    if (criteria.shipperReferenceLike !== undefined) {
      conditions.push("`shipper_reference` LIKE ?");
      values.push(criteria.shipperReferenceLike);
    }
    if (criteria.brokerReference !== undefined) {
      conditions.push("`broker_reference` = ?");
      values.push(criteria.brokerReference);
    }
    if (criteria.brokerReferenceLike !== undefined) {
      conditions.push("`broker_reference` LIKE ?");
      values.push(criteria.brokerReferenceLike);
    }
    if (criteria.brokerReferenceIsNull !== undefined) {
      conditions.push(
        criteria.brokerReferenceIsNull
          ? "`broker_reference` IS NULL"
          : "`broker_reference` IS NOT NULL",
      );
    }
    if (criteria.incoterm !== undefined) {
      conditions.push("`incoterm` = ?");
      values.push(criteria.incoterm);
    }
    if (criteria.incotermLike !== undefined) {
      conditions.push("`incoterm` LIKE ?");
      values.push(criteria.incotermLike);
    }
    if (criteria.serviceScope !== undefined) {
      conditions.push("`service_scope` = ?");
      values.push(criteria.serviceScope);
    }
    if (criteria.serviceScopeLike !== undefined) {
      conditions.push("`service_scope` LIKE ?");
      values.push(criteria.serviceScopeLike);
    }
    if (criteria.handlingFlags !== undefined) {
      conditions.push("`handling_flags` = ?");
      values.push(criteria.handlingFlags);
    }
    if (criteria.handlingFlagsLike !== undefined) {
      conditions.push("`handling_flags` LIKE ?");
      values.push(criteria.handlingFlagsLike);
    }
    if (criteria.status !== undefined) {
      conditions.push("`status` = ?");
      values.push(criteria.status);
    }
    if (criteria.statusLike !== undefined) {
      conditions.push("`status` LIKE ?");
      values.push(criteria.statusLike);
    }
    if (criteria.declaredValue !== undefined) {
      conditions.push("`declared_value` = ?");
      values.push(criteria.declaredValue);
    }
    if (criteria.declaredValueFrom !== undefined) {
      conditions.push("`declared_value` >= ?");
      values.push(criteria.declaredValueFrom);
    }
    if (criteria.declaredValueTo !== undefined) {
      conditions.push("`declared_value` <= ?");
      values.push(criteria.declaredValueTo);
    }
    if (criteria.freightAmount !== undefined) {
      conditions.push("`freight_amount` = ?");
      values.push(criteria.freightAmount);
    }
    if (criteria.freightAmountFrom !== undefined) {
      conditions.push("`freight_amount` >= ?");
      values.push(criteria.freightAmountFrom);
    }
    if (criteria.freightAmountTo !== undefined) {
      conditions.push("`freight_amount` <= ?");
      values.push(criteria.freightAmountTo);
    }
    if (criteria.insuranceRate !== undefined) {
      conditions.push("`insurance_rate` = ?");
      values.push(criteria.insuranceRate);
    }
    if (criteria.insuranceRateFrom !== undefined) {
      conditions.push("`insurance_rate` >= ?");
      values.push(criteria.insuranceRateFrom);
    }
    if (criteria.insuranceRateTo !== undefined) {
      conditions.push("`insurance_rate` <= ?");
      values.push(criteria.insuranceRateTo);
    }
    if (criteria.insuranceRateIsNull !== undefined) {
      conditions.push(
        criteria.insuranceRateIsNull
          ? "`insurance_rate` IS NULL"
          : "`insurance_rate` IS NOT NULL",
      );
    }
    if (criteria.insuredAmount !== undefined) {
      conditions.push("`insured_amount` = ?");
      values.push(criteria.insuredAmount);
    }
    if (criteria.insuredAmountFrom !== undefined) {
      conditions.push("`insured_amount` >= ?");
      values.push(criteria.insuredAmountFrom);
    }
    if (criteria.insuredAmountTo !== undefined) {
      conditions.push("`insured_amount` <= ?");
      values.push(criteria.insuredAmountTo);
    }
    if (criteria.insuredAmountIsNull !== undefined) {
      conditions.push(
        criteria.insuredAmountIsNull
          ? "`insured_amount` IS NULL"
          : "`insured_amount` IS NOT NULL",
      );
    }
    if (criteria.grossWeightKg !== undefined) {
      conditions.push("`gross_weight_kg` = ?");
      values.push(criteria.grossWeightKg);
    }
    if (criteria.grossWeightKgFrom !== undefined) {
      conditions.push("`gross_weight_kg` >= ?");
      values.push(criteria.grossWeightKgFrom);
    }
    if (criteria.grossWeightKgTo !== undefined) {
      conditions.push("`gross_weight_kg` <= ?");
      values.push(criteria.grossWeightKgTo);
    }
    if (criteria.volumeCbm !== undefined) {
      conditions.push("`volume_cbm` = ?");
      values.push(criteria.volumeCbm);
    }
    if (criteria.volumeCbmFrom !== undefined) {
      conditions.push("`volume_cbm` >= ?");
      values.push(criteria.volumeCbmFrom);
    }
    if (criteria.volumeCbmTo !== undefined) {
      conditions.push("`volume_cbm` <= ?");
      values.push(criteria.volumeCbmTo);
    }
    if (criteria.volumeCbmIsNull !== undefined) {
      conditions.push(
        criteria.volumeCbmIsNull
          ? "`volume_cbm` IS NULL"
          : "`volume_cbm` IS NOT NULL",
      );
    }
    if (criteria.notificationFlags !== undefined) {
      conditions.push("`notification_flags` = ?");
      values.push(criteria.notificationFlags);
    }
    if (criteria.notificationFlagsFrom !== undefined) {
      conditions.push("`notification_flags` >= ?");
      values.push(criteria.notificationFlagsFrom);
    }
    if (criteria.notificationFlagsTo !== undefined) {
      conditions.push("`notification_flags` <= ?");
      values.push(criteria.notificationFlagsTo);
    }
    if (criteria.isHazardous !== undefined) {
      conditions.push("`is_hazardous` = ?");
      values.push(criteria.isHazardous);
    }
    if (criteria.isHazardousFrom !== undefined) {
      conditions.push("`is_hazardous` >= ?");
      values.push(criteria.isHazardousFrom);
    }
    if (criteria.isHazardousTo !== undefined) {
      conditions.push("`is_hazardous` <= ?");
      values.push(criteria.isHazardousTo);
    }
    if (criteria.marksAndNumbers !== undefined) {
      conditions.push("`marks_and_numbers` = ?");
      values.push(criteria.marksAndNumbers);
    }
    if (criteria.marksAndNumbersLike !== undefined) {
      conditions.push("`marks_and_numbers` LIKE ?");
      values.push(criteria.marksAndNumbersLike);
    }
    if (criteria.marksAndNumbersIsNull !== undefined) {
      conditions.push(
        criteria.marksAndNumbersIsNull
          ? "`marks_and_numbers` IS NULL"
          : "`marks_and_numbers` IS NOT NULL",
      );
    }
    if (criteria.goodsDescription !== undefined) {
      conditions.push("`goods_description` = ?");
      values.push(criteria.goodsDescription);
    }
    if (criteria.goodsDescriptionLike !== undefined) {
      conditions.push("`goods_description` LIKE ?");
      values.push(criteria.goodsDescriptionLike);
    }
    if (criteria.packingList !== undefined) {
      conditions.push("`packing_list` = ?");
      values.push(criteria.packingList);
    }
    if (criteria.packingListLike !== undefined) {
      conditions.push("`packing_list` LIKE ?");
      values.push(criteria.packingListLike);
    }
    if (criteria.packingListIsNull !== undefined) {
      conditions.push(
        criteria.packingListIsNull
          ? "`packing_list` IS NULL"
          : "`packing_list` IS NOT NULL",
      );
    }
    if (criteria.termsAndConditions !== undefined) {
      conditions.push("`terms_and_conditions` = ?");
      values.push(criteria.termsAndConditions);
    }
    if (criteria.termsAndConditionsLike !== undefined) {
      conditions.push("`terms_and_conditions` LIKE ?");
      values.push(criteria.termsAndConditionsLike);
    }
    if (criteria.termsAndConditionsIsNull !== undefined) {
      conditions.push(
        criteria.termsAndConditionsIsNull
          ? "`terms_and_conditions` IS NULL"
          : "`terms_and_conditions` IS NOT NULL",
      );
    }
    if (criteria.bookedAt !== undefined) {
      conditions.push("`booked_at` = ?");
      values.push(criteria.bookedAt);
    }
    if (criteria.bookedAtFrom !== undefined) {
      conditions.push("`booked_at` >= ?");
      values.push(criteria.bookedAtFrom);
    }
    if (criteria.bookedAtTo !== undefined) {
      conditions.push("`booked_at` <= ?");
      values.push(criteria.bookedAtTo);
    }
    if (criteria.updatedAt !== undefined) {
      conditions.push("`updated_at` = ?");
      values.push(criteria.updatedAt);
    }
    if (criteria.updatedAtFrom !== undefined) {
      conditions.push("`updated_at` >= ?");
      values.push(criteria.updatedAtFrom);
    }
    if (criteria.updatedAtTo !== undefined) {
      conditions.push("`updated_at` <= ?");
      values.push(criteria.updatedAtTo);
    }

    let sql = SELECT;
    if (conditions.length > 0) {
      sql += ' WHERE ' + conditions.join(' AND ');
    }
    if (order.length > 0) {
      sql +=
        ' ORDER BY ' +
        order
          .map(
            (term) =>
              consignmentColumnSql(term.column) +
              ' ' +
              directionSql(term.direction ?? 'asc'),
          )
          .join(', ');
    }
    if (limit !== null) {
      sql += ' LIMIT ?';
      values.push(limit);
      if (offset !== null) {
        sql += ' OFFSET ?';
        values.push(offset);
      }
    }

    try {
      const [rows] = await this.#connection.execute(
        { sql, rowsAsArray: true },
        values,
      );
      return /** @type {RowDataPacket[]} */ (rows).map(toRow);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }
}
