// Code generated by tpl from freight.container_type. DO NOT EDIT.

/**
 * The `freight.container_type` row, the key that addresses it, the columns an ordering may
 * name, and the filter a search takes.
 *
 * @module
 */

/** @import { Direction } from './core.js' */

import { UnknownColumn } from './core.js';

// The table's own comment, as the catalogue carries it:
// Tipos de contentor normalizados ISO 6346

/**
 * One row of `freight.container_type`.
 *
 * Every property is present on a row. A column that admits `NULL` is typed
 * `T | null`, which is what mysql2 hands back for a `NULL` and what `tsc`
 * makes a caller narrow before reading.
 *
 * @typedef {object} ContainerType
 * @property {string} isoCode `iso_code`, declared `char(4)` NOT NULL.
 *   It is part of the primary key.
 *   Comment: ISO 6346 size-and-type code, e.g. 22G1
 * @property {string} description `description`, declared `varchar(80)` NOT NULL.
 * @property {number} lengthFt `length_ft`, declared `tinyint(3) unsigned` NOT NULL.
 * @property {string} heightFtIn `height_ft_in`, declared `varchar(6)` NOT NULL.
 *   Comment: Nominal external height, feet and inches
 * @property {string} tareWeightKg `tare_weight_kg`, declared `decimal(8,2)` NOT NULL.
 * @property {string} maxPayloadKg `max_payload_kg`, declared `decimal(8,2)` NOT NULL.
 * @property {string} internalVolumeCbm `internal_volume_cbm`, declared `decimal(7,3)` NOT NULL.
 * @property {number} isReefer `is_reefer`, declared `tinyint(1)` NOT NULL.
 * @property {number} isTank `is_tank`, declared `tinyint(1)` NOT NULL.
 */

/**
 * The primary key of `freight.container_type`.
 *
 * @typedef {object} ContainerTypeKey
 * @property {string} isoCode `iso_code`, declared `char(4)` NOT NULL.
 */

/**
 * One column of `freight.container_type`.
 *
 * A search accepts an ordering term over these values and over nothing else,
 * so an ordering can carry no SQL of its own. A caller may write the column's
 * catalogue name as a string literal instead: {@link ContainerTypeColumn} is the union
 * of the values below, so the two are the same value and the same type.
 */
export const ContainerTypeColumns = Object.freeze(
  /** @type {const} */ ({
    /** `iso_code`, declared `char(4)` NOT NULL. */
    ISO_CODE: "iso_code",
    /** `description`, declared `varchar(80)` NOT NULL. */
    DESCRIPTION: "description",
    /** `length_ft`, declared `tinyint(3) unsigned` NOT NULL. */
    LENGTH_FT: "length_ft",
    /** `height_ft_in`, declared `varchar(6)` NOT NULL. */
    HEIGHT_FT_IN: "height_ft_in",
    /** `tare_weight_kg`, declared `decimal(8,2)` NOT NULL. */
    TARE_WEIGHT_KG: "tare_weight_kg",
    /** `max_payload_kg`, declared `decimal(8,2)` NOT NULL. */
    MAX_PAYLOAD_KG: "max_payload_kg",
    /** `internal_volume_cbm`, declared `decimal(7,3)` NOT NULL. */
    INTERNAL_VOLUME_CBM: "internal_volume_cbm",
    /** `is_reefer`, declared `tinyint(1)` NOT NULL. */
    IS_REEFER: "is_reefer",
    /** `is_tank`, declared `tinyint(1)` NOT NULL. */
    IS_TANK: "is_tank",
  }),
);

/**
 * A column of `freight.container_type` an ordering may name.
 *
 * @typedef {(typeof ContainerTypeColumns)[keyof typeof ContainerTypeColumns]} ContainerTypeColumn
 */

/**
 * The one place a column of `freight.container_type` becomes SQL.
 *
 * It is closed over the constants above, and every identifier in it was quoted
 * at render time by `tpl`, so no value a caller supplies can reach a
 * statement's text through an ordering term.
 *
 * @type {Readonly<Record<ContainerTypeColumn, string>>}
 */
const COLUMN_SQL = Object.freeze({
  "iso_code": "`iso_code`",
  "description": "`description`",
  "length_ft": "`length_ft`",
  "height_ft_in": "`height_ft_in`",
  "tare_weight_kg": "`tare_weight_kg`",
  "max_payload_kg": "`max_payload_kg`",
  "internal_volume_cbm": "`internal_volume_cbm`",
  "is_reefer": "`is_reefer`",
  "is_tank": "`is_tank`",
});

/**
 * The column as a statement's text names it: quoted for MariaDB.
 *
 * The lookup is by own property and the refusal is unconditional, so a caller
 * that reached past the type — with an unchecked string, or a value read from
 * a request — is refused here rather than interpolated.
 *
 * @param {ContainerTypeColumn} column
 * @returns {string}
 * @throws {UnknownColumn} for every name the table does not carry.
 */
export function containerTypeColumnSql(column) {
  if (!Object.hasOwn(COLUMN_SQL, column)) {
    throw new UnknownColumn("freight.container_type", String(column));
  }
  return COLUMN_SQL[column];
}

/**
 * One ordering term of a search over `freight.container_type`.
 *
 * @typedef {object} ContainerTypeOrder
 * @property {ContainerTypeColumn} column the column to order by
 * @property {Direction} [direction] the direction to order in. Ascending when absent.
 */

/**
 * What narrows a search over `freight.container_type`.
 *
 * Every property is optional: a property left absent adds no condition, and the
 * conditions a search does build are joined with `AND`. The empty object is the
 * filter that matches every row.
 *
 * A property is absent for *no condition* and is never `null` for *is NULL*.
 * That question is asked through the `…IsNull` property a nullable column also
 * gets, so the two meanings never collide, and it is why no filter property
 * admits `null`.
 *
 * @typedef {object} ContainerTypeFilter
 * @property {string} [isoCode] where set, requires `iso_code` to equal it.
 * @property {string} [isoCodeLike] where set, requires `iso_code` to match it, as LIKE matches.
 * @property {string} [description] where set, requires `description` to equal it.
 * @property {string} [descriptionLike] where set, requires `description` to match it, as LIKE matches.
 * @property {number} [lengthFt] where set, requires `length_ft` to equal it.
 * @property {number} [lengthFtFrom] where set, requires `length_ft` to be at least it.
 * @property {number} [lengthFtTo] where set, requires `length_ft` to be at most it.
 * @property {string} [heightFtIn] where set, requires `height_ft_in` to equal it.
 * @property {string} [heightFtInLike] where set, requires `height_ft_in` to match it, as LIKE matches.
 * @property {string} [tareWeightKg] where set, requires `tare_weight_kg` to equal it.
 * @property {string} [tareWeightKgFrom] where set, requires `tare_weight_kg` to be at least it.
 * @property {string} [tareWeightKgTo] where set, requires `tare_weight_kg` to be at most it.
 * @property {string} [maxPayloadKg] where set, requires `max_payload_kg` to equal it.
 * @property {string} [maxPayloadKgFrom] where set, requires `max_payload_kg` to be at least it.
 * @property {string} [maxPayloadKgTo] where set, requires `max_payload_kg` to be at most it.
 * @property {string} [internalVolumeCbm] where set, requires `internal_volume_cbm` to equal it.
 * @property {string} [internalVolumeCbmFrom] where set, requires `internal_volume_cbm` to be at least it.
 * @property {string} [internalVolumeCbmTo] where set, requires `internal_volume_cbm` to be at most it.
 * @property {number} [isReefer] where set, requires `is_reefer` to equal it.
 * @property {number} [isReeferFrom] where set, requires `is_reefer` to be at least it.
 * @property {number} [isReeferTo] where set, requires `is_reefer` to be at most it.
 * @property {number} [isTank] where set, requires `is_tank` to equal it.
 * @property {number} [isTankFrom] where set, requires `is_tank` to be at least it.
 * @property {number} [isTankTo] where set, requires `is_tank` to be at most it.
 */
