// Code generated by tpl from freight.container_type. DO NOT EDIT.

/**
 * The mysql2 implementation of the `freight.container_type` data layer.
 *
 * @module
 */

/** @import { Connection, ResultSetHeader, RowDataPacket } from 'mysql2/promise' */
/** @import { BoundValue } from './core.js' */
/** @import { ContainerType, ContainerTypeFilter, ContainerTypeKey, ContainerTypeOrder } from './container_type.js' */

import { NotFound, directionSql, failure } from './core.js';
import { containerTypeColumnSql } from './container_type.js';
import { ContainerTypeRepository } from './container_type_repository.js';

/** The table every statement of this module addresses, as an error names it. */
const TABLE = "freight.container_type";

/** Selects every column of the table, in catalogue order. */
const SELECT = "SELECT `iso_code`, `description`, `length_ft`, `height_ft_in`, `tare_weight_kg`, `max_payload_kg`, `internal_volume_cbm`, `is_reefer`, `is_tank` FROM `container_type`";

/** Selects the one row a primary key names. */
const READ = "SELECT `iso_code`, `description`, `length_ft`, `height_ft_in`, `tare_weight_kg`, `max_payload_kg`, `internal_volume_cbm`, `is_reefer`, `is_tank` FROM `container_type` WHERE `iso_code` = ?";

/**
 * Inserts one row. It names neither a generated column nor an auto-increment
 * key, because the server writes both.
 */
const INSERT = "INSERT INTO `container_type` (`iso_code`, `description`, `length_ft`, `height_ft_in`, `tare_weight_kg`, `max_payload_kg`, `internal_volume_cbm`, `is_reefer`, `is_tank`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

/** Writes every column that is neither generated nor part of the key. */
const UPDATE = "UPDATE `container_type` SET `description` = ?, `length_ft` = ?, `height_ft_in` = ?, `tare_weight_kg` = ?, `max_payload_kg` = ?, `internal_volume_cbm` = ?, `is_reefer` = ?, `is_tank` = ? WHERE `iso_code` = ?";

/** Removes the one row a primary key names. */
const DELETE = "DELETE FROM `container_type` WHERE `iso_code` = ?";

/**
 * Build a row from one result tuple.
 *
 * The positions are the order `SELECT` names the columns in, which is
 * catalogue order. Every statement below is run with `rowsAsArray`, so a
 * result is an array and never an object: a column named `__proto__` or
 * `constructor` would otherwise reach an object literal as a key, and the
 * first of those sets a prototype instead of defining a property.
 *
 * The values are whatever mysql2 decoded, and the types `ContainerType` declares
 * are this example's record of what that is.
 *
 * @param {RowDataPacket} values
 * @returns {ContainerType}
 */
function toRow(values) {
  return {
    isoCode: values[0],
    description: values[1],
    lengthFt: values[2],
    heightFtIn: values[3],
    tareWeightKg: values[4],
    maxPayloadKg: values[5],
    internalVolumeCbm: values[6],
    isReefer: values[7],
    isTank: values[8],
  };
}

/**
 * The mysql2 data layer of `freight.container_type`.
 *
 * Nothing here commits. mysql2 autocommits until a caller calls
 * `beginTransaction`, so transaction control stays with the caller.
 */
export class ContainerTypeMysql2 extends ContainerTypeRepository {
  /** @type {Connection} */
  #connection;

  /**
   * Build the data layer of `freight.container_type` over `connection`.
   *
   * The connection must address the schema `SCHEMA` names, because the
   * statements above address the table unqualified. `connect` is the
   * connection that carries it.
   *
   * @param {Connection} connection
   */
  constructor(connection) {
    super();
    this.#connection = connection;
  }

  /**
   * Insert `row`.
   *
   * The whole key is taken from `row`, which the caller therefore fills.
   *
   * @override
   * @param {ContainerType} row
   * @returns {Promise<void>}
   */
  async create(row) {
    /** @type {BoundValue[]} */
    const values = [
      row.isoCode,
      row.description,
      row.lengthFt,
      row.heightFtIn,
      row.tareWeightKg,
      row.maxPayloadKg,
      row.internalVolumeCbm,
      row.isReefer,
      row.isTank,
    ];
    try {
      const [result] = await this.#connection.execute(INSERT, values);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Return the row `key` names.
   *
   * @override
   * @param {ContainerTypeKey} key
   * @returns {Promise<ContainerType>}
   */
  async read(key) {
    /** @type {BoundValue[]} */
    const values = [
      key.isoCode,
    ];
    try {
      const [rows] = await this.#connection.execute(
        { sql: READ, rowsAsArray: true },
        values,
      );
      const found = /** @type {RowDataPacket[]} */ (rows);
      if (found.length === 0) {
        throw new NotFound(TABLE);
      }
      return toRow(found[0]);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Write every writable column of `row` over the row its key names.
   *
   * @override
   * @param {ContainerType} row
   * @returns {Promise<number>}
   */
  async update(row) {
    /** @type {BoundValue[]} */
    const values = [
      row.description,
      row.lengthFt,
      row.heightFtIn,
      row.tareWeightKg,
      row.maxPayloadKg,
      row.internalVolumeCbm,
      row.isReefer,
      row.isTank,
      row.isoCode,
    ];
    try {
      const [result] = await this.#connection.execute(UPDATE, values);
      return /** @type {ResultSetHeader} */ (result).affectedRows;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Remove the row `key` names.
   *
   * @override
   * @param {ContainerTypeKey} key
   * @returns {Promise<number>}
   */
  async delete(key) {
    /** @type {BoundValue[]} */
    const values = [
      key.isoCode,
    ];
    try {
      const [result] = await this.#connection.execute(DELETE, values);
      return /** @type {ResultSetHeader} */ (result).affectedRows;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Return every row matching `criteria`, ordered by the terms of `order`.
   *
   * @override
   * @param {ContainerTypeFilter} criteria
   * @param {readonly ContainerTypeOrder[]} [order]
   * @param {number | null} [limit]
   * @param {number | null} [offset]
   * @returns {Promise<ContainerType[]>}
   */
  async search(criteria, order = [], limit = null, offset = null) {
    /** @type {string[]} */
    const conditions = [];
    /** @type {BoundValue[]} */
    const values = [];

    if (criteria.isoCode !== undefined) {
      conditions.push("`iso_code` = ?");
      values.push(criteria.isoCode);
    }
    if (criteria.isoCodeLike !== undefined) {
      conditions.push("`iso_code` LIKE ?");
      values.push(criteria.isoCodeLike);
    }
    if (criteria.description !== undefined) {
      conditions.push("`description` = ?");
      values.push(criteria.description);
    }
    if (criteria.descriptionLike !== undefined) {
      conditions.push("`description` LIKE ?");
      values.push(criteria.descriptionLike);
    }
    if (criteria.lengthFt !== undefined) {
      conditions.push("`length_ft` = ?");
      values.push(criteria.lengthFt);
    }
    if (criteria.lengthFtFrom !== undefined) {
      conditions.push("`length_ft` >= ?");
      values.push(criteria.lengthFtFrom);
    }
    if (criteria.lengthFtTo !== undefined) {
      conditions.push("`length_ft` <= ?");
      values.push(criteria.lengthFtTo);
    }
    if (criteria.heightFtIn !== undefined) {
      conditions.push("`height_ft_in` = ?");
      values.push(criteria.heightFtIn);
    }
    if (criteria.heightFtInLike !== undefined) {
      conditions.push("`height_ft_in` LIKE ?");
      values.push(criteria.heightFtInLike);
    }
    if (criteria.tareWeightKg !== undefined) {
      conditions.push("`tare_weight_kg` = ?");
      values.push(criteria.tareWeightKg);
    }
    if (criteria.tareWeightKgFrom !== undefined) {
      conditions.push("`tare_weight_kg` >= ?");
      values.push(criteria.tareWeightKgFrom);
    }
    if (criteria.tareWeightKgTo !== undefined) {
      conditions.push("`tare_weight_kg` <= ?");
      values.push(criteria.tareWeightKgTo);
    }
    if (criteria.maxPayloadKg !== undefined) {
      conditions.push("`max_payload_kg` = ?");
      values.push(criteria.maxPayloadKg);
    }
    if (criteria.maxPayloadKgFrom !== undefined) {
      conditions.push("`max_payload_kg` >= ?");
      values.push(criteria.maxPayloadKgFrom);
    }
    if (criteria.maxPayloadKgTo !== undefined) {
      conditions.push("`max_payload_kg` <= ?");
      values.push(criteria.maxPayloadKgTo);
    }
    if (criteria.internalVolumeCbm !== undefined) {
      conditions.push("`internal_volume_cbm` = ?");
      values.push(criteria.internalVolumeCbm);
    }
    if (criteria.internalVolumeCbmFrom !== undefined) {
      conditions.push("`internal_volume_cbm` >= ?");
      values.push(criteria.internalVolumeCbmFrom);
    }
    if (criteria.internalVolumeCbmTo !== undefined) {
      conditions.push("`internal_volume_cbm` <= ?");
      values.push(criteria.internalVolumeCbmTo);
    }
    if (criteria.isReefer !== undefined) {
      conditions.push("`is_reefer` = ?");
      values.push(criteria.isReefer);
    }
    if (criteria.isReeferFrom !== undefined) {
      conditions.push("`is_reefer` >= ?");
      values.push(criteria.isReeferFrom);
    }
    if (criteria.isReeferTo !== undefined) {
      conditions.push("`is_reefer` <= ?");
      values.push(criteria.isReeferTo);
    }
    if (criteria.isTank !== undefined) {
      conditions.push("`is_tank` = ?");
      values.push(criteria.isTank);
    }
    if (criteria.isTankFrom !== undefined) {
      conditions.push("`is_tank` >= ?");
      values.push(criteria.isTankFrom);
    }
    if (criteria.isTankTo !== undefined) {
      conditions.push("`is_tank` <= ?");
      values.push(criteria.isTankTo);
    }

    let sql = SELECT;
    if (conditions.length > 0) {
      sql += ' WHERE ' + conditions.join(' AND ');
    }
    if (order.length > 0) {
      sql +=
        ' ORDER BY ' +
        order
          .map(
            (term) =>
              containerTypeColumnSql(term.column) +
              ' ' +
              directionSql(term.direction ?? 'asc'),
          )
          .join(', ');
    }
    if (limit !== null) {
      sql += ' LIMIT ?';
      values.push(limit);
      if (offset !== null) {
        sql += ' OFFSET ?';
        values.push(offset);
      }
    }

    try {
      const [rows] = await this.#connection.execute(
        { sql, rowsAsArray: true },
        values,
      );
      return /** @type {RowDataPacket[]} */ (rows).map(toRow);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }
}
