// Code generated by tpl from freight.customs_declaration. DO NOT EDIT.

/**
 * The `freight.customs_declaration` row, the key that addresses it, the columns an ordering may
 * name, and the filter a search takes.
 *
 * @module
 */

/** @import { Direction } from './core.js' */

import { UnknownColumn } from './core.js';

// The table's own comment, as the catalogue carries it:
// Declarações aduaneiras associadas às expedições

/**
 * One row of `freight.customs_declaration`.
 *
 * Every property is present on a row. A column that admits `NULL` is typed
 * `T | null`, which is what mysql2 hands back for a `NULL` and what `tsc`
 * makes a caller narrow before reading.
 *
 * @typedef {object} CustomsDeclaration
 * @property {string} declarationId `declaration_id`, declared `bigint(20) unsigned` NOT NULL AUTO_INCREMENT.
 *   It is part of the primary key.
 * @property {string} consignmentId `consignment_id`, declared `bigint(20) unsigned` NOT NULL.
 * @property {number | null} clearancePortId `clearance_port_id`, declared `smallint(5) unsigned` NULL.
 *   Comment: NULL once the port record is retired; the declaration itself must survive
 * @property {string} mrn `mrn`, declared `varchar(21)` NOT NULL.
 *   It is part of a unique index.
 *   Comment: Movement Reference Number issued by the customs office
 * @property {string} procedureCode `procedure_code`, declared `char(4)` NOT NULL.
 * @property {string} regime `regime`, declared `enum('Export','Import','Transit T1','Transit T2','Temporary admission','Re-export')` NOT NULL.
 * @property {string} status `status`, declared `enum('Draft','Lodged','Under control','Released','Rejected')` NOT NULL.
 * @property {Date | null} lodgedAt `lodged_at`, declared `datetime(6)` NULL.
 * @property {Date | null} releasedAt `released_at`, declared `datetime(6)` NULL.
 * @property {string} dutyAmount `duty_amount`, declared `decimal(12,2)` NOT NULL.
 * @property {string} vatAmount `vat_amount`, declared `decimal(12,2)` NOT NULL.
 * @property {string | null} totalPayable `total_payable`, declared `decimal(12,2)` NULL STORED GENERATED AS (`duty_amount` + `vat_amount`).
 * @property {string | null} officerRemarks `officer_remarks`, declared `varchar(500)` NULL.
 */

/**
 * The primary key of `freight.customs_declaration`.
 *
 * @typedef {object} CustomsDeclarationKey
 * @property {string} declarationId `declaration_id`, declared `bigint(20) unsigned` NOT NULL AUTO_INCREMENT.
 */

/**
 * One column of `freight.customs_declaration`.
 *
 * A search accepts an ordering term over these values and over nothing else,
 * so an ordering can carry no SQL of its own. A caller may write the column's
 * catalogue name as a string literal instead: {@link CustomsDeclarationColumn} is the union
 * of the values below, so the two are the same value and the same type.
 */
export const CustomsDeclarationColumns = Object.freeze(
  /** @type {const} */ ({
    /** `declaration_id`, declared `bigint(20) unsigned` NOT NULL AUTO_INCREMENT. */
    DECLARATION_ID: "declaration_id",
    /** `consignment_id`, declared `bigint(20) unsigned` NOT NULL. */
    CONSIGNMENT_ID: "consignment_id",
    /** `clearance_port_id`, declared `smallint(5) unsigned` NULL. */
    CLEARANCE_PORT_ID: "clearance_port_id",
    /** `mrn`, declared `varchar(21)` NOT NULL. */
    MRN: "mrn",
    /** `procedure_code`, declared `char(4)` NOT NULL. */
    PROCEDURE_CODE: "procedure_code",
    /** `regime`, declared `enum('Export','Import','Transit T1','Transit T2','Temporary admission','Re-export')` NOT NULL. */
    REGIME: "regime",
    /** `status`, declared `enum('Draft','Lodged','Under control','Released','Rejected')` NOT NULL. */
    STATUS: "status",
    /** `lodged_at`, declared `datetime(6)` NULL. */
    LODGED_AT: "lodged_at",
    /** `released_at`, declared `datetime(6)` NULL. */
    RELEASED_AT: "released_at",
    /** `duty_amount`, declared `decimal(12,2)` NOT NULL. */
    DUTY_AMOUNT: "duty_amount",
    /** `vat_amount`, declared `decimal(12,2)` NOT NULL. */
    VAT_AMOUNT: "vat_amount",
    /** `total_payable`, declared `decimal(12,2)` NULL STORED GENERATED AS (`duty_amount` + `vat_amount`). */
    TOTAL_PAYABLE: "total_payable",
    /** `officer_remarks`, declared `varchar(500)` NULL. */
    OFFICER_REMARKS: "officer_remarks",
  }),
);

/**
 * A column of `freight.customs_declaration` an ordering may name.
 *
 * @typedef {(typeof CustomsDeclarationColumns)[keyof typeof CustomsDeclarationColumns]} CustomsDeclarationColumn
 */

/**
 * The one place a column of `freight.customs_declaration` becomes SQL.
 *
 * It is closed over the constants above, and every identifier in it was quoted
 * at render time by `tpl`, so no value a caller supplies can reach a
 * statement's text through an ordering term.
 *
 * @type {Readonly<Record<CustomsDeclarationColumn, string>>}
 */
const COLUMN_SQL = Object.freeze({
  "declaration_id": "`declaration_id`",
  "consignment_id": "`consignment_id`",
  "clearance_port_id": "`clearance_port_id`",
  "mrn": "`mrn`",
  "procedure_code": "`procedure_code`",
  "regime": "`regime`",
  "status": "`status`",
  "lodged_at": "`lodged_at`",
  "released_at": "`released_at`",
  "duty_amount": "`duty_amount`",
  "vat_amount": "`vat_amount`",
  "total_payable": "`total_payable`",
  "officer_remarks": "`officer_remarks`",
});

/**
 * The column as a statement's text names it: quoted for MariaDB.
 *
 * The lookup is by own property and the refusal is unconditional, so a caller
 * that reached past the type — with an unchecked string, or a value read from
 * a request — is refused here rather than interpolated.
 *
 * @param {CustomsDeclarationColumn} column
 * @returns {string}
 * @throws {UnknownColumn} for every name the table does not carry.
 */
export function customsDeclarationColumnSql(column) {
  if (!Object.hasOwn(COLUMN_SQL, column)) {
    throw new UnknownColumn("freight.customs_declaration", String(column));
  }
  return COLUMN_SQL[column];
}

/**
 * One ordering term of a search over `freight.customs_declaration`.
 *
 * @typedef {object} CustomsDeclarationOrder
 * @property {CustomsDeclarationColumn} column the column to order by
 * @property {Direction} [direction] the direction to order in. Ascending when absent.
 */

/**
 * What narrows a search over `freight.customs_declaration`.
 *
 * Every property is optional: a property left absent adds no condition, and the
 * conditions a search does build are joined with `AND`. The empty object is the
 * filter that matches every row.
 *
 * A property is absent for *no condition* and is never `null` for *is NULL*.
 * That question is asked through the `…IsNull` property a nullable column also
 * gets, so the two meanings never collide, and it is why no filter property
 * admits `null`.
 *
 * @typedef {object} CustomsDeclarationFilter
 * @property {string} [declarationId] where set, requires `declaration_id` to equal it.
 * @property {string} [declarationIdFrom] where set, requires `declaration_id` to be at least it.
 * @property {string} [declarationIdTo] where set, requires `declaration_id` to be at most it.
 * @property {string} [consignmentId] where set, requires `consignment_id` to equal it.
 * @property {string} [consignmentIdFrom] where set, requires `consignment_id` to be at least it.
 * @property {string} [consignmentIdTo] where set, requires `consignment_id` to be at most it.
 * @property {number} [clearancePortId] where set, requires `clearance_port_id` to equal it.
 * @property {number} [clearancePortIdFrom] where set, requires `clearance_port_id` to be at least it.
 * @property {number} [clearancePortIdTo] where set, requires `clearance_port_id` to be at most it.
 * @property {boolean} [clearancePortIdIsNull] where true, requires `clearance_port_id` to be NULL; where false, requires it not to be.
 * @property {string} [mrn] where set, requires `mrn` to equal it.
 * @property {string} [mrnLike] where set, requires `mrn` to match it, as LIKE matches.
 * @property {string} [procedureCode] where set, requires `procedure_code` to equal it.
 * @property {string} [procedureCodeLike] where set, requires `procedure_code` to match it, as LIKE matches.
 * @property {string} [regime] where set, requires `regime` to equal it.
 * @property {string} [regimeLike] where set, requires `regime` to match it, as LIKE matches.
 * @property {string} [status] where set, requires `status` to equal it.
 * @property {string} [statusLike] where set, requires `status` to match it, as LIKE matches.
 * @property {Date} [lodgedAt] where set, requires `lodged_at` to equal it.
 * @property {Date} [lodgedAtFrom] where set, requires `lodged_at` to be at least it.
 * @property {Date} [lodgedAtTo] where set, requires `lodged_at` to be at most it.
 * @property {boolean} [lodgedAtIsNull] where true, requires `lodged_at` to be NULL; where false, requires it not to be.
 * @property {Date} [releasedAt] where set, requires `released_at` to equal it.
 * @property {Date} [releasedAtFrom] where set, requires `released_at` to be at least it.
 * @property {Date} [releasedAtTo] where set, requires `released_at` to be at most it.
 * @property {boolean} [releasedAtIsNull] where true, requires `released_at` to be NULL; where false, requires it not to be.
 * @property {string} [dutyAmount] where set, requires `duty_amount` to equal it.
 * @property {string} [dutyAmountFrom] where set, requires `duty_amount` to be at least it.
 * @property {string} [dutyAmountTo] where set, requires `duty_amount` to be at most it.
 * @property {string} [vatAmount] where set, requires `vat_amount` to equal it.
 * @property {string} [vatAmountFrom] where set, requires `vat_amount` to be at least it.
 * @property {string} [vatAmountTo] where set, requires `vat_amount` to be at most it.
 * @property {string} [totalPayable] where set, requires `total_payable` to equal it.
 * @property {string} [totalPayableFrom] where set, requires `total_payable` to be at least it.
 * @property {string} [totalPayableTo] where set, requires `total_payable` to be at most it.
 * @property {boolean} [totalPayableIsNull] where true, requires `total_payable` to be NULL; where false, requires it not to be.
 * @property {string} [officerRemarks] where set, requires `officer_remarks` to equal it.
 * @property {string} [officerRemarksLike] where set, requires `officer_remarks` to match it, as LIKE matches.
 * @property {boolean} [officerRemarksIsNull] where true, requires `officer_remarks` to be NULL; where false, requires it not to be.
 */
