// Code generated by tpl from freight.customs_declaration. DO NOT EDIT.

/**
 * The mysql2 implementation of the `freight.customs_declaration` data layer.
 *
 * @module
 */

/** @import { Connection, ResultSetHeader, RowDataPacket } from 'mysql2/promise' */
/** @import { BoundValue } from './core.js' */
/** @import { CustomsDeclaration, CustomsDeclarationFilter, CustomsDeclarationKey, CustomsDeclarationOrder } from './customs_declaration.js' */

import { NotFound, directionSql, failure } from './core.js';
import { customsDeclarationColumnSql } from './customs_declaration.js';
import { CustomsDeclarationRepository } from './customs_declaration_repository.js';

/** The table every statement of this module addresses, as an error names it. */
const TABLE = "freight.customs_declaration";

/** Selects every column of the table, in catalogue order. */
const SELECT = "SELECT `declaration_id`, `consignment_id`, `clearance_port_id`, `mrn`, `procedure_code`, `regime`, `status`, `lodged_at`, `released_at`, `duty_amount`, `vat_amount`, `total_payable`, `officer_remarks` FROM `customs_declaration`";

/** Selects the one row a primary key names. */
const READ = "SELECT `declaration_id`, `consignment_id`, `clearance_port_id`, `mrn`, `procedure_code`, `regime`, `status`, `lodged_at`, `released_at`, `duty_amount`, `vat_amount`, `total_payable`, `officer_remarks` FROM `customs_declaration` WHERE `declaration_id` = ?";

/**
 * Inserts one row. It names neither a generated column nor an auto-increment
 * key, because the server writes both.
 */
const INSERT = "INSERT INTO `customs_declaration` (`consignment_id`, `clearance_port_id`, `mrn`, `procedure_code`, `regime`, `status`, `lodged_at`, `released_at`, `duty_amount`, `vat_amount`, `officer_remarks`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

/** Writes every column that is neither generated nor part of the key. */
const UPDATE = "UPDATE `customs_declaration` SET `consignment_id` = ?, `clearance_port_id` = ?, `mrn` = ?, `procedure_code` = ?, `regime` = ?, `status` = ?, `lodged_at` = ?, `released_at` = ?, `duty_amount` = ?, `vat_amount` = ?, `officer_remarks` = ? WHERE `declaration_id` = ?";

/** Removes the one row a primary key names. */
const DELETE = "DELETE FROM `customs_declaration` WHERE `declaration_id` = ?";

/**
 * Build a row from one result tuple.
 *
 * The positions are the order `SELECT` names the columns in, which is
 * catalogue order. Every statement below is run with `rowsAsArray`, so a
 * result is an array and never an object: a column named `__proto__` or
 * `constructor` would otherwise reach an object literal as a key, and the
 * first of those sets a prototype instead of defining a property.
 *
 * The values are whatever mysql2 decoded, and the types `CustomsDeclaration` declares
 * are this example's record of what that is.
 *
 * @param {RowDataPacket} values
 * @returns {CustomsDeclaration}
 */
function toRow(values) {
  return {
    declarationId: values[0],
    consignmentId: values[1],
    clearancePortId: values[2],
    mrn: values[3],
    procedureCode: values[4],
    regime: values[5],
    status: values[6],
    lodgedAt: values[7],
    releasedAt: values[8],
    dutyAmount: values[9],
    vatAmount: values[10],
    totalPayable: values[11],
    officerRemarks: values[12],
  };
}

/**
 * The mysql2 data layer of `freight.customs_declaration`.
 *
 * Nothing here commits. mysql2 autocommits until a caller calls
 * `beginTransaction`, so transaction control stays with the caller.
 */
export class CustomsDeclarationMysql2 extends CustomsDeclarationRepository {
  /** @type {Connection} */
  #connection;

  /**
   * Build the data layer of `freight.customs_declaration` over `connection`.
   *
   * The connection must address the schema `SCHEMA` names, because the
   * statements above address the table unqualified. `connect` is the
   * connection that carries it.
   *
   * @param {Connection} connection
   */
  constructor(connection) {
    super();
    this.#connection = connection;
  }

  /**
   * Insert `row`.
   *
   * The key is assigned by the server and is written back into `row`.
   *
   * @override
   * @param {CustomsDeclaration} row
   * @returns {Promise<void>}
   */
  async create(row) {
    /** @type {BoundValue[]} */
    const values = [
      row.consignmentId,
      row.clearancePortId,
      row.mrn,
      row.procedureCode,
      row.regime,
      row.status,
      row.lodgedAt,
      row.releasedAt,
      row.dutyAmount,
      row.vatAmount,
      row.officerRemarks,
    ];
    try {
      const [result] = await this.#connection.execute(INSERT, values);
      const { insertId } = /** @type {ResultSetHeader} */ (result);
      // The key is a BIGINT and every row of this package carries one as a
      // `string`, because `connect` sets `bigNumberStrings`. mysql2 reports
      // `insertId` as a `number` whatever the column is, so it is converted
      // here rather than left to widen the row's type.
      row.declarationId = String(insertId);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Return the row `key` names.
   *
   * @override
   * @param {CustomsDeclarationKey} key
   * @returns {Promise<CustomsDeclaration>}
   */
  async read(key) {
    /** @type {BoundValue[]} */
    const values = [
      key.declarationId,
    ];
    try {
      const [rows] = await this.#connection.execute(
        { sql: READ, rowsAsArray: true },
        values,
      );
      const found = /** @type {RowDataPacket[]} */ (rows);
      if (found.length === 0) {
        throw new NotFound(TABLE);
      }
      return toRow(found[0]);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Write every writable column of `row` over the row its key names.
   *
   * @override
   * @param {CustomsDeclaration} row
   * @returns {Promise<number>}
   */
  async update(row) {
    /** @type {BoundValue[]} */
    const values = [
      row.consignmentId,
      row.clearancePortId,
      row.mrn,
      row.procedureCode,
      row.regime,
      row.status,
      row.lodgedAt,
      row.releasedAt,
      row.dutyAmount,
      row.vatAmount,
      row.officerRemarks,
      row.declarationId,
    ];
    try {
      const [result] = await this.#connection.execute(UPDATE, values);
      return /** @type {ResultSetHeader} */ (result).affectedRows;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Remove the row `key` names.
   *
   * @override
   * @param {CustomsDeclarationKey} key
   * @returns {Promise<number>}
   */
  async delete(key) {
    /** @type {BoundValue[]} */
    const values = [
      key.declarationId,
    ];
    try {
      const [result] = await this.#connection.execute(DELETE, values);
      return /** @type {ResultSetHeader} */ (result).affectedRows;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Return every row matching `criteria`, ordered by the terms of `order`.
   *
   * @override
   * @param {CustomsDeclarationFilter} criteria
   * @param {readonly CustomsDeclarationOrder[]} [order]
   * @param {number | null} [limit]
   * @param {number | null} [offset]
   * @returns {Promise<CustomsDeclaration[]>}
   */
  async search(criteria, order = [], limit = null, offset = null) {
    /** @type {string[]} */
    const conditions = [];
    /** @type {BoundValue[]} */
    const values = [];

    if (criteria.declarationId !== undefined) {
      conditions.push("`declaration_id` = ?");
      values.push(criteria.declarationId);
    }
    if (criteria.declarationIdFrom !== undefined) {
      conditions.push("`declaration_id` >= ?");
      values.push(criteria.declarationIdFrom);
    }
    if (criteria.declarationIdTo !== undefined) {
      conditions.push("`declaration_id` <= ?");
      values.push(criteria.declarationIdTo);
    }
    if (criteria.consignmentId !== undefined) {
      conditions.push("`consignment_id` = ?");
      values.push(criteria.consignmentId);
    }
    if (criteria.consignmentIdFrom !== undefined) {
      conditions.push("`consignment_id` >= ?");
      values.push(criteria.consignmentIdFrom);
    }
    if (criteria.consignmentIdTo !== undefined) {
      conditions.push("`consignment_id` <= ?");
      values.push(criteria.consignmentIdTo);
    }
    if (criteria.clearancePortId !== undefined) {
      conditions.push("`clearance_port_id` = ?");
      values.push(criteria.clearancePortId);
    }
    if (criteria.clearancePortIdFrom !== undefined) {
      conditions.push("`clearance_port_id` >= ?");
      values.push(criteria.clearancePortIdFrom);
    }
    if (criteria.clearancePortIdTo !== undefined) {
      conditions.push("`clearance_port_id` <= ?");
      values.push(criteria.clearancePortIdTo);
    }
    if (criteria.clearancePortIdIsNull !== undefined) {
      conditions.push(
        criteria.clearancePortIdIsNull
          ? "`clearance_port_id` IS NULL"
          : "`clearance_port_id` IS NOT NULL",
      );
    }
    if (criteria.mrn !== undefined) {
      conditions.push("`mrn` = ?");
      values.push(criteria.mrn);
    }
    if (criteria.mrnLike !== undefined) {
      conditions.push("`mrn` LIKE ?");
      values.push(criteria.mrnLike);
    }
    if (criteria.procedureCode !== undefined) {
      conditions.push("`procedure_code` = ?");
      values.push(criteria.procedureCode);
    }
    if (criteria.procedureCodeLike !== undefined) {
      conditions.push("`procedure_code` LIKE ?");
      values.push(criteria.procedureCodeLike);
    }
    if (criteria.regime !== undefined) {
      conditions.push("`regime` = ?");
      values.push(criteria.regime);
    }
    if (criteria.regimeLike !== undefined) {
      conditions.push("`regime` LIKE ?");
      values.push(criteria.regimeLike);
    }
    if (criteria.status !== undefined) {
      conditions.push("`status` = ?");
      values.push(criteria.status);
    }
    if (criteria.statusLike !== undefined) {
      conditions.push("`status` LIKE ?");
      values.push(criteria.statusLike);
    }
    if (criteria.lodgedAt !== undefined) {
      conditions.push("`lodged_at` = ?");
      values.push(criteria.lodgedAt);
    }
    if (criteria.lodgedAtFrom !== undefined) {
      conditions.push("`lodged_at` >= ?");
      values.push(criteria.lodgedAtFrom);
    }
    if (criteria.lodgedAtTo !== undefined) {
      conditions.push("`lodged_at` <= ?");
      values.push(criteria.lodgedAtTo);
    }
    if (criteria.lodgedAtIsNull !== undefined) {
      conditions.push(
        criteria.lodgedAtIsNull
          ? "`lodged_at` IS NULL"
          : "`lodged_at` IS NOT NULL",
      );
    }
    if (criteria.releasedAt !== undefined) {
      conditions.push("`released_at` = ?");
      values.push(criteria.releasedAt);
    }
    if (criteria.releasedAtFrom !== undefined) {
      conditions.push("`released_at` >= ?");
      values.push(criteria.releasedAtFrom);
    }
    if (criteria.releasedAtTo !== undefined) {
      conditions.push("`released_at` <= ?");
      values.push(criteria.releasedAtTo);
    }
    if (criteria.releasedAtIsNull !== undefined) {
      conditions.push(
        criteria.releasedAtIsNull
          ? "`released_at` IS NULL"
          : "`released_at` IS NOT NULL",
      );
    }
    if (criteria.dutyAmount !== undefined) {
      conditions.push("`duty_amount` = ?");
      values.push(criteria.dutyAmount);
    }
    if (criteria.dutyAmountFrom !== undefined) {
      conditions.push("`duty_amount` >= ?");
      values.push(criteria.dutyAmountFrom);
    }
    if (criteria.dutyAmountTo !== undefined) {
      conditions.push("`duty_amount` <= ?");
      values.push(criteria.dutyAmountTo);
    }
    if (criteria.vatAmount !== undefined) {
      conditions.push("`vat_amount` = ?");
      values.push(criteria.vatAmount);
    }
    if (criteria.vatAmountFrom !== undefined) {
      conditions.push("`vat_amount` >= ?");
      values.push(criteria.vatAmountFrom);
    }
    if (criteria.vatAmountTo !== undefined) {
      conditions.push("`vat_amount` <= ?");
      values.push(criteria.vatAmountTo);
    }
    if (criteria.totalPayable !== undefined) {
      conditions.push("`total_payable` = ?");
      values.push(criteria.totalPayable);
    }
    if (criteria.totalPayableFrom !== undefined) {
      conditions.push("`total_payable` >= ?");
      values.push(criteria.totalPayableFrom);
    }
    if (criteria.totalPayableTo !== undefined) {
      conditions.push("`total_payable` <= ?");
      values.push(criteria.totalPayableTo);
    }
    if (criteria.totalPayableIsNull !== undefined) {
      conditions.push(
        criteria.totalPayableIsNull
          ? "`total_payable` IS NULL"
          : "`total_payable` IS NOT NULL",
      );
    }
    if (criteria.officerRemarks !== undefined) {
      conditions.push("`officer_remarks` = ?");
      values.push(criteria.officerRemarks);
    }
    if (criteria.officerRemarksLike !== undefined) {
      conditions.push("`officer_remarks` LIKE ?");
      values.push(criteria.officerRemarksLike);
    }
    if (criteria.officerRemarksIsNull !== undefined) {
      conditions.push(
        criteria.officerRemarksIsNull
          ? "`officer_remarks` IS NULL"
          : "`officer_remarks` IS NOT NULL",
      );
    }

    let sql = SELECT;
    if (conditions.length > 0) {
      sql += ' WHERE ' + conditions.join(' AND ');
    }
    if (order.length > 0) {
      sql +=
        ' ORDER BY ' +
        order
          .map(
            (term) =>
              customsDeclarationColumnSql(term.column) +
              ' ' +
              directionSql(term.direction ?? 'asc'),
          )
          .join(', ');
    }
    if (limit !== null) {
      sql += ' LIMIT ?';
      values.push(limit);
      if (offset !== null) {
        sql += ' OFFSET ?';
        values.push(offset);
      }
    }

    try {
      const [rows] = await this.#connection.execute(
        { sql, rowsAsArray: true },
        values,
      );
      return /** @type {RowDataPacket[]} */ (rows).map(toRow);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }
}
