// Code generated by tpl from freight.port. DO NOT EDIT.

/**
 * The mysql2 implementation of the `freight.port` data layer.
 *
 * @module
 */

/** @import { Connection, ResultSetHeader, RowDataPacket } from 'mysql2/promise' */
/** @import { BoundValue } from './core.js' */
/** @import { Port, PortFilter, PortKey, PortOrder } from './port.js' */

import { NotFound, directionSql, failure } from './core.js';
import { portColumnSql } from './port.js';
import { PortRepository } from './port_repository.js';

/** The table every statement of this module addresses, as an error names it. */
const TABLE = "freight.port";

/** Selects every column of the table, in catalogue order. */
const SELECT = "SELECT `port_id`, `un_locode`, `name`, `country_code`, `local_name`, `timezone_name`, `utc_offset_minutes`, `berth_count`, `max_draught_m`, `tidal_range_m`, `annual_throughput_teu`, `customs_round_clock`, `harbour_dues_currency`, `approach_notes` FROM `port`";

/** Selects the one row a primary key names. */
const READ = "SELECT `port_id`, `un_locode`, `name`, `country_code`, `local_name`, `timezone_name`, `utc_offset_minutes`, `berth_count`, `max_draught_m`, `tidal_range_m`, `annual_throughput_teu`, `customs_round_clock`, `harbour_dues_currency`, `approach_notes` FROM `port` WHERE `port_id` = ?";

/**
 * Inserts one row. It names neither a generated column nor an auto-increment
 * key, because the server writes both.
 */
const INSERT = "INSERT INTO `port` (`un_locode`, `name`, `country_code`, `local_name`, `timezone_name`, `utc_offset_minutes`, `berth_count`, `max_draught_m`, `tidal_range_m`, `annual_throughput_teu`, `customs_round_clock`, `harbour_dues_currency`, `approach_notes`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

/** Writes every column that is neither generated nor part of the key. */
const UPDATE = "UPDATE `port` SET `un_locode` = ?, `name` = ?, `country_code` = ?, `local_name` = ?, `timezone_name` = ?, `utc_offset_minutes` = ?, `berth_count` = ?, `max_draught_m` = ?, `tidal_range_m` = ?, `annual_throughput_teu` = ?, `customs_round_clock` = ?, `harbour_dues_currency` = ?, `approach_notes` = ? WHERE `port_id` = ?";

/** Removes the one row a primary key names. */
const DELETE = "DELETE FROM `port` WHERE `port_id` = ?";

/**
 * Build a row from one result tuple.
 *
 * The positions are the order `SELECT` names the columns in, which is
 * catalogue order. Every statement below is run with `rowsAsArray`, so a
 * result is an array and never an object: a column named `__proto__` or
 * `constructor` would otherwise reach an object literal as a key, and the
 * first of those sets a prototype instead of defining a property.
 *
 * The values are whatever mysql2 decoded, and the types `Port` declares
 * are this example's record of what that is.
 *
 * @param {RowDataPacket} values
 * @returns {Port}
 */
function toRow(values) {
  return {
    portId: values[0],
    unLocode: values[1],
    name: values[2],
    countryCode: values[3],
    localName: values[4],
    timezoneName: values[5],
    utcOffsetMinutes: values[6],
    berthCount: values[7],
    maxDraughtM: values[8],
    tidalRangeM: values[9],
    annualThroughputTeu: values[10],
    customsRoundClock: values[11],
    harbourDuesCurrency: values[12],
    approachNotes: values[13],
  };
}

/**
 * The mysql2 data layer of `freight.port`.
 *
 * Nothing here commits. mysql2 autocommits until a caller calls
 * `beginTransaction`, so transaction control stays with the caller.
 */
export class PortMysql2 extends PortRepository {
  /** @type {Connection} */
  #connection;

  /**
   * Build the data layer of `freight.port` over `connection`.
   *
   * The connection must address the schema `SCHEMA` names, because the
   * statements above address the table unqualified. `connect` is the
   * connection that carries it.
   *
   * @param {Connection} connection
   */
  constructor(connection) {
    super();
    this.#connection = connection;
  }

  /**
   * Insert `row`.
   *
   * The key is assigned by the server and is written back into `row`.
   *
   * @override
   * @param {Port} row
   * @returns {Promise<void>}
   */
  async create(row) {
    /** @type {BoundValue[]} */
    const values = [
      row.unLocode,
      row.name,
      row.countryCode,
      row.localName,
      row.timezoneName,
      row.utcOffsetMinutes,
      row.berthCount,
      row.maxDraughtM,
      row.tidalRangeM,
      row.annualThroughputTeu,
      row.customsRoundClock,
      row.harbourDuesCurrency,
      row.approachNotes,
    ];
    try {
      const [result] = await this.#connection.execute(INSERT, values);
      const { insertId } = /** @type {ResultSetHeader} */ (result);
      row.portId = insertId;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Return the row `key` names.
   *
   * @override
   * @param {PortKey} key
   * @returns {Promise<Port>}
   */
  async read(key) {
    /** @type {BoundValue[]} */
    const values = [
      key.portId,
    ];
    try {
      const [rows] = await this.#connection.execute(
        { sql: READ, rowsAsArray: true },
        values,
      );
      const found = /** @type {RowDataPacket[]} */ (rows);
      if (found.length === 0) {
        throw new NotFound(TABLE);
      }
      return toRow(found[0]);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Write every writable column of `row` over the row its key names.
   *
   * @override
   * @param {Port} row
   * @returns {Promise<number>}
   */
  async update(row) {
    /** @type {BoundValue[]} */
    const values = [
      row.unLocode,
      row.name,
      row.countryCode,
      row.localName,
      row.timezoneName,
      row.utcOffsetMinutes,
      row.berthCount,
      row.maxDraughtM,
      row.tidalRangeM,
      row.annualThroughputTeu,
      row.customsRoundClock,
      row.harbourDuesCurrency,
      row.approachNotes,
      row.portId,
    ];
    try {
      const [result] = await this.#connection.execute(UPDATE, values);
      return /** @type {ResultSetHeader} */ (result).affectedRows;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Remove the row `key` names.
   *
   * @override
   * @param {PortKey} key
   * @returns {Promise<number>}
   */
  async delete(key) {
    /** @type {BoundValue[]} */
    const values = [
      key.portId,
    ];
    try {
      const [result] = await this.#connection.execute(DELETE, values);
      return /** @type {ResultSetHeader} */ (result).affectedRows;
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }

  /**
   * Return every row matching `criteria`, ordered by the terms of `order`.
   *
   * @override
   * @param {PortFilter} criteria
   * @param {readonly PortOrder[]} [order]
   * @param {number | null} [limit]
   * @param {number | null} [offset]
   * @returns {Promise<Port[]>}
   */
  async search(criteria, order = [], limit = null, offset = null) {
    /** @type {string[]} */
    const conditions = [];
    /** @type {BoundValue[]} */
    const values = [];

    if (criteria.portId !== undefined) {
      conditions.push("`port_id` = ?");
      values.push(criteria.portId);
    }
    if (criteria.portIdFrom !== undefined) {
      conditions.push("`port_id` >= ?");
      values.push(criteria.portIdFrom);
    }
    if (criteria.portIdTo !== undefined) {
      conditions.push("`port_id` <= ?");
      values.push(criteria.portIdTo);
    }
    if (criteria.unLocode !== undefined) {
      conditions.push("`un_locode` = ?");
      values.push(criteria.unLocode);
    }
    if (criteria.unLocodeLike !== undefined) {
      conditions.push("`un_locode` LIKE ?");
      values.push(criteria.unLocodeLike);
    }
    if (criteria.name !== undefined) {
      conditions.push("`name` = ?");
      values.push(criteria.name);
    }
    if (criteria.nameLike !== undefined) {
      conditions.push("`name` LIKE ?");
      values.push(criteria.nameLike);
    }
    if (criteria.countryCode !== undefined) {
      conditions.push("`country_code` = ?");
      values.push(criteria.countryCode);
    }
    if (criteria.countryCodeLike !== undefined) {
      conditions.push("`country_code` LIKE ?");
      values.push(criteria.countryCodeLike);
    }
    if (criteria.localName !== undefined) {
      conditions.push("`local_name` = ?");
      values.push(criteria.localName);
    }
    if (criteria.localNameLike !== undefined) {
      conditions.push("`local_name` LIKE ?");
      values.push(criteria.localNameLike);
    }
    if (criteria.localNameIsNull !== undefined) {
      conditions.push(
        criteria.localNameIsNull
          ? "`local_name` IS NULL"
          : "`local_name` IS NOT NULL",
      );
    }
    if (criteria.timezoneName !== undefined) {
      conditions.push("`timezone_name` = ?");
      values.push(criteria.timezoneName);
    }
    if (criteria.timezoneNameLike !== undefined) {
      conditions.push("`timezone_name` LIKE ?");
      values.push(criteria.timezoneNameLike);
    }
    if (criteria.utcOffsetMinutes !== undefined) {
      conditions.push("`utc_offset_minutes` = ?");
      values.push(criteria.utcOffsetMinutes);
    }
    if (criteria.utcOffsetMinutesFrom !== undefined) {
      conditions.push("`utc_offset_minutes` >= ?");
      values.push(criteria.utcOffsetMinutesFrom);
    }
    if (criteria.utcOffsetMinutesTo !== undefined) {
      conditions.push("`utc_offset_minutes` <= ?");
      values.push(criteria.utcOffsetMinutesTo);
    }
    if (criteria.berthCount !== undefined) {
      conditions.push("`berth_count` = ?");
      values.push(criteria.berthCount);
    }
    if (criteria.berthCountFrom !== undefined) {
      conditions.push("`berth_count` >= ?");
      values.push(criteria.berthCountFrom);
    }
    if (criteria.berthCountTo !== undefined) {
      conditions.push("`berth_count` <= ?");
      values.push(criteria.berthCountTo);
    }
    if (criteria.maxDraughtM !== undefined) {
      conditions.push("`max_draught_m` = ?");
      values.push(criteria.maxDraughtM);
    }
    if (criteria.maxDraughtMFrom !== undefined) {
      conditions.push("`max_draught_m` >= ?");
      values.push(criteria.maxDraughtMFrom);
    }
    if (criteria.maxDraughtMTo !== undefined) {
      conditions.push("`max_draught_m` <= ?");
      values.push(criteria.maxDraughtMTo);
    }
    if (criteria.tidalRangeM !== undefined) {
      conditions.push("`tidal_range_m` = ?");
      values.push(criteria.tidalRangeM);
    }
    if (criteria.tidalRangeMFrom !== undefined) {
      conditions.push("`tidal_range_m` >= ?");
      values.push(criteria.tidalRangeMFrom);
    }
    if (criteria.tidalRangeMTo !== undefined) {
      conditions.push("`tidal_range_m` <= ?");
      values.push(criteria.tidalRangeMTo);
    }
    if (criteria.tidalRangeMIsNull !== undefined) {
      conditions.push(
        criteria.tidalRangeMIsNull
          ? "`tidal_range_m` IS NULL"
          : "`tidal_range_m` IS NOT NULL",
      );
    }
    if (criteria.annualThroughputTeu !== undefined) {
      conditions.push("`annual_throughput_teu` = ?");
      values.push(criteria.annualThroughputTeu);
    }
    if (criteria.annualThroughputTeuFrom !== undefined) {
      conditions.push("`annual_throughput_teu` >= ?");
      values.push(criteria.annualThroughputTeuFrom);
    }
    if (criteria.annualThroughputTeuTo !== undefined) {
      conditions.push("`annual_throughput_teu` <= ?");
      values.push(criteria.annualThroughputTeuTo);
    }
    if (criteria.annualThroughputTeuIsNull !== undefined) {
      conditions.push(
        criteria.annualThroughputTeuIsNull
          ? "`annual_throughput_teu` IS NULL"
          : "`annual_throughput_teu` IS NOT NULL",
      );
    }
    if (criteria.customsRoundClock !== undefined) {
      conditions.push("`customs_round_clock` = ?");
      values.push(criteria.customsRoundClock);
    }
    if (criteria.customsRoundClockFrom !== undefined) {
      conditions.push("`customs_round_clock` >= ?");
      values.push(criteria.customsRoundClockFrom);
    }
    if (criteria.customsRoundClockTo !== undefined) {
      conditions.push("`customs_round_clock` <= ?");
      values.push(criteria.customsRoundClockTo);
    }
    if (criteria.harbourDuesCurrency !== undefined) {
      conditions.push("`harbour_dues_currency` = ?");
      values.push(criteria.harbourDuesCurrency);
    }
    if (criteria.harbourDuesCurrencyLike !== undefined) {
      conditions.push("`harbour_dues_currency` LIKE ?");
      values.push(criteria.harbourDuesCurrencyLike);
    }
    if (criteria.approachNotes !== undefined) {
      conditions.push("`approach_notes` = ?");
      values.push(criteria.approachNotes);
    }
    if (criteria.approachNotesLike !== undefined) {
      conditions.push("`approach_notes` LIKE ?");
      values.push(criteria.approachNotesLike);
    }
    if (criteria.approachNotesIsNull !== undefined) {
      conditions.push(
        criteria.approachNotesIsNull
          ? "`approach_notes` IS NULL"
          : "`approach_notes` IS NOT NULL",
      );
    }

    let sql = SELECT;
    if (conditions.length > 0) {
      sql += ' WHERE ' + conditions.join(' AND ');
    }
    if (order.length > 0) {
      sql +=
        ' ORDER BY ' +
        order
          .map(
            (term) =>
              portColumnSql(term.column) +
              ' ' +
              directionSql(term.direction ?? 'asc'),
          )
          .join(', ');
    }
    if (limit !== null) {
      sql += ' LIMIT ?';
      values.push(limit);
      if (offset !== null) {
        sql += ' OFFSET ?';
        values.push(offset);
      }
    }

    try {
      const [rows] = await this.#connection.execute(
        { sql, rowsAsArray: true },
        values,
      );
      return /** @type {RowDataPacket[]} */ (rows).map(toRow);
    } catch (cause) {
      throw failure(TABLE, cause);
    }
  }
}
