// Code generated by tpl from freight.port. DO NOT EDIT.

/**
 * The `freight.port` row, the key that addresses it, the columns an ordering may
 * name, and the filter a search takes.
 *
 * @module
 */

/** @import { Direction } from './core.js' */

import { UnknownColumn } from './core.js';

// The table's own comment, as the catalogue carries it:
// Portos marítimos, respectivos códigos UN/LOCODE e características de acostagem — ver anexo técnico do manual de operações

/**
 * One row of `freight.port`.
 *
 * Every property is present on a row. A column that admits `NULL` is typed
 * `T | null`, which is what mysql2 hands back for a `NULL` and what `tsc`
 * makes a caller narrow before reading.
 *
 * @typedef {object} Port
 * @property {number} portId `port_id`, declared `smallint(5) unsigned` NOT NULL AUTO_INCREMENT.
 *   It is part of the primary key.
 *   Comment: Surrogate key; UN/LOCODE is the natural key
 * @property {string} unLocode `un_locode`, declared `char(5)` NOT NULL.
 *   It is part of a unique index.
 *   Comment: UN/LOCODE, e.g. PTLIS — two-letter country plus three-letter location
 * @property {string} name `name`, declared `varchar(120)` NOT NULL.
 *   Comment: Port name as published by the port authority
 * @property {string} countryCode `country_code`, declared `char(2)` NOT NULL.
 *   Comment: ISO 3166-1 alpha-2; ASCII by definition, so stored as ASCII
 * @property {string | null} localName `local_name`, declared `varchar(120)` NULL.
 *   Comment: Name in the local language — binary collation, since Ålesund and Alesund are different ports
 * @property {string} timezoneName `timezone_name`, declared `varchar(64)` NOT NULL.
 *   Comment: IANA time zone identifier
 * @property {number} utcOffsetMinutes `utc_offset_minutes`, declared `smallint(6)` NOT NULL.
 *   Comment: Standard-time offset in minutes; negative west of Greenwich
 * @property {number} berthCount `berth_count`, declared `tinyint(3) unsigned` NOT NULL.
 *   Comment: Number of commercial berths
 * @property {string} maxDraughtM `max_draught_m`, declared `decimal(5,2)` NOT NULL.
 *   Comment: Maximum permitted draught at the deepest berth, in metres
 * @property {number | null} tidalRangeM `tidal_range_m`, declared `float` NULL.
 *   Comment: Mean spring tidal range, in metres
 * @property {number | null} annualThroughputTeu `annual_throughput_teu`, declared `int(10) unsigned` NULL.
 *   Comment: Container throughput for the last reported calendar year
 * @property {Buffer} customsRoundClock `customs_round_clock`, declared `bit(1)` NOT NULL.
 *   Comment: Customs desk staffed 24/7
 * @property {string} harbourDuesCurrency `harbour_dues_currency`, declared `char(3)` NOT NULL.
 *   Comment: ISO 4217 code in which harbour dues are invoiced
 * @property {string | null} approachNotes `approach_notes`, declared `text` NULL.
 *   Comment: Free text from the pilot book
 */

/**
 * The primary key of `freight.port`.
 *
 * @typedef {object} PortKey
 * @property {number} portId `port_id`, declared `smallint(5) unsigned` NOT NULL AUTO_INCREMENT.
 */

/**
 * One column of `freight.port`.
 *
 * A search accepts an ordering term over these values and over nothing else,
 * so an ordering can carry no SQL of its own. A caller may write the column's
 * catalogue name as a string literal instead: {@link PortColumn} is the union
 * of the values below, so the two are the same value and the same type.
 */
export const PortColumns = Object.freeze(
  /** @type {const} */ ({
    /** `port_id`, declared `smallint(5) unsigned` NOT NULL AUTO_INCREMENT. */
    PORT_ID: "port_id",
    /** `un_locode`, declared `char(5)` NOT NULL. */
    UN_LOCODE: "un_locode",
    /** `name`, declared `varchar(120)` NOT NULL. */
    NAME: "name",
    /** `country_code`, declared `char(2)` NOT NULL. */
    COUNTRY_CODE: "country_code",
    /** `local_name`, declared `varchar(120)` NULL. */
    LOCAL_NAME: "local_name",
    /** `timezone_name`, declared `varchar(64)` NOT NULL. */
    TIMEZONE_NAME: "timezone_name",
    /** `utc_offset_minutes`, declared `smallint(6)` NOT NULL. */
    UTC_OFFSET_MINUTES: "utc_offset_minutes",
    /** `berth_count`, declared `tinyint(3) unsigned` NOT NULL. */
    BERTH_COUNT: "berth_count",
    /** `max_draught_m`, declared `decimal(5,2)` NOT NULL. */
    MAX_DRAUGHT_M: "max_draught_m",
    /** `tidal_range_m`, declared `float` NULL. */
    TIDAL_RANGE_M: "tidal_range_m",
    /** `annual_throughput_teu`, declared `int(10) unsigned` NULL. */
    ANNUAL_THROUGHPUT_TEU: "annual_throughput_teu",
    /** `customs_round_clock`, declared `bit(1)` NOT NULL. */
    CUSTOMS_ROUND_CLOCK: "customs_round_clock",
    /** `harbour_dues_currency`, declared `char(3)` NOT NULL. */
    HARBOUR_DUES_CURRENCY: "harbour_dues_currency",
    /** `approach_notes`, declared `text` NULL. */
    APPROACH_NOTES: "approach_notes",
  }),
);

/**
 * A column of `freight.port` an ordering may name.
 *
 * @typedef {(typeof PortColumns)[keyof typeof PortColumns]} PortColumn
 */

/**
 * The one place a column of `freight.port` becomes SQL.
 *
 * It is closed over the constants above, and every identifier in it was quoted
 * at render time by `tpl`, so no value a caller supplies can reach a
 * statement's text through an ordering term.
 *
 * @type {Readonly<Record<PortColumn, string>>}
 */
const COLUMN_SQL = Object.freeze({
  "port_id": "`port_id`",
  "un_locode": "`un_locode`",
  "name": "`name`",
  "country_code": "`country_code`",
  "local_name": "`local_name`",
  "timezone_name": "`timezone_name`",
  "utc_offset_minutes": "`utc_offset_minutes`",
  "berth_count": "`berth_count`",
  "max_draught_m": "`max_draught_m`",
  "tidal_range_m": "`tidal_range_m`",
  "annual_throughput_teu": "`annual_throughput_teu`",
  "customs_round_clock": "`customs_round_clock`",
  "harbour_dues_currency": "`harbour_dues_currency`",
  "approach_notes": "`approach_notes`",
});

/**
 * The column as a statement's text names it: quoted for MariaDB.
 *
 * The lookup is by own property and the refusal is unconditional, so a caller
 * that reached past the type — with an unchecked string, or a value read from
 * a request — is refused here rather than interpolated.
 *
 * @param {PortColumn} column
 * @returns {string}
 * @throws {UnknownColumn} for every name the table does not carry.
 */
export function portColumnSql(column) {
  if (!Object.hasOwn(COLUMN_SQL, column)) {
    throw new UnknownColumn("freight.port", String(column));
  }
  return COLUMN_SQL[column];
}

/**
 * One ordering term of a search over `freight.port`.
 *
 * @typedef {object} PortOrder
 * @property {PortColumn} column the column to order by
 * @property {Direction} [direction] the direction to order in. Ascending when absent.
 */

/**
 * What narrows a search over `freight.port`.
 *
 * Every property is optional: a property left absent adds no condition, and the
 * conditions a search does build are joined with `AND`. The empty object is the
 * filter that matches every row.
 *
 * A property is absent for *no condition* and is never `null` for *is NULL*.
 * That question is asked through the `…IsNull` property a nullable column also
 * gets, so the two meanings never collide, and it is why no filter property
 * admits `null`.
 *
 * @typedef {object} PortFilter
 * @property {number} [portId] where set, requires `port_id` to equal it.
 * @property {number} [portIdFrom] where set, requires `port_id` to be at least it.
 * @property {number} [portIdTo] where set, requires `port_id` to be at most it.
 * @property {string} [unLocode] where set, requires `un_locode` to equal it.
 * @property {string} [unLocodeLike] where set, requires `un_locode` to match it, as LIKE matches.
 * @property {string} [name] where set, requires `name` to equal it.
 * @property {string} [nameLike] where set, requires `name` to match it, as LIKE matches.
 * @property {string} [countryCode] where set, requires `country_code` to equal it.
 * @property {string} [countryCodeLike] where set, requires `country_code` to match it, as LIKE matches.
 * @property {string} [localName] where set, requires `local_name` to equal it.
 * @property {string} [localNameLike] where set, requires `local_name` to match it, as LIKE matches.
 * @property {boolean} [localNameIsNull] where true, requires `local_name` to be NULL; where false, requires it not to be.
 * @property {string} [timezoneName] where set, requires `timezone_name` to equal it.
 * @property {string} [timezoneNameLike] where set, requires `timezone_name` to match it, as LIKE matches.
 * @property {number} [utcOffsetMinutes] where set, requires `utc_offset_minutes` to equal it.
 * @property {number} [utcOffsetMinutesFrom] where set, requires `utc_offset_minutes` to be at least it.
 * @property {number} [utcOffsetMinutesTo] where set, requires `utc_offset_minutes` to be at most it.
 * @property {number} [berthCount] where set, requires `berth_count` to equal it.
 * @property {number} [berthCountFrom] where set, requires `berth_count` to be at least it.
 * @property {number} [berthCountTo] where set, requires `berth_count` to be at most it.
 * @property {string} [maxDraughtM] where set, requires `max_draught_m` to equal it.
 * @property {string} [maxDraughtMFrom] where set, requires `max_draught_m` to be at least it.
 * @property {string} [maxDraughtMTo] where set, requires `max_draught_m` to be at most it.
 * @property {number} [tidalRangeM] where set, requires `tidal_range_m` to equal it.
 * @property {number} [tidalRangeMFrom] where set, requires `tidal_range_m` to be at least it.
 * @property {number} [tidalRangeMTo] where set, requires `tidal_range_m` to be at most it.
 * @property {boolean} [tidalRangeMIsNull] where true, requires `tidal_range_m` to be NULL; where false, requires it not to be.
 * @property {number} [annualThroughputTeu] where set, requires `annual_throughput_teu` to equal it.
 * @property {number} [annualThroughputTeuFrom] where set, requires `annual_throughput_teu` to be at least it.
 * @property {number} [annualThroughputTeuTo] where set, requires `annual_throughput_teu` to be at most it.
 * @property {boolean} [annualThroughputTeuIsNull] where true, requires `annual_throughput_teu` to be NULL; where false, requires it not to be.
 * @property {Buffer} [customsRoundClock] where set, requires `customs_round_clock` to equal it.
 * @property {Buffer} [customsRoundClockFrom] where set, requires `customs_round_clock` to be at least it.
 * @property {Buffer} [customsRoundClockTo] where set, requires `customs_round_clock` to be at most it.
 * @property {string} [harbourDuesCurrency] where set, requires `harbour_dues_currency` to equal it.
 * @property {string} [harbourDuesCurrencyLike] where set, requires `harbour_dues_currency` to match it, as LIKE matches.
 * @property {string} [approachNotes] where set, requires `approach_notes` to equal it.
 * @property {string} [approachNotesLike] where set, requires `approach_notes` to match it, as LIKE matches.
 * @property {boolean} [approachNotesIsNull] where true, requires `approach_notes` to be NULL; where false, requires it not to be.
 */
