// Code generated by tpl from freight.voyage_leg. DO NOT EDIT.

/**
 * The `freight.voyage_leg` row, the key that addresses it, the columns an ordering may
 * name, and the filter a search takes.
 *
 * @module
 */

/** @import { Direction } from './core.js' */

import { UnknownColumn } from './core.js';

// The table's own comment, as the catalogue carries it:
// Escalas de cada viagem, pela ordem da rotação

/**
 * One row of `freight.voyage_leg`.
 *
 * Every property is present on a row. A column that admits `NULL` is typed
 * `T | null`, which is what mysql2 hands back for a `NULL` and what `tsc`
 * makes a caller narrow before reading.
 *
 * @typedef {object} VoyageLeg
 * @property {string} vesselImo `vessel_imo`, declared `char(7)` NOT NULL.
 *   It is part of the primary key.
 * @property {string} voyageNumber `voyage_number`, declared `varchar(12)` NOT NULL.
 *   It is part of the primary key.
 * @property {number} legSequence `leg_sequence`, declared `tinyint(3) unsigned` NOT NULL.
 *   It is part of the primary key.
 *   Comment: Rotation position, 1 for the first call
 * @property {number} portId `port_id`, declared `smallint(5) unsigned` NOT NULL.
 * @property {Date} eta `eta`, declared `datetime` NOT NULL.
 * @property {Date} etd `etd`, declared `datetime` NOT NULL.
 * @property {Date | null} ata `ata`, declared `datetime(6)` NULL.
 *   Comment: Actual arrival, microsecond precision as reported by AIS
 * @property {string | null} berthShiftTime `berth_shift_time`, declared `time(3)` NULL.
 *   Comment: Time spent shifting between berths during the call
 * @property {number} pilotRequired `pilot_required`, declared `tinyint(1)` NOT NULL.
 * @property {number} movesDischarged `moves_discharged`, declared `smallint(5) unsigned` NOT NULL.
 * @property {number} movesLoaded `moves_loaded`, declared `smallint(5) unsigned` NOT NULL.
 * @property {number | null} movesTotal `moves_total`, declared `smallint(5) unsigned` NULL VIRTUAL GENERATED AS (`moves_discharged` + `moves_loaded`).
 *   Comment: Virtual generated column: total crane moves for the call
 */

/**
 * The primary key of `freight.voyage_leg`.
 *
 * @typedef {object} VoyageLegKey
 * @property {string} vesselImo `vessel_imo`, declared `char(7)` NOT NULL.
 * @property {string} voyageNumber `voyage_number`, declared `varchar(12)` NOT NULL.
 * @property {number} legSequence `leg_sequence`, declared `tinyint(3) unsigned` NOT NULL.
 */

/**
 * One column of `freight.voyage_leg`.
 *
 * A search accepts an ordering term over these values and over nothing else,
 * so an ordering can carry no SQL of its own. A caller may write the column's
 * catalogue name as a string literal instead: {@link VoyageLegColumn} is the union
 * of the values below, so the two are the same value and the same type.
 */
export const VoyageLegColumns = Object.freeze(
  /** @type {const} */ ({
    /** `vessel_imo`, declared `char(7)` NOT NULL. */
    VESSEL_IMO: "vessel_imo",
    /** `voyage_number`, declared `varchar(12)` NOT NULL. */
    VOYAGE_NUMBER: "voyage_number",
    /** `leg_sequence`, declared `tinyint(3) unsigned` NOT NULL. */
    LEG_SEQUENCE: "leg_sequence",
    /** `port_id`, declared `smallint(5) unsigned` NOT NULL. */
    PORT_ID: "port_id",
    /** `eta`, declared `datetime` NOT NULL. */
    ETA: "eta",
    /** `etd`, declared `datetime` NOT NULL. */
    ETD: "etd",
    /** `ata`, declared `datetime(6)` NULL. */
    ATA: "ata",
    /** `berth_shift_time`, declared `time(3)` NULL. */
    BERTH_SHIFT_TIME: "berth_shift_time",
    /** `pilot_required`, declared `tinyint(1)` NOT NULL. */
    PILOT_REQUIRED: "pilot_required",
    /** `moves_discharged`, declared `smallint(5) unsigned` NOT NULL. */
    MOVES_DISCHARGED: "moves_discharged",
    /** `moves_loaded`, declared `smallint(5) unsigned` NOT NULL. */
    MOVES_LOADED: "moves_loaded",
    /** `moves_total`, declared `smallint(5) unsigned` NULL VIRTUAL GENERATED AS (`moves_discharged` + `moves_loaded`). */
    MOVES_TOTAL: "moves_total",
  }),
);

/**
 * A column of `freight.voyage_leg` an ordering may name.
 *
 * @typedef {(typeof VoyageLegColumns)[keyof typeof VoyageLegColumns]} VoyageLegColumn
 */

/**
 * The one place a column of `freight.voyage_leg` becomes SQL.
 *
 * It is closed over the constants above, and every identifier in it was quoted
 * at render time by `tpl`, so no value a caller supplies can reach a
 * statement's text through an ordering term.
 *
 * @type {Readonly<Record<VoyageLegColumn, string>>}
 */
const COLUMN_SQL = Object.freeze({
  "vessel_imo": "`vessel_imo`",
  "voyage_number": "`voyage_number`",
  "leg_sequence": "`leg_sequence`",
  "port_id": "`port_id`",
  "eta": "`eta`",
  "etd": "`etd`",
  "ata": "`ata`",
  "berth_shift_time": "`berth_shift_time`",
  "pilot_required": "`pilot_required`",
  "moves_discharged": "`moves_discharged`",
  "moves_loaded": "`moves_loaded`",
  "moves_total": "`moves_total`",
});

/**
 * The column as a statement's text names it: quoted for MariaDB.
 *
 * The lookup is by own property and the refusal is unconditional, so a caller
 * that reached past the type — with an unchecked string, or a value read from
 * a request — is refused here rather than interpolated.
 *
 * @param {VoyageLegColumn} column
 * @returns {string}
 * @throws {UnknownColumn} for every name the table does not carry.
 */
export function voyageLegColumnSql(column) {
  if (!Object.hasOwn(COLUMN_SQL, column)) {
    throw new UnknownColumn("freight.voyage_leg", String(column));
  }
  return COLUMN_SQL[column];
}

/**
 * One ordering term of a search over `freight.voyage_leg`.
 *
 * @typedef {object} VoyageLegOrder
 * @property {VoyageLegColumn} column the column to order by
 * @property {Direction} [direction] the direction to order in. Ascending when absent.
 */

/**
 * What narrows a search over `freight.voyage_leg`.
 *
 * Every property is optional: a property left absent adds no condition, and the
 * conditions a search does build are joined with `AND`. The empty object is the
 * filter that matches every row.
 *
 * A property is absent for *no condition* and is never `null` for *is NULL*.
 * That question is asked through the `…IsNull` property a nullable column also
 * gets, so the two meanings never collide, and it is why no filter property
 * admits `null`.
 *
 * @typedef {object} VoyageLegFilter
 * @property {string} [vesselImo] where set, requires `vessel_imo` to equal it.
 * @property {string} [vesselImoLike] where set, requires `vessel_imo` to match it, as LIKE matches.
 * @property {string} [voyageNumber] where set, requires `voyage_number` to equal it.
 * @property {string} [voyageNumberLike] where set, requires `voyage_number` to match it, as LIKE matches.
 * @property {number} [legSequence] where set, requires `leg_sequence` to equal it.
 * @property {number} [legSequenceFrom] where set, requires `leg_sequence` to be at least it.
 * @property {number} [legSequenceTo] where set, requires `leg_sequence` to be at most it.
 * @property {number} [portId] where set, requires `port_id` to equal it.
 * @property {number} [portIdFrom] where set, requires `port_id` to be at least it.
 * @property {number} [portIdTo] where set, requires `port_id` to be at most it.
 * @property {Date} [eta] where set, requires `eta` to equal it.
 * @property {Date} [etaFrom] where set, requires `eta` to be at least it.
 * @property {Date} [etaTo] where set, requires `eta` to be at most it.
 * @property {Date} [etd] where set, requires `etd` to equal it.
 * @property {Date} [etdFrom] where set, requires `etd` to be at least it.
 * @property {Date} [etdTo] where set, requires `etd` to be at most it.
 * @property {Date} [ata] where set, requires `ata` to equal it.
 * @property {Date} [ataFrom] where set, requires `ata` to be at least it.
 * @property {Date} [ataTo] where set, requires `ata` to be at most it.
 * @property {boolean} [ataIsNull] where true, requires `ata` to be NULL; where false, requires it not to be.
 * @property {string} [berthShiftTime] where set, requires `berth_shift_time` to equal it.
 * @property {string} [berthShiftTimeFrom] where set, requires `berth_shift_time` to be at least it.
 * @property {string} [berthShiftTimeTo] where set, requires `berth_shift_time` to be at most it.
 * @property {boolean} [berthShiftTimeIsNull] where true, requires `berth_shift_time` to be NULL; where false, requires it not to be.
 * @property {number} [pilotRequired] where set, requires `pilot_required` to equal it.
 * @property {number} [pilotRequiredFrom] where set, requires `pilot_required` to be at least it.
 * @property {number} [pilotRequiredTo] where set, requires `pilot_required` to be at most it.
 * @property {number} [movesDischarged] where set, requires `moves_discharged` to equal it.
 * @property {number} [movesDischargedFrom] where set, requires `moves_discharged` to be at least it.
 * @property {number} [movesDischargedTo] where set, requires `moves_discharged` to be at most it.
 * @property {number} [movesLoaded] where set, requires `moves_loaded` to equal it.
 * @property {number} [movesLoadedFrom] where set, requires `moves_loaded` to be at least it.
 * @property {number} [movesLoadedTo] where set, requires `moves_loaded` to be at most it.
 * @property {number} [movesTotal] where set, requires `moves_total` to equal it.
 * @property {number} [movesTotalFrom] where set, requires `moves_total` to be at least it.
 * @property {number} [movesTotalTo] where set, requires `moves_total` to be at most it.
 * @property {boolean} [movesTotalIsNull] where true, requires `moves_total` to be NULL; where false, requires it not to be.
 */
