// Code generated by tpl from world.countrylanguage. DO NOT EDIT.

//! The `sqlx` implementation of the `world.countrylanguage` data layer.

use sqlx::{MySql, QueryBuilder};

use super::Error;
use super::countrylanguage::{Countrylanguage, CountrylanguageFilter, CountrylanguageKey, CountrylanguageOrder};
use super::countrylanguage_repository::CountrylanguageRepository;

/// The table every statement of this module addresses, as an error names it.
const TABLE: &str = "world.countrylanguage";

/// Selects every column of the table, in catalogue order.
const SELECT: &str = "SELECT `CountryCode`, `Language`, `IsOfficial`, `Percentage` FROM `countrylanguage`";

/// Selects the one row a primary key names.
const READ: &str = "SELECT `CountryCode`, `Language`, `IsOfficial`, `Percentage` FROM `countrylanguage` WHERE `CountryCode` = ? AND `Language` = ?";

/// Inserts one row.
///
/// It names neither a generated column nor an auto-increment key, because the
/// server writes both.
const INSERT: &str = "INSERT INTO `countrylanguage` (`CountryCode`, `Language`, `IsOfficial`, `Percentage`) VALUES (?, ?, ?, ?)";

/// Writes every column that is neither generated nor part of the key.
const UPDATE: &str = "UPDATE `countrylanguage` SET `IsOfficial` = ?, `Percentage` = ? WHERE `CountryCode` = ? AND `Language` = ?";

/// Removes the one row a primary key names.
const DELETE: &str = "DELETE FROM `countrylanguage` WHERE `CountryCode` = ? AND `Language` = ?";

/// The `sqlx` data layer of `world.countrylanguage`.
#[derive(Debug, Clone)]
pub struct CountrylanguageSqlx {
    pool: sqlx::MySqlPool,
}

impl CountrylanguageSqlx {
    /// Builds the data layer of `world.countrylanguage` over `pool`.
    ///
    /// The pool must address the schema [`SCHEMA`] names, because the
    /// statements above address the table unqualified. [`connect`] is the pool
    /// that carries it.
    ///
    /// [`SCHEMA`]: super::SCHEMA
    /// [`connect`]: super::connect
    #[must_use]
    pub fn new(pool: sqlx::MySqlPool) -> Self {
        Self { pool }
    }
}

impl CountrylanguageRepository for CountrylanguageSqlx {
    async fn create(&self, row: &mut Countrylanguage) -> Result<(), Error> {
        sqlx::query(INSERT)
            .bind(&row.country_code)
            .bind(&row.language)
            .bind(&row.is_official)
            .bind(&row.percentage)
            .execute(&self.pool)
            .await?;
        Ok(())
    }

    async fn read(&self, key: &CountrylanguageKey) -> Result<Countrylanguage, Error> {
        sqlx::query_as::<_, Countrylanguage>(READ)
            .bind(&key.country_code)
            .bind(&key.language)
            .fetch_optional(&self.pool)
            .await?
            .ok_or(Error::NotFound { table: TABLE })
    }

    async fn update(&self, row: &Countrylanguage) -> Result<u64, Error> {
        let outcome = sqlx::query(UPDATE)
            .bind(&row.is_official)
            .bind(&row.percentage)
            .bind(&row.country_code)
            .bind(&row.language)
            .execute(&self.pool)
            .await?;

        Ok(outcome.rows_affected())
    }

    async fn delete(&self, key: &CountrylanguageKey) -> Result<u64, Error> {
        let outcome = sqlx::query(DELETE)
            .bind(&key.country_code)
            .bind(&key.language)
            .execute(&self.pool)
            .await?;

        Ok(outcome.rows_affected())
    }

    async fn search(
        &self,
        filter: CountrylanguageFilter,
        order: &[CountrylanguageOrder],
        limit: Option<u64>,
        offset: Option<u64>,
    ) -> Result<Vec<Countrylanguage>, Error> {
        let mut builder: QueryBuilder<MySql> = QueryBuilder::new(SELECT);

        if !filter.is_empty() {
            builder.push(" WHERE ");
            let mut conditions = builder.separated(" AND ");

            if let Some(value) = filter.country_code {
                conditions
                    .push("`CountryCode` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.country_code_like {
                conditions
                    .push("`CountryCode` LIKE ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.language {
                conditions
                    .push("`Language` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.language_like {
                conditions
                    .push("`Language` LIKE ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.is_official {
                conditions
                    .push("`IsOfficial` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.is_official_like {
                conditions
                    .push("`IsOfficial` LIKE ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.percentage {
                conditions
                    .push("`Percentage` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.percentage_from {
                conditions
                    .push("`Percentage` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.percentage_to {
                conditions
                    .push("`Percentage` <= ")
                    .push_bind_unseparated(value);
            }
        }

        if !order.is_empty() {
            builder.push(" ORDER BY ");
            for (position, term) in order.iter().enumerate() {
                if position > 0 {
                    builder.push(", ");
                }
                builder.push(term.column.as_sql());
                builder.push(" ");
                builder.push(term.direction.as_sql());
            }
        }

        if let Some(limit) = limit {
            builder.push(" LIMIT ").push_bind(limit);

            if let Some(offset) = offset {
                builder.push(" OFFSET ").push_bind(offset);
            }
        }

        builder
            .build_query_as::<Countrylanguage>()
            .fetch_all(&self.pool)
            .await
            .map_err(Error::from)
    }
}
