// Code generated by tpl from world.country. DO NOT EDIT.

//! The `world.country` row, the key that addresses it, the columns an
//! ordering may name, and the filter a search takes.

/// One row of `world.country`.
#[derive(Debug, Clone)]
pub struct Country {
    /// `Code`, declared `char(3)` NOT NULL.
    ///
    /// It is part of the primary key.
    pub code: String,
    /// `Name`, declared `char(52)` NOT NULL.
    pub name: String,
    /// `Continent`, declared `enum('Asia','Europe','North America','Africa','Oceania','Antarctica','South America')` NOT NULL.
    pub continent: String,
    /// `Region`, declared `char(26)` NOT NULL.
    pub region: String,
    /// `SurfaceArea`, declared `decimal(10,2)` NOT NULL.
    pub surface_area: super::Decimal,
    /// `IndepYear`, declared `smallint(6)` NULL.
    pub indep_year: Option<i16>,
    /// `Population`, declared `int(11)` NOT NULL.
    pub population: i32,
    /// `LifeExpectancy`, declared `decimal(3,1)` NULL.
    pub life_expectancy: Option<super::Decimal>,
    /// `GNP`, declared `decimal(10,2)` NULL.
    pub gnp: Option<super::Decimal>,
    /// `GNPOld`, declared `decimal(10,2)` NULL.
    pub gnp_old: Option<super::Decimal>,
    /// `LocalName`, declared `char(45)` NOT NULL.
    pub local_name: String,
    /// `GovernmentForm`, declared `char(45)` NOT NULL.
    pub government_form: String,
    /// `HeadOfState`, declared `char(60)` NULL.
    pub head_of_state: Option<String>,
    /// `Capital`, declared `int(11)` NULL.
    pub capital: Option<i32>,
    /// `Code2`, declared `char(2)` NOT NULL.
    pub code2: String,
}

impl Country {
    /// The primary key of the row.
    #[must_use]
    pub fn key(&self) -> CountryKey {
        CountryKey {
            code: self.code.clone(),
        }
    }
}

impl<'r> sqlx::FromRow<'r, sqlx::mysql::MySqlRow> for Country {
    fn from_row(row: &'r sqlx::mysql::MySqlRow) -> Result<Self, sqlx::Error> {
        use sqlx::Row as _;

        Ok(Self {
            code: row.try_get("Code")?,
            name: row.try_get("Name")?,
            continent: row.try_get("Continent")?,
            region: row.try_get("Region")?,
            surface_area: row.try_get("SurfaceArea")?,
            indep_year: row.try_get("IndepYear")?,
            population: row.try_get("Population")?,
            life_expectancy: row.try_get("LifeExpectancy")?,
            gnp: row.try_get("GNP")?,
            gnp_old: row.try_get("GNPOld")?,
            local_name: row.try_get("LocalName")?,
            government_form: row.try_get("GovernmentForm")?,
            head_of_state: row.try_get("HeadOfState")?,
            capital: row.try_get("Capital")?,
            code2: row.try_get("Code2")?,
        })
    }
}

/// The primary key of `world.country`.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct CountryKey {
    /// `Code`, declared `char(3)`.
    pub code: String,
}

/// One column of `world.country`.
///
/// A search accepts an ordering term over these variants and over nothing
/// else, so an ordering can carry no SQL of its own: [`as_sql`] answers from a
/// closed `match` with a quoted identifier the template wrote, and
/// [`FromStr`] is the one door a name a caller supplied can come through.
///
/// [`as_sql`]: CountryColumn::as_sql
/// [`FromStr`]: std::str::FromStr
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CountryColumn {
    /// `Code`, declared `char(3)`.
    Code,
    /// `Name`, declared `char(52)`.
    Name,
    /// `Continent`, declared `enum('Asia','Europe','North America','Africa','Oceania','Antarctica','South America')`.
    Continent,
    /// `Region`, declared `char(26)`.
    Region,
    /// `SurfaceArea`, declared `decimal(10,2)`.
    SurfaceArea,
    /// `IndepYear`, declared `smallint(6)`.
    IndepYear,
    /// `Population`, declared `int(11)`.
    Population,
    /// `LifeExpectancy`, declared `decimal(3,1)`.
    LifeExpectancy,
    /// `GNP`, declared `decimal(10,2)`.
    Gnp,
    /// `GNPOld`, declared `decimal(10,2)`.
    GnpOld,
    /// `LocalName`, declared `char(45)`.
    LocalName,
    /// `GovernmentForm`, declared `char(45)`.
    GovernmentForm,
    /// `HeadOfState`, declared `char(60)`.
    HeadOfState,
    /// `Capital`, declared `int(11)`.
    Capital,
    /// `Code2`, declared `char(2)`.
    Code2,
}

impl CountryColumn {
    /// The column as a statement's text names it: quoted for MariaDB.
    #[must_use]
    pub const fn as_sql(self) -> &'static str {
        match self {
            Self::Code => "`Code`",
            Self::Name => "`Name`",
            Self::Continent => "`Continent`",
            Self::Region => "`Region`",
            Self::SurfaceArea => "`SurfaceArea`",
            Self::IndepYear => "`IndepYear`",
            Self::Population => "`Population`",
            Self::LifeExpectancy => "`LifeExpectancy`",
            Self::Gnp => "`GNP`",
            Self::GnpOld => "`GNPOld`",
            Self::LocalName => "`LocalName`",
            Self::GovernmentForm => "`GovernmentForm`",
            Self::HeadOfState => "`HeadOfState`",
            Self::Capital => "`Capital`",
            Self::Code2 => "`Code2`",
        }
    }

    /// The column as the catalogue names it, unquoted.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::Code => "Code",
            Self::Name => "Name",
            Self::Continent => "Continent",
            Self::Region => "Region",
            Self::SurfaceArea => "SurfaceArea",
            Self::IndepYear => "IndepYear",
            Self::Population => "Population",
            Self::LifeExpectancy => "LifeExpectancy",
            Self::Gnp => "GNP",
            Self::GnpOld => "GNPOld",
            Self::LocalName => "LocalName",
            Self::GovernmentForm => "GovernmentForm",
            Self::HeadOfState => "HeadOfState",
            Self::Capital => "Capital",
            Self::Code2 => "Code2",
        }
    }

    /// Every column of the table, in catalogue order.
    #[must_use]
    pub const fn all() -> &'static [Self] {
        &[
            Self::Code,
            Self::Name,
            Self::Continent,
            Self::Region,
            Self::SurfaceArea,
            Self::IndepYear,
            Self::Population,
            Self::LifeExpectancy,
            Self::Gnp,
            Self::GnpOld,
            Self::LocalName,
            Self::GovernmentForm,
            Self::HeadOfState,
            Self::Capital,
            Self::Code2,
        ]
    }
}

impl std::fmt::Display for CountryColumn {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.name())
    }
}

impl std::str::FromStr for CountryColumn {
    type Err = super::Error;

    /// Reads a column a caller supplied as text.
    ///
    /// # Errors
    ///
    /// Returns [`super::Error::UnknownColumn`] for every name the table does
    /// not carry. That refusal is what keeps a caller's text out of a
    /// statement.
    fn from_str(name: &str) -> Result<Self, Self::Err> {
        match name {
            "Code" => Ok(Self::Code),
            "Name" => Ok(Self::Name),
            "Continent" => Ok(Self::Continent),
            "Region" => Ok(Self::Region),
            "SurfaceArea" => Ok(Self::SurfaceArea),
            "IndepYear" => Ok(Self::IndepYear),
            "Population" => Ok(Self::Population),
            "LifeExpectancy" => Ok(Self::LifeExpectancy),
            "GNP" => Ok(Self::Gnp),
            "GNPOld" => Ok(Self::GnpOld),
            "LocalName" => Ok(Self::LocalName),
            "GovernmentForm" => Ok(Self::GovernmentForm),
            "HeadOfState" => Ok(Self::HeadOfState),
            "Capital" => Ok(Self::Capital),
            "Code2" => Ok(Self::Code2),
            _ => Err(super::Error::UnknownColumn {
                table: "world.country",
                name: name.to_owned(),
            }),
        }
    }
}

/// One ordering term of a search over `world.country`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct CountryOrder {
    /// The column to order by.
    pub column: CountryColumn,
    /// The direction to order in.
    pub direction: super::Direction,
}

/// What narrows a search over `world.country`.
///
/// Every field is optional: a field left `None` adds no condition, and the
/// conditions a search does build are joined with `AND`. [`Default`] is the
/// filter that matches every row.
#[derive(Debug, Clone, Default)]
pub struct CountryFilter {
    /// Where set, requires `Code` to equal it.
    pub code: Option<String>,
    /// Where set, requires `Code` to match it, as `LIKE` matches.
    pub code_like: Option<String>,
    /// Where set, requires `Name` to equal it.
    pub name: Option<String>,
    /// Where set, requires `Name` to match it, as `LIKE` matches.
    pub name_like: Option<String>,
    /// Where set, requires `Continent` to equal it.
    pub continent: Option<String>,
    /// Where set, requires `Continent` to match it, as `LIKE` matches.
    pub continent_like: Option<String>,
    /// Where set, requires `Region` to equal it.
    pub region: Option<String>,
    /// Where set, requires `Region` to match it, as `LIKE` matches.
    pub region_like: Option<String>,
    /// Where set, requires `SurfaceArea` to equal it.
    pub surface_area: Option<super::Decimal>,
    /// Where set, requires `SurfaceArea` to be at least it.
    pub surface_area_from: Option<super::Decimal>,
    /// Where set, requires `SurfaceArea` to be at most it.
    pub surface_area_to: Option<super::Decimal>,
    /// Where set, requires `IndepYear` to equal it.
    pub indep_year: Option<i16>,
    /// Where set, requires `IndepYear` to be at least it.
    pub indep_year_from: Option<i16>,
    /// Where set, requires `IndepYear` to be at most it.
    pub indep_year_to: Option<i16>,
    /// Where set, requires `IndepYear` to be `NULL` when `true` and not to be `NULL` when `false`.
    pub indep_year_is_null: Option<bool>,
    /// Where set, requires `Population` to equal it.
    pub population: Option<i32>,
    /// Where set, requires `Population` to be at least it.
    pub population_from: Option<i32>,
    /// Where set, requires `Population` to be at most it.
    pub population_to: Option<i32>,
    /// Where set, requires `LifeExpectancy` to equal it.
    pub life_expectancy: Option<super::Decimal>,
    /// Where set, requires `LifeExpectancy` to be at least it.
    pub life_expectancy_from: Option<super::Decimal>,
    /// Where set, requires `LifeExpectancy` to be at most it.
    pub life_expectancy_to: Option<super::Decimal>,
    /// Where set, requires `LifeExpectancy` to be `NULL` when `true` and not to be `NULL` when `false`.
    pub life_expectancy_is_null: Option<bool>,
    /// Where set, requires `GNP` to equal it.
    pub gnp: Option<super::Decimal>,
    /// Where set, requires `GNP` to be at least it.
    pub gnp_from: Option<super::Decimal>,
    /// Where set, requires `GNP` to be at most it.
    pub gnp_to: Option<super::Decimal>,
    /// Where set, requires `GNP` to be `NULL` when `true` and not to be `NULL` when `false`.
    pub gnp_is_null: Option<bool>,
    /// Where set, requires `GNPOld` to equal it.
    pub gnp_old: Option<super::Decimal>,
    /// Where set, requires `GNPOld` to be at least it.
    pub gnp_old_from: Option<super::Decimal>,
    /// Where set, requires `GNPOld` to be at most it.
    pub gnp_old_to: Option<super::Decimal>,
    /// Where set, requires `GNPOld` to be `NULL` when `true` and not to be `NULL` when `false`.
    pub gnp_old_is_null: Option<bool>,
    /// Where set, requires `LocalName` to equal it.
    pub local_name: Option<String>,
    /// Where set, requires `LocalName` to match it, as `LIKE` matches.
    pub local_name_like: Option<String>,
    /// Where set, requires `GovernmentForm` to equal it.
    pub government_form: Option<String>,
    /// Where set, requires `GovernmentForm` to match it, as `LIKE` matches.
    pub government_form_like: Option<String>,
    /// Where set, requires `HeadOfState` to equal it.
    pub head_of_state: Option<String>,
    /// Where set, requires `HeadOfState` to match it, as `LIKE` matches.
    pub head_of_state_like: Option<String>,
    /// Where set, requires `HeadOfState` to be `NULL` when `true` and not to be `NULL` when `false`.
    pub head_of_state_is_null: Option<bool>,
    /// Where set, requires `Capital` to equal it.
    pub capital: Option<i32>,
    /// Where set, requires `Capital` to be at least it.
    pub capital_from: Option<i32>,
    /// Where set, requires `Capital` to be at most it.
    pub capital_to: Option<i32>,
    /// Where set, requires `Capital` to be `NULL` when `true` and not to be `NULL` when `false`.
    pub capital_is_null: Option<bool>,
    /// Where set, requires `Code2` to equal it.
    pub code2: Option<String>,
    /// Where set, requires `Code2` to match it, as `LIKE` matches.
    pub code2_like: Option<String>,
}

impl CountryFilter {
    /// Is no field set?
    ///
    /// A search over an empty filter builds no `WHERE` clause and matches
    /// every row of the table.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.code.is_none()
            && self.code_like.is_none()
            && self.name.is_none()
            && self.name_like.is_none()
            && self.continent.is_none()
            && self.continent_like.is_none()
            && self.region.is_none()
            && self.region_like.is_none()
            && self.surface_area.is_none()
            && self.surface_area_from.is_none()
            && self.surface_area_to.is_none()
            && self.indep_year.is_none()
            && self.indep_year_from.is_none()
            && self.indep_year_to.is_none()
            && self.indep_year_is_null.is_none()
            && self.population.is_none()
            && self.population_from.is_none()
            && self.population_to.is_none()
            && self.life_expectancy.is_none()
            && self.life_expectancy_from.is_none()
            && self.life_expectancy_to.is_none()
            && self.life_expectancy_is_null.is_none()
            && self.gnp.is_none()
            && self.gnp_from.is_none()
            && self.gnp_to.is_none()
            && self.gnp_is_null.is_none()
            && self.gnp_old.is_none()
            && self.gnp_old_from.is_none()
            && self.gnp_old_to.is_none()
            && self.gnp_old_is_null.is_none()
            && self.local_name.is_none()
            && self.local_name_like.is_none()
            && self.government_form.is_none()
            && self.government_form_like.is_none()
            && self.head_of_state.is_none()
            && self.head_of_state_like.is_none()
            && self.head_of_state_is_null.is_none()
            && self.capital.is_none()
            && self.capital_from.is_none()
            && self.capital_to.is_none()
            && self.capital_is_null.is_none()
            && self.code2.is_none()
            && self.code2_like.is_none()
    }
}
