// Code generated by tpl from freight.container_type. DO NOT EDIT.

//! The `freight.container_type` row, the key that addresses it, the columns an
//! ordering may name, and the filter a search takes.

/// One row of `freight.container_type`.
///
/// Tipos de contentor normalizados ISO 6346
#[derive(Debug, Clone)]
pub struct ContainerType {
    /// `iso_code`, declared `char(4)` NOT NULL.
    ///
    /// It is part of the primary key.
    ///
    /// ISO 6346 size-and-type code, e.g. 22G1
    pub iso_code: String,
    /// `description`, declared `varchar(80)` NOT NULL.
    pub description: String,
    /// `length_ft`, declared `tinyint(3) unsigned` NOT NULL.
    pub length_ft: u8,
    /// `height_ft_in`, declared `varchar(6)` NOT NULL.
    ///
    /// Nominal external height, feet and inches
    pub height_ft_in: String,
    /// `tare_weight_kg`, declared `decimal(8,2)` NOT NULL.
    pub tare_weight_kg: super::Decimal,
    /// `max_payload_kg`, declared `decimal(8,2)` NOT NULL.
    pub max_payload_kg: super::Decimal,
    /// `internal_volume_cbm`, declared `decimal(7,3)` NOT NULL.
    pub internal_volume_cbm: super::Decimal,
    /// `is_reefer`, declared `tinyint(1)` NOT NULL.
    pub is_reefer: i8,
    /// `is_tank`, declared `tinyint(1)` NOT NULL.
    pub is_tank: i8,
}

impl ContainerType {
    /// The primary key of the row.
    #[must_use]
    pub fn key(&self) -> ContainerTypeKey {
        ContainerTypeKey {
            iso_code: self.iso_code.clone(),
        }
    }
}

impl<'r> sqlx::FromRow<'r, sqlx::mysql::MySqlRow> for ContainerType {
    fn from_row(row: &'r sqlx::mysql::MySqlRow) -> Result<Self, sqlx::Error> {
        use sqlx::Row as _;

        Ok(Self {
            iso_code: row.try_get("iso_code")?,
            description: row.try_get("description")?,
            length_ft: row.try_get("length_ft")?,
            height_ft_in: row.try_get("height_ft_in")?,
            tare_weight_kg: row.try_get("tare_weight_kg")?,
            max_payload_kg: row.try_get("max_payload_kg")?,
            internal_volume_cbm: row.try_get("internal_volume_cbm")?,
            is_reefer: row.try_get("is_reefer")?,
            is_tank: row.try_get("is_tank")?,
        })
    }
}

/// The primary key of `freight.container_type`.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ContainerTypeKey {
    /// `iso_code`, declared `char(4)`.
    pub iso_code: String,
}

/// One column of `freight.container_type`.
///
/// A search accepts an ordering term over these variants and over nothing
/// else, so an ordering can carry no SQL of its own: [`as_sql`] answers from a
/// closed `match` with a quoted identifier the template wrote, and
/// [`FromStr`] is the one door a name a caller supplied can come through.
///
/// [`as_sql`]: ContainerTypeColumn::as_sql
/// [`FromStr`]: std::str::FromStr
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ContainerTypeColumn {
    /// `iso_code`, declared `char(4)`.
    IsoCode,
    /// `description`, declared `varchar(80)`.
    Description,
    /// `length_ft`, declared `tinyint(3) unsigned`.
    LengthFt,
    /// `height_ft_in`, declared `varchar(6)`.
    HeightFtIn,
    /// `tare_weight_kg`, declared `decimal(8,2)`.
    TareWeightKg,
    /// `max_payload_kg`, declared `decimal(8,2)`.
    MaxPayloadKg,
    /// `internal_volume_cbm`, declared `decimal(7,3)`.
    InternalVolumeCbm,
    /// `is_reefer`, declared `tinyint(1)`.
    IsReefer,
    /// `is_tank`, declared `tinyint(1)`.
    IsTank,
}

impl ContainerTypeColumn {
    /// The column as a statement's text names it: quoted for MariaDB.
    #[must_use]
    pub const fn as_sql(self) -> &'static str {
        match self {
            Self::IsoCode => "`iso_code`",
            Self::Description => "`description`",
            Self::LengthFt => "`length_ft`",
            Self::HeightFtIn => "`height_ft_in`",
            Self::TareWeightKg => "`tare_weight_kg`",
            Self::MaxPayloadKg => "`max_payload_kg`",
            Self::InternalVolumeCbm => "`internal_volume_cbm`",
            Self::IsReefer => "`is_reefer`",
            Self::IsTank => "`is_tank`",
        }
    }

    /// The column as the catalogue names it, unquoted.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::IsoCode => "iso_code",
            Self::Description => "description",
            Self::LengthFt => "length_ft",
            Self::HeightFtIn => "height_ft_in",
            Self::TareWeightKg => "tare_weight_kg",
            Self::MaxPayloadKg => "max_payload_kg",
            Self::InternalVolumeCbm => "internal_volume_cbm",
            Self::IsReefer => "is_reefer",
            Self::IsTank => "is_tank",
        }
    }

    /// Every column of the table, in catalogue order.
    #[must_use]
    pub const fn all() -> &'static [Self] {
        &[
            Self::IsoCode,
            Self::Description,
            Self::LengthFt,
            Self::HeightFtIn,
            Self::TareWeightKg,
            Self::MaxPayloadKg,
            Self::InternalVolumeCbm,
            Self::IsReefer,
            Self::IsTank,
        ]
    }
}

impl std::fmt::Display for ContainerTypeColumn {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.name())
    }
}

impl std::str::FromStr for ContainerTypeColumn {
    type Err = super::Error;

    /// Reads a column a caller supplied as text.
    ///
    /// # Errors
    ///
    /// Returns [`super::Error::UnknownColumn`] for every name the table does
    /// not carry. That refusal is what keeps a caller's text out of a
    /// statement.
    fn from_str(name: &str) -> Result<Self, Self::Err> {
        match name {
            "iso_code" => Ok(Self::IsoCode),
            "description" => Ok(Self::Description),
            "length_ft" => Ok(Self::LengthFt),
            "height_ft_in" => Ok(Self::HeightFtIn),
            "tare_weight_kg" => Ok(Self::TareWeightKg),
            "max_payload_kg" => Ok(Self::MaxPayloadKg),
            "internal_volume_cbm" => Ok(Self::InternalVolumeCbm),
            "is_reefer" => Ok(Self::IsReefer),
            "is_tank" => Ok(Self::IsTank),
            _ => Err(super::Error::UnknownColumn {
                table: "freight.container_type",
                name: name.to_owned(),
            }),
        }
    }
}

/// One ordering term of a search over `freight.container_type`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ContainerTypeOrder {
    /// The column to order by.
    pub column: ContainerTypeColumn,
    /// The direction to order in.
    pub direction: super::Direction,
}

/// What narrows a search over `freight.container_type`.
///
/// Every field is optional: a field left `None` adds no condition, and the
/// conditions a search does build are joined with `AND`. [`Default`] is the
/// filter that matches every row.
#[derive(Debug, Clone, Default)]
pub struct ContainerTypeFilter {
    /// Where set, requires `iso_code` to equal it.
    pub iso_code: Option<String>,
    /// Where set, requires `iso_code` to match it, as `LIKE` matches.
    pub iso_code_like: Option<String>,
    /// Where set, requires `description` to equal it.
    pub description: Option<String>,
    /// Where set, requires `description` to match it, as `LIKE` matches.
    pub description_like: Option<String>,
    /// Where set, requires `length_ft` to equal it.
    pub length_ft: Option<u8>,
    /// Where set, requires `length_ft` to be at least it.
    pub length_ft_from: Option<u8>,
    /// Where set, requires `length_ft` to be at most it.
    pub length_ft_to: Option<u8>,
    /// Where set, requires `height_ft_in` to equal it.
    pub height_ft_in: Option<String>,
    /// Where set, requires `height_ft_in` to match it, as `LIKE` matches.
    pub height_ft_in_like: Option<String>,
    /// Where set, requires `tare_weight_kg` to equal it.
    pub tare_weight_kg: Option<super::Decimal>,
    /// Where set, requires `tare_weight_kg` to be at least it.
    pub tare_weight_kg_from: Option<super::Decimal>,
    /// Where set, requires `tare_weight_kg` to be at most it.
    pub tare_weight_kg_to: Option<super::Decimal>,
    /// Where set, requires `max_payload_kg` to equal it.
    pub max_payload_kg: Option<super::Decimal>,
    /// Where set, requires `max_payload_kg` to be at least it.
    pub max_payload_kg_from: Option<super::Decimal>,
    /// Where set, requires `max_payload_kg` to be at most it.
    pub max_payload_kg_to: Option<super::Decimal>,
    /// Where set, requires `internal_volume_cbm` to equal it.
    pub internal_volume_cbm: Option<super::Decimal>,
    /// Where set, requires `internal_volume_cbm` to be at least it.
    pub internal_volume_cbm_from: Option<super::Decimal>,
    /// Where set, requires `internal_volume_cbm` to be at most it.
    pub internal_volume_cbm_to: Option<super::Decimal>,
    /// Where set, requires `is_reefer` to equal it.
    pub is_reefer: Option<i8>,
    /// Where set, requires `is_reefer` to be at least it.
    pub is_reefer_from: Option<i8>,
    /// Where set, requires `is_reefer` to be at most it.
    pub is_reefer_to: Option<i8>,
    /// Where set, requires `is_tank` to equal it.
    pub is_tank: Option<i8>,
    /// Where set, requires `is_tank` to be at least it.
    pub is_tank_from: Option<i8>,
    /// Where set, requires `is_tank` to be at most it.
    pub is_tank_to: Option<i8>,
}

impl ContainerTypeFilter {
    /// Is no field set?
    ///
    /// A search over an empty filter builds no `WHERE` clause and matches
    /// every row of the table.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.iso_code.is_none()
            && self.iso_code_like.is_none()
            && self.description.is_none()
            && self.description_like.is_none()
            && self.length_ft.is_none()
            && self.length_ft_from.is_none()
            && self.length_ft_to.is_none()
            && self.height_ft_in.is_none()
            && self.height_ft_in_like.is_none()
            && self.tare_weight_kg.is_none()
            && self.tare_weight_kg_from.is_none()
            && self.tare_weight_kg_to.is_none()
            && self.max_payload_kg.is_none()
            && self.max_payload_kg_from.is_none()
            && self.max_payload_kg_to.is_none()
            && self.internal_volume_cbm.is_none()
            && self.internal_volume_cbm_from.is_none()
            && self.internal_volume_cbm_to.is_none()
            && self.is_reefer.is_none()
            && self.is_reefer_from.is_none()
            && self.is_reefer_to.is_none()
            && self.is_tank.is_none()
            && self.is_tank_from.is_none()
            && self.is_tank_to.is_none()
    }
}
