// Code generated by tpl from freight.customs_declaration. DO NOT EDIT.

//! The `sqlx` implementation of the `freight.customs_declaration` data layer.

use sqlx::{MySql, QueryBuilder};

use super::Error;
use super::customs_declaration::{CustomsDeclaration, CustomsDeclarationFilter, CustomsDeclarationKey, CustomsDeclarationOrder};
use super::customs_declaration_repository::CustomsDeclarationRepository;

/// The table every statement of this module addresses, as an error names it.
const TABLE: &str = "freight.customs_declaration";

/// Selects every column of the table, in catalogue order.
const SELECT: &str = "SELECT `declaration_id`, `consignment_id`, `clearance_port_id`, `mrn`, `procedure_code`, `regime`, `status`, `lodged_at`, `released_at`, `duty_amount`, `vat_amount`, `total_payable`, `officer_remarks` FROM `customs_declaration`";

/// Selects the one row a primary key names.
const READ: &str = "SELECT `declaration_id`, `consignment_id`, `clearance_port_id`, `mrn`, `procedure_code`, `regime`, `status`, `lodged_at`, `released_at`, `duty_amount`, `vat_amount`, `total_payable`, `officer_remarks` FROM `customs_declaration` WHERE `declaration_id` = ?";

/// Inserts one row.
///
/// It names neither a generated column nor an auto-increment key, because the
/// server writes both.
const INSERT: &str = "INSERT INTO `customs_declaration` (`consignment_id`, `clearance_port_id`, `mrn`, `procedure_code`, `regime`, `status`, `lodged_at`, `released_at`, `duty_amount`, `vat_amount`, `officer_remarks`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

/// Writes every column that is neither generated nor part of the key.
const UPDATE: &str = "UPDATE `customs_declaration` SET `consignment_id` = ?, `clearance_port_id` = ?, `mrn` = ?, `procedure_code` = ?, `regime` = ?, `status` = ?, `lodged_at` = ?, `released_at` = ?, `duty_amount` = ?, `vat_amount` = ?, `officer_remarks` = ? WHERE `declaration_id` = ?";

/// Removes the one row a primary key names.
const DELETE: &str = "DELETE FROM `customs_declaration` WHERE `declaration_id` = ?";

/// The `sqlx` data layer of `freight.customs_declaration`.
#[derive(Debug, Clone)]
pub struct CustomsDeclarationSqlx {
    pool: sqlx::MySqlPool,
}

impl CustomsDeclarationSqlx {
    /// Builds the data layer of `freight.customs_declaration` over `pool`.
    ///
    /// The pool must address the schema [`SCHEMA`] names, because the
    /// statements above address the table unqualified. [`connect`] is the pool
    /// that carries it.
    ///
    /// [`SCHEMA`]: super::SCHEMA
    /// [`connect`]: super::connect
    #[must_use]
    pub fn new(pool: sqlx::MySqlPool) -> Self {
        Self { pool }
    }
}

impl CustomsDeclarationRepository for CustomsDeclarationSqlx {
    async fn create(&self, row: &mut CustomsDeclaration) -> Result<(), Error> {
        let assigned = sqlx::query(INSERT)
            .bind(row.consignment_id)
            .bind(row.clearance_port_id)
            .bind(&row.mrn)
            .bind(&row.procedure_code)
            .bind(&row.regime)
            .bind(&row.status)
            .bind(row.lodged_at)
            .bind(row.released_at)
            .bind(&row.duty_amount)
            .bind(&row.vat_amount)
            .bind(&row.officer_remarks)
            .execute(&self.pool)
            .await?
            .last_insert_id();
        row.declaration_id = assigned;
        Ok(())
    }

    async fn read(&self, key: &CustomsDeclarationKey) -> Result<CustomsDeclaration, Error> {
        sqlx::query_as::<_, CustomsDeclaration>(READ)
            .bind(key.declaration_id)
            .fetch_optional(&self.pool)
            .await?
            .ok_or(Error::NotFound { table: TABLE })
    }

    async fn update(&self, row: &CustomsDeclaration) -> Result<u64, Error> {
        let outcome = sqlx::query(UPDATE)
            .bind(row.consignment_id)
            .bind(row.clearance_port_id)
            .bind(&row.mrn)
            .bind(&row.procedure_code)
            .bind(&row.regime)
            .bind(&row.status)
            .bind(row.lodged_at)
            .bind(row.released_at)
            .bind(&row.duty_amount)
            .bind(&row.vat_amount)
            .bind(&row.officer_remarks)
            .bind(row.declaration_id)
            .execute(&self.pool)
            .await?;

        Ok(outcome.rows_affected())
    }

    async fn delete(&self, key: &CustomsDeclarationKey) -> Result<u64, Error> {
        let outcome = sqlx::query(DELETE)
            .bind(key.declaration_id)
            .execute(&self.pool)
            .await?;

        Ok(outcome.rows_affected())
    }

    async fn search(
        &self,
        filter: CustomsDeclarationFilter,
        order: &[CustomsDeclarationOrder],
        limit: Option<u64>,
        offset: Option<u64>,
    ) -> Result<Vec<CustomsDeclaration>, Error> {
        let mut builder: QueryBuilder<MySql> = QueryBuilder::new(SELECT);

        if !filter.is_empty() {
            builder.push(" WHERE ");
            let mut conditions = builder.separated(" AND ");

            if let Some(value) = filter.declaration_id {
                conditions
                    .push("`declaration_id` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.declaration_id_from {
                conditions
                    .push("`declaration_id` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.declaration_id_to {
                conditions
                    .push("`declaration_id` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.consignment_id {
                conditions
                    .push("`consignment_id` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.consignment_id_from {
                conditions
                    .push("`consignment_id` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.consignment_id_to {
                conditions
                    .push("`consignment_id` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.clearance_port_id {
                conditions
                    .push("`clearance_port_id` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.clearance_port_id_from {
                conditions
                    .push("`clearance_port_id` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.clearance_port_id_to {
                conditions
                    .push("`clearance_port_id` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(is_null) = filter.clearance_port_id_is_null {
                conditions.push(if is_null {
                    "`clearance_port_id` IS NULL"
                } else {
                    "`clearance_port_id` IS NOT NULL"
                });
            }
            if let Some(value) = filter.mrn {
                conditions
                    .push("`mrn` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.mrn_like {
                conditions
                    .push("`mrn` LIKE ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.procedure_code {
                conditions
                    .push("`procedure_code` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.procedure_code_like {
                conditions
                    .push("`procedure_code` LIKE ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.regime {
                conditions
                    .push("`regime` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.regime_like {
                conditions
                    .push("`regime` LIKE ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.status {
                conditions
                    .push("`status` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.status_like {
                conditions
                    .push("`status` LIKE ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.lodged_at {
                conditions
                    .push("`lodged_at` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.lodged_at_from {
                conditions
                    .push("`lodged_at` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.lodged_at_to {
                conditions
                    .push("`lodged_at` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(is_null) = filter.lodged_at_is_null {
                conditions.push(if is_null {
                    "`lodged_at` IS NULL"
                } else {
                    "`lodged_at` IS NOT NULL"
                });
            }
            if let Some(value) = filter.released_at {
                conditions
                    .push("`released_at` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.released_at_from {
                conditions
                    .push("`released_at` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.released_at_to {
                conditions
                    .push("`released_at` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(is_null) = filter.released_at_is_null {
                conditions.push(if is_null {
                    "`released_at` IS NULL"
                } else {
                    "`released_at` IS NOT NULL"
                });
            }
            if let Some(value) = filter.duty_amount {
                conditions
                    .push("`duty_amount` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.duty_amount_from {
                conditions
                    .push("`duty_amount` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.duty_amount_to {
                conditions
                    .push("`duty_amount` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.vat_amount {
                conditions
                    .push("`vat_amount` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.vat_amount_from {
                conditions
                    .push("`vat_amount` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.vat_amount_to {
                conditions
                    .push("`vat_amount` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.total_payable {
                conditions
                    .push("`total_payable` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.total_payable_from {
                conditions
                    .push("`total_payable` >= ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.total_payable_to {
                conditions
                    .push("`total_payable` <= ")
                    .push_bind_unseparated(value);
            }
            if let Some(is_null) = filter.total_payable_is_null {
                conditions.push(if is_null {
                    "`total_payable` IS NULL"
                } else {
                    "`total_payable` IS NOT NULL"
                });
            }
            if let Some(value) = filter.officer_remarks {
                conditions
                    .push("`officer_remarks` = ")
                    .push_bind_unseparated(value);
            }
            if let Some(value) = filter.officer_remarks_like {
                conditions
                    .push("`officer_remarks` LIKE ")
                    .push_bind_unseparated(value);
            }
            if let Some(is_null) = filter.officer_remarks_is_null {
                conditions.push(if is_null {
                    "`officer_remarks` IS NULL"
                } else {
                    "`officer_remarks` IS NOT NULL"
                });
            }
        }

        if !order.is_empty() {
            builder.push(" ORDER BY ");
            for (position, term) in order.iter().enumerate() {
                if position > 0 {
                    builder.push(", ");
                }
                builder.push(term.column.as_sql());
                builder.push(" ");
                builder.push(term.direction.as_sql());
            }
        }

        if let Some(limit) = limit {
            builder.push(" LIMIT ").push_bind(limit);

            if let Some(offset) = offset {
                builder.push(" OFFSET ").push_bind(offset);
            }
        }

        builder
            .build_query_as::<CustomsDeclaration>()
            .fetch_all(&self.pool)
            .await
            .map_err(Error::from)
    }
}
