// Code generated by tpl from freight.vessel. DO NOT EDIT.

//! The `freight.vessel` row, the key that addresses it, the columns an
//! ordering may name, and the filter a search takes.

/// One row of `freight.vessel`.
///
/// Navios porta-contentores em serviço ou fretados
#[derive(Debug, Clone)]
pub struct Vessel {
    /// `imo_number`, declared `char(7)` NOT NULL.
    ///
    /// It is part of the primary key.
    ///
    /// IMO ship identification number, seven digits, check digit included
    pub imo_number: String,
    /// `name`, declared `varchar(100)` NOT NULL.
    ///
    /// Registered name; changes on sale
    pub name: String,
    /// `call_sign`, declared `varchar(10)` NOT NULL.
    pub call_sign: String,
    /// `mmsi`, declared `int(10) unsigned` NULL.
    ///
    /// It is part of a unique index.
    ///
    /// AIS Maritime Mobile Service Identity, nine digits
    pub mmsi: Option<u32>,
    /// `flag_state`, declared `char(2)` NOT NULL.
    pub flag_state: String,
    /// `class_society`, declared `enum('Lloyd''s Register','DNV','Bureau Veritas','ClassNK','American Bureau of Shipping','RINA')` NOT NULL.
    ///
    /// Classification society; note the apostrophe in the first member
    pub class_society: String,
    /// `hull_number`, declared `mediumint(9)` NULL.
    ///
    /// Builder yard number; signed, as some yards used negative rework codes
    pub hull_number: Option<i32>,
    /// `capacity_teu`, declared `mediumint(8) unsigned` NOT NULL.
    ///
    /// Nominal intake in twenty-foot equivalent units
    pub capacity_teu: u32,
    /// `reefer_plugs`, declared `smallint(5) unsigned` NOT NULL.
    pub reefer_plugs: u16,
    /// `deadweight_tonnes`, declared `int(10) unsigned` NOT NULL.
    pub deadweight_tonnes: u32,
    /// `gross_tonnage`, declared `decimal(10,2)` NOT NULL.
    ///
    /// ITC 1969 gross tonnage
    pub gross_tonnage: super::Decimal,
    /// `net_tonnage`, declared `decimal(10,2)` NULL.
    ///
    /// Declared as NUMERIC to observe how the catalogue reports the synonym
    pub net_tonnage: Option<super::Decimal>,
    /// `service_speed_knots`, declared `float` NOT NULL.
    pub service_speed_knots: f32,
    /// `ballast_capacity_m3`, declared `double` NULL.
    pub ballast_capacity_m3: Option<f64>,
    /// `loa_m`, declared `decimal(6,2)` NOT NULL.
    ///
    /// Length overall, metres
    pub loa_m: super::Decimal,
    /// `beam_m`, declared `decimal(5,2)` NOT NULL.
    pub beam_m: super::Decimal,
    /// `design_draught_m`, declared `decimal(5,2)` NOT NULL.
    pub design_draught_m: super::Decimal,
    /// `year_built`, declared `year(4)` NOT NULL.
    pub year_built: u16,
    /// `crew_complement`, declared `tinyint(3) unsigned` NOT NULL.
    pub crew_complement: u8,
    /// `lifetime_distance_nm`, declared `bigint(20) unsigned` NOT NULL.
    ///
    /// Cumulative logged distance, nautical miles
    pub lifetime_distance_nm: u64,
    /// `in_service`, declared `tinyint(1)` NOT NULL.
    ///
    /// Declared BOOLEAN; MariaDB stores TINYINT(1)
    pub in_service: i8,
    /// `scrubber_fitted`, declared `bit(1)` NOT NULL.
    pub scrubber_fitted: u64,
    /// `particulars_sheet`, declared `mediumtext` NULL.
    ///
    /// Full ship particulars as supplied by the owner
    pub particulars_sheet: Option<String>,
}

impl Vessel {
    /// The primary key of the row.
    #[must_use]
    pub fn key(&self) -> VesselKey {
        VesselKey {
            imo_number: self.imo_number.clone(),
        }
    }
}

impl<'r> sqlx::FromRow<'r, sqlx::mysql::MySqlRow> for Vessel {
    fn from_row(row: &'r sqlx::mysql::MySqlRow) -> Result<Self, sqlx::Error> {
        use sqlx::Row as _;

        Ok(Self {
            imo_number: row.try_get("imo_number")?,
            name: row.try_get("name")?,
            call_sign: row.try_get("call_sign")?,
            mmsi: row.try_get("mmsi")?,
            flag_state: row.try_get("flag_state")?,
            class_society: row.try_get("class_society")?,
            hull_number: row.try_get("hull_number")?,
            capacity_teu: row.try_get("capacity_teu")?,
            reefer_plugs: row.try_get("reefer_plugs")?,
            deadweight_tonnes: row.try_get("deadweight_tonnes")?,
            gross_tonnage: row.try_get("gross_tonnage")?,
            net_tonnage: row.try_get("net_tonnage")?,
            service_speed_knots: row.try_get("service_speed_knots")?,
            ballast_capacity_m3: row.try_get("ballast_capacity_m3")?,
            loa_m: row.try_get("loa_m")?,
            beam_m: row.try_get("beam_m")?,
            design_draught_m: row.try_get("design_draught_m")?,
            year_built: row.try_get("year_built")?,
            crew_complement: row.try_get("crew_complement")?,
            lifetime_distance_nm: row.try_get("lifetime_distance_nm")?,
            in_service: row.try_get("in_service")?,
            scrubber_fitted: row.try_get("scrubber_fitted")?,
            particulars_sheet: row.try_get("particulars_sheet")?,
        })
    }
}

/// The primary key of `freight.vessel`.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct VesselKey {
    /// `imo_number`, declared `char(7)`.
    pub imo_number: String,
}

/// One column of `freight.vessel`.
///
/// A search accepts an ordering term over these variants and over nothing
/// else, so an ordering can carry no SQL of its own: [`as_sql`] answers from a
/// closed `match` with a quoted identifier the template wrote, and
/// [`FromStr`] is the one door a name a caller supplied can come through.
///
/// [`as_sql`]: VesselColumn::as_sql
/// [`FromStr`]: std::str::FromStr
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum VesselColumn {
    /// `imo_number`, declared `char(7)`.
    ImoNumber,
    /// `name`, declared `varchar(100)`.
    Name,
    /// `call_sign`, declared `varchar(10)`.
    CallSign,
    /// `mmsi`, declared `int(10) unsigned`.
    Mmsi,
    /// `flag_state`, declared `char(2)`.
    FlagState,
    /// `class_society`, declared `enum('Lloyd''s Register','DNV','Bureau Veritas','ClassNK','American Bureau of Shipping','RINA')`.
    ClassSociety,
    /// `hull_number`, declared `mediumint(9)`.
    HullNumber,
    /// `capacity_teu`, declared `mediumint(8) unsigned`.
    CapacityTeu,
    /// `reefer_plugs`, declared `smallint(5) unsigned`.
    ReeferPlugs,
    /// `deadweight_tonnes`, declared `int(10) unsigned`.
    DeadweightTonnes,
    /// `gross_tonnage`, declared `decimal(10,2)`.
    GrossTonnage,
    /// `net_tonnage`, declared `decimal(10,2)`.
    NetTonnage,
    /// `service_speed_knots`, declared `float`.
    ServiceSpeedKnots,
    /// `ballast_capacity_m3`, declared `double`.
    BallastCapacityM3,
    /// `loa_m`, declared `decimal(6,2)`.
    LoaM,
    /// `beam_m`, declared `decimal(5,2)`.
    BeamM,
    /// `design_draught_m`, declared `decimal(5,2)`.
    DesignDraughtM,
    /// `year_built`, declared `year(4)`.
    YearBuilt,
    /// `crew_complement`, declared `tinyint(3) unsigned`.
    CrewComplement,
    /// `lifetime_distance_nm`, declared `bigint(20) unsigned`.
    LifetimeDistanceNm,
    /// `in_service`, declared `tinyint(1)`.
    InService,
    /// `scrubber_fitted`, declared `bit(1)`.
    ScrubberFitted,
    /// `particulars_sheet`, declared `mediumtext`.
    ParticularsSheet,
}

impl VesselColumn {
    /// The column as a statement's text names it: quoted for MariaDB.
    #[must_use]
    pub const fn as_sql(self) -> &'static str {
        match self {
            Self::ImoNumber => "`imo_number`",
            Self::Name => "`name`",
            Self::CallSign => "`call_sign`",
            Self::Mmsi => "`mmsi`",
            Self::FlagState => "`flag_state`",
            Self::ClassSociety => "`class_society`",
            Self::HullNumber => "`hull_number`",
            Self::CapacityTeu => "`capacity_teu`",
            Self::ReeferPlugs => "`reefer_plugs`",
            Self::DeadweightTonnes => "`deadweight_tonnes`",
            Self::GrossTonnage => "`gross_tonnage`",
            Self::NetTonnage => "`net_tonnage`",
            Self::ServiceSpeedKnots => "`service_speed_knots`",
            Self::BallastCapacityM3 => "`ballast_capacity_m3`",
            Self::LoaM => "`loa_m`",
            Self::BeamM => "`beam_m`",
            Self::DesignDraughtM => "`design_draught_m`",
            Self::YearBuilt => "`year_built`",
            Self::CrewComplement => "`crew_complement`",
            Self::LifetimeDistanceNm => "`lifetime_distance_nm`",
            Self::InService => "`in_service`",
            Self::ScrubberFitted => "`scrubber_fitted`",
            Self::ParticularsSheet => "`particulars_sheet`",
        }
    }

    /// The column as the catalogue names it, unquoted.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::ImoNumber => "imo_number",
            Self::Name => "name",
            Self::CallSign => "call_sign",
            Self::Mmsi => "mmsi",
            Self::FlagState => "flag_state",
            Self::ClassSociety => "class_society",
            Self::HullNumber => "hull_number",
            Self::CapacityTeu => "capacity_teu",
            Self::ReeferPlugs => "reefer_plugs",
            Self::DeadweightTonnes => "deadweight_tonnes",
            Self::GrossTonnage => "gross_tonnage",
            Self::NetTonnage => "net_tonnage",
            Self::ServiceSpeedKnots => "service_speed_knots",
            Self::BallastCapacityM3 => "ballast_capacity_m3",
            Self::LoaM => "loa_m",
            Self::BeamM => "beam_m",
            Self::DesignDraughtM => "design_draught_m",
            Self::YearBuilt => "year_built",
            Self::CrewComplement => "crew_complement",
            Self::LifetimeDistanceNm => "lifetime_distance_nm",
            Self::InService => "in_service",
            Self::ScrubberFitted => "scrubber_fitted",
            Self::ParticularsSheet => "particulars_sheet",
        }
    }

    /// Every column of the table, in catalogue order.
    #[must_use]
    pub const fn all() -> &'static [Self] {
        &[
            Self::ImoNumber,
            Self::Name,
            Self::CallSign,
            Self::Mmsi,
            Self::FlagState,
            Self::ClassSociety,
            Self::HullNumber,
            Self::CapacityTeu,
            Self::ReeferPlugs,
            Self::DeadweightTonnes,
            Self::GrossTonnage,
            Self::NetTonnage,
            Self::ServiceSpeedKnots,
            Self::BallastCapacityM3,
            Self::LoaM,
            Self::BeamM,
            Self::DesignDraughtM,
            Self::YearBuilt,
            Self::CrewComplement,
            Self::LifetimeDistanceNm,
            Self::InService,
            Self::ScrubberFitted,
            Self::ParticularsSheet,
        ]
    }
}

impl std::fmt::Display for VesselColumn {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.name())
    }
}

impl std::str::FromStr for VesselColumn {
    type Err = super::Error;

    /// Reads a column a caller supplied as text.
    ///
    /// # Errors
    ///
    /// Returns [`super::Error::UnknownColumn`] for every name the table does
    /// not carry. That refusal is what keeps a caller's text out of a
    /// statement.
    fn from_str(name: &str) -> Result<Self, Self::Err> {
        match name {
            "imo_number" => Ok(Self::ImoNumber),
            "name" => Ok(Self::Name),
            "call_sign" => Ok(Self::CallSign),
            "mmsi" => Ok(Self::Mmsi),
            "flag_state" => Ok(Self::FlagState),
            "class_society" => Ok(Self::ClassSociety),
            "hull_number" => Ok(Self::HullNumber),
            "capacity_teu" => Ok(Self::CapacityTeu),
            "reefer_plugs" => Ok(Self::ReeferPlugs),
            "deadweight_tonnes" => Ok(Self::DeadweightTonnes),
            "gross_tonnage" => Ok(Self::GrossTonnage),
            "net_tonnage" => Ok(Self::NetTonnage),
            "service_speed_knots" => Ok(Self::ServiceSpeedKnots),
            "ballast_capacity_m3" => Ok(Self::BallastCapacityM3),
            "loa_m" => Ok(Self::LoaM),
            "beam_m" => Ok(Self::BeamM),
            "design_draught_m" => Ok(Self::DesignDraughtM),
            "year_built" => Ok(Self::YearBuilt),
            "crew_complement" => Ok(Self::CrewComplement),
            "lifetime_distance_nm" => Ok(Self::LifetimeDistanceNm),
            "in_service" => Ok(Self::InService),
            "scrubber_fitted" => Ok(Self::ScrubberFitted),
            "particulars_sheet" => Ok(Self::ParticularsSheet),
            _ => Err(super::Error::UnknownColumn {
                table: "freight.vessel",
                name: name.to_owned(),
            }),
        }
    }
}

/// One ordering term of a search over `freight.vessel`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct VesselOrder {
    /// The column to order by.
    pub column: VesselColumn,
    /// The direction to order in.
    pub direction: super::Direction,
}

/// What narrows a search over `freight.vessel`.
///
/// Every field is optional: a field left `None` adds no condition, and the
/// conditions a search does build are joined with `AND`. [`Default`] is the
/// filter that matches every row.
#[derive(Debug, Clone, Default)]
pub struct VesselFilter {
    /// Where set, requires `imo_number` to equal it.
    pub imo_number: Option<String>,
    /// Where set, requires `imo_number` to match it, as `LIKE` matches.
    pub imo_number_like: Option<String>,
    /// Where set, requires `name` to equal it.
    pub name: Option<String>,
    /// Where set, requires `name` to match it, as `LIKE` matches.
    pub name_like: Option<String>,
    /// Where set, requires `call_sign` to equal it.
    pub call_sign: Option<String>,
    /// Where set, requires `call_sign` to match it, as `LIKE` matches.
    pub call_sign_like: Option<String>,
    /// Where set, requires `mmsi` to equal it.
    pub mmsi: Option<u32>,
    /// Where set, requires `mmsi` to be at least it.
    pub mmsi_from: Option<u32>,
    /// Where set, requires `mmsi` to be at most it.
    pub mmsi_to: Option<u32>,
    /// Where set, requires `mmsi` to be `NULL` when `true` and not to be `NULL` when `false`.
    pub mmsi_is_null: Option<bool>,
    /// Where set, requires `flag_state` to equal it.
    pub flag_state: Option<String>,
    /// Where set, requires `flag_state` to match it, as `LIKE` matches.
    pub flag_state_like: Option<String>,
    /// Where set, requires `class_society` to equal it.
    pub class_society: Option<String>,
    /// Where set, requires `class_society` to match it, as `LIKE` matches.
    pub class_society_like: Option<String>,
    /// Where set, requires `hull_number` to equal it.
    pub hull_number: Option<i32>,
    /// Where set, requires `hull_number` to be at least it.
    pub hull_number_from: Option<i32>,
    /// Where set, requires `hull_number` to be at most it.
    pub hull_number_to: Option<i32>,
    /// Where set, requires `hull_number` to be `NULL` when `true` and not to be `NULL` when `false`.
    pub hull_number_is_null: Option<bool>,
    /// Where set, requires `capacity_teu` to equal it.
    pub capacity_teu: Option<u32>,
    /// Where set, requires `capacity_teu` to be at least it.
    pub capacity_teu_from: Option<u32>,
    /// Where set, requires `capacity_teu` to be at most it.
    pub capacity_teu_to: Option<u32>,
    /// Where set, requires `reefer_plugs` to equal it.
    pub reefer_plugs: Option<u16>,
    /// Where set, requires `reefer_plugs` to be at least it.
    pub reefer_plugs_from: Option<u16>,
    /// Where set, requires `reefer_plugs` to be at most it.
    pub reefer_plugs_to: Option<u16>,
    /// Where set, requires `deadweight_tonnes` to equal it.
    pub deadweight_tonnes: Option<u32>,
    /// Where set, requires `deadweight_tonnes` to be at least it.
    pub deadweight_tonnes_from: Option<u32>,
    /// Where set, requires `deadweight_tonnes` to be at most it.
    pub deadweight_tonnes_to: Option<u32>,
    /// Where set, requires `gross_tonnage` to equal it.
    pub gross_tonnage: Option<super::Decimal>,
    /// Where set, requires `gross_tonnage` to be at least it.
    pub gross_tonnage_from: Option<super::Decimal>,
    /// Where set, requires `gross_tonnage` to be at most it.
    pub gross_tonnage_to: Option<super::Decimal>,
    /// Where set, requires `net_tonnage` to equal it.
    pub net_tonnage: Option<super::Decimal>,
    /// Where set, requires `net_tonnage` to be at least it.
    pub net_tonnage_from: Option<super::Decimal>,
    /// Where set, requires `net_tonnage` to be at most it.
    pub net_tonnage_to: Option<super::Decimal>,
    /// Where set, requires `net_tonnage` to be `NULL` when `true` and not to be `NULL` when `false`.
    pub net_tonnage_is_null: Option<bool>,
    /// Where set, requires `service_speed_knots` to equal it.
    pub service_speed_knots: Option<f32>,
    /// Where set, requires `service_speed_knots` to be at least it.
    pub service_speed_knots_from: Option<f32>,
    /// Where set, requires `service_speed_knots` to be at most it.
    pub service_speed_knots_to: Option<f32>,
    /// Where set, requires `ballast_capacity_m3` to equal it.
    pub ballast_capacity_m3: Option<f64>,
    /// Where set, requires `ballast_capacity_m3` to be at least it.
    pub ballast_capacity_m3_from: Option<f64>,
    /// Where set, requires `ballast_capacity_m3` to be at most it.
    pub ballast_capacity_m3_to: Option<f64>,
    /// Where set, requires `ballast_capacity_m3` to be `NULL` when `true` and not to be `NULL` when `false`.
    pub ballast_capacity_m3_is_null: Option<bool>,
    /// Where set, requires `loa_m` to equal it.
    pub loa_m: Option<super::Decimal>,
    /// Where set, requires `loa_m` to be at least it.
    pub loa_m_from: Option<super::Decimal>,
    /// Where set, requires `loa_m` to be at most it.
    pub loa_m_to: Option<super::Decimal>,
    /// Where set, requires `beam_m` to equal it.
    pub beam_m: Option<super::Decimal>,
    /// Where set, requires `beam_m` to be at least it.
    pub beam_m_from: Option<super::Decimal>,
    /// Where set, requires `beam_m` to be at most it.
    pub beam_m_to: Option<super::Decimal>,
    /// Where set, requires `design_draught_m` to equal it.
    pub design_draught_m: Option<super::Decimal>,
    /// Where set, requires `design_draught_m` to be at least it.
    pub design_draught_m_from: Option<super::Decimal>,
    /// Where set, requires `design_draught_m` to be at most it.
    pub design_draught_m_to: Option<super::Decimal>,
    /// Where set, requires `year_built` to equal it.
    pub year_built: Option<u16>,
    /// Where set, requires `year_built` to be at least it.
    pub year_built_from: Option<u16>,
    /// Where set, requires `year_built` to be at most it.
    pub year_built_to: Option<u16>,
    /// Where set, requires `crew_complement` to equal it.
    pub crew_complement: Option<u8>,
    /// Where set, requires `crew_complement` to be at least it.
    pub crew_complement_from: Option<u8>,
    /// Where set, requires `crew_complement` to be at most it.
    pub crew_complement_to: Option<u8>,
    /// Where set, requires `lifetime_distance_nm` to equal it.
    pub lifetime_distance_nm: Option<u64>,
    /// Where set, requires `lifetime_distance_nm` to be at least it.
    pub lifetime_distance_nm_from: Option<u64>,
    /// Where set, requires `lifetime_distance_nm` to be at most it.
    pub lifetime_distance_nm_to: Option<u64>,
    /// Where set, requires `in_service` to equal it.
    pub in_service: Option<i8>,
    /// Where set, requires `in_service` to be at least it.
    pub in_service_from: Option<i8>,
    /// Where set, requires `in_service` to be at most it.
    pub in_service_to: Option<i8>,
    /// Where set, requires `scrubber_fitted` to equal it.
    pub scrubber_fitted: Option<u64>,
    /// Where set, requires `scrubber_fitted` to be at least it.
    pub scrubber_fitted_from: Option<u64>,
    /// Where set, requires `scrubber_fitted` to be at most it.
    pub scrubber_fitted_to: Option<u64>,
    /// Where set, requires `particulars_sheet` to equal it.
    pub particulars_sheet: Option<String>,
    /// Where set, requires `particulars_sheet` to match it, as `LIKE` matches.
    pub particulars_sheet_like: Option<String>,
    /// Where set, requires `particulars_sheet` to be `NULL` when `true` and not to be `NULL` when `false`.
    pub particulars_sheet_is_null: Option<bool>,
}

impl VesselFilter {
    /// Is no field set?
    ///
    /// A search over an empty filter builds no `WHERE` clause and matches
    /// every row of the table.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.imo_number.is_none()
            && self.imo_number_like.is_none()
            && self.name.is_none()
            && self.name_like.is_none()
            && self.call_sign.is_none()
            && self.call_sign_like.is_none()
            && self.mmsi.is_none()
            && self.mmsi_from.is_none()
            && self.mmsi_to.is_none()
            && self.mmsi_is_null.is_none()
            && self.flag_state.is_none()
            && self.flag_state_like.is_none()
            && self.class_society.is_none()
            && self.class_society_like.is_none()
            && self.hull_number.is_none()
            && self.hull_number_from.is_none()
            && self.hull_number_to.is_none()
            && self.hull_number_is_null.is_none()
            && self.capacity_teu.is_none()
            && self.capacity_teu_from.is_none()
            && self.capacity_teu_to.is_none()
            && self.reefer_plugs.is_none()
            && self.reefer_plugs_from.is_none()
            && self.reefer_plugs_to.is_none()
            && self.deadweight_tonnes.is_none()
            && self.deadweight_tonnes_from.is_none()
            && self.deadweight_tonnes_to.is_none()
            && self.gross_tonnage.is_none()
            && self.gross_tonnage_from.is_none()
            && self.gross_tonnage_to.is_none()
            && self.net_tonnage.is_none()
            && self.net_tonnage_from.is_none()
            && self.net_tonnage_to.is_none()
            && self.net_tonnage_is_null.is_none()
            && self.service_speed_knots.is_none()
            && self.service_speed_knots_from.is_none()
            && self.service_speed_knots_to.is_none()
            && self.ballast_capacity_m3.is_none()
            && self.ballast_capacity_m3_from.is_none()
            && self.ballast_capacity_m3_to.is_none()
            && self.ballast_capacity_m3_is_null.is_none()
            && self.loa_m.is_none()
            && self.loa_m_from.is_none()
            && self.loa_m_to.is_none()
            && self.beam_m.is_none()
            && self.beam_m_from.is_none()
            && self.beam_m_to.is_none()
            && self.design_draught_m.is_none()
            && self.design_draught_m_from.is_none()
            && self.design_draught_m_to.is_none()
            && self.year_built.is_none()
            && self.year_built_from.is_none()
            && self.year_built_to.is_none()
            && self.crew_complement.is_none()
            && self.crew_complement_from.is_none()
            && self.crew_complement_to.is_none()
            && self.lifetime_distance_nm.is_none()
            && self.lifetime_distance_nm_from.is_none()
            && self.lifetime_distance_nm_to.is_none()
            && self.in_service.is_none()
            && self.in_service_from.is_none()
            && self.in_service_to.is_none()
            && self.scrubber_fitted.is_none()
            && self.scrubber_fitted_from.is_none()
            && self.scrubber_fitted_to.is_none()
            && self.particulars_sheet.is_none()
            && self.particulars_sheet_like.is_none()
            && self.particulars_sheet_is_null.is_none()
    }
}
